selectTemplate: dict = {
    "selectTemplate.templateStart":"你想从哪里开始？",
    "selectTemplate.generateRandom":"创建新世界",
    "selectTemplate.createRealm":"新建 Realm",
    "selectTemplate.create":"新建…",
    "selectTemplate.realm":"新 Realm",
    "selectTemplate.realmInfo":"你可以在创建 Realm 后将世界上传！",
    "selectTemplate.signIn":"用 Microsoft 账户创建 Realm",
    "selectTemplate.unableToSignIn":"Microsoft 服务在此设备上不可用",
    "selectTemplate.world":"新的世界",
    "selectTemplate.help":"?",
    "selectTemplate.templateDescription":"模板",
    "selectTemplate.deleteTemplate":"删除世界模板…",
    "selectTemplate.deleteTemplateDone":"完成",
    "selectTemplate.deleteMessage":"您即将永久性删除 %s。您确定吗？",
    "selectTemplate.delete.confirm":"是否删除世界模板？",
    "selectTemplate.delete":"删除",
    "selectTemplate.myTemplates":"我的世界模板",
    "selectTemplate.realmsPlus":"精选 Realms Plus 模板",
    "selectTemplate.importedTemplates":"导入的模板",
    "selectTemplate.download":"下载",
    "selectTemplate.noTemplates":"这台设备上没有任何世界模板。",
    "selectTemplate.suggestedContent.title":"特色市场模板",
    "selectTemplate.suggestedContent.button":"查看更多模板",
    "selectTemplate.createdBy":"创建者：%s",
    "selectTemplate.inventory":"我的市场包",
    "selectTemplate.seeMore":"查看更多",

}