realmsSharingScreen: dict = {
    "realmsSharingScreen.join":"加入",
    "realmsSharingScreen.joinTitle":"加入 Realm？",
    "realmsSharingScreen.joinMessage":"加入 %s  Realm？",
    "realmsSharingScreen.blockedInviteTitle":"用户被屏蔽",
    "realmsSharingScreen.blockedInviteMessage":"很抱歉，您已被屏蔽！请让 Realm 所有者将您从“屏蔽”列表中移除。",
    "realmsSharingScreen.badInviteTitle":"无效的 Realm 链接",
    "realmsSharingScreen.badInviteMessage":"邀请链接不正确或已停用。向 Realm 的所有者索取更新的链接，并确保输入的内容无误。",
    "realmsSharingScreen.regenerateLinkFailed":"无法产生新邀请链接",
    "realmsSharingScreen.cantJoinExpiredTitle":"%s 的 Realm 已过期",
    "realmsSharingScreen.cantJoinExpiredMessage":"%s 已过期。要求 %s 进行更新。",
    "realmsSharingScreen.cantJoinClosedTitle":"%s 已关闭此 Realm",
    "realmsSharingScreen.cantJoinClosedMessage":"%s 已关闭。要求 %s 重新打开。",
    "realmsSharingScreen.failedSignInModalTitle":"登录以加入此 Realm",
    "realmsSharingScreen.failedSignInModalMessage":"您需要用 Microsoft 账户登录，才能加入 Realm。请登录，然后重试。",
    "realmsSharingScreen.invalidPermissionTitle":"无效权限",
    "realmsSharingScreen.unexpectedServerResponseTitle":"Realms 错误",
    "realmsSharingScreen.unexpectedServerResponseMessage":"很抱歉，连接到 Realm 时出现了问题。请稍后重试。",

}