multiplayer: dict = {
    "multiplayer.connect":连接",
    "multiplayer.downloadingStats":正在下载统计和成就中…",
    "multiplayer.downloadingTerrain":下载地形中",
    "multiplayer.info1":《我的世界》多人模式还未完成，但我们",
    "multiplayer.info2":正在进行一些早期测试。",
    "multiplayer.ipinfo":输入服务器的IP来连接：",
    "multiplayer.packErrors":至少一个资源或行为包加载失败。",
    "multiplayer.packErrors.realms":至少一个资源或行为包加载失败。可以尝试从您的 Realm 设置中下载这个世界和查看错误的详细信息。",
    "multiplayer.player.inventory.recovered":物品栏已恢复并被放置在您附近的箱子里。",
    "multiplayer.player.inventory.failed":物品栏已恢复。找一个安全的地方，我们将会在您下一次加入世界时在您附近放置一个箱子。",
    "multiplayer.player.joined":%s 加入了游戏",
    "multiplayer.player.joined.renamed":%s (之前被称为 %s)加入了游戏",
    "multiplayer.player.joined.realms":%s 加入了 Realm",
    "multiplayer.player.joined.realms.renamed":%s (之前被称为 %s) 加入了 Realm",
    "multiplayer.player.left":%s 退出了游戏",
    "multiplayer.player.left.realms":%s 退出了 Realm",
    "multiplayer.player.changeToPersona":%s编辑了角色外观。",
    "multiplayer.player.changeToSkin":%s 已更改他们的皮肤。",
    "multiplayer.stopSleeping":起床",
    "multiplayer.playersSleeping":%s/%s 名玩家已入睡",
    "multiplayer.texturePrompt.line1":这个服务器推荐使用自定义的资源包。",
    "multiplayer.texturePrompt.line2":你想要自动下载和安装它吗？",
    "multiplayer.title":多人游戏",
    "multiplayer.inBedOpenChat":打开聊天栏",
    "multiplayer.joincode.refreshed":该游戏的加入代码已更新。",

}