manifestvalidation: dict = {
    'manifestvalidation.title=包信息",
    'manifestvalidation.error=错误",
    'manifestvalidation.info=信息",
    'manifestvalidation.noerror=未找到错误",
    'manifestvalidation.warning=警告",
    'manifestvalidation.delete=删除",
    'manifestvalidation.delete.confirm_title=删除资源包？",
    'manifestvalidation.delete.confirm_body=你即将永远删除此资源/行为包。确定吗？",
    'manifestvalidation.delete.confirm_delete=删除",
    'manifestvalidation.delete.confirm_goBack=返回",
    'manifestvalidation.packid=包 ID：",
    'manifestvalidation.packversion=包版本：",
    'manifestvalidation.filelocation=文件位置：",
    'manifestvalidation.errorlist=错误列表",
    'manifestvalidation.file=文件：",
    'manifestvalidation.issue=问题：",
    'manifestvalidation.unkown.packtype=未知资源包类型",
    'manifestvalidation.unkown.packtitle=未知资源包名称",
    'manifestvalidation.unkown.packdescription=未知资源包描述",
    'manifestvalidation.unkown.packid=未知资源包 ID",
    'manifestvalidation.unkown.packversion=未知资源包版本",
    'manifestvalidation.noname=缺少名称",

}