realmsInvitationScreen: dict = {
    "realmsInvitationScreen.addingPlayers":添加玩家中...",
    "realmsInvitationScreen.findFriends":查找好友",
    "realmsInvitationScreen.continue":继续",
    "realmsInvitationScreen.done":完成了，我们开始游戏吧！",
    "realmsInvitationScreen.friends":好友",
    "realmsInvitationScreen.invitedFriends":邀请的好友",
    "realmsInvitationScreen.members":成员",
    "realmsInvitationScreen.unableToAddPlayers":无法添加玩家",
    "realmsInvitationScreen.loadingFriends":正在加载好友和成员...",
    "realmsInvitationScreen.loadingProfiles":正在加载档案 (%s/%s)",
    "realmsInvitationScreen.noInvites":未找到任何玩家。",
    "realmsInvitationScreen.savingChanges":保存更改中...",
    "realmsInvitationScreen.sendingInvitesFailed":出错了。我们无法将您所选的用户添加到您的 Realm。请稍后再试。",
    "realmsInvitationScreen.title":添加成员",
    "realmsInvitationScreen.undo":撤消",
    "realmsInvitationScreen.unblock":取消阻止",
    "realmsInvitationScreen.unblocked":已取消阻止",
    "realmsInvitationScreen.blocked":已阻止",
    "realmsInvitationScreen.myRealm":我的 Realm",
    "realmsInvitationScreen.fetchingLink":正在获取新链接...",
    "realmsInvitationScreen.fetchingCode":正在获取新的邀请代码...",
    "realmsInvitationScreen.shareTitle":Realms 邀请",
    "realmsInvitationScreen.shareText":在这个 Realm 中加入我吧！",
    "realmsInvitationScreen.refreshDialogTitle":禁用当前链接？",
    "realmsInvitationScreen.refreshDialogLabel":这将禁用当前链接并生成一个新链接。已成为成员的任何人仍能够加入您的 Realm。",
    "realmsInvitationScreen.createLinkDialogTitle":生成 Realm 链接？",
    "realmsInvitationScreen.createLinkDialogLabel":打开此链接的任何人都将成为您的 Realm 成员。您可以通过生成一个新链接来停用某个链接。",
    "realmsInvitationScreen.shareDialogTitle":分享之前下载备份？",
    "realmsInvitationScreen.shareDialogLabel":具有此链接的任何人都可以成为您的 Realm 成员。慎重选择要分享的人员。您可能希望首先下载您的世界的备份。您可以从 Realm 设置中删除成员。",
    "realmsInvitationScreen.shareDialogShareButton":分享",
    "realmsInvitationScreen.shareDialogCopyButton":复制",
    "realmsInvitationScreen.shareDialogNewLinkButton":创建新链接",
    "realmsInvitationScreen.shareDialogNewCodeButton":创建新代码",
    "realmsInvitationScreen.closedRealmWarning":您的 Realm 处于关闭状态。成员无法加入。",
    "realmsInvitationScreen.generate":生成",
    "realmsInvitationScreen.disable":禁用",
    "realmsInvitationScreen.backup":下载",
    "realmsInvitationScreen.shareByLink":分享链接",
    "realmsInvitationScreen.shareByCode":共享邀请代码",
    "realmsInvitationScreen.shareLinkToRealm":分享指向 Realm 的链接",
    "realmsInvitationScreen.shareCodeToRealm":将邀请代码共享至 Realm",
    "realmsInvitationScreen.shareInfoMessage":具有该链接的任何人都可以加入您的 Realm。转到“游戏”>“下载世界”即可下载您的世界的备份。",
    "realmsInvitationScreen.shareInfoMessageCode":任何持有该邀请代码的人都可以加入您的 Realm。前往游戏 > 下载世界即可下载您的世界的备份。",
    "realmsInvitationScreen.refreshLinkInfoMessage":这会停用旧链接并创建一个新链接。是否要继续？",
    "realmsInvitationScreen.refreshCodeInfoMessage":这将停用旧邀请代码并创建一个新代码。是否要继续？",
    "realmsInvitationScreen.kick":删除",
    "realmsInvitationScreen.kickAndBlock":阻止",
    "realmsInvitationScreen.kickPopupTitle":撤消访问权限？",
    "realmsInvitationScreen.kickPopupText":您是否希望撤消此玩家的访问权限？您可以随时撤销该操作。",
    "realmsInvitationScreen.copyToastMessage":您的 Realm 链接已复制到剪贴板！",
    "realmsInvitationScreen.playerFilterTitle":筛选玩家",
    "realmsInvitationScreen.setPermissionFail":为用户%s设置许可失败。",
    "realmsInvitationScreen.setDefaultPermissionFail":设置默认许可失败。",

}