progressScreen: dict = {
    "progressScreen.cantConnect":"无法连接到世界。请检查您的互联网连接并重试。",
    "progressScreen.generating":"正在生成世界",
    "progressScreen.saving":"正在保存世界",
    "progressScreen.loading":"加载中...",
    "progressScreen.title.downloading":"正在下载资源包 %1",
    "progressScreen.title.applyingPacks":"正在加载资源包",
    "progressScreen.title.searchingForSession":"正在搜索游戏会话...",
    "progressScreen.title.waitingForStorageProvider":"正在同步用户数据",
    "progressScreen.title.connectingLocal":"正在启动世界",
    "progressScreen.title.connectingLAN":"正在连接多人游戏",
    "progressScreen.title.connectingExternal":"正在连接外部服务器",
    "progressScreen.title.connectingRealms":"正在连接 Realm",
    "progressScreen.title.copyingWorld":"复制世界",
    "progressScreen.title.deleteStorageAreaContent":"清除存储缓存",
    "progressScreen.title.loadingSplitScreenAppearances":"加载分屏外观",
    "progressScreen.message.appearanceLoaded":"外观已加载",
    "progressScreen.message.appearanceLoadWaitTimeMet":"外观需要很长时间才能加载。正在继续生成世界...",
    "progressScreen.message.deleteStorageAreaContent":"这可能需要几分钟。",
    "progressScreen.message.copyingWorld":"正在复制世界... %d%%",
    "progressScreen.message.tts.copyingWorld":"正在复制世界",
    "progressScreen.message.building":"生成地形中",
    "progressScreen.message.done":"完成！",
    "progressScreen.message.exporting":"正在导出中",
    "progressScreen.message.exporting.warning":"请不要退出游戏。退出可能会破坏导出。",
    "progressScreen.message.importing":"正在导入世界",
    "progressScreen.message.importingContent":"2/2 步 - 正在导入内容",
    "progressScreen.message.updatingContent":"正在更新 %1/%2 个包",
    "progressScreen.message.locating":"定位服务器",
    "progressScreen.message.loadingAppearance":"正在加载外观...",
    "progressScreen.message.waitingForRealms":"这可能要花一段时间",
    "progressScreen.message.waitingForStorageProvider":"这可能要花一段时间...",
    "progressScreen.message.waitingForTickingAreas":"正在加载常加载区域",
    "progressScreen.message.storageProviderSyncError":"无法同步用户数据。",
    "progressScreen.message.waitingForStoreProducts":"这可能要花一段时间",
    "progressScreen.message.allDone":"全部完成！",
    "progressScreen.message.letsGo":"出发吧！",
    "progressScreen.message.failed":"失败",
    "progressScreen.message.failedNoNetwork":"失败：无网络连接",
    "progressScreen.message.downloadingWorld":"下载世界中",
    "progressScreen.message.downloadingContent":"1/2 步 - 正在下载内容",
    "progressScreen.message.uploadingWorld":"世界文件上传中......",
    "progressScreen.message.uploadingWorldError":"世界上传失败。是否要重试？",
    "progressScreen.message.copyingPacks":"保存世界资源包中",
    "progressScreen.message.initiatingTemplate":"正在初始化世界模板",
    "progressScreen.message.fileSize":"文件大小",
    "progressScreen.message.initializingUpload":"正在初始化上传",
    "progressScreen.message.initializingDownload":"正在初始化下载",
    "progressScreen.message.invalidWorldFile":"无效的世界文件。请重新打开您的世界并保存，随后请重试。",
    "progressScreen.message.resourceLoading":"正在加载资源",
    "progressScreen.message.leaveLevel":"正在保存您的游戏。请不要关闭您的设备。",
    "progressScreen.message.genericMayTakeAMoment":"这可能要花一段时间",
    "progressScreen.message.noUploadResponse":"我们无法确认您的世界是否成功上传。请加入您的 Realm 进行检查，如果仍未更新至新的世界，请重新再试一次。",
    "progressScreen.message.noUploadEndpoint":"找不到上传世界的地方。或许您可以检查一下网络连接？",
    "progressScreen.message.unownedTemplate":"您似乎没有此世界所需要的市场模板。您可以从《我的世界》市场中购买。",
    "progressScreen.message.createArchiveFileFailed":"我们无法将您的世界文件打包上传。或许是您的硬盘空间不足了？",
    "progressScreen.message.createLevelStorageFailed":"在准备上传您的世界时出现了问题。如果这种情况一直发生，重新启动设备可能会有所帮助。",
    "progressScreen.message.unknownError":"出现错误",
    "progressScreen.message.directoryDepthError":"由于包中的目录问题，无法打开此世界。",
    "progressScreen.message.forbiddenContent":"您未拥有一个或多个所应用的包",
    "progressScreen.message.loadingSplitScreenAppearances":"正在加载分屏外观...",
    "progressScreen.message.finishedLoadingSplitScreenAppearances":"已完成分屏外观的加载。",
    "progressScreen.dialog.title.resourcePack":"下载资源包？",
    "progressScreen.dialog.title.behaviorAndResourcePack":"下载世界行为和资源包？",
    "progressScreen.dialog.title.onlyBehavior":"下载世界行为包？",
    "progressScreen.dialog.title.storageProviderError":"同步世界数据失败",
    "progressScreen.dialog.title.storageProviderLongWait":"正在同步世界数据",
    "progressScreen.dialog.title.storageProviderSucceeded":"同步世界数据成功",
    "progressScreen.dialog.message.onlyBehavior":"此世界已应用行为包，您必须下载才能加入。您要下载并加入吗？",
    "progressScreen.dialog.message.behaviorAndOptionalResourcePack":"此世界已应用行为包，您必须下载才能加入，此外还有资源包，您可在加入前选择下载。您要在加入之前下载哪些？",
    "progressScreen.dialog.message.behaviorAndResourcePack":"此世界已应用行为包和资源包，您必须下载才能加入。您要下载并加入吗？",
    "progressScreen.dialog.message.resourcePackOptional":"此世界已应用资源包。您要在加入前下载吗？",
    "progressScreen.dialog.message.resourcePackRequired":"此世界已应用资源包，您必须下载才能加入。您要下载并加入吗？",
    "progressScreen.dialog.message.resourcePackOptional.rayTracing.line1":"这个世界已启用了光线追踪资源包 	。",
    "progressScreen.dialog.message.resourcePackOptional.rayTracing.line2":"您的设备与高级照明和材质功能不兼容，因此该世界将无法应用这些高级效果。您想在加入世界之前下载它们吗？",
    "progressScreen.dialog.message.resourcePackRequired.rayTracing.line1":"这个世界已启用了光线追踪资源包 	。",
    "progressScreen.dialog.message.resourcePackRequired.rayTracing.line2":"您的设备与高级照明和材质功能不兼容，因此该世界将无法应用这些高级效果。您想在加入世界之前下载它们吗？",
    "progressScreen.dialog.message.storageProviderError":"无法同步您的世界数据。是否要重试？",
    "progressScreen.dialog.message.storageProviderUnusableError":"该世界未完全同步，或者已经损坏。请尝试在状态良好的主机上玩该世界，然后再次尝试进行迁移。",
    "progressScreen.dialog.message.storageProviderQuotaError":"本地保存成功，但由于配额原因，云同步失败。通过从设置菜单中删除世界来释放云空间。",
    "progressScreen.dialog.message.storageProviderOutOfLocalStorage":"本地可用空间不足，无法支持云同步。",
    "progressScreen.dialog.message.worldCorrupted":"该世界已损坏。请在 bugs.mojang.com 上报告",
    "progressScreen.dialog.message.storageProviderLongWait":"同步此世界要花很长时间。是否要继续等待？",
    "progressScreen.dialog.button.enter":"进入世界",
    "progressScreen.dialog.button.joinAndDownload":"下载并加入 - %1",
    "progressScreen.dialog.button.joinAndDownload.everything":"全部下载并加入 - %1",
    "progressScreen.dialog.button.joinAndDownload.onlyBehaviorPacks":"仅下载行为并加入 - %1",
    "progressScreen.dialog.button.join":"加入",
    "progressScreen.dialog.button.leave":"退出",
    "progressScreen.dialog.button.retry":"重试",
    "progressScreen.dialog.button.wait":"等待",
    "progressScreen.editor.message.copyingProject":"正在复制项目... %d%%",
    "progressScreen.editor.message.tts.copyingProject":"正在复制项目",
    "progressScreen.editor.title.copyingProject":"项目副本",
    "progressScreen.editor.dialog.message.resourcePackOptional":"此项目已应用资源包。您要在加入前下载吗？",
    "progressScreen.editor.dialog.message.resourcePackRequired":"此项目已应用资源包，您必须下载才能加入。是否要下载并加入？",
    "progressScreen.editor.message.convert.projectToWorld":"正在将项目转换为世界并制作项目副本...",
    "progressScreen.editor.message.convert.worldToProject":"正在将世界转换为项目...",
    "progressScreen.editor.message.convert.projectToWorld.saveWorld":"正在保存世界数据...",
    "progressScreen.editor.message.convert.worldToProject.saveProject":"正在保存项目数据...",
    "progressScreen.label.mobileData":"移动数据",
    "progressScreen.noWifi.mobileDataWarning":"您当前未连接到无线网络。可能会收取移动数据费用。",

}