name: Build and release

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 */6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        npm install

    - name: Build project
      run: |
        npm run build

    - name: Compress src directory
      run: |
        tar -czf src.tar.gz src

    - name: Optimize compression
      run: |
        gzip -9 src.tar.gz

    - name: Get version from ToolDelta repository
      id: get_version
      run: |
        VERSION=$(curl -s https://raw.githubusercontent.com/ToolDelta/ToolDelta/main/version)
        echo "::set-output name=version::$VERSION"

    - name: Create release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.version }}
        release_name: Release ${{ steps.get_version.outputs.version }}
        body: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false

    - name: Upload release asset
      id: upload_release_asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: src.tar.gz
        asset_name: ToolDelta-Game_{{ steps.get_version.outputs.version }}.tar.gz
        asset_content_type: application/gzip
