resourcePack: dict = {
    "resourcePack.available.title":"可用的资源包",
    "resourcePack.available.title.behaviorPacks":"可用的行为包",
    "resourcePack.available.title.packs":"我的包",
    "resourcePack.available.add":"激活",
    "resourcePack.available.none.text":"您没有资源包",
    "resourcePack.available.none.behavior":"您没有行为资源包",
    "resourcePack.available.none.store":"查看市场",
    "resourcePack.message.noneFound.packs":"这台设备上没有可用的包。",
    "resourcePack.message.allInUse.packs":"您的包当前正在使用中。",
    "resourcePack.message.error":"一个包具有会使它无法正常运转的错误",
    "resourcePack.message.warning":"一个包具有可能会导致异常行为的警告",
    "resourcePack.suggestedContent.title":"获取更多包",
    "resourcePack.suggestedContent.button.viewMore":"查看更多包",
    "resourcePack.cached.title":"缓存包",
    "resourcePack.folderInfo":"（请把资源包文件放在这里）",
    "resourcePack.openFolder":"打开资源包文件夹",
    "resourcePack.selected.title":"已选的资源包",
    "resourcePack.selected.title.behaviorPacks":"有效行为包",
    "resourcePack.selected.title.packs":"活跃",
    "resourcePack.selected.remove":"关闭",
    "resourcePack.realmsPlus.title.packs":"Realms Plus 包",
    "resourcePack.realmsPlus.expired":"已过期",
    "resourcePack.errors":"错误：",
    "resourcePack.error.ingame.packs":"您在一个世界中游戏时无法更改资源包。",
    "resourcePack.error.ingame.behaviorPacks":"您在一个世界中游戏时无法更改行为包。",
    "resourcePack.error.enteringgame.title":"Realm 上过期的包",
    "resourcePack.error.enteringgame.message":"这个 Realm 包含在 Realms Plus 上过期的资源或行为包。您需要关闭这些包或从市场购买它们才能在这个 Realm 中玩。",
    "resourcePack.error.enteringgame.button":"查看活跃包",
    "resourcePack.title":"选择资源包",
    "resourcePack.toast.atlasFallback.message":"内存不足。材质的细节级别将会降低。",
    "resourcePack.toast.atlasFallback.title":"资源包回退",
    "resourcePack.copyGlobal":"从 Global 上复制",
    "resourcePack.description":"资源包从下到上应用。这表示两个包中的任何资产都会由更高级的资源包覆盖。",
    "resourcePack.description.default.level":"您可以在设置中编辑这些项目。",
    "resourcePack.description.default.behaviorPacks":"默认的《我的世界》游戏玩法。",
    "resourcePack.description.bottom.global":"资源包从下到上应用。这表示两个包中的任何资产都会由更高级的资源包覆盖。您世界中的这些资源包会应用于这些全局包上方。这些资源仅供您使用，别人无法看到您设置的资源。在您的世界中或您加入的世界中，资源包将应用于这些全局资源上方。",
    "resourcePack.description.bottom.behaviorPacks":"行为包从下到上应用。这表示两种行为包中的任何内容都会由更高级的附加件覆盖。",
    "resourcePack.description.bottom.level":"资源包从下到上应用。这表示两个包中的任何资产都会由更高级的资源包覆盖。您世界中的这些资源包会应用于您的全局包上方。",
    "resourcePack.description.store":"在商店中查看",
    "resourcePack.header.behavior":"激活的行为包适用于全部玩家。",
    "resourcePack.header.level":"要求玩家接受资源包才能加入",
    "resourcePack.crashRecovery.title":"全局资源重置",
    "resourcePack.crashRecovery.message":"上一次资源加载失败。",
    "resourcePack.warnings":"警告：",
    "resourcePack.warning.title":"这很危险！",
    "resourcePack.warning.body":"游玩世界后添加或删除行为包可能会对世界造成破坏，导致您丢失自己创建的行为包。点击“确定”可停用包，或点击“取消”以保持其活跃状态。",
    "resourcePack.requiredDependency.title":"必备依赖项",
    "resourcePack.requiredDependency.body":"此资源包是当前已应用的另一个资源包的必备依赖项。",
    "resourcePack.missingDependency.title":"缺少依赖项",
    "resourcePack.missingDependency.body":"此资源包缺少一个或多个依赖项。是否仍要应用？",
    "resourcePack.delete":"您即将永久性删除 %s 。您确定吗？",
    "resourcePack.delete.confirm":"删除包？",
    "resourcePack.deleteSelected":"该包当前已被选中！您即将永久性删除%s。您确定吗？",
    "resourcePack.deleteMultiple":"您即将永久性删除下列包：%s您确定吗？",
    "resourcePack.editPack":"删除包…",
    "resourcePack.editPackDone":"完成",
    "resourcePack.toast.unownedContent.title":"%s已无效",
    "resourcePack.toast.unownedContent.subtitle":"当前账户未拥有该资源包。",
    "resourcePack.incompatibleDependency":"此资源包的依赖项 (%s) 与您的设备不兼容",
    "resourcePack.incompatibleDependency.memory":"此资源包的依赖项 (%s) 与您的设备不兼容，因为您的设备内存不足。",
    "resourcePack.incompatibleDependency.graphics.raytracing":"此资源包的依赖项 (%s) 与您的设备不兼容，因为您的设备没有支持光线追踪的兼容硬件",
    "resourcePack.subpackResolution":"分辨率：%s",
    "resourcePack.incompatible":"此资源包与您的设备不兼容。",
    "resourcePack.incompatible.memory":"此分辨率与您的设备不兼容，因为您的设备内存不足。",
    "resourcePack.incompatible.graphics.raytracing":"此资源包包含允许光线追踪的信息，但您的设备不支持此选项。",
    "resourcePack.packSettingsTitle":"%s 个设置",
    "resourcePack.missingPackDescription":"找不到此包！",
    "resourcePack.legacyPackName":"遗产资源包",
    "resourcePack.vanilla.name":"《我的世界》材质包",
    "resourcePack.vanilla.description":"默认的《我的世界》图形，现已新增了时尚的新材质！",
    "resourcePack.city.name":"城市",
    "resourcePack.city.description":"适合建筑结构。",
    "resourcePack.plastic.name":"塑料的",
    "resourcePack.plastic.description":"简单、多彩、活力四射。",
    "resourcePack.natural.name":"自然",
    "resourcePack.natural.description":"赋予您的世界更加自然的外观。",
    "resourcePack.fantasy.name":"魔幻",
    "resourcePack.fantasy.description":"将自己传送到骑士都是英雄的时候。",
    "resourcePack.cartoon.name":"卡通",
    "resourcePack.cartoon.description":"大大的眼睛！憨憨的笑容！用此包将您的世界变成卡通版吧。",
    "resourcePack.candy.name":"糖果",
    "resourcePack.candy.description":"用糖衣包裹你的世界，把所有的材质都变成糖浆点心。",
    "resourcePack.festivemashup2016.name":"节日混搭 2016",
    "resourcePack.festivemashup2016.description":"用此白雪皑皑的季节包创造一个冬季仙境。",
    "resourcePack.chinesemythology.name":"中国神话混搭包",
    "resourcePack.chinesemythology.description":"这些材质的灵感来自于中国的神话传说。",
    "resourcePack.Fallout.name":"《辐射》混搭",
    "resourcePack.Fallout.description":"欢迎来到废土！",
    "resourcePack.GreekMythology":"希腊神话混搭包",
    "resourcePack.GreekMythology.name":"希腊神话混搭包",
    "resourcePack.GreekMythology.description":"把神话传说中的希腊带到你的指尖。",
    "resourcePack.Skyrim.name":"《天际》混搭包",
    "resourcePack.Skyrim.description":"在《天际》大地上建立您专属的世界。",
    "resourcePack.MashupAdventureTime.name":"探险时光",
    "resourcePack.MashupAdventureTime.description":"",
    "resourcePack.skin.name":"皮肤",
    "resourcePack.skin.description":"皮肤、皮肤、皮肤！！！",
    "resourcePack.invalid.description":"无法成功解析资源包。点击显示错误。",
    "resourcePack.loading.description":"资源包仍在加载。",

}