sidebar: dict = {
    "sidebar.action":"动作",
    "sidebar.adventure":"冒险",
    "sidebar.capes":"披风",
    "sidebar.categories":"类别",
    "sidebar.categoryBody":"身体",
    "sidebar.categoryStyle":"样式",
    "sidebar.characterCreator":"角色创建器",
    "sidebar.classicSkins":"经典皮肤",
    "sidebar.emotes":"表情",
    "sidebar.fantasy":"幻想",
    "sidebar.featured":"精选",
    "sidebar.genre":"类型",
    "sidebar.marketplace":"市场",
    "sidebar.mashups":"混搭包",
    "sidebar.minigame":"小游戏",
    "sidebar.myCharacters":"我的角色",
    "sidebar.myContent":"我的内容",
    "sidebar.newReleases":"新发布",
    "sidebar.openWorld":"开放世界",
    "sidebar.parkour":"跑酷",
    "sidebar.resources":"资源",
    "sidebar.roleplay":"角色扮演",
    "sidebar.skins":"皮肤",
    "sidebar.skinsOwned":"拥有的皮肤",
    "sidebar.skyblock":"Skyblock",
    "sidebar.simulation":"模拟",
    "sidebar.survival":"生存",
    "sidebar.realmsPlus":"Realms Plus",
    "sidebar.skinsRealmsPlus":"Realms Plus 皮肤",
    "sidebar.skinsUnowned":"获取更多",
    "sidebar.topSellers":"畅销产品",
    "sidebar.trending":"趋势",
    "sidebar.tts.sidebarCollapseList":"侧边栏选项：折叠 %s",
    "sidebar.tts.sidebarExpandList":"侧边栏选项：展开 %s",
    "sidebar.tts.sidebarNavigateTo":"侧边栏选项：前往 %s",
    "sidebar.tts.verboseToggleExpand":"展开侧边栏",
    "sidebar.tts.verboseToggleCollapse":"折叠侧边栏",
    "sidebar.worlds":"世界",

}