death: dict = {
    "death.attack.anvil": "{} 被坠落的铁砧压扁了",
    "death.attack.arrow": "{} 被 {} 射杀",
    "death.attack.arrow.item": "{} 被 {} 用 {} 射杀",
    "death.attack.bullet": "{} 被 {} 狙击了",
    "death.attack.cactus": "{} 被戳死了",
    "death.attack.cactus.player": "{} 在试图逃离 {} 时撞入了仙人掌中",
    "death.attack.drown": "{} 淹死了",
    "death.attack.drown.player": "{} 在试图逃离 {} 时淹死了",
    "death.attack.explosion": "{} 爆炸了",
    "death.attack.explosion.player": "{} 被 {} 炸死了",
    "death.attack.fall": "{}落地过猛",
    "death.attack.fallingBlock": "{} 被下落的方块压扁了",
    "death.attack.fireball": "{} 被 {} 用火球烤死了",
    "death.attack.fireball.item": "{} 被 {} 用 {} 发射的火球烤死了",
    "death.attack.fireworks": "{} 在一声巨响中阵亡了",
    "death.attack.flyIntoWall": "{} 遭受了动态能量",
    "death.attack.generic": "{} 死了",
    "death.attack.indirectMagic": "{} 被 {} 使用的魔法杀死了",
    "death.attack.indirectMagic.item": "{} 被 {} 用 {} 杀死了",
    "death.attack.inFire": "{} 浴火焚身",
    "death.attack.inFire.player": "{} 在与 {} 战斗中不慎走入了火中",
    "death.attack.inWall": "{} 在墙里窒息而亡",
    "death.attack.lava": "{} 试图在熔岩里游泳",
    "death.attack.lava.player": "{} 在逃离 {} 时试图在熔岩里游泳",
    "death.attack.lightningBolt": "{} 被闪电击中",
    "death.attack.magic": "{} 被魔法杀死了",
    "death.attack.magma": "{} 发现地面是熔岩",
    "death.attack.magma.player": "由于 {}，{} 行走于危险地带",
    "death.attack.mob": "{} 被 {} 杀死了",
    "death.attack.onFire": "{} 被烧死了",
    "death.attack.onFire.player": "{} 在试图与 {} 战斗时被烤的酥脆",
    "death.attack.outOfWorld": "{} 掉出了这个世界",
    "death.attack.player": "{} 被 {} 杀死了",
    "death.attack.player.item": "{} 被 {} 用 {} 杀死了",
    "death.attack.spit": "{} 被 {} 吹了纸团",
    "death.attack.starve": "{} 饿死了",
    "death.attack.thorns": "{} 在试图伤害 {} 时被杀",
    "death.attack.thrown": "{} 被 {} 给砸死了",
    "death.attack.thrown.item": "{} 被 {} 用 {} 给砸死了",
    "death.attack.trident": "{} 被 {} 穿透了",
    "death.attack.wither": "{} 凋谢了",
    "death.attack.freeze": "{} 冻死了",
    "death.attack.stalactite": "{} 被坠落的钟乳石刺穿了",
    "death.attack.stalagmite": "{} 被钉在了石笋上",
    "death.fell.accident.generic": "{} 从高处摔了下来",
    "death.fell.accident.ladder": "{} 从梯子上摔了下来",
    "death.fell.accident.vines": "{} 从一些藤蔓上摔了下来",
    "death.fell.accident.water": "{} 从水中掉了下来",
    "death.fell.assist": "{} 因为 {} 注定要摔死",
    "death.fell.assist.item": "{} 因为 {} 使用了 {} 注定要摔死",
    "death.fell.finish": "{} 摔伤得太重并被 {} 完结了生命",
    "death.fell.finish.item": "{} 摔伤得太重并被 {} 用 {} 完结了生命",
    "death.fell.killer": "{} 注定要摔死"
}