dynamicPackage: dict = {
    'dynamicPackage.download.android.state_unknown=正在启动……",
    'dynamicPackage.download.android.state_idle=正在等待下载……",
    'dynamicPackage.download.android.state_fetchingUrl=正在查找资源……",
    'dynamicPackage.download.android.state_connecting=连接中",
    'dynamicPackage.download.android.state_downloading=正在更新",
    'dynamicPackage.download.android.state_completed=更新已完成！",
    'dynamicPackage.download.android.state_paused_networkUnavailable=已暂停，无可用网络",
    'dynamicPackage.download.android.state_paused_networkSetupFailure=已暂停，无可用网络",
    'dynamicPackage.download.android.state_paused_byRequest=已暂停",
    'dynamicPackage.download.android.state_paused_wifiUnavailable=已暂停，无可用 WI-FI",
    'dynamicPackage.download.android.state_paused_wifiDisabled=已暂停，无可用 WI-FI",
    'dynamicPackage.download.android.state_paused_roaming=已暂停，请检查漫游设置",
    'dynamicPackage.download.android.state_paused_sdcardUnavailable=已暂停，无可用存储空间",
    'dynamicPackage.download.android.state_failed_unlicensed=失败，未经许可的应用程序",
    'dynamicPackage.download.android.state_failed_fetchingUrl=失败，找不到资源",
    'dynamicPackage.download.android.state_failed_sdcardFull=失败，存储空间已满",
    'dynamicPackage.download.android.state_failed_cancelled=已取消",
    'dynamicPackage.download.android.state_failed=更新失败",
    'dynamicPackage.download.android.kilobytesPerSecond=%1$s KB/s						 %1$s is the download speed in kbps",
    'dynamicPackage.download.android.timeRemainingNotification=还剩 %1$s					 %1$s is the time remaining",
    'dynamicPackage.download.android.notificationChannelName=更新状态",
    'dynamicPackage.download.android.NotificationChannelDescription=显示更新状态和进度",

}