howtoplay: dict = {
    "howtoplay.next":"下一步",
    "howtoplay.previous":"上一步",
    "howtoplay.category.basics":"基本操作",
    "howtoplay.category.crafting":"合成",
    "howtoplay.category.education":"教育",
    "howtoplay.category.engineering":"工程",
    "howtoplay.category.enhancedPlay":"增强游戏",
    "howtoplay.category.firstDay":"第一天",
    "howtoplay.category.optionsAndCheats":"选项和作弊",
    "howtoplay.category.play":"游戏",
    "howtoplay.category.theEnd":"末地",
    "howtoplay.adventureMode":"冒险模式",
    "howtoplay.adventureMode.title":"游戏指南：冒险模式",
    "howtoplay.adventureMode.text.1":"冒险模式是世界建造者的一种游戏模式。在冒险模式中，玩家必须使用特殊工具来放置或击破方块。",
    "howtoplay.adventureMode.text.2":"要获得这些特殊工具，您必须在创造模式下使用 /give 与 canplace 或 candestroy 参数。",
    "howtoplay.anvil":"铁砧",
    "howtoplay.anvil.title":"游戏指南：铁砧",
    "howtoplay.anvil.text.1":"经验级别可用于使用铁砧修复、附魔或重命名物品。",
    "howtoplay.anvil.header.1":"重命名和应用附魔",
    "howtoplay.anvil.text.2":"可以重命名所有物品，尽管在铁砧上只可以使用书修复或附魔具有持久性的物品。",
    "howtoplay.anvil.header.2":"修复",
    "howtoplay.anvil.text.3":"修复物品需要将它放置在左侧的一个输入槽中，同时还要放入一些该物品的原材料（如用于铁剑的铁锭）或与另一种相同类型的物品组合。",
    "howtoplay.anvil.text.4":"使用铁砧组合物品时，效率更高。",
    "howtoplay.anvil.text.5":"铁砧在每次使用时有可能损坏，并且在使用足够次数后将被销毁。",
    "howtoplay.armor":"盔甲",
    "howtoplay.armor.title":"游戏指南：盔甲",
        "howtoplay.armor.header.1":"合成",
    "howtoplay.armor.text.2":"盔甲可以由皮革、铁、黄金或钻石制成。链甲可以通过村民交易获得，也可以从僵尸和骷髅处掠夺。",
    "howtoplay.armor.text.3":"通过打开您的物品栏并将盔甲碎片移动到玩家皮肤旁边的相应槽位中，即可装备盔甲。",
    "howtoplay.armor.text.4":"铁质盔甲、锁链盔甲和黄金盔甲可以在熔炉中熔化成铁粒或金粒。",
    "howtoplay.armor.header.2":"护盾",
                        "howtoplay.armor.text.6":"护盾甚至可以格挡一次爬行者的爆炸！",
    "howtoplay.armor.header.3":"伪装",
        "howtoplay.armorStand":"盔甲架",
    "howtoplay.armorStand.title":"游戏指南：盔甲架",
    "howtoplay.armorStand.text.1":"盔甲架用于挂载您未在使用的盔甲。",
    "howtoplay.armorStand.header.1":"装备",
        "howtoplay.armorStand.text.2.touch":"在持拿一件盔甲的同时点击盔甲架即可将盔甲置于盔甲架上。",
        "howtoplay.armorStand.text.3.touch":"在张开手时点击盔甲架即可从盔甲架中移除物品。",
    "howtoplay.armorStand.header.2":"摆姿势",
        "howtoplay.armorStand.text.4.touch":"盔甲架可以更改其姿势，潜行并点击盔甲架可更改姿势。",
    "howtoplay.armorStand.header.3":"跳舞",
    "howtoplay.armorStand.text.5":"盔甲架会对红石信号作出反应，请尝试给予它不同的信号强度，然后看看会发生什么。",
    "howtoplay.banners":"旗帜",
    "howtoplay.banners.title":"游戏指南：旗帜",
    "howtoplay.banners.text.1":"旗帜一种是使用自定义图案和颜色装饰您的房子或城堡的超酷方式。",
    "howtoplay.banners.text.2":"在合成旗帜后，您可以将它放置在工作台或织布机上并添加不同染料，以创建自己独一无二的超酷设计！",
    "howtoplay.banners.header.1":"应用一个图案",
    "howtoplay.banners.text.3":"可以使用您的染料创建许多不同的图案，如：",
    "howtoplay.banners.text.4":"  - 制作一个三角形将给予您一个 v 形图案。",
    "howtoplay.banners.text.5":"  - 制作一个十字将给予您一个十字图案。",
    "howtoplay.banners.text.6":"  - 添加一朵滨菊将给予您一个花朵图案。",
    "howtoplay.banners.text.7":"试验不同组合可获得更多图案！",
    "howtoplay.banners.header.2":"多层",
    "howtoplay.banners.text.8":"旗帜也可以有多层，这使您在旗帜上可以布置多个图案。如果您不喜欢放置在旗帜上的最后一个图案，则可以在炼药锅中洗掉最后一层。",
    "howtoplay.banners.header.3":"制作副本",
    "howtoplay.banners.text.9":"如果您想要复制旗帜，请将相应旗帜放置在具有空白旗帜的工作台上。",
    "howtoplay.beacons":"信标",
    "howtoplay.beacons.title":"游戏指南：信标",
    "howtoplay.beacons.text.1":"活动信标会将一束亮光投射到空中。",
    "howtoplay.beacons.text.2":"信标由玻璃、黑曜石和下界之星（可通过打败凋灵获得）制成。",
    "howtoplay.beacons.header.1":"建筑",
    "howtoplay.beacons.text.3":"必须将信标放置在不会阻挡天空视界之地，并且必须放置在铁块、金块、绿宝石块或钻石块搭建的金字塔上。",
    "howtoplay.beacons.text.4":"在其上放置信标的材料不会对信标的效果产生影响。",
    "howtoplay.beacons.header.2":"使用",
    "howtoplay.beacons.text.5":"您可以在“信标”菜单中为您的信标选择一个主要效果。金字塔层数越多，提供的效果就越多。",
    "howtoplay.beacons.text.6":"要设置信标效果，您必须在付款槽内使用绿宝石、钻石、金锭或铁锭。",
    "howtoplay.beacons.text.7":"设置完成后，信标会永久地发射效果。这些效果会授予附近的所有玩家。",
    "howtoplay.beacons.text.8":"若要更改光束颜色，请在其路径中放置一个染色玻璃方块。",
    "howtoplay.beds":"床",
    "howtoplay.beds.title":"游戏指南：床",
    "howtoplay.beds.text.1":"睡在床上过夜，并设置您的出生点。",
        "howtoplay.beds.text.2.touch":"点击床即可入睡。此操作只可在晚上执行。",
    "howtoplay.beds.text.3":"如果您正在玩多人游戏，则世界中的每个人都必须同时在床上过夜。",
    "howtoplay.beds.text.4":"如果您的床已损毁，您将返回到您在这个世界中的第一个出生点。",
    "howtoplay.beds.text.5":"在下界中使用床时请小心，通常会因太热而无法入睡。",
    "howtoplay.blocks":"方块",
    "howtoplay.blocks.title":"游戏指南：方块",
    "howtoplay.blocks.text.1":"《我的世界》的世界由数以百万计的方块构成。每一个方块都可破坏、可收集和可放置。您几乎可以不受限制的创造一切事物！",
    "howtoplay.blocks.text.2":"大多数方块必须在世界中寻找，但一些方块只能通过在工作台上组合其他方块制成（如红石方块）或者在熔炉中熔化制成（如玻璃）。",
    "howtoplay.blocks.header.1":"下落的方块",
    "howtoplay.blocks.text.3":"大多数方块不受重力影响，可以漂浮在半空；但像沙子和砂砾之类的物品将会落下（如果没有方块在其下方）。",
    "howtoplay.blocks.header.2":"趣味方块",
    "howtoplay.blocks.text.4":"以下是一些《我的世界》中更多有趣方块的示例：",
    "howtoplay.blocks.text.5":"玻璃 - 这是一种透明方块，通过在熔炉中熔化沙子制成。",
    "howtoplay.blocks.text.6":"混凝土 - 通过将混凝土粉末方块倒入水中制成。",
    "howtoplay.blocks.text.7":"陶瓦 - 该方块自然存在于荒地生物群系中，或者可以使用在水下找到的粘土作为原料合成并染色制成。通过将陶瓦放入熔炉中熔化可将其制成带釉陶瓦。",
    "howtoplay.blocks.text.8":"岩浆 - 该方块自然存在于下界中，它发出一点光，并且会烧毁踩到它的任何生物。",
    "howtoplay.blocks.text.9":"粗粒土 - 该方块与普通泥土方块极为相似，但其上无法长出草。可在热带草原和大型针叶林生物群系中找到它。",
    "howtoplay.bookAndQuill":"书和羽毛笔",
    "howtoplay.bookAndQuill.title":"游戏指南：书和羽毛笔",
    "howtoplay.bookAndQuill.text.1":"书和羽毛笔使您可以记录自己的冒险经历。通过在页面中输入文字和图像来讲述您的故事。您甚至可以更改标题和作者！对书和羽毛笔签名即可完成您的工作。在签名之前，书和羽毛笔将处于可编辑状态。",
    "howtoplay.brewingStand":"酿造台",
    "howtoplay.brewingStand.title":"游戏指南：酿造台",
    "howtoplay.brewingStand.text.1":"酿造药水需要一个酿造台。每份药水首先需要一瓶水，该瓶水可使用来自炼药锅或水源地的水灌满玻璃瓶获得。",
    "howtoplay.brewingStand.header.1":"了解您的酿造台",
    "howtoplay.brewingStand.text.2":"酿造台有三个槽，可用于制作不同的药水。一种成分可用于全部三个瓶子，因此始终同时酿造三份药水，以充分利用您的资源。",
    "howtoplay.brewingStand.header.2":"成分和药水",
    "howtoplay.brewingStand.text.3":"将下界疣放入酿造台的顶部位置会为您制成一份粗制的药水。该药水本身没有任何效果，但可制作用于制作更高级药水的基础药水。",
    "howtoplay.brewingStand.text.4":"有许多药水效果等待着被发现，使用不同的成份和组合进行试验才能成为一名真正的炼金术士。",
    "howtoplay.cauldron":"炼药锅",
    "howtoplay.cauldron.title":"游戏指南：炼药锅",
    "howtoplay.cauldron.text.1":"炼药锅是一种可容纳数桶或数瓶液体的容器。",
    "howtoplay.cauldron.header.1":"装满",
        "howtoplay.cauldron.text.2.touch":"拿着一桶水或一份药水时，点击炼药锅即可向炼药锅中注入其中的成份。",
    "howtoplay.cauldron.text.3":"一份药水只能够部分填满炼药锅，因此您将需要使用多份药水才能完全填满炼药锅。",
    "howtoplay.cauldron.header.2":"浸泡箭",
        "howtoplay.cauldron.text.4.touch":"手中握有箭时，点击炼药锅即可制作各种不同用途的箭！",
    "howtoplay.cauldron.header.3":"给盔甲染色",
        "howtoplay.cauldron.text.5.touch":"若要给皮革盔甲或皮革马铠染色，请在持有所需染料时，点击填满水的炼药锅。这会改变炼药锅中水的颜色。然后，在手中拿着盔甲时点击炼药锅即可将您的盔甲浸入炼药锅中。",
    "howtoplay.cauldron.text.6":"如果您想要洗去染色，只需将染色物品浸入填有未染色的水的炼药锅中即可。",
    "howtoplay.chat":"聊天",
    "howtoplay.chat.title":"游戏指南：聊天",
            "howtoplay.chat.text.1.touch":"点击“聊天”按钮以打开聊天。键入消息，然后点击“发送”按钮。",
    "howtoplay.chests":"箱子",
    "howtoplay.chests.title":"游戏指南：箱子",
        "howtoplay.chests.text.1.touch":"在您制成箱子后，您可以将其置于世界中，然后以点击方式打开箱子并存放您的物品栏中的物品。",
    "howtoplay.chests.text.2":"存放在箱子中的物品可供您稍后放入您的物品栏中。",
    "howtoplay.chests.text.3":"将合并相邻放置的两个箱子，以合成一个大箱子。",
    "howtoplay.commandBlocks":"命令方块",
    "howtoplay.commandBlocks.title":"游戏指南：命令方块",
    "howtoplay.commandBlocks.text.1":"命令方块对于地图创建者而言是一个功能非常强大的工具。这些命令方块可存储命令，并会在收到红石信号后执行命令。",
    "howtoplay.commandBlocks.text.2":"若要获取命令方块，您必须使用 /give。",
    "howtoplay.commandBlocks.text.3":"在命令方块成功执行或未能执行其存储的命令时，它都会从箭头所指的那一侧发出红石信号。",
    "howtoplay.commandBlocks.text.4":"您可以在“悬停注释”字段中设置命令方块的名称。",
    "howtoplay.commandBlocks.text.5":"方块类型 - 有三种类型的命令方块，每一种都有自己独有的颜色和行为：",
    "howtoplay.commandBlocks.text.5.1":"  - 脉冲 - 仅在方块收到红石信号时才会执行存储的命令。",
    "howtoplay.commandBlocks.text.5.2":"  - 连锁 - 无论其前面的命令方块是否已执行其命令，都会执行存储的命令。",
    "howtoplay.commandBlocks.text.5.3":"  - 重复 - 激活后，只要此命令方块存在，它就会继续执行其存储的命令。",
    "howtoplay.commandBlocks.text.6":"条件 - 有两个条件，每一个条件都会影响命令方块的行为：",
    "howtoplay.commandBlocks.text.6.1":"  - 无条件 - 即使其后面的命令方块未能执行其命令，也会执行存储的命令。",
    "howtoplay.commandBlocks.text.6.2":"  - 有条件 - 仅当其后面的命令方块成功执行其命令时，才会执行存储的命令。",
    "howtoplay.commandBlocks.text.7":"红石 - 有两种红石设置，每一种都会影响命令方块的行为：",
    "howtoplay.commandBlocks.text.7.1":"  - 需要红石 - 需要红石信号才能激活。",
    "howtoplay.commandBlocks.text.7.2":"  - 始终活动 - 不需要红石信号也能激活。",
    "howtoplay.commandBlocks.text.8":"命令方块还将向您显示其以前的输出。这可帮助您了解命令方块是否未能执行其命令及原因。",
    "howtoplay.commands":"命令",
    "howtoplay.commands.title":"游戏指南：命令",
    "howtoplay.commands.text.1":"可通过聊天执行命令。在您键入命令之前，请先键入 /。",
    "howtoplay.commands.text.2":"有大量命令，使您能够做令人惊奇的事情。有许多来源出自这些命令，可提供给您所需要的所有信息。",
    "howtoplay.conduits":"潮涌核心",
    "howtoplay.conduits.title":"游戏指南：潮涌核心",
    "howtoplay.conduits.text.1":"当您处于水下时，处于激活状态的潮涌核心会给您提供能量。",
    "howtoplay.conduits.text.2":"一个潮涌核心由若干鹦鹉螺壳和一枚海洋之心制成。潮涌核心会从海晶石和海晶灯中吸取能量。",
    "howtoplay.conduits.header.1":"建设",
    "howtoplay.conduits.text.3":"一旦被激活，潮涌核心会将潮涌能量赋予给附近的任何物体。",
    "howtoplay.conduits.text.4":"其吸取的能量越多，能力的作用范围就越远。",
    "howtoplay.controls":"控制",
    "howtoplay.controls.title":"游戏指南：控制",
    "howtoplay.controls.text.1":"《我的世界》是一款通过堆方块创造出一切您所想事物的游戏。怪物会在夜晚出没，所以要提前建造一个避难所。",
    "howtoplay.controls.header.1":"移动",
    "howtoplay.controls.text.2.keyboard":"使用鼠标可环顾四周。",
        "howtoplay.controls.text.2.touch":"触摸并沿屏幕拖动可环顾四周。",
                                                                        "howtoplay.controls.header.2":"打破和放置",
        "howtoplay.controls.text.6.touch":"触摸并按住方块所在的屏幕，可用手或者手里的东西开采和砍劈。您可能需要制作一件工具来开采一些方块。",
                    "howtoplay.controls.text.7.touch":"如果您手里正握着一件物品，触摸屏幕来使用该物品，或者触摸并按住热键中的物品来丢弃它。",
    "howtoplay.controls.header.3":"潜行",
                        "howtoplay.controls.text.swim.keyboard":"在水中奔跑会使您游泳。使用鼠标来控制您游泳的方向。",
        "howtoplay.controls.text.swim.touch":"在水中奔跑会使您游泳。触摸屏幕并沿着屏幕拖动来控制您游泳的方向。",
            "howtoplay.worldBuilder":"世界建造者",
    "howtoplay.worldBuilder.title":"游戏指南：世界建造者",
        "howtoplay.worldBuilder.text.2":"启用作弊后，主机可启用或禁用这个世界中任何玩家的世界建造者能力。",
    "howtoplay.worldBuilder.text.3":"如果想让这个世界的所有玩家获得世界建造者能力，那么请运行下述命令：",
    "howtoplay.worldBuilder.text.4":"/ability @a worldbuilder true",
    "howtoplay.worldBuilder.text.5":"如果想快速打开您自己的世界建造者能力，请运行下述命令中的一个：",
    "howtoplay.worldBuilder.text.6":"/worldbuilder",
    "howtoplay.worldBuilder.text.7":"/wb",
    "howtoplay.worldBuilder.text.8":"如果想查询您的世界建造者能力，请运行下述命令：",
    "howtoplay.worldBuilder.text.9":"/ability @p worldbuilder",
    "howtoplay.permissionBlocks":"权限块",
    "howtoplay.permissionBlocks.title":"游戏指南：权限块",
        "howtoplay.permissionBlocks.title.1":"允许/拒绝方块",
    "howtoplay.permissionBlocks.text.2":"允许和拒绝方块可控制在一个世界中可供玩家进行建造的地方。",
    "howtoplay.permissionBlocks.text.3":"用户可以在允许方块上放置或摧毁方块。用户不可以在拒绝方块上放置或摧毁方块。",
    "howtoplay.permissionBlocks.text.4":"允许和拒绝方块不会影响他们下方的区域。",
    "howtoplay.permissionBlocks.text.5":"下方有拒绝方块的允许方块会阻止用户在这个两个方块中间进行建造。用户可以在允许方块上方放置和摧毁方块。",
    "howtoplay.permissionBlocks.title.2":"边界方块",
    "howtoplay.permissionBlocks.text.6":"边界方块可提供一个能向上和向下无线延伸的力场，这个力场不受其他方块的影响。用户无法穿过，挪开或从下方穿过边界方块。用户也无法在边界方块上方或下方放置或摧毁方块。",
    "howtoplay.chalkboard":"黑板",
    "howtoplay.chalkboard.title":"游戏指南：黑板",
        "howtoplay.chalkboard.text.1.touch":"黑板可以用来显示世界中的文本。相较于告示牌，黑板能够显示的文本更多，并且可以在不被摧毁的情况下进行编辑。锁定切换可让您阻止非世界建造者摧毁或编辑您的黑板。点击现有黑板可对其进行编辑。",
    "howtoplay.chemistry":"化学",
    "howtoplay.chemistry.title":"游戏指南：化学",
    "howtoplay.chemistry.text.1":"用户可使用化学设备块模拟真实世界的化学反应。通过调整元素构造器的滑动条可制作 118 种不同元素中的一种，或者将元素放元素构造器中可查看元素的成分。在化合物创建器中合成元素，以制造化合物。将元素和化合物放到实验台上可创建 Minecraft 物品。使用材料分解器可将方块分解为其组成元素。",
        "howtoplay.npc":"非玩家角色",
    "howtoplay.npc.title":"游戏指南：非玩家角色",
    "howtoplay.npc.text.1":"NPC 是能够提供额外的课程信息、提示或者指导的非玩家角色。",
    "howtoplay.npc.text.2":"只有世界建造者能够放置、删除、命名或编辑非用户角色。非用户角色可以执行命令和网站链接。命令可在非用户角色的对话窗口中分配到按钮上；网站链接始终都会有按钮。",
    "howtoplay.npc.text.3":"NPC 有大量皮肤可供选择，是稳定的。",
    "howtoplay.camera":"摄像机",
    "howtoplay.camera.title":"游戏指南：摄像机",
    "howtoplay.camera.text.1":"摄像机能够允许玩家在世界中拍照。",
        "howtoplay.camera.text.2.touch":"如果要用您的视角拍照片，请点击并按住，然后释放。",
        "howtoplay.camera.text.3.touch":"自拍时，放置摄像机，点击拍照按钮。",
    "howtoplay.camera.text.4":"您可以在相片簿中查看照片，或者将其插入“书和羽毛笔”。",
    "howtoplay.portfolio":"相片簿",
    "howtoplay.portfolio.title":"游戏指南：相片簿",
        "howtoplay.portfolio.text.1.touch":"您拍摄的照片会出现在相片簿中。按住可查看相片簿。查看相片簿时，您可以为图片添加标题，删除图片，将图片导出为一系列图片。",
    "howtoplay.classroomMode":"教室模式",
    "howtoplay.classroomMode.title":"游戏指南：教室模式",
            "howtoplay.codeBuilder":"代码编辑器",
    "howtoplay.codeBuilder.title":"游戏指南：代码编辑器",
    "howtoplay.codeBuilder.text.1":"代码编辑器可让玩家使用自己熟悉的编程学习平台，写代码，探索、创建和玩《我的世界》。",
            "howtoplay.crafting":"合成",
    "howtoplay.crafting.title":"游戏指南：合成",
            "howtoplay.crafting.text.1.touch":"点击物品栏按钮可访问配方书和网格合成表。",
            "howtoplay.crafting.header.1":"网格合成表",
    "howtoplay.crafting.text.2":"按各物品配方的形状排列物品栏中的物品或网格合成表中的热键。",
    "howtoplay.crafting.text.3":"如果配方正确，您尝试合成的物品将出现在网格合成表右侧的输出槽中。请从输出槽中取出该物品并将其放入物品栏。现在，您可以使用该物品了。",
    "howtoplay.crafting.text.4":"有很多配方，部分配方将需要比一开始所使用的 2x2 网格更大的网格合成表。",
    "howtoplay.crafting.text.5":"用 4 块木板来制作 1 个工作台并将其放到世界中。",
                    "howtoplay.crafting.text.6.touch":"点击世界中的工作台来获得一个 3x3 网格合成表。",
    "howtoplay.crafting.header.2":"配方书",
    "howtoplay.crafting.text.7":"在屏幕左侧，您将看到配方书，当您不知道配方或者希望快速合成已知配方时，查看配方书是不错的选择。您还会在屏幕右侧的物品栏上方看到网格合成表。",
            "howtoplay.crafting.text.8.touch":"找到要合成的配方后，点击配方将其加载至网格合成表，然后点击输出槽中的物品以进行合成。按住输出槽中的物品可持续合成。",
        "howtoplay.craftingTable":"工作台",
    "howtoplay.craftingTable.title":"游戏指南：工作台",
    "howtoplay.craftingTable.text.1":"工作台让您可以合成更复杂的配方。",
        "howtoplay.craftingTable.text.2.touch":"将它放到世界中，然后点击工作台来使用它。",
    "howtoplay.creativeMode":"创造模式",
    "howtoplay.creativeMode.title":"游戏指南：创造模式",
    "howtoplay.creativeMode.text.1":"创造模式使您能够不受限制地创建包含各种所想生物的土地！",
    "howtoplay.creativeMode.header.1":"无限构造",
    "howtoplay.creativeMode.text.2":"在创造模式界面中，游戏中的任何物品都可移到玩家的物品栏中，无需挖掘或制农作物品。当在世界中放置或使用玩家物品栏中的物品时，不会移除这些物品，这使玩家能够专注于创建而不是资源收集。",
    "howtoplay.creativeMode.text.3":"如果您在创造模式下创造、加载或保存世界，那么即使是随后载入到生存模式，您在该世界中的成就及排行榜更新也会被禁用。",
    "howtoplay.creativeMode.header.2":"飞行",
                "howtoplay.difficulty":"难度",
    "howtoplay.difficulty.title":"游戏指南：难度",
    "howtoplay.difficulty.text.1":"《我的世界》有不同的难度级别，因此您可以根据您的水平定制游戏。",
    "howtoplay.difficulty.header.1":"和平",
    "howtoplay.difficulty.text.2":"除了潜影贝和末影龙之外，不存在任何敌对生物，但潜影贝和末影龙也不会伤害您。",
    "howtoplay.difficulty.header.2":"简单",
    "howtoplay.difficulty.text.3":"会生成敌对生物，但其造成的伤害较少。饥饿条会消耗，且生命值降低至 5 颗心。",
    "howtoplay.difficulty.header.3":"普通",
    "howtoplay.difficulty.text.4":"敌对生物会造成一般伤害，如果您的饥饿程度降为零，您的生命值也会开始下降，但不会死亡。",
    "howtoplay.difficulty.header.4":"困难",
    "howtoplay.difficulty.text.5":"敌对生物会造成更大的伤害，僵尸会破门而入，如果您的饥饿程度降为零，您的生命值也会下降并且可能会死亡。",
    "howtoplay.dispensers":"发射器",
    "howtoplay.dispensers.title":"游戏指南：发射器",
    "howtoplay.dispensers.text.1":"发射器用于抛射物品。您需要将红石信号（例如，一根拉杆）放置于每个发射器旁边才能触发它。",
        "howtoplay.dispensers.text.2.touch":"若要填充发射器，请点击发射器，然后将想要发射的物品从您的物品栏移到发射器。",
    "howtoplay.dispensers.header.1":"用法",
    "howtoplay.dispensers.text.3":"只要您为发射器提供能量，发射器就会抛射物品。",
    "howtoplay.dispensers.text.4":"发射器也可用于放置物品，如将南瓜放置于铁傀儡上，或将装备放置于盔甲架上。",
    "howtoplay.droppers":"投掷器",
    "howtoplay.droppers.title":"游戏指南：投掷器",
        "howtoplay.droppers.text.1.touch":"当由红石提供能量时，投掷器会随机投掷其中包含的一个物品。点击投掷器即可打开它，然后可以将您物品栏中的物品加载到其中。",
    "howtoplay.droppers.header.1":"用法",
    "howtoplay.droppers.text.2":"如果投掷器面朝箱子或其他类型的容器，反而会将物品置于其中。可以构建长链投掷器以实现远距离传输物品。",
    "howtoplay.dyes":"染料",
    "howtoplay.dyes.title":"游戏指南：染料",
    "howtoplay.dyes.text.1":"染料可用于改变《我的世界》中许多事物的颜色。",
    "howtoplay.dyes.text.2":"有些染料的材料比其他染料更难找到。大多数染料可以用花朵合成（例如用罂粟花合成红色染料），但一些染料的发现或制作方式更隐蔽，比如：",
    "howtoplay.dyes.text.3":"- 挖掘地下深层中的青金石",
    "howtoplay.dyes.text.4":"- 收集水下的墨囊",
    "howtoplay.dyes.text.5":"- 采集丛林中的可可豆",
    "howtoplay.dyes.text.6":"- 绿色染料必须通过熔化仙人掌才能获得",
    "howtoplay.dyes.text.7":"- 骨粉可以帮助植物和树木生长，也可以用来合成白色染料",
    "howtoplay.dyes.text.8":"- 从鱿鱼上收集墨囊以制作黑色染料",
    "howtoplay.elytra":"鞘翅",
    "howtoplay.elytra.title":"游戏指南：鞘翅",
    "howtoplay.elytra.text.1":"鞘翅是一种用于允许滑翔的可装备物品。鞘翅装备在胸部盔甲槽中。",
    "howtoplay.elytra.text.2":"鞘翅无法制作，但可在稀少的末地船（由可怕的潜影贝把守）中的物品展示框中找到。",
    "howtoplay.elytra.header.1":"学习飞行",
            "howtoplay.elytra.text.4":"滑翔期间，您可以通过环顾四周来掌控方向。朝下看时，会加快移动 - 但也会更快地撞向地面。朝上看时，会获得一些高度 - 但时间过长，您会失速、坠落而不是上升！",
    "howtoplay.elytra.text.5":"飞行时您的鞘翅的耐性用会降低。 您可以在铁砧上使用幻翼膜将鞘翅合并起来，修复他们。 如果在飞行过程中断裂，那么您将会掉到地上，小心点！",
    "howtoplay.elytra.header.2":"火箭动力飞行",
    "howtoplay.elytra.text.6":"无效的焰火火箭可用于延长鞘翅飞行。如果您使用有效的焰火火箭来延长飞行，则您会受伤。",
    "howtoplay.enchantingTable":"附魔台",
    "howtoplay.enchantingTable.title":"游戏指南：附魔台",
    "howtoplay.enchantingTable.text.1":"通过拾取经验球收集到的经验点可用于附魔武器、盔甲、工具和书。",
    "howtoplay.enchantingTable.header.1":"附魔",
    "howtoplay.enchantingTable.text.2":"当将可附魔物品放置于附魔台中书下方的槽中时，该槽右侧的三个按钮会显示一些附魔项及其经验级别损耗和青金石损耗。",
    "howtoplay.enchantingTable.text.3":"实际应用的附魔是基于显示的损耗随机选取的。",
    "howtoplay.enchantingTable.header.2":"更强大的附魔",
    "howtoplay.enchantingTable.text.4":"如果附魔台环绕着书架（最多 15 个）且书架和附魔台间隔一个方块，则会看到附魔台上书中的晦涩铭文，附魔的效力将会增加。",
    "howtoplay.enchantingTable.header.3":"附魔书",
    "howtoplay.enchantingTable.text.5":"在铁砧上使用附魔书可将附魔加持到物品上。这使您可以进一步控制要对您的物品加持的附魔。",
    "howtoplay.endCities":"末地城",
    "howtoplay.endCities.title":"游戏指南：末地城",
    "howtoplay.endCities.text.1":"在杀死末影龙后，会显示末地折跃门。将末影珍珠投入该传送门会将您瞬移到外岛。",
    "howtoplay.endCities.text.2":"此全新的异域场景一定会隐藏一些有趣的物品，也许是您可以带回的物品。",
    "howtoplay.enderChest":"末影箱",
    "howtoplay.enderChest.title":"游戏指南：末影箱",
    "howtoplay.enderChest.text.1":"世界中的所有末影箱都互相关联。您可从任一末影箱内获取置于其他末影箱内的物品。但是，对于每个玩家来说，末影箱中所装物品都是特定的。这让玩家可将物品存储在任一末影箱内，然后从世界不同位置的其他末影箱内取回它们。",
    "howtoplay.eyeOfEnder":"末影之眼",
    "howtoplay.eyeOfEnder.title":"游戏指南：末影之眼",
    "howtoplay.eyeOfEnder.text.1":"末影之眼与末地神秘相连，在使用时表现得非常奇怪。",
    "howtoplay.eyeOfEnder.text.2":"传言它们可能会导致您打开另一个维度。",
    "howtoplay.farming":"种植",
    "howtoplay.farming.title":"游戏指南：种植",
    "howtoplay.farming.text.1":"您可以在《我的世界》中种植各种不同的农作物。种植虽然具有挑战性，但能够无限量地提供食物来源。",
    "howtoplay.farming.header.1":"未雨绸缪",
    "howtoplay.farming.text.2":"农作物需要光、水和农地才能生长。您需要锄头、水源和种子才能种植。",
    "howtoplay.farming.text.3":"水旁边的方块需要转化为农地，为此需要使用锄头。水最多可灌溉四个方块。",
    "howtoplay.farming.header.2":"种植和收获",
    "howtoplay.farming.text.4":"现在，您可以种下您的种子。请确保您的农作物受到保护，因为遭踩踏或者缺少水或光很容易导致它们死亡。",
    "howtoplay.farming.text.5":"栅栏可帮助保护您的农作物，使其免受饥肠辘辘的兔子祸害或遭到踩踏！",
    "howtoplay.farming.text.6":"农作物成熟后，它们的外观会发生变化，并且可以收割。",
    "howtoplay.farming.text.7":"诸如南瓜和西瓜之类的植物生长在茎上。小心不要收割这些茎！",
    "howtoplay.fireworks":"焰火",
    "howtoplay.fireworks.title":"游戏指南：焰火",
    "howtoplay.fireworks.text.1":"焰火是一种在《我的世界》中创建自己独特庆祝的有趣方式！",
    "howtoplay.fireworks.text.2":"焰火有两个部分，即焰火火箭和焰火之星。",
    "howtoplay.fireworks.header.1":"焰火火箭",
        "howtoplay.fireworks.text.3.touch":"若要使用焰火，只需点击方块即可将焰火发射到空中。",
    "howtoplay.fireworks.text.4":"焰火除了向上射入空中之外没有其他作用。",
    "howtoplay.fireworks.header.2":"焰火之星",
    "howtoplay.fireworks.text.5":"在制作焰火火箭的过程中，可以添加焰火之星，以赋予它许多不同的颜色和效果。",
    "howtoplay.fireworks.text.6":"焰火之星由火药和其他各种物品制成。",
    "howtoplay.fireworks.text.6.1":"  - 颜色 - 添加任何颜色的染料可实现以该颜色爆炸。",
    "howtoplay.fireworks.text.6.2":"  - 闪烁 - 添加荧石粉可实现爆炸闪烁。",
    "howtoplay.fireworks.text.6.3":"  - 爬行者形状 - 添加头部可在空中形成爬行者图案。",
    "howtoplay.fireworks.text.6.4":"  - 爆发 - 添加羽毛可给予爆炸一个爆发效果。",
    "howtoplay.fireworks.text.6.5":"  - 拖尾 - 添加钻石可给予爆炸拖尾效果。",
    "howtoplay.fireworks.text.6.6":"  - 星形 - 添加金粒可在空中形成星形图案。",
    "howtoplay.fireworks.header.3":"焰火制造术",
    "howtoplay.fireworks.text.7":"焰火可由发射器发射。将以发射器的朝向方向发射焰火。",
    "howtoplay.fishing":"钓鱼",
    "howtoplay.fishing.title":"游戏指南：钓鱼",
    "howtoplay.fishing.text.1":"必须使用钓鱼竿来钓鱼，这是从海里捕获某种鱼或其他炫酷物品的绝佳方式！",
    "howtoplay.fishing.header.1":"抛",
        "howtoplay.fishing.text.2.touch":"盯着水中的一个方块，在持有钓鱼竿的同时点击“钓鱼”按钮即可将饵钩抛进水里。",
    "howtoplay.fishing.header.2":"开始钓鱼！",
    "howtoplay.fishing.text.3":"等待直至您留意到饵钩处出现泡泡的痕迹。",
        "howtoplay.fishing.text.4.touch":"当泡泡碰到饵钩时，饵钩会上下摆动。再次点击“钓鱼”按钮可收回饵钩。小心不要让鱼跑掉！",
    "howtoplay.furnace":"熔炉",
    "howtoplay.furnace.title":"游戏指南：熔炉",
    "howtoplay.furnace.text.1":"您可以使用熔炉烹饪或熔化物品。例如，可以将铁矿石熔化为铁锭。",
        "howtoplay.furnace.text.2.touch":"将熔炉置于世界中，通过点击方式使用它。",
    "howtoplay.furnace.header.1":"燃料",
    "howtoplay.furnace.text.3":"您需要在熔炉底部放一些燃料并将您想要熔化的物品放在熔炉上面。熔炉随后会点燃并开始工作。许多东西都可以用作燃料；尝试使用任何可燃之物！",
    "howtoplay.gameSettings":"游戏设置",
    "howtoplay.gameSettings.title":"游戏指南：游戏设置",
    "howtoplay.gameSettings.text.1":"创建世界时，您有多个选项。以下是可用来微调您的体验的各种设置。如果您在创建世界时未设置它们，不用担心，您可以随时更改这些设置。",
    "howtoplay.gameSettings.text.2":"-世界名称：您可以在此处对您的世界进行命名。",
    "howtoplay.gameSettings.text.3":"-默认游戏模式：这是所有新玩家进入世界的初始游戏模式。您可以让玩家从生存模式或创造模式开始。选择创造模式将会开启作弊。",
    "howtoplay.gameSettings.text.4":"-难度：该设置会影响世界的难度等级。您可以选择和平、简单、一般或困难。",
    "howtoplay.gameSettings.header.1":"世界偏好",
    "howtoplay.gameSettings.text.5":"-初始地图：如果启用该设置，每位玩家都可以在其热键中开始玩一个地图。",
    "howtoplay.gameSettings.text.6":"-奖励箱子：如果启用该设置，则在您的初始出生位置附近将会有一个箱子，其中包含一些初始战利品。",
    "howtoplay.gameSettings.text.7":"-世界类型：该设置控制世界的创建方式。通过从下拉菜单中选择无限、平坦或旧的来更改世界类型。",
    "howtoplay.gameSettings.text.7.1":"  - 无限世界永无止尽。",
    "howtoplay.gameSettings.text.7.2":"  - 平坦世界中没有任何山丘或树木，仅仅是可供您在其中进行创建的无限平坦区域。",
    "howtoplay.gameSettings.text.7.3":"  - 旧世界的大小和高度受限。",
    "howtoplay.gameSettings.text.8":"-种子：这是世界的唯一代码。通过在创造新世界时输入种子，您可以控制它的创建方式。您也可以使用字或词组作为种子，游戏会为您将其转换为数字。",
    "howtoplay.gameSettings.header.2":"作弊和游戏规则",
    "howtoplay.gameSettings.text.9":"-激活作弊：该设置允许玩家使用命令。如果在创建世界时此设置处于启用状态，则会禁用所有成就。",
    "howtoplay.gameSettings.text.10":"下面是必须启用作弊才能使用的游戏规则：",
    "howtoplay.gameSettings.text.11":"-终为白日：启用该设置时，夜晚永远不会降临。",
    "howtoplay.gameSettings.text.12":"-开启昼夜更替：禁用该设置时，时间不会前进。",
    "howtoplay.gameSettings.text.13":"-保留物品栏：该设置允许玩家在死亡时保留其物品栏。",
    "howtoplay.gameSettings.text.14":"-生物生成：禁用该设置时会阻止所有生物生成。",
    "howtoplay.gameSettings.text.15":"-生物破坏：阻止生物摧毁世界。",
    "howtoplay.gameSettings.text.16":"-实体掉落战利品：控制矿车和盔甲架等物品在损坏后是否会掉落矿车和盔甲架。",
    "howtoplay.gameSettings.text.17":"-天气更替：禁用该设置后天气将不会更替。",
    "howtoplay.hoppers":"漏斗",
    "howtoplay.hoppers.title":"游戏指南：漏斗",
    "howtoplay.hoppers.text.1":"漏斗用于自动移送物品。漏斗可以连接到其他一些物品，例如箱子或唱片机等容器。",
    "howtoplay.hoppers.text.2":"漏斗会持续从放置在其上的容器中移除物品，并把物品移入漏斗所指向的容器中。",
    "howtoplay.hoppers.header.1":"用法",
    "howtoplay.hoppers.text.3":"要使漏斗指向特定方块，请在潜行时将漏斗置于该方块上。",
    "howtoplay.hoppers.text.4":"如果漏斗由红石提供能量，漏斗会变成非活动状态并停止移动物品。",
    "howtoplay.hostAndPlayerOptions":"主控者和玩家选项",
    "howtoplay.hostAndPlayerOptions.title":"游戏指南：主控者和玩家选项",
    "howtoplay.hostAndPlayerOptions.text.1.notTouch":"当在启用作弊的情况下玩游戏时，您可以通过主控者选项传送您自己或好友、更改天气、设置当日时间、更改游戏的入口点或世界生成。启用作弊后，您可以通过点击聊天栏旁边的 [/] 按钮在聊天窗口中找到这些选项。",
    "howtoplay.hostAndPlayerOptions.text.1.touch":"当在启用作弊的情况下玩游戏时，您可以通过主控者选项传送您自己或好友、更改天气、设置当日时间、更改游戏的入口点或世界生成。启用作弊后，您可以通过点击“聊天”按钮在聊天窗口中找到这些选项。",
    "howtoplay.HUD":"HUD",
    "howtoplay.HUD.title":"游戏指南：HUD",
    "howtoplay.HUD.text.1":"HUD 会显示关于您的状态、生命值、剩余氧气（当您位于水下时）、饥饿程度和盔甲（如果您有穿盔甲）的信息。",
    "howtoplay.HUD.header.1":"食物和生命值",
                        "howtoplay.HUD.text.3.touch":"按住一份食物即可进食。",
        "howtoplay.HUD.header.2":"经验",
    "howtoplay.HUD.text.5":"经验条也会显示在 HUD 上。该数值显示您当前的经验级别，并且该条会指示需要多少经验点才能提升您的经验级别。",
    "howtoplay.HUD.text.6":"通过收集经验球可获得经验点。您可从杀死生物、挖掘特定方块等活动中获得经验球！请勿错过任何经验球，您将需要它们。靠近经验球即可进行收集。",
    "howtoplay.HUD.header.3":"热键",
    "howtoplay.HUD.text.7.keyboard":"热键显示可供使用的物品。滚动鼠标滚轮即可更改您手中的物品。",
        "howtoplay.HUD.text.7.touch":"热键显示可供使用的物品。点击热键中的物品即可更改您手中的物品。",
            "howtoplay.inventory":"物品栏",
    "howtoplay.inventory.title":"游戏指南：物品栏",
                    "howtoplay.inventory.text.1.touch":"点击物品栏选项卡来查看物品栏。",
    "howtoplay.inventory.text.2":"此屏幕显示了您手里可用的物品和您携带的所有其他物品。盔甲也在这里显示。",
            "howtoplay.inventory.text.3.touch":"点击来选择一个物品。如果这里有一个以上物品，该动作会选择所有物品。",
            "howtoplay.inventory.text.4.touch":"点击物品栏的其他位置来移动物品。",
            "howtoplay.inventory.text.6.keyboard":"若要投掷物品，请选取物品并将其放置在物品栏窗口外部。",
        "howtoplay.inventory.text.6.touch":"若要投掷物品，请点击物品，然后点击物品栏窗口外部。",
    "howtoplay.jukebox":"唱片机",
    "howtoplay.jukebox.title":"游戏指南：唱片机",
    "howtoplay.jukebox.text.1":"唱片机将播放您找到的音乐唱片。",
    "howtoplay.jukebox.header.1":"开始派对",
        "howtoplay.jukebox.text.2.touch":"手里拿着音乐唱片的同时点击唱片机来播放它。再次点击唱片机可弹出音乐唱片。",
    "howtoplay.jukebox.header.2":"红石",
    "howtoplay.jukebox.text.3":"当唱片机播放音乐唱片时，将为红石粉提供能量。",
    "howtoplay.jukebox.text.4":"尝试播放不同的音乐唱片来获得不同的能量等级。",
    "howtoplay.jukebox.text.5":"看看当让唱片播放到结尾时会发生什么。",
    "howtoplay.jukebox.text.6":"一个漏斗可供您放入一张音乐唱片，在唱片播放完后，请取出该唱片。",
    "howtoplay.jukebox.header.3":"查找音乐唱片",
    "howtoplay.jukebox.text.7":"可以在世界各处的箱子里找到一些音乐唱片。",
    "howtoplay.jukebox.text.8":"其他唱片查找起来较为困难，爬行者会秘密欣赏音乐。",
    "howtoplay.loom":"织布机",
    "howtoplay.loom.title":"游戏指南：织布机",
    "howtoplay.loom.text.1":"织布机可以迅速而有效地将图案应用到旗帜上。织布机一次只使用一种染料来织造图案。它还可以使用织布机图案来应用特殊的图案。",
    "howtoplay.loom.header.1":"编织",
    "howtoplay.loom.text.2":"通过将旗帜放置进织布机的第一个槽位，并将任一颜色的染料放进第二个槽位，就可以向旗帜上添加图案。一旦选择了某个图案，就可以将它从右边的输出槽位移到您的物品栏中。",
    "howtoplay.loom.text.3":"一个旗帜可以有多个层，让您试验旗帜许多不同的可能性。一个旗帜上至多可以应用 6 种图案，以创造出独特的设计。",
    "howtoplay.loom.header.2":"织布机图案",
    "howtoplay.loom.text.4":"通过将一个织布机图案添加到织布机的第三个槽位，可以合成特殊图案，例如爬行者的脸或花卉图案。当将这些图案添加到您的旗帜时，您不会失去您的织布机图案。",
    "howtoplay.mounts":"骑乘",
    "howtoplay.mounts.title":"游戏指南：骑乘",
    "howtoplay.mounts.text.1":"玩家可以骑乘所有成年的马、驴或骡子。只有马可以穿盔甲。",
    "howtoplay.mounts.text.2":"骡子和驴可以通过挂一个箱子来装备鞍囊（用于运输物品）。在骑乘或潜行时均可使用这些鞍囊。",
    "howtoplay.mounts.header.1":"驯服",
        "howtoplay.mounts.text.3.touch":"马、驴和骡子在利用之前必须先驯服。要驯服一匹马，需要先骑上去，在它想把您摔下来的时候保持不掉下来。点击在靠近一匹马时出现的“骑乘”按键来试图驯服马、驴和骡子。",
    "howtoplay.mounts.text.4":"当马周围出现心时，表示它已经被驯服，将不再试图将玩家摔下马背。",
    "howtoplay.mounts.header.2":"骑乘动物",
    "howtoplay.mounts.text.5":"玩家必须给马装备鞍才能驾驭它。",
    "howtoplay.mounts.text.6":"可以从村民那里购买鞍，在世界里的隐藏箱子里找到鞍，或者通过钓鱼获得鞍。当骑马时，打开物品栏并将一个鞍放入马鞍槽。",
    "howtoplay.mounts.text.7":"和其他动物一样，马和驴都可以用金苹果或金胡萝卜喂食。",
    "howtoplay.mounts.text.8":"小马驹随后会长成成年马，喂食小麦或干草可加速其成长。",
    "howtoplay.mounts.header.3":"驮畜",
    "howtoplay.mounts.text.9":"羊驼是另一可以驯服的可骑乘生物，可用来运输大件物品。",
    "howtoplay.mounts.text.10":"可以像驯服马一样驯服羊驼。但即使已经驯服羊驼，玩家在骑乘它们时仍然无法控制它们的行动。",
    "howtoplay.mounts.text.11":"可以用一根拴绳拴住一只羊驼，随后周围的羊驼（驯服和未驯服的羊驼）都将跟随其后，组成一支商队。",
    "howtoplay.mounts.text.12":"可以给羊驼装备箱子，根据羊驼的体力，给予羊驼 3 到 15 格物品栏空间。还可以给羊驼装备地毯。各色地毯的图案都各不相同。",
    "howtoplay.mounts.header.4":"猪",
    "howtoplay.mounts.text.13":"也可以骑乘猪，但如果您不采取激励手段，它们不会前往您想去的地方。",
    "howtoplay.mounts.text.14":"给猪装备鞍，然后将胡萝卜钓竿指向您想去的方向。",
    "howtoplay.mounts.header.5":"跳下",
            "howtoplay.multiplayer":"多人游戏",
    "howtoplay.multiplayer.title":"游戏指南：多人游戏",
    "howtoplay.multiplayer.text.1":"《我的世界》默认为多人游戏。",
    "howtoplay.multiplayer.header.1":"拆分屏幕",
    "howtoplay.multiplayer.text.2.splitscreen":"您可以让本地玩家加入游戏，方法是连接控制器并在游戏期间的任一时间点按下其控制器上的任一按钮。",
    "howtoplay.multiplayer.header.2":"在线多人游戏",
    "howtoplay.multiplayer.text.3":"所有世界开始时默认启用多人游戏模式。如果您想让世界变成单人模式，转到“世界设置”并选择“多人游戏”选项，然后将多人游戏模式关闭。",
    "howtoplay.multiplayer.text.3.norealms":"所有世界开始时默认启用多人游戏模式。如果您想让世界变成单人模式，转到“世界设置”并选择“多人游戏”选项，然后将多人游戏模式关闭。",
    "howtoplay.multiplayer.header.3":"正在加入在线游戏",
    "howtoplay.multiplayer.text.4":"要加入多人游戏，请转到“好友”选项卡。所有可加入的 Realms、好友和局域网游戏都将在此处显示。选择某个游戏并选中它来加入。",
    "howtoplay.multiplayer.text.4.norealms":"要加入多人游戏，请转到“好友”选项卡。所有可加入的 Realms、好友和局域网游戏都将在此处显示。选择某个游戏并选中它来加入。",
    "howtoplay.multiplayer.text.5":"当您开始或加入在线游戏时，游戏将在您的“好友”选项卡中对大家可见。如果您的好友已加入，游戏将立即对这些好友的好友可见。",
    "howtoplay.multiplayer.text.6":"注意：您必须具有互联网连接并且必须登录至 Microsoft 账户才能玩多人游戏。",
    "howtoplay.multiplayer.header.4":"玩家权限",
    "howtoplay.multiplayer.text.7":"如果您想要管理各个玩家的权限，玩家权限使其变得非常容易。打开暂停菜单，您会在右侧看到当前在世界中的玩家列表。选择其权限图标可调整该玩家的权限。",
    "howtoplay.navigation":"导航",
    "howtoplay.navigation.title":"游戏指南：导航",
    "howtoplay.navigation.text.1":"导航是您在《我的世界》中将要学习的一项重要技能，因为有时找到回家之路并非易事。",
    "howtoplay.navigation.text.2":"首先，您应该对一些基本工具有所了解。",
    "howtoplay.navigation.header.1":"导航工具",
    "howtoplay.navigation.text.3":"指南针将指向您在世界中的第一个出生地的方向，此方法可让您轻松找到您的出发位置。",
    "howtoplay.navigation.text.4":"地图使您能够查看已经探索过的区域。将其置于您的副手槽中并像使用小地图一样使用它。您可以通过在工作台上向地图边缘添加更多纸来扩大其尺寸。",
    "howtoplay.navigation.text.5":"定位器地图将显示您的所在位置以及您相对于定位器地图原点的朝向。它也会向您显示同一个世界中其他玩家的位置。",
    "howtoplay.navigation.text.6":"制图台可以帮助您创建、扩展、复制甚至命名地图。",
    "howtoplay.navigation.text.7":"把纸放进第一个槽来合成地图。如果您在第二个槽中加入一个指南针，您可以合成一个定位器地图。添加纸或空白地图将允许您扩展或复制您的地图。",
    "howtoplay.navigation.header.2":"导航技术",
    "howtoplay.navigation.text.8":"请尽量在探索时留意地标。在一个世界中玩的时间越长，越容易记住您的位置。另一个非常好的诀窍是在移动时放置火把，这样您就可以找到回家的路了。",
    "howtoplay.navigation.text.9":"太阳也能指示您的朝向。记住：太阳东升西落！",
    "howtoplay.navigation.header.3":"探险者地图",
    "howtoplay.navigation.text.10":"有许多地方可供您探索。找到村庄并寻找制图师。他会和您交易探险者地图，这些地图将带您前往非常遥远的陌生地域。",
    "howtoplay.netherPortals":"下界传送门",
    "howtoplay.netherPortals.title":"游戏指南：下界传送门",
    "howtoplay.netherPortals.text.1":"下界传送门使您能够进入不同的维度。",
    "howtoplay.netherPortals.text.2":"如果构造正确，下界传送门就能够被点燃和激活。",
    "howtoplay.netherPortals.text.3":"这里显示了传送门构造示例：",
    "howtoplay.nightfall":"黄昏",
    "howtoplay.nightfall.title":"游戏指南：黄昏",
    "howtoplay.nightfall.text.1":"在《我的世界》中，当您在世界中冒险时太阳会升起和落下。当太阳落下时，必须要采取预防措施，因为夜间危机四伏！",
    "howtoplay.nightfall.header.1":"寻求庇护",
    "howtoplay.nightfall.text.2":"如果您并未采取预防措施，则需要寻找一个地方来躲避黑暗以及黑暗中潜藏着的危险。这样的地方很容易找，比如山丘一侧的洞或森林中的小木屋。",
    "howtoplay.nightfall.text.3":"请务必封堵所有入口，您可能需要使用门来方便您进出。如果您制作了一张床，此处非常适合放置它，可将它与工作台和熔炉放置在一起。",
    "howtoplay.nightfall.text.4":"另外务必使用火把照亮此区域，这可能会救您的命。",
    "howtoplay.pets":"宠物",
    "howtoplay.pets.title":"游戏指南：宠物",
    "howtoplay.pets.header.1":"照顾宠物",
        "howtoplay.pets.text.1.touch":"在《我的世界》中，有多种可以驯服的生物，而且可以让它们成为您的宠物。可以通过给予各生物喜爱的物品来驯服它们。驯服后，您可以点击“坐”按钮来让它们留下。",
    "howtoplay.pets.header.2":"狼",
    "howtoplay.pets.text.2":"狼是在较冷的气候中狩猎的中立型生物。它们会攻击兔子、骷髅和羊，但会远离羊驼。除非您向它们挑衅，否则它们不会攻击您。您可以通过给它们喂骨头来驯服它们。",
    "howtoplay.pets.header.3":"猫",
    "howtoplay.pets.text.3":"猫是出没于村庄中的中立型生物。它们会攻击兔子和海龟宝宝。它们还会赶走幻翼和爬行者。它们会试着躲着您，因此驯服它们可能并非易事。它们喜欢吃鱼，所以给它们喂生鳕鱼或鲑鱼来驯服它们。",
    "howtoplay.pets.header.4":"鹦鹉",
    "howtoplay.pets.text.4":"鹦鹉是居住在丛林中的被动型生物。它们会模仿所在区域中的任何其他生物。它们最喜欢种子，给它们喂一些种子来驯服它们。鹦鹉还会站在您的肩膀上……是的，您可以让多只鹦鹉站在您的肩膀上。",
    "howtoplay.raids":"劫掠",
    "howtoplay.raids.title":"游戏指南：劫掠",
    "howtoplay.raids.text.1":"在探索世界的过程中，您可能会遇到掠夺者的营地或巡逻队。掠夺者总是在寻找村庄进行袭击，携带他们的旗帜会引起他们的注意，他们还可能会选择袭击附近的村庄。",
    "howtoplay.raids.text.2":"一定要保卫您的村庄，如果您击败了所有的劫掠者，攻击就会停止。",
    "howtoplay.raids.header.1":"英雄救我",
    "howtoplay.raids.text.3":"村民们很可能会非常感激您把他们从劫掠者手中救了出来。一定要和他们确认一下，您可能会做成一笔好交易。",
    "howtoplay.ranching":"牧场经营",
    "howtoplay.ranching.title":"游戏指南：牧场经营",
    "howtoplay.ranching.text.1":"在《我的世界》中，您可以拥有自己的牧场，养满牲畜！牧场经营可获得许多资源，如羊毛、鸡蛋和生肉。",
    "howtoplay.ranching.header.1":"扩大您的牧群",
    "howtoplay.ranching.text.2":"为了使牲畜数量不断增长，必须让动物繁殖。成年动物必须进入“爱情模式”才能繁殖。喂动物吃喜欢的食物来让它们进入“爱情模式”。",
    "howtoplay.ranching.text.3":"当两只同类动物彼此靠近并且都处于“爱情模式”时，它们就会亲吻一会儿，然后生出一只动物宝宝！动物宝宝会与其父母呆在一起直至成年。生完宝宝后，成年动物必须等 5 分钟才能再次进入“爱情模式”。",
    "howtoplay.ranching.header.2":"生物吃什么？",
    "howtoplay.ranching.text.4":"牛、哞菇和羊都吃小麦。猪可以吃胡萝卜或甜菜根。鸡喜欢吃各种种子。兔子吃胡萝卜、金胡萝卜或蒲公英。豹猫喜欢吃生鳕鱼或鲑鱼。狼喜欢吃各种肉类。",
    "howtoplay.ranching.text.5":"当您拿着动物喜欢的食物物品时，它们会跟着您。这将有助于您将它们引入您的牧场或引导它们走向其他动物。",
    "howtoplay.realms":"Realms",
    "howtoplay.realms.title":"游戏指南：Realms",
    "howtoplay.realms.text.1":"Realms 是开展持续运行的多人游戏的绝佳场所。即使您没有在玩，您的Realms 也会正常运行，以供您的好友探索！",
    "howtoplay.realms.header.1":"开始使用",
    "howtoplay.realms.text.2":"要设置 Realm，请在“世界”选项卡中选择“新建”。然后依次选择“新建 Realm ”按钮和“新建世界”按钮。可在此处对您的 Realm 命名，并设置玩家数量。随后即可向 Realm 中添加好友。",
    "howtoplay.realms.header.2":"Realm 设置",
    "howtoplay.realms.text.3":"创建好 Realm 后，选择“铅笔”按钮来更改 Realm 设置。",
    "howtoplay.realms.text.4":"在“游戏”按钮下，您可以对 Realm 重命名、设置难度和游戏模式、启用作弊以及下载/上传世界。",
    "howtoplay.realms.text.5":"在“成员”按钮下，您可以管理已经邀请加入 Realm 的所有好友、添加/移除成员以及设置他们的权限。",
    "howtoplay.realms.text.6":"在“订阅”按钮下，您可以看到 Realm 的到期时间、延长到期日以及打开/关闭 Realm。",
    "howtoplay.redstone":"红石",
    "howtoplay.redstone.title":"游戏指南：红石",
    "howtoplay.redstone.text.1":"红石粉来自传输电子信号的红石。具有能量时，它将点亮并将其信号传输给邻近的其他红石物品。",
    "howtoplay.redstone.header.1":"红石能量",
    "howtoplay.redstone.text.2":"若要为其中一个物品提供能量，它需要诸如拉杆、按钮或压力板等能量源。试着找到全部能量源！",
    "howtoplay.redstone.text.3":"在能量源旁边放置一些红石粉并开启它来赋予能量。",
    "howtoplay.redstone.text.4":"有许多物品会使用红石信号来发挥作用，例如漏斗或活塞。",
    "howtoplay.redstone.text.5":"红石可以实现无限可能性！试着为自己创建一些有用的东西，例如自动农场！",
    "howtoplay.resourceAndBehaviorPacks":"资源和行为包",
    "howtoplay.resourceAndBehaviorPacks.title":"游戏指南：资源和行为包",
    "howtoplay.resourceAndBehaviorPacks.text.1":"您可以使用资源和行为包更改《我的世界》的外观和行为方式。",
    "howtoplay.resourceAndBehaviorPacks.text.2":"在“设置”菜单中，从可用包列表中选择一个包并选中其旁边的加号。现在您的包就可以应用对默认《我的世界》包的更改了。",
    "howtoplay.scaffolding":"脚手架",
    "howtoplay.scaffolding.title":"游戏指南：脚手架",
    "howtoplay.scaffolding.header.1":"触摸天际",
                        "howtoplay.scaffolding.header.2":"为您的建造提供支撑",
    "howtoplay.scaffolding.text.2":"脚手架需要支撑。您只能在水平方向放置若干个脚手架而不接触到不同的方块。当您试图在没有适当支撑的情况下放置过多的脚手架时，它会倒塌。脚手架可以像普通的方块一样进行放置，但它也可以被放置在自己的地基上，以便快速建成一座高塔。",
    "howtoplay.scaffolding.header.3":"快速打破",
    "howtoplay.scaffolding.text.3":"当脚手架被破坏时，它也会破坏由它所支撑的每一个脚手架。这将让您能够通过破坏支撑方块来快速清理您的脚手架！",
    "howtoplay.structureBlocks":"结构方块",
    "howtoplay.structureBlocks.title":"游戏指南：结构方块",
    "howtoplay.structureBlocks.text.1":"结构方块使得创建者们能够将世界的部分复制并保存为结构。所保存的结构在之后又可以粘贴回世界中。",
    "howtoplay.structureBlocks.header.1":"获得方式",
    "howtoplay.structureBlocks.text.2":"要获得结构方块，您必须使用 /give 斜杠命令。要使用结构方块，您必须具有操作员权限。",
    "howtoplay.structureBlocks.header.2":" 模式",
    "howtoplay.structureBlocks.text.3":"结构方块有 4 种模式：保存、加载、角落和 3D 导出，您可以使用模式下拉菜单在它们之间进行切换。",
    "howtoplay.structureBlocks.text.4":"保存模式会将世界的一个区域保存为一个结构。",
    "howtoplay.structureBlocks.text.5":"加载模式会将结构加载到世界中。只有保存至世界中的结构或者世界中应用的行为包所包含的结构才能被加载。",
    "howtoplay.structureBlocks.text.6":"角模式与保存模式的检测按钮一起使用，以自动设置要保存的区域。详细信息，请参阅下面的”角落模式“部分。",
    "howtoplay.structureBlocks.text.7":"3D 导出会在支持的平台上导出 3D 模型文件。",
    "howtoplay.structureBlocks.header.3":"预览窗口",
    "howtoplay.structureBlocks.text.8":"在结构方块屏幕的右侧，将根据方块所处的模式，显示您所选择的区域或者要加载的结构的预览。",
            "howtoplay.structureBlocks.text.9.touch":"触摸并拖动预览以旋转 3D 预览。",
    "howtoplay.structureBlocks.header.4":"红石激活",
    "howtoplay.structureBlocks.text.10":"红石可以用来激活一个结构方块。根据方块的模式及其设置，这会导致红石将结构保存到外部或将结构加载入世界。",
    "howtoplay.structureBlocks.header.5":"完整性和种子",
    "howtoplay.structureBlocks.text.11":"您可以通过更改完整性和种子的值来更改某个结构的加载量。",
    "howtoplay.structureBlocks.text.12":"完整性——从结构中加载的方块的百分比，接受的值是 0 到 100。如果没有指定种子，将随机选择方块。",
    "howtoplay.structureBlocks.text.13":"种子——在这里输入的值将决定在使用完整性时将删除哪些方块。如果您希望随机选择方块，请将此字段留空。",
    "howtoplay.structureBlocks.header.6":"结构空位方块",
    "howtoplay.structureBlocks.text.14":"当一个带有结构空位方块的结构被加载到世界中时，结构空位方块加载目的地上的任何原本可能被移除的方块将会转而留在该世界中。",
    "howtoplay.structureBlocks.text.15":"举例：在把一艘空的沉船加载到海底时，通常会在水方块上方复制空气。如果沉船充满了结构空位，那么水就会留下来，您就会获得一个充满水的沉船了。",
    "howtoplay.structureBlocks.header.7":"检测和角落模式",
    "howtoplay.structureBlocks.text.16":"要自动选择要保存的区域，您可以在结构周围放置角落模式方块，并使用与要保存的结构相同的名称来命名它们。",
    "howtoplay.structureBlocks.text.17":"在保存模式下按下检测按钮将找到所有具有相同名称的角落方块，并创建一个选择区域，以便保存这些角落方块所生成的卷中的所有内容。",
    "howtoplay.servers":"服务器",
    "howtoplay.servers.title":"游戏指南：服务器",
    "howtoplay.servers.text":"服务器选项卡将显示热门《我的世界》服务器。",
    "howtoplay.shulkerBoxes":"潜影盒",
    "howtoplay.shulkerBoxes.title":"游戏指南：潜影盒",
    "howtoplay.shulkerBoxes.text.1":"将两个潜影壳与箱子结合来制作潜影盒。潜影壳是末地城中的潜影贝掉落之物。与其他容器不同，潜影盒被损坏后会保留它们的物品。被活塞推动的潜影盒会损坏并且会作为物品掉落，可以使用发射器来放置潜影盒。",
    "howtoplay.theEnd":"末地",
    "howtoplay.theEnd.title":"游戏指南：末地",
    "howtoplay.theEnd.text.1":"末地是可通过激活的末地传送门进入的另外一个维度。末地传送门可在要塞之中找到，要塞位于主世界的地底深处。",
    "howtoplay.theEnd.text.2":"每个末地传送门框架方块都缺少一些神秘之物来诱发内部的力量。",
    "howtoplay.theEnd.header.1":"另一边",
    "howtoplay.theEnd.text.3":"传送门被激活后，跳入其中即可前往末地。",
    "howtoplay.theEnd.text.4":"末地是可怕的末影龙的家园。她是既凶残又强大的敌人，似乎能从奇异水晶中汲取力量。她的龙息和火球攻击可以在整个战地留下滞留酸性物。带上一些好友以确保取得胜利！",
    "howtoplay.theEnd.text.5":"一次不行的话，可以将四颗末影水晶添加到返回传送门的各个角落来重新唤醒末影龙。",
    "howtoplay.theStore":"市场",
    "howtoplay.theStore.title":"游戏指南：市场",
    "howtoplay.theStore.text.1":"在《我的世界》市场中可以找到由各位才华横溢的创作者创作的新皮肤、世界、材质和混搭包。",
    "howtoplay.theStore.header.1":"探索内容",
    "howtoplay.theStore.text.2":"尝试使用新皮肤获取崭新的外观！",
    "howtoplay.theStore.text.3":"了解各个世界，解除锁定您想一玩再玩的新地图和挑战！",
    "howtoplay.theStore.text.4":"在您当前的世界和 Realms 上叠加材质包，从而赋予旧游戏新外观！",
    "howtoplay.theStore.text.4.norealms":"使用可以被覆盖在您的当前世界上的材质包，让您的旧游戏焕然一新！",
    "howtoplay.theStore.text.5":"或者尝试使用包含精选的皮肤、世界和材质集合的所有混搭包，结合使用这些皮肤、世界和材质，会改变您的世界和 Realms 的外观！",
    "howtoplay.theStore.text.5.norealms":"或者对您的世界尝试使用混搭包，后者是由皮肤、世界和材质组成的精选集合，在它们的共同作用下，您的世界将截然不同！",
    "howtoplay.tools":"工具",
    "howtoplay.tools.title":"游戏指南：工具",
    "howtoplay.tools.text.1":"在《我的世界》中有许多工具，使用这些工具开采方块比徒手开采要快得多。这些工具可使用木头、石头、铁、金子或钻石制成。",
    "howtoplay.tools.text.2":"使用合适的工具进行工作不仅可以让您更快速地开采方块，而且还能够减慢耐久度消耗。若要开采更稀有的资源，必须制作更复杂的工具。",
    "howtoplay.tools.header.1":"破坏东西的工具",
    "howtoplay.tools.text.3":"镐非常适合用来破坏坚硬的方块，例如圆石、铁或熔炉。",
    "howtoplay.tools.text.4":"斧头非常适合用来破坏木质方块，例如原木、木板或工作台。",
        "howtoplay.tools.text.5.touch":"锹非常适合用来破坏疏松的方块，例如泥土、沙子和砂砾。锹还可用于创建草径，只要在草方块上进行点击即可。",
        "howtoplay.tools.text.6.touch":"需要使用锄头来耕作泥土从而种植农作物。点击泥土或草方块可让它们转换为土壤。",
    "howtoplay.tools.text.7":"所有这些工具都可接受附魔，无论是从附魔台还是铁砧进行附魔。",
    "howtoplay.tools.header.2":"其他工具",
    "howtoplay.tools.text.8":"还有更多工具可协助您冒险：",
    "howtoplay.tools.text.9":"使用桶可以收集水、牛奶、熔岩，甚至鱼等物体。",
    "howtoplay.tools.text.10":"使用打火石可以点火...在树林茂密的区域使用时需小心！",
    "howtoplay.tools.text.11":"使用钓鱼竿可以从水方块中捕获鱼和其他战利品。还可使用它拖动其他玩家和生物。钓鱼竿也可以附魔！",
    "howtoplay.tools.text.12":"剪刀非常适合收集羊毛、树叶和蜘蛛网等物品。",
    "howtoplay.trading":"村民交易",
    "howtoplay.trading.title":"游戏指南：村民交易",
    "howtoplay.trading.text.1":"在村庄中可进行交易。每个村民都有一项职业，他们可能是农民、屠夫、铁匠、制图师、图书管理员或牧师。有些职业可以交易其他职业无法交易的物品。探索并与许多村民交易以找到所有的可进行交易。",
    "howtoplay.trading.header.1":"用于换取绿宝石的商品",
    "howtoplay.trading.text.2":"您可以通过与村民互动来了解他们会提供什么来进行交易。村民可能会在与玩家交易时调整交易价格。村民可能会缺货，或者由于过于频繁地使用某项交易从而导致其暂时被禁用。交易通常涉及到绿宝石的买卖。",
    "howtoplay.trading.text.3":"当您与村民进行交易时，他们的职业水平会提高，并开始提供更好、更有价值的交易。",
    "howtoplay.trading.text.4":"照顾好您的村民，他们需要休息、工作和吃饭才能茁壮成长。",
    "howtoplay.transportation":"交通运输",
    "howtoplay.transportation.title":"游戏指南：交通运输",
    "howtoplay.transportation.text.1":"除了步行、骑乘或飞行外，还有很多方法可以到达各地。",
    "howtoplay.transportation.header.1":"矿车",
    "howtoplay.transportation.text.2":"矿车是在铁轨上滚动的可乘坐的车子。您可以通过彼此相邻放置铁轨来前往您要去的地方，将矿车放置在铁轨上，现在可以乘坐了。",
                "howtoplay.transportation.header.2":"船",
    "howtoplay.transportation.text.4":"船让您可以在水面上旅行，将一艘船放在水方块上，即可出发。",
                "howtoplay.weapons":"武器",
    "howtoplay.weapons.title":"游戏指南：武器",
    "howtoplay.weapons.header.1":"木剑",
    "howtoplay.weapons.text.1":"剑是《我的世界》中的主要近战武器。可以使用木头、石头、铁、金子或钻石制成。跳劈会造成暴击伤害！",
        "howtoplay.weapons.text.2.touch":"点击生物对其进行攻击。",
    "howtoplay.weapons.header.2":"弓",
        "howtoplay.weapons.text.3.touch":"弓是《我的世界》中的主要远程武器。按住屏幕可拉弓。释放所按屏幕可射箭。弓在有箭的情况下才能射出。",
    "howtoplay.weapons.text.4":"弦往后拉得越多，弓造成的伤害就越大，请确保将弦拉满。",
    "howtoplay.weapons.header.3":"弩",
        "howtoplay.weapons.text.5.touch":"弩是一种可选的远程武器。按下并长按屏幕以装载弩。一旦弩装载成功，它会保持在装载状态，直至您用它进行射箭，即便您将它放在物品栏中也是如此。按下并长按屏幕可以射出一枚箭。弩需要装载箭。",
    "howtoplay.weapons.header.4":"三叉戟",
        "howtoplay.weapons.text.6.touch":"三叉戟是近战和远程两用武器。点击生物可攻击它们。按住屏幕可将三叉戟收回。释放所按屏幕可投掷三叉戟。三叉戟是最好的水下武器。",
    "howtoplay.weapons.header.5":"附魔武器",
    "howtoplay.weapons.text.7":"您可从附魔台或铁砧为剑、弓、弩和三叉戟获取特定附魔，它们将提高伤害值、耐久度甚至可以放火烧生物！",
    "howtoplay.whatsNew":"新增内容",

}