howtoplay: dict = {
    "howtoplay.next":"下一步",
    "howtoplay.previous":"上一步",
    "howtoplay.category.education":"教育",
    "howtoplay.category.gettingSettled":"安顿下来",
    "howtoplay.category.gettingStarted":"入门",
    "howtoplay.category.overworld":"主世界 A-Z",
    "howtoplay.category.preparingForTheNight":"迎接夜晚",
    "howtoplay.category.redstoneEngineering":"红石工程",
    "howtoplay.category.standsAndTables":"架子与桌子",
    "howtoplay.category.survivingTheFirstNight":"度过首夜",
    "howtoplay.category.theEndDimension":"末地维度",
    "howtoplay.category.optionsAndCheats":"选项和作弊",
    "howtoplay.adventureMode":"冒险模式",
    "howtoplay.adventureMode.text.1":"冒险模式是世界建造者的一种游戏模式。在冒险模式中，玩家必须使用特殊工具来放置或击破方块。",
    "howtoplay.adventureMode.text.2":"要获得这些特殊工具，必须在创造模式下使用 §e/give§f 与 §ecanplace§f 或 §ecandestroy§f 参数。",
    "howtoplay.anvil":"铁砧",
    "howtoplay.anvil.text.1":"经验级别可用于使用铁砧修复、附魔或重命名物品。",
    "howtoplay.anvil.header.1":"重命名和应用附魔",
    "howtoplay.anvil.text.2":"可以重命名所有物品，尽管在铁砧上只可以使用书修复或附魔具有持久性的物品。",
    "howtoplay.anvil.header.2":"修复",
    "howtoplay.anvil.text.3":"修复物品需要将它放置在左侧的一个输入槽中，同时还要放入一些该物品的原材料（如用于铁剑的铁锭）或与另一种相同类型的物品组合。",
    "howtoplay.anvil.text.4":"使用铁砧组合物品时，效率更高。",
    "howtoplay.anvil.text.5":"铁砧在每次使用时有可能损坏，并且在使用足够次数后将被销毁。",
    "howtoplay.armor":"盔甲",
        "howtoplay.armor.header.1":"合成",
    "howtoplay.armor.text.2":"盔甲可以由皮革、铁、黄金或钻石制成。链甲可以通过村民交易获得，也可以从僵尸和骷髅处掠夺。",
    "howtoplay.armor.text.3":"通过打开您的物品栏并将盔甲碎片移动到玩家皮肤旁边的相应槽位中，即可装备盔甲。",
    "howtoplay.armor.text.4":"铁质盔甲、锁链盔甲和黄金盔甲可以在熔炉中熔化成铁粒或金粒。",
    "howtoplay.armor.header.2":"盾牌",
            "howtoplay.armor.text.5a.touch":"盾牌可以阻挡各种伤害，甚至是苦力怕爆炸！它可以装备在副手栏位或快捷栏中。",
                    "howtoplay.armor.text.6":"盾牌甚至可以格挡一次苦力怕的爆炸！",
    "howtoplay.armor.header.3":"伪装",
        "howtoplay.armorStand":"盔甲架",
    "howtoplay.armorStand.text.1":"盔甲架用于挂载您未在使用的盔甲。",
    "howtoplay.armorStand.header.1":"装备",
        "howtoplay.armorStand.text.2.touch":"在持拿一件盔甲的同时点击盔甲架即可将盔甲置于盔甲架上。",
        "howtoplay.armorStand.text.3.touch":"在张开手时点击盔甲架即可从盔甲架中移除物品。",
    "howtoplay.armorStand.header.2":"摆姿势",
        "howtoplay.armorStand.text.4.touch":"盔甲架可以更改其姿势，潜行并点击盔甲架可更改姿势。",
    "howtoplay.armorStand.header.3":"跳舞",
    "howtoplay.armorStand.text.5":"盔甲架会对红石信号作出反应，请尝试给予它不同的信号强度，然后看看会发生什么。",
    "howtoplay.banners":"旗帜",
    "howtoplay.banners.text.1":"旗帜一种是使用自定义图案和颜色装饰您的房子或城堡的超酷方式。",
    "howtoplay.banners.text.2":"在合成旗帜后，您可以将它放置在工作台或织布机上并添加不同染料，以创建自己独一无二的超酷设计！",
    "howtoplay.banners.header.1":"应用一个图案",
    "howtoplay.banners.text.3":"可以使用您的染料创建许多不同的图案，如：",
    "howtoplay.banners.text.4":"  - 制作一个三角形将给予您一个 v 形图案。",
    "howtoplay.banners.text.5":"  - 制作一个十字将给予您一个十字图案。",
    "howtoplay.banners.text.6":"  - 添加一朵滨菊将给予您一个花朵盾徽。",
    "howtoplay.banners.text.7":"试验不同组合可获得更多图案！",
    "howtoplay.banners.header.2":"多层",
    "howtoplay.banners.text.8":"旗帜也可以有多层，这使您在旗帜上可以布置多个图案。如果您不喜欢放置在旗帜上的最后一个图案，则可以在炼药锅中洗掉最后一层。",
    "howtoplay.banners.header.3":"制作副本",
    "howtoplay.banners.text.9":"如果您想要复制旗帜，请将相应旗帜放置在具有空白旗帜的工作台上。",
    "howtoplay.beacons":"信标",
    "howtoplay.beacons.text.1":"活动信标会将一束亮光投射到空中。",
    "howtoplay.beacons.text.2":"信标由玻璃、黑曜石和下界之星（可通过打败凋灵获得）制成。",
    "howtoplay.beacons.header.1":"建筑",
    "howtoplay.beacons.text.3":"必须将信标放置在不会阻挡天空视界之地，并且必须放置在铁块、金块、绿宝石块或钻石块搭建的金字塔上。",
    "howtoplay.beacons.text.4":"在其上放置信标的材料不会对信标的效果产生影响。",
    "howtoplay.beacons.header.2":"使用",
    "howtoplay.beacons.text.5":"您可以在“信标”菜单中为您的信标选择一个主要效果。金字塔层数越多，提供的效果就越多。",
    "howtoplay.beacons.text.6":"要设置信标效果，必须在付款槽内使用下界合金锭、绿宝石、钻石、金锭或铁锭。",
    "howtoplay.beacons.text.7":"设置完成后，信标会永久地发射效果。这些效果会授予附近的所有玩家。",
    "howtoplay.beacons.text.8":"若要更改光束颜色，请在其路径中放置一个遮光玻璃方块。",
    "howtoplay.beds":"床",
    "howtoplay.beds.text.1":"睡在床上过夜，并设置您的出生点。",
        "howtoplay.beds.text.2.touch":"点击床即可入睡。此操作只可在晚上执行。",
    "howtoplay.beds.text.3":"如果您正在玩多人游戏，则世界中的每个人都必须同时在床上过夜。",
    "howtoplay.beds.text.4":"如果您的床已损毁，您将返回到您在这个世界中的第一个出生点。",
    "howtoplay.beds.text.5":"在下界中使用床时请小心，通常会因太热而无法入睡。",
    "howtoplay.bedsNew":"床",
    "howtoplay.bedsNew.title":"游戏指南：床",
    "howtoplay.bedsNew.text.1":"柔软的床可以让你在睡梦中安然度过夜晚。合成一张床需要羊毛，另外还得找个安全的地方把床安置下来。",
    "howtoplay.bedsNew.text.2":"在床上休息也可以设置§e重生点§f，这意味着如果死了，你会重新出现在家里！",
    "howtoplay.bedsNew.text.3":"你只能在舒适的时候睡觉，比如夜晚或雷暴期间。",
    "howtoplay.blocks":"方块",
    "howtoplay.blocks.text.1":"《我的世界》的世界由数以百万计的方块构成。每一个方块都可破坏、可收集和可放置。您几乎可以不受限制的创造一切事物！",
    "howtoplay.blocks.text.2":"大多数方块必须在世界中寻找，但一些方块只能通过在工作台上组合其他方块制成（如红石方块）或者在熔炉中熔化制成（如玻璃）。",
    "howtoplay.blocks.header.1":"下落的方块",
    "howtoplay.blocks.text.3":"大多数方块不受重力影响，可以漂浮在半空；但像沙子和砂砾之类的物品将会落下（如果没有方块在其下方）。",
    "howtoplay.blocks.header.2":"趣味方块",
    "howtoplay.blocks.text.4":"以下是一些《我的世界》中更多有趣方块的示例：",
    "howtoplay.blocks.text.5":"§e玻璃§f - 这是一种透明方块，通过在熔炉中熔化沙子制成。",
    "howtoplay.blocks.text.6":"§e混凝土§f - 通过将混凝土粉末方块倒入水中制成。",
    "howtoplay.blocks.text.7":"§e陶瓦§f - 该方块自然存在于荒地生物群系中，或者可以使用在水下找到的粘土作为原料合成并染色制成。通过将陶瓦放入熔炉中熔化可将其制成带釉陶瓦。",
    "howtoplay.blocks.text.8":"§e岩浆方块§f - 该方块自然存在于下界中，它发出一点光，并且会烧毁踩到它的任何生物。",
    "howtoplay.blocks.text.9":"§e粗粒土§f - 该方块与普通泥土方块极为相似，但其上无法长出草。可在热带草原和大型针叶林生物群系中找到它。",
    "howtoplay.bookAndQuill":"书与笔",
    "howtoplay.bookAndQuill.text.1":"“书与笔”使您可以记录自己的冒险经历。通过在页面中输入文字和图像来讲述您的故事。您甚至可以更改标题和作者！对“书与笔”签名即可完成您的工作。在签名之前，“书与笔”将处于可编辑状态。",
    "howtoplay.brewingStand":"酿造台",
    "howtoplay.brewingStand.text.1":"酿造药水需要一个酿造台。每份药水首先需要一瓶水，该瓶水可使用来自炼药锅或水源地的水灌满玻璃瓶获得。",
    "howtoplay.brewingStand.header.1":"了解您的酿造台",
    "howtoplay.brewingStand.text.2":"酿造台有三个槽，可用于制作不同的药水。一种成分可用于全部三个瓶子，因此始终同时酿造三份药水，以充分利用您的资源。",
    "howtoplay.brewingStand.header.2":"成分和药水",
    "howtoplay.brewingStand.text.3":"将下界疣放入酿造台的顶部位置会为你制成一份粗制的药水。该药水本身没有任何效果，但可制作用于制作更高级药水的基础药水。",
    "howtoplay.brewingStand.text.4":"有许多药水效果等待着被发现，使用不同的成份和组合进行试验才能成为一名真正的炼金术士。",
    "howtoplay.buildingAShelter":"建造一个避难所",
    "howtoplay.buildingAShelter.title":"游戏指南：建造一个避难所",
    "howtoplay.buildingAShelter.text.1":"当危险降临时，坚固的§e避难所§f可以保护你免受外部威胁。",
    "howtoplay.buildingAShelter.text.2":"度过首夜的关键在于建造一个避难所，而这并不难做到。",
    "howtoplay.buildingAShelter.text.3":"你可以用任何材料来建造，从泥土到石头，甚至封闭一个洞穴来作为临时住所！",
    "howtoplay.cauldron":"炼药锅",
    "howtoplay.cauldron.text.1":"炼药锅是一种可容纳数桶或数瓶液体的容器。",
    "howtoplay.cauldron.header.1":"装满",
        "howtoplay.cauldron.text.2.touch":"拿着一桶水或一份药水时，点击炼药锅即可向炼药锅中注入其中的成份。",
    "howtoplay.cauldron.text.3":"一份药水只能够部分填满炼药锅，因此您将需要使用多份药水才能完全填满炼药锅。",
    "howtoplay.cauldron.header.2":"浸泡箭",
        "howtoplay.cauldron.text.4.touch":"手中握有箭时，点击炼药锅即可制作各种不同用途的箭！",
    "howtoplay.cauldron.header.3":"给盔甲染色",
        "howtoplay.cauldron.text.5.touch":"若要给皮革盔甲或皮革马铠染色，请在持有所需染料时，点击填满水的炼药锅。这会改变炼药锅中水的颜色。然后，在手中拿着盔甲时点击炼药锅即可将您的盔甲浸入炼药锅中。",
    "howtoplay.cauldron.text.6":"如果您想要洗去染色，只需将染色物品浸入填有未染色的水的炼药锅中即可。",
    "howtoplay.chat":"聊天",
            "howtoplay.chat.text.1.touch":"点击“聊天”按钮以打开聊天。键入消息，然后点击“发送”按钮。",
    "howtoplay.chests":"箱子",
        "howtoplay.chests.text.1.touch":"在您制成箱子后，您可以将其置于世界中，然后以点击方式打开箱子并存放您的物品栏中的物品。",
    "howtoplay.chests.text.2":"存放在箱子中的物品可供您稍后放入您的物品栏中。",
    "howtoplay.chests.text.3":"将合并相邻放置的两个箱子，以合成一个大箱子。",
    "howtoplay.commandBlocks":"命令方块",
    "howtoplay.commandBlocks.text.1":"命令方块对于地图创建者而言是一个功能非常强大的工具。这些命令方块可存储命令，并会在收到红石信号后执行命令。",
    "howtoplay.commandBlocks.text.2":"若要获取命令方块，您必须使用 /give。",
    "howtoplay.commandBlocks.text.3":"在命令方块成功执行或未能执行其存储的命令时，它都会从箭头所指的那一侧发出红石信号。",
    "howtoplay.commandBlocks.text.4":"您可以在“悬停注释”字段中设置命令方块的名称。",
    "howtoplay.commandBlocks.text.5":"§e方块类型§f - 有三种类型的命令方块，每一种都有自己独有的颜色和行为：",
    "howtoplay.commandBlocks.text.5.1":"§e脉冲§f - 仅在方块收到红石信号时才会执行存储的命令。",
    "howtoplay.commandBlocks.text.5.2":"§e连锁§f - 无论后面的命令方块是否已执行其命令，都会执行存储的命令。",
    "howtoplay.commandBlocks.text.5.3":"§e重复§f - 激活后，只要此命令方块存在，它就会继续执行其存储的命令。",
    "howtoplay.commandBlocks.text.6":"§e条件§f - 有两个条件，每一个条件都会影响命令方块的行为：",
    "howtoplay.commandBlocks.text.6.1":"§e无条件§f - 即使后面的命令方块未能执行其命令，也会执行存储的命令。",
    "howtoplay.commandBlocks.text.6.2":"§e有条件§f - 仅当后面的命令方块成功执行其命令时，才会执行存储的命令。",
    "howtoplay.commandBlocks.text.7":"§e红石§f - 有两种红石设置，每一种都会影响命令方块的行为：",
    "howtoplay.commandBlocks.text.7.1":"§e需要红石§f - 需要红石信号才能激活。",
    "howtoplay.commandBlocks.text.7.2":"§e始终活动§f - 不需要红石信号也能激活。",
    "howtoplay.commandBlocks.text.8":"命令方块还将向您显示其以前的输出。这可帮助您了解命令方块是否未能执行其命令及原因。",
    "howtoplay.commands":"命令",
    "howtoplay.commands.text.1":"可通过聊天执行命令。在您键入命令之前，请先键入 /。",
    "howtoplay.commands.text.2":"有大量命令，使您能够做令人惊奇的事情。有许多来源出自这些命令，可提供给您所需要的所有信息。",
    "howtoplay.conduits":"潮涌核心",
    "howtoplay.conduits.text.1":"当您处于水下时，处于激活状态的潮涌核心会给您提供能量。",
    "howtoplay.conduits.text.2":"一个潮涌核心由若干鹦鹉螺壳和一枚海洋之心制成。潮涌核心会从海晶石和海晶灯中吸取能量。",
    "howtoplay.conduits.header.1":"建设",
    "howtoplay.conduits.text.3":"一旦被激活，潮涌核心会将潮涌能量赋予给附近的任何物体。",
    "howtoplay.conduits.text.4":"其吸取的能量越多，能力的作用范围就越远。",
    "howtoplay.craftingATool":"合成工具",
    "howtoplay.craftingATool.title":"游戏指南：合成工具",
                    "howtoplay.worldBuilder":"世界建造者",
    "howtoplay.worldBuilder.text.1":"若要放置或使用特定的 Minecraft Education 方块或物品，用户必须拥有一种名为“World Builder”的特殊能力。",
    "howtoplay.worldBuilder.text.2":"启用作弊后，主机可启用或禁用这个世界中任何玩家的世界建造者能力。",
    "howtoplay.worldBuilder.text.3":"如果想让这个世界的所有玩家获得世界建造者能力，那么请运行下述命令：",
    "howtoplay.worldBuilder.text.4":"/ability @a worldbuilder true",
    "howtoplay.worldBuilder.text.5":"如果想快速打开您自己的世界建造者能力，请运行下述命令中的一个：",
    "howtoplay.worldBuilder.text.6":"/worldbuilder",
    "howtoplay.worldBuilder.text.7":"/wb",
    "howtoplay.worldBuilder.text.8":"如果想查询您的世界建造者能力，请运行下述命令：",
    "howtoplay.worldBuilder.text.9":"/ability @p worldbuilder",
    "howtoplay.permissionBlocks":"权限块",
    "howtoplay.permissionBlocks.text.1":"Minecraft Education 包含数个特殊的块，这些块可让教师更便捷地创建和使用课程。只有拥有世界建造者能力的用户才能放置和摧毁这些块。没有世界建造者能力的用户会受到这些块施加的限制约束。",
    "howtoplay.permissionBlocks.title.1":"允许/拒绝方块",
    "howtoplay.permissionBlocks.text.2":"允许和拒绝方块可控制在一个世界中可供玩家进行建造的地方。",
    "howtoplay.permissionBlocks.text.3":"用户可以在允许方块上放置或摧毁方块。用户不可以在拒绝方块上放置或摧毁方块。",
    "howtoplay.permissionBlocks.text.4":"允许和拒绝方块不会影响他们下方的区域。",
    "howtoplay.permissionBlocks.text.5":"下方有拒绝方块的允许方块会阻止用户在这个两个方块中间进行建造。用户可以在允许方块上方放置和摧毁方块。",
    "howtoplay.permissionBlocks.title.2":"边界方块",
    "howtoplay.permissionBlocks.text.6":"边界方块可提供一个能向上和向下无线延伸的力场，这个力场不受其他方块的影响。用户无法穿过，挪开或从下方穿过边界方块。用户也无法在边界方块上方或下方放置或摧毁方块。",
    "howtoplay.playingTogether":"一起玩游戏",
    "howtoplay.playingTogether.title":"一起玩游戏",
    "howtoplay.playingTogether.text.1":"《我的世界》默认为一款§e多人游戏§f。",
    "howtoplay.playingTogether.header.1":"在线多人游戏",
    "howtoplay.playingTogether.text.2":"你创建的所有新世界默认启用多人游戏。如果你想让世界变为§e单人游戏§f，转到“世界设置”将多人游戏选项关闭。",
    "howtoplay.playingTogether.header.2":"正在加入在线游戏",
    "howtoplay.playingTogether.text.3":"如果想和其他人一起玩，转到§e“朋友”选项卡§f查看所有可加入的 Realms、朋友以及局域网游戏。只需选择任意游戏即可加入。",
    "howtoplay.playingTogether.text.4":"当你开始玩或加入在线游戏时，你的好友可以在他们的“朋友”选项卡中看到你。在他们加入时，他们的好友也会看到。",
    "howtoplay.playingTogether.text.5":"你需要通过有效的网络网连接登录 §eMicrosoft 账户§f，才能玩多人游戏。",
    "howtoplay.playingTogether.header.3":"Realms：一起玩游戏的最佳方式",
    "howtoplay.playingTogether.text.6":"§eRealms§f 能够方便你和朋友一起玩游戏。",
    "howtoplay.playingTogether.text.7":"你可以和多达 10 名好友一天 24 小时沉浸在这个始终在线的世界中，探索，发挥创意，或者尝试从市场中精挑细选一些内容。",
    "howtoplay.playingTogether.text.8":"只需付费订阅 Realms 即可体验。不妨先来试试免费的 30 天试用版？",
    "howtoplay.playingTogether.header.4":"玩家权限",
    "howtoplay.playingTogether.text.9":"在你的世界中，你可以通过更改§e玩家权限§f对玩家行为作出限制。",
    "howtoplay.playingTogether.text.10":"打开游戏菜单，查看当前在世界中的玩家列表，然后选择 “权限”图标调整玩家的权限。",
    "howtoplay.playingTogether.realms":"试用 Realms",
    "howtoplay.playingTogether.signIn":"注册并体验 Realms",
    "howtoplay.chalkboard":"黑板",
        "howtoplay.chalkboard.text.1.touch":"黑板可以用来显示世界中的文本。相较于告示牌，黑板能够显示的文本更多，并且可以在不被摧毁的情况下进行编辑。锁定切换可让您阻止非世界建造者摧毁或编辑您的黑板。点击现有黑板可对其进行编辑。",
    "howtoplay.chemistry":"化学",
    "howtoplay.chemistry.text.1":"用户可使用化学设备块模拟真实世界的化学反应。通过调整元素构造器的滑动条可制作 118 种不同元素中的一种，或者将元素放元素构造器中可查看元素的成分。在化合物创建器中合成元素，以制造化合物。将元素和化合物放到实验台上可创建 Minecraft 物品。使用材料分解器可将方块分解为其组成元素。",
    "howtoplay.chemistry.text.2":"从 Minecraft Education 网站下载化学日记，获得完整的 Minecraft 化学指南。",
    "howtoplay.npc":"非玩家角色",
    "howtoplay.npc.text.1":"NPC 是能够提供额外的课程信息、提示或者指导的非玩家角色。",
    "howtoplay.npc.text.2":"只有世界建造者能够放置、删除、命名或编辑非用户角色。非用户角色可以执行命令和网站链接。命令可在非用户角色的对话窗口中分配到按钮上；网站链接始终都会有按钮。",
    "howtoplay.npc.text.3":"NPC 有大量皮肤可供选择，是稳定的。",
    "howtoplay.camera":"摄像机",
    "howtoplay.camera.text.1":"摄像机能够允许玩家在世界中拍照。",
        "howtoplay.camera.text.2.touch":"如果要用您的视角拍照片，请点击并按住，然后释放。",
        "howtoplay.camera.text.3.touch":"自拍时，放置摄像机，点击拍照按钮。",
    "howtoplay.camera.text.4":"您可以在相片簿中查看照片，或者将其插入“书与笔”。",
    "howtoplay.portfolio":"相片簿",
        "howtoplay.portfolio.text.1.touch":"您拍摄的照片会出现在相片簿中。按住可查看相片簿。查看相片簿时，您可以为图片添加标题，删除图片，将图片导出为 PDF 格式文件。",
    "howtoplay.classroomMode":"教室模式",
    "howtoplay.classroomMode.text.1":"教室模式是外置应用，可为教育工作者提供与用户互动的功能。您可以从 Minecraft Education 网站下载教室模式。",
    "howtoplay.classroomMode.text.2":"作为一个世界的主人，您可以使用命令 /classroommode，启动教室模式应用，将其连接到 Minecraft Education 上。",
    "howtoplay.codeBuilder":"代码编辑器",
    "howtoplay.codeBuilder.text.1":"代码编辑器可让玩家使用自己熟悉的编程学习平台，写代码，探索、创建和玩《我的世界》。",
            "howtoplay.craftingTable":"工作台",
    "howtoplay.craftingTable.text.1":"工作台让您可以合成更复杂的配方。",
        "howtoplay.craftingTable.text.2.touch":"将它放到世界中，然后点击工作台来使用它。",
    "howtoplay.creativeMode":"创造模式",
    "howtoplay.creativeMode.text.1":"创造模式使您能够不受限制地创建包含各种所想生物的土地！",
    "howtoplay.creativeMode.header.1":"无限构造",
    "howtoplay.creativeMode.text.2":"在创造模式界面中，游戏中的任何物品都可移到玩家的物品栏中，无需挖掘或制农作物品。当在世界中放置或使用玩家物品栏中的物品时，不会移除这些物品，这使玩家能够专注于创建而不是资源收集。",
    "howtoplay.creativeMode.text.3":"如果您在创造模式下创造、加载或保存世界，那么即使是随后载入到生存模式，您在该世界中的成就及排行榜更新也会被禁用。",
    "howtoplay.creativeMode.header.2":"飞行",
                            "howtoplay.deathAndRespawn":"死亡和重生",
    "howtoplay.deathAndRespawn.title":"游戏指南：死亡和重生",
        "howtoplay.deathAndRespawn.text.2":"你可以无限次重生，但每次死亡都会掉落物品栏中的所有物品。如果动作够快的话，你可以于复活后在物品掉落的位置处重新收回它们。",
    "howtoplay.difficulty":"难度",
    "howtoplay.difficulty.text.1":"《我的世界》有不同的难度级别，因此您可以根据您的水平定制游戏。",
    "howtoplay.difficulty.header.1":"和平",
    "howtoplay.difficulty.text.2":"除了潜影贝和末影龙之外，不存在任何敌对生物，但潜影贝和末影龙也不会伤害您。",
    "howtoplay.difficulty.header.2":"简单",
    "howtoplay.difficulty.text.3":"会生成敌对生物，但其造成的伤害较少。饥饿条会消耗，且生命值降低至 5 颗心。",
    "howtoplay.difficulty.header.3":"普通",
    "howtoplay.difficulty.text.4":"敌对生物会造成一般伤害，如果您的饥饿程度降为零，您的生命值也会开始下降，但不会死亡。",
    "howtoplay.difficulty.header.4":"困难",
    "howtoplay.difficulty.text.5":"敌对生物会造成更大的伤害，僵尸会破门而入，如果您的饥饿程度降为零，您的生命值也会下降并且可能会死亡。",
    "howtoplay.dispensers":"发射器",
    "howtoplay.dispensers.text.1":"发射器用于抛射物品。您需要将红石信号（例如，一根拉杆）放置于每个发射器旁边才能触发它。",
        "howtoplay.dispensers.text.2.touch":"若要填充发射器，请点击发射器，然后将想要发射的物品从您的物品栏移到发射器。",
    "howtoplay.dispensers.header.1":"用法",
    "howtoplay.dispensers.text.3":"只要您为发射器提供能量，发射器就会抛射物品。",
    "howtoplay.dispensers.text.4":"发射器也可用于放置物品，如将南瓜放置于铁傀儡上，或将装备放置于盔甲架上。",
    "howtoplay.droppers":"投掷器",
        "howtoplay.droppers.text.1.touch":"当由红石提供能量时，投掷器会随机投掷其中包含的一个物品。点击投掷器即可打开它，然后可以将您物品栏中的物品加载到其中。",
    "howtoplay.droppers.header.1":"用法",
    "howtoplay.droppers.text.2":"如果投掷器面朝箱子或其他类型的容器，反而会将物品置于其中。可以构建长链投掷器以实现远距离传输物品。",
    "howtoplay.dyes":"染料",
    "howtoplay.dyes.text.1":"染料可用于改变《我的世界》中许多事物的颜色。",
    "howtoplay.dyes.text.2":"有些染料的材料比其他染料更难找到。大多数染料可以用花朵合成（例如用罂粟花合成§e红色染料§f），但一些染料的发现或制作方式更隐蔽，比如：",
    "howtoplay.dyes.text.3":"§e蓝色染料§f - 挖掘地下深层中的青金石",
    "howtoplay.dyes.text.4":"§e黑色染料§f - 从鱿鱼身上收集墨囊",
    "howtoplay.dyes.text.5":"§e棕色染料§f - 采集丛林中的可可豆",
    "howtoplay.dyes.text.6":"§e绿色染料§f - 熔化仙人掌获得",
    "howtoplay.dyes.text.7":"§e白色染料§f - 由骨粉制成",
    "howtoplay.elytra":"鞘翅",
    "howtoplay.elytra.text.1":"鞘翅是一种用于允许滑翔的可装备物品。鞘翅装备在胸部盔甲槽中。",
    "howtoplay.elytra.text.2":"鞘翅无法制作，但可在稀少的末地船（由可怕的潜影贝把守）中的物品展示框中找到。",
    "howtoplay.elytra.header.1":"学习飞行",
            "howtoplay.elytra.text.4":"滑翔期间，您可以通过环顾四周来掌控方向。朝下看时，会加快移动 - 但也会更快地撞向地面。朝上看时，会获得一些高度 - 但时间过长，您会失速、坠落而不是上升！",
    "howtoplay.elytra.text.4.touch":"你可以在滑翔时环顾四周进行转向。如果你向下看，可以提升一些速度，但你也会更快落地。如果你向上看，可以提升一些高度，但持续太久就会停滞不前，这意味着你会开始坠落。",
    "howtoplay.elytra.text.5":"你的鞘翅在飞行时会慢慢失去耐久度，如果它们在飞行中断裂，你就会坠落。你可以在铁砧上将其与幻翼膜合成以进行修复。",
    "howtoplay.elytra.header.2":"火箭动力飞行",
    "howtoplay.elytra.text.6":"无效的焰火火箭可用于延长鞘翅飞行。如果您使用有效的焰火火箭来延长飞行，则您会受伤。",
    "howtoplay.enchantingTable":"附魔台",
    "howtoplay.enchantingTable.text.1":"通过拾取经验球收集到的经验点可用于附魔武器、盔甲、工具和书。",
    "howtoplay.enchantingTable.header.1":"附魔",
    "howtoplay.enchantingTable.text.2":"当将可附魔物品放置于附魔台中书下方的槽中时，该槽右侧的三个按钮会显示一些附魔项及其经验级别损耗和青金石损耗。",
    "howtoplay.enchantingTable.text.3":"实际应用的附魔是基于显示的损耗随机选取的。",
    "howtoplay.enchantingTable.header.2":"更强大的附魔",
    "howtoplay.enchantingTable.text.4":"如果附魔台环绕着书架（最多 15 个）且书架和附魔台间隔一个方块，则会看到附魔台上书中的神秘符号，附魔的效力将会增加。",
    "howtoplay.enchantingTable.header.3":"附魔书",
    "howtoplay.enchantingTable.text.5":"在铁砧上使用附魔书可将附魔加持到物品上。这使您可以进一步控制要对您的物品加持的附魔。",
    "howtoplay.encyclopedia":"百科全书",
    "howtoplay.encyclopedia.title":"《我的世界》百科全书",
    "howtoplay.encyclopedia.text.1":"《我的世界》百科全书",
    "howtoplay.endCities":"末地城",
    "howtoplay.endCities.text.1":"在杀死末影龙后，会显示末地折跃门。将末影珍珠投入该传送门会将您瞬移到外岛。",
    "howtoplay.endCities.text.2":"此全新的异域场景一定会隐藏一些有趣的物品，也许是您可以带回的物品。",
    "howtoplay.enderChest":"末影箱",
    "howtoplay.enderChest.text.1":"世界中的所有末影箱都互相关联。您可从任一末影箱内获取置于其他末影箱内的物品。但是，对于每个玩家来说，末影箱中所装物品都是特定的。这让玩家可将物品存储在任一末影箱内，然后从世界不同位置的其他末影箱内取回它们。",
    "howtoplay.eyeOfEnder":"末影之眼",
    "howtoplay.eyeOfEnder.text.1":"末影之眼与末地神秘相连，在使用时表现得非常奇怪。",
    "howtoplay.eyeOfEnder.text.2":"传言它们可能会导致您打开另一个维度。",
    "howtoplay.farming":"种植",
    "howtoplay.farming.text.1":"您可以在《我的世界》中种植各种不同的农作物。种植虽然具有挑战性，但能够无限量地提供食物来源。",
    "howtoplay.farming.header.1":"未雨绸缪",
    "howtoplay.farming.text.2":"农作物需要光、水和耕地才能生长。您需要锄头、水源和种子才能种植。",
    "howtoplay.farming.text.3":"水旁边的方块需要转化为耕地，为此需要使用锄头。水最多可灌溉四个方块。",
    "howtoplay.farming.header.2":"种植和收获",
    "howtoplay.farming.text.4":"现在，您可以种下您的种子。请确保您的农作物受到保护，因为遭踩踏或者缺少水或光很容易导致它们死亡。",
    "howtoplay.farming.text.5":"栅栏可帮助保护您的农作物，使其免受饥肠辘辘的兔子祸害或遭到踩踏！",
    "howtoplay.farming.text.6":"农作物成熟后，它们的外观会发生变化，并且可以收割。",
    "howtoplay.farming.text.7":"诸如南瓜和西瓜之类的植物生长在茎上。小心不要收割这些茎！",
    "howtoplay.fireworks":"焰火",
    "howtoplay.fireworks.text.1":"焰火是一种在《我的世界》中创建自己独特庆祝的有趣方式！",
    "howtoplay.fireworks.text.2":"焰火有两个部分，即焰火火箭和焰火之星。",
    "howtoplay.fireworks.header.1":"焰火火箭",
        "howtoplay.fireworks.text.3.touch":"若要使用焰火，只需点击方块即可将焰火发射到空中。",
    "howtoplay.fireworks.text.4":"焰火除了向上射入空中之外没有其他作用。",
    "howtoplay.fireworks.header.2":"焰火之星",
    "howtoplay.fireworks.text.5":"在制作焰火火箭的过程中，可以添加焰火之星，以赋予它许多不同的颜色和效果。",
    "howtoplay.fireworks.text.6":"焰火之星由火药和各种其他物品制成：",
    "howtoplay.fireworks.text.6.1":"§e颜色§f - 添加任何颜色的染料可实现以该颜色爆炸。",
    "howtoplay.fireworks.text.6.2":"§e闪烁§f - 添加荧石粉可实现爆炸闪烁。",
    "howtoplay.fireworks.text.6.3":"§e苦力怕形状§f - 添加头部可在空中形成苦力怕图案。",
    "howtoplay.fireworks.text.6.4":"§e爆发§f - 添加羽毛可给予爆炸一个爆发效果。",
    "howtoplay.fireworks.text.6.5":"§e拖尾§f - 添加钻石可给予爆炸拖尾效果。",
    "howtoplay.fireworks.text.6.6":"§e星形§f - 添加金粒可在空中形成星形图案。",
    "howtoplay.fireworks.header.3":"焰火制造术",
    "howtoplay.fireworks.text.7":"焰火可由发射器发射。将以发射器的朝向方向发射焰火。",
    "howtoplay.fishing":"钓鱼",
    "howtoplay.fishing.text.1":"必须使用钓鱼竿来钓鱼，这是从海里捕获某种鱼或其他炫酷物品的绝佳方式！",
    "howtoplay.fishing.header.1":"抛",
        "howtoplay.fishing.text.2.touch":"盯着水中的一个方块，在持有钓鱼竿的同时点击“钓鱼”按钮即可将饵钩抛进水里。",
    "howtoplay.fishing.header.2":"开始钓鱼！",
    "howtoplay.fishing.text.3":"等待直至您留意到饵钩处出现泡泡的痕迹。",
        "howtoplay.fishing.text.4.touch":"当泡泡碰到饵钩时，饵钩会上下摆动。再次点击“钓鱼”按钮可收回饵钩。小心不要让鱼跑掉！",
    "howtoplay.food":"食物",
    "howtoplay.food.title":"游戏指南：食物",
    "howtoplay.food.text.1":"在冒险期间，你的饥饿度会缓慢增长，不过好在主世界里到处都能找到食物！你可以从树上采集苹果，从动物身上获得肉，或者何不自己拿起锄头种植农作物呢？",
                "howtoplay.food.text.3":"有些未经加工的食物先在营火或熔炉上烹饪后会更美味，你的胃会感到非常满足！",
    "howtoplay.furnace":"熔炉",
    "howtoplay.furnace.text.1":"您可以使用熔炉烹饪或熔化物品。例如，可以将铁矿石熔化为铁锭。",
        "howtoplay.furnace.text.2.touch":"将熔炉置于世界中，通过点击方式使用它。",
    "howtoplay.furnace.header.1":"燃料",
    "howtoplay.furnace.text.3":"您需要在熔炉底部放一些燃料并将您想要熔化的物品放在熔炉上面。熔炉随后会点燃并开始工作。许多东西都可以用作燃料；尝试使用任何可燃之物！",
    "howtoplay.gameSettings":"游戏设置",
    "howtoplay.gameSettings.text.1":"创建世界时，您有多个选项。以下是可用来微调您的体验的各种设置。如果您在创建世界时未设置它们，不用担心，您可以随时更改这些设置。",
    "howtoplay.gameSettings.text.2":"§e世界名称§f：可以在此处对你的世界进行命名。",
    "howtoplay.gameSettings.text.3":"§e默认游戏模式§f：这是所有新玩家进入世界的初始游戏模式。可以让玩家从生存模式或创造模式开始。选择创造模式将会开启作弊。",
    "howtoplay.gameSettings.text.4":"§e难度§f：该设置会影响世界的难度等级。可以选择和平、简单、一般或困难。",
    "howtoplay.gameSettings.header.1":"世界偏好",
    "howtoplay.gameSettings.text.5":"§e初始地图§f：如果启用该设置，每位玩家都可以在其热键栏中开始玩一个地图。",
    "howtoplay.gameSettings.text.6":"§e奖励宝箱§f：如果启用该设置，则在初始生成位置附近将会有一个宝箱，里面有一些初始战利品。",
    "howtoplay.gameSettings.text.7":"§e世界类型§f：该设置控制世界的创建方式。通过从下拉菜单中选择无限或平坦来更改世界类型。",
    "howtoplay.gameSettings.text.7.1":"  §e无限世界§f永无止尽。",
    "howtoplay.gameSettings.text.7.2":"  §e平坦世界§f中没有任何山丘或树木，仅仅是可供你在其中进行创建的无限平坦区域。",
    "howtoplay.gameSettings.text.8":"§e种子§f：这是世界的唯一数字。通过在创造新世界时输入种子，可以控制世界的创建方式。此外，也可以使用字或词组作为种子，游戏会将其转换为数字。",
    "howtoplay.gameSettings.header.2":"作弊和游戏规则",
    "howtoplay.gameSettings.text.9":"§e激活作弊§f：此设置允许玩家使用命令。如果在创建世界时此设置处于启用状态，则会禁用所有成就。",
    "howtoplay.gameSettings.text.10":"下面是必须启用作弊才能使用的游戏规则：",
    "howtoplay.gameSettings.text.11":"§e终为白日§f：启用此设置时，夜晚永远不会降临。",
    "howtoplay.gameSettings.text.12":"§e开启昼夜更替§f：禁用此设置时，时间不会前进。",
    "howtoplay.gameSettings.text.13":"§e保留物品栏§f：此设置允许玩家在死亡时保留其物品栏。",
    "howtoplay.gameSettings.text.14":"§e生物生成§f：禁用此设置时，这会阻止所有生物生成。",
    "howtoplay.gameSettings.text.15":"§e生物破坏§f：阻止生物破坏世界。",
    "howtoplay.gameSettings.text.16":"§e实体掉落战利品§f：控制矿车和盔甲架等物品在损坏后是否会自行掉落。",
    "howtoplay.gameSettings.text.17":"§e天气更替§f：禁用此设置时，天气将不会更替。",
    "howtoplay.hoppers":"漏斗",
    "howtoplay.hoppers.text.1":"漏斗用于自动移送物品。漏斗可以连接到其他一些物品，例如箱子或唱片机等容器。",
    "howtoplay.hoppers.text.2":"漏斗会持续从放置在其上的容器中移除物品，并把物品移入漏斗所指向的容器中。",
    "howtoplay.hoppers.header.1":"用法",
    "howtoplay.hoppers.text.3":"要使漏斗指向特定方块，请在潜行时将漏斗置于该方块上。",
    "howtoplay.hoppers.text.4":"如果漏斗由红石提供能量，漏斗会变成非活动状态并停止移动物品。",
    "howtoplay.hostAndPlayerOptions":"主控者和玩家选项",
    "howtoplay.hostAndPlayerOptions.text.1.notTouch":"当在启用作弊的情况下玩游戏时，您可以通过主控者选项传送您自己或好友、更改天气、设置当日时间、更改游戏的入口点或世界生成。启用作弊后，您可以通过点击聊天栏旁边的 [/] 按钮在聊天窗口中找到这些选项。",
    "howtoplay.hostAndPlayerOptions.text.1.touch":"当在启用作弊的情况下玩游戏时，您可以通过主控者选项传送您自己或好友、更改天气、设置当日时间、更改游戏的入口点或世界生成。启用作弊后，您可以通过点击“聊天”按钮在聊天窗口中找到这些选项。",
    "howtoplay.improvedTools":"改进的工具",
    "howtoplay.improvedTools.title":"游戏指南：改进的工具",
    "howtoplay.improvedTools.text.1":"频繁使用工具会导致它们最终损坏。当你收集到新的材料，例如石头时，你可以合成更好的工具。",
    "howtoplay.improvedTools.text.2":"更高级别的工具会更加耐用、高效，也能够收集到更多宝贵资源。走进这个世界，亲自去探索一番吧！",
    "howtoplay.inventory":"物品栏",
    "howtoplay.inventory.title":"游戏指南：物品栏",
    "howtoplay.inventory.header.1":"1. 物品栏",
    "howtoplay.inventory.header.2":"2. 快捷栏",
                    "howtoplay.inventory.text.2.keyboard":"想要在§e快捷栏§f和物品栏之间移动物品吗？打开你的物品栏，点击你选择的物品，然后将其拖放到你想要移至的空物品栏位上。",
        "howtoplay.inventory.text.2.touch":"想要在§e快捷栏§f和物品栏之间移动物品吗？点击你选择的物品，然后点击你想要移至的空物品栏位。",
        "howtoplay.jukebox":"唱片机",
    "howtoplay.jukebox.text.1":"唱片机将播放您找到的音乐唱片。",
    "howtoplay.jukebox.header.1":"开始派对",
        "howtoplay.jukebox.text.2.touch":"手里拿着音乐唱片的同时点击唱片机来播放它。再次点击唱片机可弹出音乐唱片。",
    "howtoplay.jukebox.header.2":"红石",
    "howtoplay.jukebox.text.3":"当唱片机播放音乐唱片时，将为红石粉提供能量。",
    "howtoplay.jukebox.text.4":"尝试播放不同的音乐唱片来获得不同的能量等级。",
    "howtoplay.jukebox.text.5":"看看当让唱片播放到结尾时会发生什么。",
    "howtoplay.jukebox.text.6":"一个漏斗可供您放入一张音乐唱片，在唱片播放完后，请取出该唱片。",
    "howtoplay.jukebox.header.3":"查找音乐唱片",
    "howtoplay.jukebox.text.7":"可以在世界各处的箱子里找到一些音乐唱片。",
    "howtoplay.jukebox.text.8":"其他唱片查找起来较为困难，苦力怕会秘密欣赏音乐。",
    "howtoplay.loom":"织布机",
    "howtoplay.loom.text.1":"织布机可以迅速而有效地将图案应用到旗帜上。织布机一次只使用一种染料来织造图案。它还可以使用织布机图案来应用特殊的图案。",
    "howtoplay.loom.header.1":"编织",
    "howtoplay.loom.text.2":"通过将旗帜放置进织布机的第一个槽位，并将任一颜色的染料放进第二个槽位，就可以向旗帜上添加图案。一旦选择了某个图案，就可以将它从右边的输出槽位移到您的物品栏中。",
    "howtoplay.loom.text.3":"一个旗帜可以有多个层，让您试验旗帜许多不同的可能性。一个旗帜上至多可以应用 6 种图案，以创造出独特的设计。",
    "howtoplay.loom.header.2":"织布机图案",
    "howtoplay.loom.text.4":"通过将一个织布机图案添加到织布机的第三个槽位，可以合成特殊图案，例如苦力怕的脸或花卉图案。当将这些图案添加到您的旗帜时，您不会失去您的织布机图案。",
    "howtoplay.mining":"采矿",
    "howtoplay.mining.title":"游戏指南：采矿",
    "howtoplay.mining.text.1":"并不是所有合成材料都在地表上，有些可能需要你深入地下或挖掘山体内部。",
            "howtoplay.mounts":"骑乘",
    "howtoplay.mounts.text.1":"玩家可以骑乘任何成年的§e马§f、§e驴§f、§e骡子§f或§e骆驼§f。只有马可以套上盔甲。",
    "howtoplay.mounts.text.2":"骡和驴可以通过挂一个箱子来装备鞍囊（用于运输物品）。在骑乘或潜行时均可使用这些鞍囊。",
    "howtoplay.mounts.header.1":"驯服",
        "howtoplay.mounts.text.3.touch":"马、驴和骡子在利用之前必须先§e驯服§f。要驯服一匹马，玩家需要先骑上去，在它想把你摔下来的时候保持不掉下来。点击在靠近一匹马时出现的“骑乘”按钮来尝试驯服马、驴和骡子。",
    "howtoplay.mounts.text.4":"当马周围出现心时，表示它已经被驯服，将不再试图将玩家摔下马背。",
    "howtoplay.mounts.header.2":"骑乘动物",
    "howtoplay.mounts.text.5":"玩家必须给马和骆驼装备§e鞍§f，才能驾驭它们。",
    "howtoplay.mounts.text.6":"可以从村民那里购买鞍，在世界里的隐藏宝箱里找到鞍，或者通过钓鱼获得鞍。当骑马时，打开物品栏并将一个鞍放入马鞍栏位。",
    "howtoplay.mounts.text.6b":"骆驼可以同时携带两名玩家。",
    "howtoplay.mounts.text.7":"和其他动物一样，马和驴都可以用金苹果或金胡萝卜喂食。",
    "howtoplay.mounts.text.8":"小马驹随后会长成成年马，喂食小麦或干草可加速其成长。",
    "howtoplay.mounts.header.3":"驮畜",
    "howtoplay.mounts.text.9":"羊驼是另一可以驯服的可骑乘生物，可用来运输大件物品。",
    "howtoplay.mounts.text.10":"可以像驯服马一样驯服羊驼。但即使已经驯服羊驼，玩家在骑乘它们时仍然无法控制它们的行动。",
    "howtoplay.mounts.text.11":"可以用一根拴绳拴住一只羊驼，随后周围的羊驼（驯服和未驯服的羊驼）都将跟随其后，组成一支商队。",
    "howtoplay.mounts.text.12":"可以给羊驼装备箱子，根据羊驼的体力，给予羊驼 3 到 15 格物品栏空间。还可以给羊驼装备地毯。各色地毯的图案都各不相同。",
    "howtoplay.mounts.header.4":"猪",
    "howtoplay.mounts.text.13":"也可以骑乘猪，但如果您不采取激励手段，它们不会前往您想去的地方。",
    "howtoplay.mounts.text.14":"给猪装备鞍，然后将胡萝卜钓竿指向您想去的方向。",
    "howtoplay.mounts.header.5":"跳下",
                "howtoplay.movingAround":"四处移动",
    "howtoplay.movingAround.title":"游戏指南：四处移动",
    "howtoplay.movingAround.text.1":"欢迎来到主世界，一个充满冒险的方块世界带给你无限可能！",
    "howtoplay.movingAround.text.2.keyboard":"使用鼠标环顾四周。",
        "howtoplay.movingAround.text.2.touch":"通过触碰并拖动屏幕来环顾四周。",
                            "howtoplay.movingAround.text.3a.touch.classic_dpad":"使用屏幕上的按钮在世界中四处移动。",
                                        "howtoplay.gatheringResources":"收集资源",
    "howtoplay.gatheringResources.title":"游戏指南：收集资源",
    "howtoplay.gatheringResources.text.1":"这个世界中资源丰富，包括§e建造方块§f、§e合成材料§f以及§e食物§f。",
        "howtoplay.gatheringResources.text.2.touch":"泥土、木头和南瓜等大多数资源都可以徒手采集。只需走到资源附近，然后触碰并按住屏幕直至其掉落。我们称这个过程为§e打破方块§f。",
        "howtoplay.gatheringResources.text.3":"靠近浮空图标即可捡起任何掉落的资源。",
    "howtoplay.selectingItems":"选择物品",
    "howtoplay.selectingItems.title":"游戏指南：选择物品",
    "howtoplay.selectingItems.text.1":"你捡起的资源会出现在屏幕底部的§e快捷栏§f中。",
    "howtoplay.selectingItems.text.2.keyboard":"要将物品拿在手中，滚动鼠标滚轮进行选择。你也可以用数字键进行选择，1 对应于快捷栏第一个栏位，而 9 则对应于最后一个栏位。",
        "howtoplay.selectingItems.text.2.touch":"要将物品拿在手中，只需点击快捷栏中的物品即可。",
                "howtoplay.selectingItems.text.3.touch":"通过触碰并按住屏幕任意位置可以使用一些物品，例如桶、钓鱼竿和弓。",
        "howtoplay.selectingItems.header.1":"1. 快捷栏",
    "howtoplay.placingBlocks":"放置方块",
    "howtoplay.placingBlocks.title":"游戏指南：放置方块",
    "howtoplay.placingBlocks.text.1":"你捡起的所有方块都可以重新放置在世界中。这样便可建造温暖舒适的§e避难所§f，也可以发挥想象力肆意建造！",
        "howtoplay.placingBlocks.text.2.touch":"点击快捷栏中的方块选择它，然后点击世界中的某个位置进行放置。",
        "howtoplay.placingBlocks.text.3":"如果不小心把方块放错了位置，不用担心，只需要再次将其破坏，然后再捡回来即可！",
    "howtoplay.navigation":"导航",
    "howtoplay.navigation.text.1":"导航是您在《我的世界》中将要学习的一项重要技能，因为有时找到回家之路并非易事。",
    "howtoplay.navigation.text.2":"首先，您应该对一些基本工具有所了解。",
    "howtoplay.navigation.header.1":"导航工具",
    "howtoplay.navigation.text.3":"指南针将指向您在世界中的第一个出生地的方向，此方法可让您轻松找到您的出发位置。",
    "howtoplay.navigation.text.4":"地图使您能够查看已经探索过的区域。将其置于您的副手槽中并像使用小地图一样使用它。您可以通过在工作台上向地图边缘添加更多纸来扩大其尺寸。",
    "howtoplay.navigation.text.5":"定位器地图将显示您的所在位置以及您相对于定位器地图原点的朝向。它也会向您显示同一个世界中其他玩家的位置。",
    "howtoplay.navigation.text.6":"制图台可以帮助您创建、扩展、复制甚至命名地图。",
    "howtoplay.navigation.text.7":"把纸放进第一个槽来合成地图。如果您在第二个槽中加入一个指南针，您可以合成一个定位器地图。添加纸或空地图将允许您扩展或复制您的地图。",
    "howtoplay.navigation.header.2":"导航技术",
    "howtoplay.navigation.text.8":"请尽量在探索时留意地标。在一个世界中玩的时间越长，越容易记住您的位置。另一个非常好的诀窍是在移动时放置火把，这样您就可以找到回家的路了。",
    "howtoplay.navigation.text.9":"太阳也能指示您的朝向。记住：太阳东升西落！",
    "howtoplay.navigation.header.3":"探险者地图",
    "howtoplay.navigation.text.10":"有许多地方可供您探索。找到村庄并寻找制图师。他会和您交易探险者地图，这些地图将带您前往非常遥远的陌生地域。",
    "howtoplay.netherPortals":"下界传送门",
    "howtoplay.netherPortals.text.1":"下界传送门使您能够进入不同的维度。",
    "howtoplay.netherPortals.text.2":"如果构造正确，下界传送门就能够被点燃和激活。",
    "howtoplay.netherPortals.text.3":"这里显示了传送门建造示例：",
    "howtoplay.nightfall":"黄昏",
    "howtoplay.nightfall.text.1":"在《我的世界》中，当您在世界中冒险时太阳会升起和落下。当太阳落下时，必须要采取预防措施，因为夜间危机四伏！",
    "howtoplay.nightfall.header.1":"寻求庇护",
    "howtoplay.nightfall.text.2":"如果您并未采取预防措施，则需要寻找一个地方来躲避黑暗以及黑暗中潜藏着的危险。这样的地方很容易找，比如山丘一侧的洞或森林中的小木屋。",
    "howtoplay.nightfall.text.3":"请务必封堵所有入口，您可能需要使用门来方便您进出。如果您制作了一张床，此处非常适合放置它，可将它与工作台和熔炉放置在一起。",
    "howtoplay.nightfall.text.4":"另外务必使用火把照亮此区域，这可能会救您的命。",
    "howtoplay.nightfallNew":"黄昏",
    "howtoplay.nightfallNew.title":"游戏指南：黄昏",
    "howtoplay.nightfall.new.text.1":"夕阳西下，是时候做好准备了。",
    "howtoplay.nightfall.new.text.2":"晚上，主世界成为了僵尸、蜘蛛、骷髅及其他危险生物（我们称其为§e敌对生物§f）的乐园。",
    "howtoplay.nightfall.new.text.3":"合成一些§e火把§f可以帮助你在黑暗中看清四周，同时阻止一些生物靠得过近。",
    "howtoplay.nightfall.new.text.4.keyboard":"手持火把时，右键点击附近的空地即可将其放置在世界中。",
        "howtoplay.nightfall.new.text.4.touch":"手持火把时，点击附近的空地即可将其放置在世界中。",
        "howtoplay.pets":"宠物",
    "howtoplay.pets.header.1":"照顾宠物",
        "howtoplay.pets.text.1.touch":"在《我的世界》中，有多种可以驯服的生物，而且可以让它们成为您的宠物。可以通过给予各生物喜爱的物品来驯服它们。驯服后，您可以点击“坐”按钮来让它们留下。",
    "howtoplay.pets.header.2":"狼",
    "howtoplay.pets.text.2":"狼是在较冷的气候中狩猎的中立型生物。它们会攻击兔子、骷髅和羊，但会远离羊驼。除非您向它们挑衅，否则它们不会攻击您。您可以通过给它们喂骨头来驯服它们。",
    "howtoplay.pets.header.3":"猫",
    "howtoplay.pets.text.3":"猫是出没于村庄中的中立型生物。它们会攻击兔子和海龟宝宝。它们还会赶走幻翼和苦力怕。它们会试着躲着您，因此驯服它们可能并非易事。它们喜欢吃鱼，所以给它们喂生鳕鱼或鲑鱼来驯服它们。",
    "howtoplay.pets.header.4":"鹦鹉",
    "howtoplay.pets.text.4":"鹦鹉是居住在丛林中的被动型生物。它们会模仿所在区域中的任何其他生物。它们最喜欢种子，给它们喂一些种子来驯服它们。鹦鹉还会站在您的肩膀上……是的，您可以让多只鹦鹉站在您的肩膀上。",
    "howtoplay.raids":"劫掠",
    "howtoplay.raids.text.1":"在探索世界的过程中，您可能会遇到掠夺者的营地或巡逻队。掠夺者总是在寻找村庄进行袭击，携带他们的旗帜会引起他们的注意，他们还可能会选择袭击附近的村庄。",
    "howtoplay.raids.text.2":"一定要保卫您的村庄，如果您击败了所有的劫掠者，攻击就会停止。",
    "howtoplay.raids.header.1":"英雄救我",
    "howtoplay.raids.text.3":"村民们很可能会非常感激您把他们从劫掠者手中救了出来。一定要和他们确认一下，您可能会做成一笔好交易。",
    "howtoplay.ranching":"牧场经营",
    "howtoplay.ranching.text.1":"在《我的世界》中，您可以拥有自己的牧场，养满牲畜！牧场经营可获得许多资源，如羊毛、鸡蛋和生肉。",
    "howtoplay.ranching.header.1":"扩大您的牧群",
    "howtoplay.ranching.text.2":"为了使牲畜数量不断增长，必须让动物繁殖。成年动物必须进入“爱情模式”才能繁殖。喂动物吃喜欢的食物来让它们进入“爱情模式”。",
    "howtoplay.ranching.text.3":"当两只同类动物彼此靠近并且都处于“爱情模式”时，它们就会亲吻一会儿，然后生出一只动物宝宝！动物宝宝会与其父母呆在一起直至成年。生完宝宝后，成年动物必须等 5 分钟才能再次进入“爱情模式”。",
    "howtoplay.ranching.header.2":"生物吃什么？",
    "howtoplay.ranching.text.4":"牛、哞菇和羊都吃小麦。猪可以吃胡萝卜或甜菜根。鸡喜欢吃各种种子。兔子吃胡萝卜、金胡萝卜或蒲公英。豹猫喜欢吃生鳕鱼或鲑鱼。狼喜欢吃各种肉类。",
    "howtoplay.ranching.text.5":"当您拿着动物喜欢的食物物品时，它们会跟着您。这将有助于您将它们引入您的牧场或引导它们走向其他动物。",
    "howtoplay.recipeBook":"配方书",
    "howtoplay.recipeBook.title":"游戏指南：配方书",
    "howtoplay.recipeBook.text.1.keyboard":"别担心，你无需记住每个配方。物品栏中的§e配方书§f会记录方块以及你可以合成的物品。只需点击配方即可查看合成所需的原料。",
    "howtoplay.recipeBook.text.1.gamepad":"别担心，你无需记住每个配方。物品栏中的§e配方书§f会记录方块以及你可以合成的物品。只需选择配方即可查看合成所需的原料。",
    "howtoplay.recipeBook.text.1.touch":"别担心，你无需记住每个配方。物品栏中的§e配方书§f会记录方块以及你可以合成的物品。只需点击配方即可查看合成所需的原料。",
    "howtoplay.recipeBook.text.2.keyboard":"收集到所需的合成原料后，请再次点击配方，然后将其从输出槽移动到快捷栏或物品栏。",
    "howtoplay.recipeBook.text.2.gamepad":"收集到所需的合成原料后，请再次选择配方，然后将其从输出槽移动到快捷栏或物品栏。",
    "howtoplay.recipeBook.text.2.touch":"收集到所需的合成原料后，请再次点击配方，然后将其从输出槽移动到快捷栏或物品栏。",
    "howtoplay.redstone":"红石",
    "howtoplay.redstone.text.1":"红石粉来自传输电子信号的红石。具有能量时，它将点亮并将其信号传输给邻近的其他红石物品。",
    "howtoplay.redstone.header.1":"红石能量",
    "howtoplay.redstone.text.2":"若要为其中一个物品提供能量，它需要诸如拉杆、按钮或压力板等能量源。试着找到全部能量源！",
    "howtoplay.redstone.text.3":"在能量源旁边放置一些红石粉并开启它来赋予能量。",
    "howtoplay.redstone.text.4":"有许多物品会使用红石信号来发挥作用，例如漏斗或活塞。",
    "howtoplay.redstone.text.5":"红石可以实现无限可能性！试着为自己创建一些有用的东西，例如自动农场！",
    "howtoplay.scaffolding":"脚手架",
    "howtoplay.scaffolding.header.1":"触摸天际",
            "howtoplay.scaffolding.text.1a.touch":"脚手架可让你能到达更高的地方，且在不受坠落伤害的情况下安全下降，以此来方便你建造大型结构。",
                    "howtoplay.scaffolding.header.2":"为您的建造提供支撑",
    "howtoplay.scaffolding.text.2":"脚手架需要支撑。您只能在水平方向放置若干个脚手架而不接触到不同的方块。当您试图在没有适当支撑的情况下放置过多的脚手架时，它会倒塌。脚手架可以像普通的方块一样进行放置，但它也可以被放置在自己的地基上，以便快速建成一座高塔。",
    "howtoplay.scaffolding.header.3":"快速打破",
    "howtoplay.scaffolding.text.3":"当脚手架被破坏时，它也会破坏由它所支撑的每一个脚手架。这将让您能够通过破坏支撑方块来快速清理您的脚手架！",
    "howtoplay.structureBlocks":"结构方块",
    "howtoplay.structureBlocks.text.1":"结构方块使得创建者们能够将世界的部分复制并保存为结构。所保存的结构在之后又可以粘贴回世界中。",
    "howtoplay.structureBlocks.header.1":"获得方式",
    "howtoplay.structureBlocks.text.2":"要获得结构方块，您必须使用 /give 斜杠命令。要使用结构方块，您必须具有操作员权限。",
    "howtoplay.structureBlocks.header.2":" 模式",
    "howtoplay.structureBlocks.text.3":"结构方块有 4 种模式：保存、加载、角落和 3D 导出，您可以使用模式下拉菜单在它们之间进行切换。",
    "howtoplay.structureBlocks.text.4":"保存模式会将世界的一个区域保存为一个结构。",
    "howtoplay.structureBlocks.text.5":"加载模式会将结构加载到世界中。只有保存至世界中的结构或者世界中应用的行为包所包含的结构才能被加载。",
    "howtoplay.structureBlocks.text.6":"角模式与保存模式的检测按钮一起使用，以自动设置要保存的区域。详细信息，请参阅下面的”角落模式“部分。",
    "howtoplay.structureBlocks.text.7":"3D 导出会在支持的平台上导出 3D 模型文件。",
    "howtoplay.structureBlocks.header.3":"预览窗口",
    "howtoplay.structureBlocks.text.8":"在结构方块屏幕的右侧，将根据方块所处的模式，显示您所选择的区域或者要加载的结构的预览。",
            "howtoplay.structureBlocks.text.9.touch":"触摸并拖动预览以旋转 3D 预览。",
    "howtoplay.structureBlocks.header.4":"红石激活",
    "howtoplay.structureBlocks.text.10":"红石可以用来激活一个结构方块。根据方块的模式及其设置，这会导致红石将结构保存到外部或将结构加载入世界。",
    "howtoplay.structureBlocks.header.5":"完整性和种子",
    "howtoplay.structureBlocks.text.11":"您可以通过更改完整性和种子的值来更改某个结构的加载量。",
    "howtoplay.structureBlocks.text.12":"完整性——从结构中加载的方块的百分比，接受的值是 0 到 100。如果没有指定种子，将随机选择方块。",
    "howtoplay.structureBlocks.text.13":"种子——在这里输入的值将决定在使用完整性时将删除哪些方块。如果您希望随机选择方块，请将此字段留空。",
    "howtoplay.structureBlocks.header.6":"结构空位方块",
    "howtoplay.structureBlocks.text.14":"当一个带有结构空位方块的结构被加载到世界中时，结构空位方块加载目的地上的任何原本可能被移除的方块将会转而留在该世界中。",
    "howtoplay.structureBlocks.text.15":"举例：在把一艘空的沉船加载到海底时，通常会在水方块上方复制空气。如果沉船充满了结构空位，那么水就会留下来，您就会获得一个充满水的沉船了。",
    "howtoplay.structureBlocks.header.7":"检测和角落模式",
    "howtoplay.structureBlocks.text.16":"要自动选择要保存的区域，您可以在结构周围放置角落模式方块，并使用与要保存的结构相同的名称来命名它们。",
    "howtoplay.structureBlocks.text.17":"在保存模式下按下检测按钮将找到所有具有相同名称的角落方块，并创建一个选择区域，以便保存这些角落方块所生成的卷中的所有内容。",
    "howtoplay.shulkerBoxes":"潜影盒",
    "howtoplay.shulkerBoxes.text.1":"将两个潜影壳与箱子结合来制作潜影盒。潜影壳是末地城中的潜影贝掉落之物。与其他容器不同，潜影盒被损坏后会保留它们的物品。被活塞推动的潜影盒会损坏并且会作为物品掉落，可以使用发射器来放置潜影盒。",
    "howtoplay.theCraftingTable":"工作台",
    "howtoplay.theCraftingTable.title":"游戏指南：工作台",
        "howtoplay.theCraftingTable.text.2.keyboard":"将你的工作台放置在世界中，然后右键点击打开。可合成的物品包括工具、床还有门等等，网格合成表越大，可合成的物品就会更大更好。",
        "howtoplay.theCraftingTable.text.2.touch":"将你的工作台放置在世界中，然后点击打开。可合成的物品包括工具、床还有门等等，网格合成表越大，可合成的物品就会更大更好。",
    "howtoplay.theEnd":"末地",
    "howtoplay.theEnd.text.1":"末地是可通过激活的末地传送门进入的另外一个维度。末地传送门可在要塞之中找到，要塞位于主世界的地底深处。",
    "howtoplay.theEnd.text.2":"每个末地传送门框架方块都缺少一些神秘之物来诱发内部的力量。",
    "howtoplay.theEnd.header.1":"另一边",
    "howtoplay.theEnd.text.3":"传送门被激活后，跳入其中即可前往末地。",
    "howtoplay.theEnd.text.4":"末地是可怕的末影龙的家园。她是既凶残又强大的敌人，似乎能从奇异水晶中汲取力量。她的龙息和火球攻击可以在整个战地留下滞留酸性物。带上一些好友以确保取得胜利！",
    "howtoplay.theEnd.text.5":"一次不行的话，可以将四颗末影水晶添加到返回传送门的各个角落来重新唤醒末影龙。",
    "howtoplay.tools":"工具",
    "howtoplay.tools.text.1":"在《我的世界》中有许多工具，用来开采方块比徒手开采要快得多。这些工具可使用木头、石头、铁、黄金、钻石或下界合金合成。",
    "howtoplay.tools.text.2":"使用合适的工具进行工作不仅可以让您更快速地开采方块，而且还能够减慢耐久度消耗。若要开采更稀有的资源，必须制作更复杂的工具。",
    "howtoplay.tools.header.1":"破坏东西的工具",
    "howtoplay.tools.text.3":"镐非常适合用来破坏坚硬的方块，例如圆石、铁或熔炉。",
    "howtoplay.tools.text.4":"斧头非常适合用来破坏木质方块，例如原木、木板或工作台。",
        "howtoplay.tools.text.5.touch":"锹非常适合用来破坏疏松的方块，例如泥土、沙子和砂砾。锹还可用于创建草径，只要在草方块上进行点击即可。",
        "howtoplay.tools.text.6.touch":"需要使用锄头来耕作泥土从而种植农作物。点击泥土或草方块可让它们转换为农地。",
    "howtoplay.tools.text.7":"所有这些工具都可接受附魔，无论是从附魔台还是铁砧进行附魔。",
    "howtoplay.tools.header.2":"其他工具",
    "howtoplay.tools.text.8":"还有更多工具可协助您冒险：",
    "howtoplay.tools.text.9":"使用桶可以收集水、奶、熔岩，甚至鱼等物体。",
    "howtoplay.tools.text.10":"使用打火石可以点火...在树林茂密的区域使用时需小心！",
    "howtoplay.tools.text.11":"使用钓鱼竿可以从水方块中捕获鱼和其他战利品。还可使用它拖动其他玩家和生物。钓鱼竿也可以附魔！",
    "howtoplay.tools.text.12":"剪刀非常适合收集羊毛、树叶和蜘蛛网等物品。",
    "howtoplay.trading":"村民交易",
    "howtoplay.trading.text.1":"在村庄中可进行交易。每个村民都有一项职业，他们可能是农民、屠夫、铁匠、制图师、图书管理员或牧师。有些职业可以交易其他职业无法交易的物品。探索并与许多村民交易以找到所有的可进行交易。",
    "howtoplay.trading.header.1":"用于换取绿宝石的商品",
    "howtoplay.trading.text.2":"您可以通过与村民互动来了解他们会提供什么来进行交易。村民可能会在与玩家交易时调整交易价格。村民可能会缺货，或者由于过于频繁地使用某项交易从而导致其暂时被禁用。交易通常涉及到绿宝石的买卖。",
    "howtoplay.trading.text.3":"当您与村民进行交易时，他们的职业水平会提高，并开始提供更好、更有价值的交易。",
    "howtoplay.trading.text.4":"照顾好您的村民，他们需要休息、工作和吃饭才能茁壮成长。",
    "howtoplay.transportation":"交通运输",
    "howtoplay.transportation.text.1":"除了步行、骑乘或飞行外，还有很多方法可以到达各地。",
    "howtoplay.transportation.header.1":"矿车",
    "howtoplay.transportation.text.2":"矿车是在轨道上运行的小车，可以乘坐。通过连接放置，你可以造出通往任意地点的轨道。将矿车放置在轨道上，你就可以乘坐了。",
    "howtoplay.transportation.text.2.touch":"矿车是在轨道上运行的小车，可以乘坐，建造后可用于前往任何地方。只需将多个轨道并排放置，将矿车放置在铁轨上，您就可以乘坐了。",
            "howtoplay.transportation.text.3a.touch":"看向一辆矿车，然后点击“骑乘”即可跳进去。",
            "howtoplay.transportation.header.2":"船",
    "howtoplay.transportation.text.4":"船让您可以在水面上旅行，将一艘船放置在水方块上即可出发。",
    "howtoplay.transportation.text.4.touch":"船让您可以在水面上旅行，只需将一艘船放置在水方块上即可出发。",
            "howtoplay.transportation.text.5a.touch":"看向一艘船，然后点击“上船”即可登上船只。",
            "howtoplay.weapons":"武器",
    "howtoplay.weapons.header.1":"木剑",
    "howtoplay.weapons.text.1":"剑是《我的世界》中的主要近战武器。可以使用木头、石头、铁、黄金、钻石或下界合金制成。跳劈会造成暴击伤害！",
        "howtoplay.weapons.text.2.touch":"点击生物对其进行攻击。",
    "howtoplay.weapons.header.2":"弓",
        "howtoplay.weapons.text.3.touch":"弓是《我的世界》中的主要远程武器。按住屏幕可拉弓。释放所按屏幕可射箭。弓在有箭的情况下才能射出。",
    "howtoplay.weapons.text.4":"弦往后拉得越多，弓造成的伤害就越大，请确保将弦拉满。",
    "howtoplay.weapons.header.3":"弩",
        "howtoplay.weapons.text.5a.touch":"弩是一种远程武器，需要装入箭矢。长按屏幕上的任意位置，为弩装填箭矢。",
    "howtoplay.weapons.text.5b.touch":"弩装填完毕后，即使你把它放在物品栏中，它也会保持装填状态，可随时射击。",
    "howtoplay.weapons.text.5c.touch":"点击屏幕上的任意位置即可用装填好的弩射击。",
        "howtoplay.weapons.header.4":"三叉戟",
        "howtoplay.weapons.text.6.touch":"三叉戟是近战和远程两用武器。点击生物可攻击它们。按住屏幕可将三叉戟收回。释放所按屏幕可投掷三叉戟。三叉戟是最好的水下武器。",
    "howtoplay.weapons.header.5":"附魔武器",
    "howtoplay.weapons.text.7":"您可从附魔台或铁砧为剑、弓、弩和三叉戟获取特定附魔，它们将提高伤害值、耐久度甚至可以放火烧生物！",
    "howtoplay.yourFirstCraft":"首次合成",
    "howtoplay.yourFirstCraft.title":"游戏指南：首次合成",
    "howtoplay.yourFirstCraft.header.1":"1. 网格合成表",
    "howtoplay.yourFirstCraft.text.1":"木头等很多方块都可以通过合成变为有用的物品。如果想要进行合成，你需要在物品栏界面的右侧找到一个简单的§e网格合成表§f。",
    "howtoplay.yourFirstCraft.text.2":"例如，只要在网格合成表的任意位置放一个原木，那么§e输出槽§f中就会出现几块木板。",
    "howtoplay.yourFirstCraft.text.3.touch":"只需点击这些崭新的木板，它们就会出现在快捷栏中。这样就可以把它们放置在世界中了！",
    "howtoplay.yourFirstCraft.text.3.keyboard":"只需将这些崭新的木板拖动到快捷栏，就可以把它们放置在世界中了！",
    "howtoplay.yourFirstCraft.text.3.gamepad":"只需选择这些崭新的木板，它们就会出现在快捷栏中。这样就可以把它们放置在世界中了！",
    "howtoplay.yourFirstCraft.header.2":"2. 合成配方",
    "howtoplay.yourFirstCraft.text.4":"合成某些物品时，需要将合成原料摆放成特定的形状 - 也称为§e配方§f。",
    "howtoplay.yourFirstCraft.text.5":"试试将两块木板叠放在一起合成一条木棍。它的用处可就大了！",
    "howtoplay.smithing_table.header.1":"锻造模板",
    "howtoplay.smithing_table.header.2":"纹饰盔甲",
    "howtoplay.smithing_table.text.1":"想要充分利用设备？你需要一张锻造台。",
    "howtoplay.smithing_table.text.2":"使用它可以进行各种更改，例如，将钻石装备升级到下界合金，或使用纹饰盔甲进行外观更改。",
    "howtoplay.smithing_table.text.3":"为了升级装备，你需要一个锻造模板。你可以在世界各地找到各种各样的模板，用于各种升级。",
    "howtoplay.smithing_table.text.4":"将模板放入锻造台最左侧的槽中，看看升级需要哪些物品。",
    "howtoplay.smithing_table.text.5":"例如，要将钻石装备升级到下界合金，你需要一个下界合金升级锻造模板，你可以在堡垒遗迹中找到锻造模板。然后，将钻石装备放入装备槽中，将下界合金锭放入配料槽，大功告成！",
    "howtoplay.smithing_table.text.6":"附魔物品和纹饰盔甲等物品属性将被保留，但锻造模板将在你升级装备时被消耗。别担心，你可以用你的工作台制作模板副本。",
    "howtoplay.smithing_table.text.7":"发挥创意，使用纹饰盔甲来定制盔甲的外观。你需要一个盔甲装饰锻造模板才能开始，这种模板可以在世界各地找到。",
    "howtoplay.smithing_table.text.8":"将模板放入锻造台最左侧的槽中，看看升级需要哪些物品。然后在装备槽中放入一件盔甲，在配料槽中放入一块水晶或锭。完成了！",
    "howtoplay.smithing_table.text.9":"只有特定的水晶和金属锭可用于纹饰盔甲。请尝试用不同种类的铁、金或青金石来创造独特的设计！",
    "howtoplay.smithing_table.title":"锻造台",
    "howtoplay.smithing_table":"锻造台",

}