store: dict = {
    "store.sign_in_warning.no_xbl_and_local_content":"您之前在市场中下载过内容或使用过仅在此设备上可用的 Minecoins。",
    "store.sign_in_warning.no_xbl_and_no_local_content.line1":"立即登录以保存并跨平台共享您的购买。保存购买，以免在系统出现问题或《我的世界》被卸载时导致丢失。从任意平台访问您在市场中购买的内容，并跨平台使用您的自定义角色。",
    "store.sign_in_warning.no_xbl_and_no_local_content.line2":"没有 Microsoft 帐户？立即免费创建一个",
    "store.title":"市场",
    "store.allStores":"全部商店",
    "store.menu.home":"首页",
    "store.itemDetail.back":"详情",
    "store.coin.bonus":"奖励！",
    "store.coin.title":"购买 Minecoin",
    "store.disabledOnBeta":"此功能当前在测试版中已禁用。",
    "store.disabled.nopermission":"您目前没有使用商店的权限。",
    "store.disabled.generic":"商店目前不可用。",
    "store.disabled.preview":"在预览版中无法访问市场。",
    "store.loading.error.unavailable":"市场不可用。",
    "store.loading.error.trying":"我们仍在尝试连接。请稍候。",
    "store.loading.error.failure":"我们遇到了错误。请重启游戏并重试。",
    "store.loading.error.connecting":"我们遇到了连接问题。请返回并重试。",
    "store.loading.error.issues":"嗯，市场出现了一些问题。请稍后尝试连接。",
    "store.loading.error.internetDown":"我们无法检测到互联网连接。",
    "store.loading.error.account":"您的帐户出现了问题。请稍后重试，如果此问题仍然存在，请联系支持人员。",
    "store.giftPromo.day":"第 %s 天			 %s being day number such as 'Day 1', 'Day 2', etc. Please use short translations. 3 letters if possible",
    "store.equipped":"已领取",
    "store.promo.title":"夏日庆典",
    "store.promo.incompatible":"这个世界与此设备不兼容。请在支持的设备上领取。",
    "store.promo.details":"查看详细信息",
    "store.promo.view":"在角色创建器中查看",
    "store.promo.claimDay":"领取日",
    "store.promo.restrictedPopup.title":"受平台限制",
    "store.promo.restrictedPopup.body":"该物品与此设备不兼容。",
    "store.realmsPreview":"Realms 预览版",
    "store.realmsBeta":"Realms 测试版",
    "store.realmsPlus":"Realms Plus",
    "store.realmsPlus.content":"内容",
    "store.realmsPlus.faq":"常见问题解答",
    "store.realmsPlus.buyNow":"立即订阅 	 Maximum 13 characters",
    "store.realmsPlus.buyNowPerMonth":"立即订阅 %s/月",
    "store.realmsPlus.signInToSubscribe":"登录以订阅 Realms Plus",
    "store.realmsPlus.buyNowTrialPerMonth":"开始试用	 Maximum 25 characters",
    "store.realmsPlus.errorNoOffer":"错误：未发现优惠",
    "store.realmsPlus.manageSubscription":"管理订阅",
    "store.realmsPlus.viewAllPacksTitle":"超值 - 包价值超过 §g$150 美元！§r",
    "store.realmsPlus.nowActive":"该设备上的 Realms Plus 现已激活。现在您无需花费额外的费用，即可访问来自市场的 150 多个内容包。至多 10 名玩家可以同时在您的 Realms 上玩，并且他们可以访问您的 Realm 内的所有订阅内容——免费地！",
    "store.realmsPlus.buyNow.buttonText":"为%s购买",
    "store.realmsPlus.buyNow.viewTerms":"条款和条件",
    "store.realmsPlus.buyNow.viewPrivacyPolicy":"隐私政策",
    "store.realmsPlus.buyNow.title":"开始您的 Realms Plus 订阅",
    "store.realmsPlus.startTrial.description":"您的 Realm 和 150 多个市场包将立即可用。至多 10 名玩家可以同时玩，并且他们可以免费访问您的 Realm 内的世界！首月是免费的，之后您将被收取 %s/月的费用，并且您可以随时取消。",
        "store.realmsPlus.noTrial.description.iap":"您的 Realm 和 150 多个市场包将立即可用。至多 10 名用户可以同时探索，并且他们可以免费访问您的 Realm 内的世界！您将被收取 %s/月的费用，并且您可以在订阅设置中取消订阅，避免未来出现收费的情况。",
    "store.realmsPlus.realmName.placeholder":"%s的 Realm		The string passed in here is the gamertag of the player to indicate the name of the player's world.",
    "store.realmsPlus.recurring.offerTrial":"Realms Plus 是一项持续订阅，每月自动收取续订费，直到订阅取消为止。%s 您的 Realm 和 150 多个市场包将立即可用。至多 10 名用户可以同时探索，并且他们可以免费访问您的 Realm 内的世界！前 30 天是免费的，之后将按 %s/月的价格收费。您可以在订阅设置中取消订阅，避免未来出现收费的情况。",
    "store.realmsPlus.recurring.withoutTrial":"Realms Plus 是一项持续订阅，每月自动收取续订费，直到订阅取消为止。%s 您的 Realm 和 150 多个市场包将立即可用。至多 10 名用户可以同时探索，并且他们可以免费访问您的 Realm 内的世界！按 %s/月的价格收费。您可以在订阅设置中取消订阅，避免未来出现收费的情况。",
    "store.realmsPlus.consumable.offerTrial":"您的 Realm 和 150 多个市场包将立即可用。至多 10 名玩家可以同时玩，并且他们可以免费访问您的 Realm 内的世界！前 30 天是免费的，之后您可以按 %s 的价格续费 30 天。",
    "store.realmsPlus.consumable.withoutTrial":"您的 Realm 和 150 多个市场包将立即可用。至多 10 名玩家可以同时玩，并且他们可以免费访问您的 Realm 内的世界！您的定期服务期为 30 天，价格为 %s。",
    "store.realmsPlus.landing.header":"订阅包含：",
    "store.realmsPlus.landing.headerTrial":"免费试用 30 天，之后按 %s/月价格收费",
    "store.realmsPlus.landing.info1.line1":"您专属的私人 Realm 服务器：一个永远为您和好友准备的在线世界！",
    "store.realmsPlus.landing.info1.line2":"好友可以在您的 Realm 中免费游玩",
    "store.realmsPlus.landing.info1.line3":"无论是主机、手机还是电脑，任何设备都可访问《我的世界》市场",
    "store.realmsPlus.landing.info2.line1":"免费访问包含 150+ 市场包的目录",
    "store.realmsPlus.landing.info2.line2":"您 Realm 上的世界享有安全备份",
    "store.realmsPlus.landing.info2.line3":"前 30 天免费",
    "store.realmsPlus.landing.info2.line4":"立即以 %s/月的价格订阅",
    "store.realmsPlus.landing.info2.catalog":"免费访问包含 150+ 市场包的目录",
    "store.realmsPlus.landing.info2.backups":"您 Realm 上的世界享有安全备份",
    "store.realmsPlus.landing.info2.trial":"前 30 天免费",
    "store.realmsPlus.landing.info2.subscribe":"立即以 %s/月的价格订阅",
    "store.realmsPlus.landing.info2.persona":"免费角色创建器物品 - 每月兑换一套新的！",
    "store.realmsPlus.landing.beta":"Beta 版",
    "store.realmsPlus.landing.preview":"预览版",
    "store.realmsPlus.landing.info3.para1":"Realms 在《我的世界》%s 中免费提供给所有 Realms 订阅者！这是一个新的 Realm，让您有机会在新功能发布之前进行试用。",
    "store.realmsPlus.landing.info3.para2":"通过 Realm 订阅，您可以使用主菜单中的“新建”按钮创建新的 %s Realm。如果您还没有 Realm 订阅，请转到完整版的《我的世界》进行注册。",
    "store.realmsPlus.landing.info3.para3":"所有 Realm 屏幕和功能都可以在 %s 中使用，除了购买新的订阅或管理现有 Realm 的订阅。",
    "store.realmsPlus.landing.info3.para4":"只要您拥有 %s Realm 所链接到的付费 Realm 订阅，您的 %s Realm 就会保持活跃状态。",
    "store.realmsPlus.faq.header":"常见问题",
    "store.realmsPlus.faq.question1":"什么是 Realms Plus？",
    "store.realmsPlus.faq.answer1":"Realms Plus 是一项私人服务器的订阅服务，支持多达 10 名玩家同时游玩，每月只需支付一点费用，即可无限访问 150 多个超棒的《我的世界》世界、材质包、皮肤包和混搭包。",
    "store.realmsPlus.faq.question2":"什么是私人服务器？",
    "store.realmsPlus.faq.answer2":"私人服务器允许您创建一个共享的世界，这个世界将永远保持在线，可从包含《我的世界》市场的任何设备进行访问。您邀请至您的 Realm 的玩家可以随时在这个世界中游玩。",
    "store.realmsPlus.faq.question3":"我的好友是不是需要购买 Realms Plus 才能在我的 Realm 上玩？",
    "store.realmsPlus.faq.answer3":"您的好友无需购买 Realms Plus 订阅即可使用您的 Realm。您可以邀请任何好友（在对方已允许多人使用的情况下）免费加入您的 Realm。",
    "store.realmsPlus.faq.question4":"那些设备支持《我的世界》Realms Plus？",
    "store.realmsPlus.faq.answer4":"Realms Plus 目前适用于任何可安装《我的世界》基岩版的平台。如果您已登录 Microsoft 帐户，则可以在任何这些设备上玩 Realms 并使用 Realms Plus 中的任何内容。	disable_3rd_party_console_resource_pack_check",
    "store.realmsPlus.faq.question5":"Realms Plus 订阅的费用是多少？",
    "store.realmsPlus.faq.answer5":"一个可容纳 10 名玩家的服务器，且可获取 150+ 市场包，仅需 %s 每月。",
    "store.realmsPlus.faq.question6":"Realms Plus 多久添加一次新的包？",
    "store.realmsPlus.faq.answer6":"每月都会有新的包添加到 Realms Plus。",
    "store.realmsPlus.faq.question7":"我可以访问 Realms Plus 中的包的时间是多长？",
    "store.realmsPlus.faq.answer7":"Realms Plus 成员可以无限制访问 150 多个超棒的《我的世界》的世界、材质包、皮肤包和混搭包，直到订阅过期，或者包不再在目录中。",
    "store.realmsPlus.faq.question8":"我在哪里可以使用我的 Realms Plus 包？",
    "store.realmsPlus.faq.answer8":"您可以在线、在您的私人 Realm 中或在您的本地设备上使用订阅中包含的世界和包。您只需要每 30 天上线一次，验证您的订阅是否处于活跃状态即可。",
    "store.realmsPlus.faq.question9":"当我的订阅到期时，我的 Realms 和世界会发生什么？",
    "store.realmsPlus.faq.answer9":"如果您的订阅结束，您和您的好友将不再能够在 Realm 上一起在线使用，并且您将不再能够访问 Realms Plus 包。您将能够下载已保存到您的 Realm 中的任何世界（仅限于订阅结束后的 18 个月内）。如果您此前使用的是 Realms Plus 世界、材质包或混搭包，您需要在商店中购买这些包，或者如果这些包仍在 Realms Plus 中的话，您需要重新订阅，才能使用这些世界模板。",
    "store.realmsPlus.content.skinDescription":"用皮肤改变您的外观！",
    "store.realmsPlus.content.skinDescriptionPersona":"用皮肤进行装扮！",
    "store.realmsPlus.content.worldDescription":"探索热门内容包！",
    "store.realmsPlus.content.textureDescription":"让您的世界焕然一新！",
    "store.realmsPlus.content.mashupDescription":"每种都尝试一点——尽在混搭包！",
    "store.realmsPlus.content.personaDescription":"用角色创建器物品自定义你的外观！",
    "store.realmsPlus.content.friendsGetAccess":"您的好友可免费享受您 Realm 中使用的内容",
        "store.realmsPlus.content.viewAllPacks":"查看所有的包",
    "store.realmsPlus.content.contentDescription":"畅享精彩的《我的世界》内容！有了 Realms Plus，您可以立即访问 150 多个市场物品，例如混搭包、世界、皮肤包和史诗级冒险——而且每个月都会添加新的内容。您的内容将存储在您专属的个人服务器上，并且可以在任何您享有 Realms 和《我的世界》市场的平台上进行使用。至多 10 名玩家可以同时玩，并且他们可以免费访问您的 Realm 内的世界！",
    "store.realmsPlus.freeTrial":"开始免费试用",
    "store.realmsPlus.purchase.warningDialog.title":"注意",
    "store.realmsPlus.purchase.warningDialog.body":"Realms Plus 包含市场通行证内容。我们建议您在注册后取消订阅市场通行证。",
    "store.realmsPlus.purchase.warningDialog.checkbox":"我理解",
    "store.realmsPlus.purchase.warningDialog.button.back":"返回",
    "store.realmsPlus.purchase.warningDialog.button.continue":"继续",
    "store.csb.brand.1":"卖场",
    "store.csb.brand.2":"超车",
    "store.csb":"市场通行证",
    "store.csb.pass":"超车",
    "store.csb.content":"内容",
    "store.csb.faq":"常见问题解答",
    "store.csb.buyNow":"立即订阅 	 Maximum 13 characters",
    "store.csb.buyNowPerMonth":"购买价格为 %s /月",
    "store.csb.signInToSubscribe":"登录以订阅市场通行证",
    "store.csb.buyNowTrialPerMonth":"开始试用	 Maximum 25 characters",
    "store.csb.errorNoOffer":"错误：未发现优惠",
    "store.csb.manageSubscription":"管理订阅",
    "store.csb.viewAllPacksTitle":"超值 - 包价值超过 §g$150 美元！§r",
    "store.csb.buyNow.buttonText":"为%s购买",
    "store.csb.buyNow.viewTerms":"条款和条件",
    "store.csb.buyNow.viewPrivacyPolicy":"隐私政策",
    "store.csb.buyNow.title":"开始订阅市场通行证",
    "store.csb.subscription":"注册后，你将获得 150+ 项令人兴奋的 Minecraft 市场内容。你可以下载并畅玩冒险地图、穿戴皮肤、玩转材质包，每月还可以领取一套角色创建器物品。目录会定期更新，订阅市场通行证后，总有新内容等你去发现。订阅费每月 %s，可随时取消以避免后续扣费。",
    "store.csb.recurring.offerTrial":"市场通行证是一项持续订阅，每月自动收取续订费，直到订阅取消为止。%s订阅后，150 多个市场包将立即可用。你可以在订阅设置中取消订阅，避免未来出现收费的情况。",
    "store.csb.recurring.withoutTrial":"市场通行证是一项持续订阅，每月自动收取续订费，直到订阅取消为止。%s订阅后，150 多个市场包将立即可用。您将被收取 %s/月的费用，并且您可以在订阅设置中取消订阅，避免未来出现收费的情况。",
    "store.csb.consumable.offerTrial":"订阅后，150 多个市场包将立即可用。前 30 天免费，之后您可以按 %s 的价格续订 30 天。",
    "store.csb.consumable.withoutTrial":"150 多个市场包将立即可用。您的定期服务期为 30 天，价格为 %s。",
    "store.csb.landing.header":"开始订阅市场通行证",
    "store.csb.landing.headerTrial":"免费试用 30 天，之后按 %s/月价格收费",
    "store.csb.landing.info":"市场通行证是一项包月服务，每月收费 %s。订阅后，除了获得 Minecraft 市场的 150+ 项内容外，你还将能够：",
    "store.csb.landing.info.line1":"下载并玩转众多主题世界和迷你游戏，踏上充满冒险的故事之旅",
    "store.csb.landing.info.line2":"更改方块、生物群系或是你最爱的 Minecraft 生物的外观",
    "store.csb.landing.info.line3":"丰富游戏中的衣柜",
    "store.csb.landing.info.line4":"每月永久获得一套全新限时角色创造器物品",
    "store.csb.landing.beta":"Beta 版",
    "store.csb.landing.preview":"预览版",
    "store.csb.faq.header":"常见问题",
    "store.csb.faq.question1":"什么是市场通行证？",
    "store.csb.faq.answer1":"市场通行证是一项订阅服务，购买后可访问 Minecraft 市场中的 150 多项内容，订阅价格为 %s/月。",
    "store.csb.faq.question2":"市场通行证中的内容多久更新一次？",
    "store.csb.faq.answer2":"精选内容每月更新，不断提供新鲜内容供你探索。",
    "store.csb.faq.question3":"我需要什么才能享有市场通行证呢？",
    "store.csb.faq.answer3":"访问市场通行证需要有活跃的订阅，以及带有 Minecraft 市场的《Minecraft：基岩版》兼容版本。需要登录 Microsoft 账号。",
    "store.csb.faq.question4":"取消市场通行证后，我的内容会发生什么？",
    "store.csb.faq.answer4":"一旦世界、材质包、皮肤包或混搭包移出目录，您将需要从市场中购买物品来继续游玩。除非您手动删除包，否则包不会从您的本地存储中删除。所兑换的每月角色创建器物品均可保留。",
    "store.csb.faq.question5":"订阅结束后会发生什么？",
    "store.csb.faq.answer5":"在订阅结束后的 18 个月内，您将能够购买和下载任何保存到您的云存储中的世界模板，Minecraft 不再提供这些世界模板的情况除外。所兑换的每月角色创建器物品均可保留。",
    "store.csb.faq.question6":"这和 Realms Plus 有什么不同？",
    "store.csb.faq.answer6":"两项订阅内容的区别在于，Realms Plus 的订阅内容包括个人服务器，其中可支持同时与最多十位好友一起玩。订阅市场通行证后可访问的内容目录与 Realms Plus 订阅的内容目录相同。",
    "store.csb.faq.question7":"我可以同时订阅市场通行证与 Realms Plus 吗？",
    "store.csb.faq.answer7":"Realms Plus 的订阅内容已包含市场通行证。如果在已订阅市场通行证的情况下希望探索 Realms Plus，我们建议先取消订阅市场通行证。在已订阅 Realms Plus 的情况下，无法再订阅市场通行证。",
    "store.csb.faq.question8":"我可以在任何设备上使用市场通行证内容吗？",
    "store.csb.faq.answer8":"如果您购买了市场通行证，那么只要您使用的是带有 Minecraft 市场（单独出售）的《Minecraft：基岩版》兼容版本，且登录了您的 Minecraft 账号，就可以在任何设备上访问所有包。在 Amazon Kindle Fire 和 Minecraft Java 版上不受支持。",
    "store.csb.faq.question9":"如果我在 Windows 或 XBOX 平台上参与了 Minecraft 版本测试，那我能不能玩市场通行证内容？",
    "store.csb.faq.answer9":"如果您已经订阅了市场通行证，就能在该版本游戏中看到订阅内容。但是您无法在预览版/测试版游戏中订阅市场通行证。",
    "store.csb.faq.bottom1":"找不到所需内容？",
    "store.csb.faq.bottom2":"请访问我们的帮助页面",
    "store.csb.contentPacks.worldDescription":"畅玩小游戏、探索主题世界，还有更多内容等你发掘！",
    "store.csb.contentPacks.textureDescription":"让你的世界焕然一新！",
    "store.csb.contentPacks.personaDescription":"每月都能获取更衣室中的物品！",
    "store.csb.contentPacks.skinDescription":"领取皮肤，丰富你的衣柜！",
    "store.csb.contentPacks.mashupDescription":"每种都尝试一点——尽在混搭包！",
    "store.csb.content.popularPacks":"了解市场通行证",
    "store.csb.content.viewAllPacks":"查看所有的包",
    "store.csb.content.viewCharacterCreatorItems":"查看角色创建器物品",
    "store.csb.content.contentDescription":"畅享精彩的 Minecraft 内容！有了市场通行证，您可以立即获取 150 多个市场物品，例如混搭包、世界、皮肤包和史诗级冒险，而且每个月都会添加新的内容。",
    "store.csb.freeTrial":"开始免费试用",
    "store.csb.welcomeDialog.title":"欢迎订阅市场通行证！",
    "store.csb.welcomeDialog.body":"立即开始使用 150 多种冒险游戏、迷你小游戏、皮肤包、材质等！",
    "store.csb.welcomeDialog.continue":"开始浏览",
    "store.csb.purchase.warningDialog.title":"注意",
    "store.csb.purchase.warningDialog.body.line1":"市场通行证包含在您的 Realms Plus 订阅中。",
    "store.csb.purchase.warningDialog.body.line2":"请先取消活跃的 Realms Plus 订阅，等待计费周期结束，然后再尝试购买。",
    "store.csb.purchase.warningDialog.button.back":"返回",
    "store.csb.upsell.bestValue":"最佳价值",
    "store.csb.upsell.leftBullet.1":"150 多个市场包目录",
    "store.csb.upsell.leftBullet.2":"内容每月更新",
    "store.csb.upsell.leftBullet.3":"每月限时推出角色创建器物品",
    "store.csb.upsell.rightBullet.1":"可容纳 10 个好友的个人服务器",
    "store.csb.upsell.rightBullet.2":"好友免费玩",
    "store.csb.upsell.rightBullet.3":"包含			 Precedes the term Marketplace Pass in a different font",
    "store.csb.upsell.learnMore":"了解更多",
    "store.csb.upsell.price":"%s/月",
    "store.csb.upsell.firstPeriodFree":"30 天免费试用！*",
    "store.csb.upsell.realmsPlus":"§dREALMS PLUS",
    "store.csb.purchaseErrorDialog.title":"购买错误",
    "store.csb.purchaseErrorDialog.body":"目前处理您的订阅时遇到问题。请稍后重试。谢谢！",
    "store.csb.purchaseErrorDialog.back":"返回",
    "store.csb.purchaseErrorDialog.errorCode":"错误代码：%s",
    "store.csb.purchaseErrorDialog.correlationId":"关联 ID：%s",
    "store.csb.purchase.amazonDeviceWarning.title":"注意",
    "store.csb.purchase.amazonDeviceWarning.body.line1":"抱歉！当前无法在 Amazon 设备上购买市场通行证。",
    "store.csb.purchase.amazonDeviceWarning.body.line2":"如有任何疑问，请访问 support.minecraft.net。",
    "store.csb.purchase.amazonDeviceWarning.button.back":"返回",
    "store.csb.alreadySubscribed.toolTip":"您已经订阅了市场通行证。",
    "store.inventory.button":"我的内容",
    "store.inventory.title":"我的内容",
    "store.inventory.dropdown.owned":"已拥有",
    "store.inventory.dropdown.current":"当前",
    "store.inventory.dropdown.removed":"已移除",
    "store.inventory.button.subscriptions":"定期服务",
    "store.free":"免费",
    "store.redeem":"获得",
    "store.view_achievement":"查看成就",
    "store.incompatible":"不兼容",
    "store.incompatibleOnDevice":"在设备上不兼容",
    "store.itemIsIncompatible":"该物品与您的设备不兼容。",
    "store.itemMayNotBeCompatible":"该物品与您的设备不兼容。",
    "store.owned":"已拥有",
    "store.owned.legacy":"已拥有(P)",
    "store.unlocked":"已解锁",
    "store.mypacks":"我的内容",
    "store.error":"市场错误",
                        "store.toast.autofulfillment.title":"完成！",
    "store.toast.autofulfillment.message":"您的购买已完成",
    "store.popup.goBack":"返回",
    "store.popup.xblRequired.title":"免费注册",
    "store.popup.xblRequired.button1":"登录",
    "store.popup.xblRequired.button2":"取消",
    "store.popup.xblRequired.message":"您需要登录之后才能解锁商店中的项目，以便我们记住您已解锁的项目。",
    "store.popup.download.title.KB":"下载内容？ - %s KB",
    "store.popup.download.title.MB":"下载内容？- %s MB",
    "store.popup.download.msg":"这将会将 %s 下载到您的设备上。",
    "store.popup.downloadCell.title.KB":"通过流量下载？ - %s KB",
    "store.popup.downloadCell.title.MB":"通过流量下载？ - %s MB",
    "store.popup.downloadCell.msg":"您未连接到 Wi-Fi。要使用流量网络将 %s 下载至您的设备吗？",
    "store.popup.download.button1":"下载",
    "store.popup.download.button2":"跳过",
    "store.popup.download.back":"返回",
    "store.popup.wifiWarn.title":"警告",
    "store.popup.wifiWarn.msg":"你没有连接到 WiFi，仍然下载吗？",
    "store.popup.download.failed.title":"出错了",
    "store.popup.download.failed.msg":"抱歉，此内容无法下载",
    "store.popup.download.noInternet.title":"出错了",
    "store.popup.download.noInternet.msg":"抱歉，无法开始下载 %s。请检查您的网络连接？",
    "store.popup.download.noSpace.title.KB":"空间不足 - %s MB",
    "store.popup.download.noSpace.title.MB":"空间不足 - %s MB",
    "store.popup.download.noSpace.msg":"您的设备上没有足够的空间，无法下载 %s 。",
    "store.popup.download.unOwned.title":"是否购买包？",
    "store.popup.download.unOwned.msg":"是否要购买这个世界所用的包？",
    "store.popup.download.unOwnedTemplate.title":"是否购买世界模板？",
    "store.popup.download.unOwnedTemplate.msg":"这个世界是使用您未解锁的模板所创建。您必须购买模板才能解锁该世界。是否要购买这个世界所用的模板？",
    "store.popup.downloadWorldTemplate.noInternet.title":"需要互联网才能获得模板",
    "store.popup.downloadWorldTemplate.noInternet.msg":"我们无法连接市场以下载用于创建这个世界的模板。该模板包含您用来继续玩此世界所必须的加载项。重新联网并下载此模板以继续。",
    "store.popup.downloadWorldTemplate.noSpace.msg":"我们没有足够的空间来下载用于创建这个世界的模板。该模板包含您用来继续探索此世界所必须的加载项。请清理设备空间，然后继续。",
    "store.popup.downloadWorldTemplate.title.KB":"下载缺失的模板？- %s KB",
    "store.popup.downloadWorldTemplate.title.MB":"下载缺失的模板？- %s MB",
    "store.popup.downloadWorldTemplate.msg":"用于创建这个世界的模板缺失。该模板包含您用来继续探索此世界所必须的加载项。",
    "store.popup.downloadWorldTemplate.msg.removePacks":"您可以前往这个世界的资源与行为包设置，移除这些包，然后继续，但是这样的话这个世界可能就无法再游玩了。",
    "store.popup.downloadWorldTemplate.download":"下载模板",
    "store.popup.downloadWorldTemplateCell.download":"使用移动网络下载模板",
    "store.popup.update.title.KB":"更新内容？ - %s KB",
    "store.popup.update.title.MB":"更新内容？- %s MB",
    "store.popup.update.msg":"这将会更新设备上的 %s 。",
    "store.popup.updateCell.title.KB":"通过手机网络更新？ - %s KB",
    "store.popup.updateCell.title.MB":"通过手机网络更新？ - %s MB",
    "store.popup.updateCell.msg":"您未连接到 Wi-Fi。是否要通过手机网络更新您设备上的 %s？",
    "store.popup.update.button1":"更新",
    "store.popup.update.button2":"跳过",
    "store.popup.update.back":"返回",
    "store.popup.purchaseInProgress.title":"正在购买",
    "store.popup.purchaseInProgress.msg":"稍后即可完成。",
    "store.popup.purchaseFailed.title":"出错了",
    "store.popup.purchaseFailed.msg":"抱歉，无法完成购买。请检查网络连接？",
    "store.popup.purchasePending.title":"仍在尝试",
    "store.popup.purchasePending.msg":"很抱歉，我们仍在验证您是否购买成功。成功后我们会通知您！",
    "store.popup.purchaseFailedInsufficientFunds.title":"您需要更多硬币",
    "store.popup.purchaseFailedInsufficientFunds.msg":"您没有足够的硬币来解除锁定此物品。您可以从应用程序商店购买硬币。",
    "store.popup.purchaseFailedInsufficientFunds.buyButton":"获取硬币",
    "store.popup.purchasePriceMismatch.msg":"对不起，我们无法完成您的购买。请稍后在试。",
    "store.popup.trialUpgradeFail.title":"游戏解锁错误",
    "store.popup.trialUpgradeFail.msg":"您似乎登录了一个与您最初下载《我的世界》试用版的账户不同的 Microsoft 账户。在登录那个账户后再试一次。",
    "store.popup.downloaded.unOwnedTemplate.title":"是否购买世界模板？",
    "store.popup.downloaded.unOwnedTemplate.msg":"您未拥有该模板，必须先购买它才能解锁。您想购买该模板吗？",
    "store.popup.rtx.title":"下载光线追踪包？",
    "store.popup.rtx.msg":"此世界应用了启用光线追踪的资源包，您必须下载这些资源包才能进行游戏。您的设备不兼容光线追踪，因此您在下载后只能看到基本材质。要下载此包吗？",
    "store.popup.skinEquipWarn.title":"外观警告",
    "store.popup.skinEquipWarn.msg":"如果您的世界有角色创建器，此外观将切换为经典外观。您依然可以在更衣室中切换回角色创建器。是否装配？",
    "store.claim.success":"您刚刚领取了 %s",
    "store.claimAll.success":"您刚刚领取了今天的物品",
    "store.purchase.success":"你刚刚购买了：%s",
    "store.purchase.bundle":"解锁 %d 个包（共 %d 个）？",
    "store.purchase.bundle.confirm":"立即解锁！",
    "store.purchase.bundle.partiallyOwnedWarning":"正如您所知，您已经拥有以下包：%s。您要解锁这个同捆包中的其他包吗？",
    "store.purchase.bundle.owned":"已拥有",
    "store.purchase.bundle.unowned":"您将获得",
    "store.createdBy":"作者：%s",
    "store.seeMoreBy":"查看由 %s 提供的更多内容",
    "store.seeMoreBy.multiCreatorBundle":"按同捆包创建者查看更多",
    "store.fetchingItem":"正在连接到市场…",
    "store.timer.daysAbbreviated":"%s天		 This is to let player know how many days are left in a sale. It needs to be abbreviated with no more than 3 characters",
    "store.timer.hoursAbbreviated":"%s时		 This is to let player know how many days are left in a sale. It needs to be abbreviated with no more than 3 characters",
    "store.timer.minutesAbbreviated":"%s分		 This is to let player know how many days are left in a sale. It needs to be abbreviated with no more than 3 characters",
    "store.timer.secondsAbbreviated":"%s秒		 This is to let player know how many days are left in a sale. It needs to be abbreviated with no more than 3 characters",
    "store.timer.left":"剩余 %s",
    "store.startMenu.sale":"特惠！",
    "store.progress.fetchingProducts":"正在获取产品",
    "store.progress.checkingDownload":"正在检查下载",
    "store.content.download":"下载",
    "store.content.update":"更新",
    "store.content.updating":"正在更新...",
    "store.content.requireXbl.signedIn":"用 Microsoft 账户可免费下载。",
    "store.content.requireXbl.notSignedIn":"登录至 Microsoft 账户以解锁。",
    "store.mashup.count.personaPiece":"1 件角色物品",
    "store.mashup.count.personaPieces":"%s 件角色物品",
    "store.mashup.count.skin":"1 个皮肤",
    "store.mashup.count.skins":"%s 款皮肤",
    "store.mashup.count.texturePack":"1 个材质包",
    "store.mashup.count.texturePacks":"%s 个材质包	number of texture packs",
    "store.mashup.count.world":"1 个世界",
    "store.mashup.count.worlds":"%s 个世界	number of worlds",
    "store.mashup.bundle":"同捆包",
    "store.mashup.bundle.multipleCreators":"多个创建者",
    "store.mashup.continue":"继续",
    "store.mashup.createWorld":"创建此世界！",
    "store.mashup.leaveWorldToCreate":"必须在创建之前先退出世界",
    "store.mashup.equipSkin":"装备",
    "store.mashup.equipThisSkin":"装备 %s 皮肤！",
    "store.mashup.readMore":"阅读更多",
    "store.mashup.readLess":"阅读较少",
    "store.mashup.mashupPack":"混搭包",
    "store.mashup.skinPack":"皮肤包",
    "store.mashup.texturePack":"材质包",
    "store.mashup.ratings":"评级",
    "store.mashup.world":"世界",
    "store.mashup.missingContent":"无法完成操作。本地缺少内容。",
    "store.mashup.title.bundles":"同捆包中包含 %s 个包！",
    "store.mashup.title.bundleUpsell":"在捆绑包中获得此物品及更多内容！",
    "store.mashup.title.resourcePack":"游览！",
    "store.mashup.title.skinPack":"%s：%s",
    "store.mashup.title.worldView":"新世界之旅！",
    "store.mashup.title.ratings":"社区评级",
    "store.mashup.title.recentlyViewed":"最近查看",
    "store.mashup.title.relatedItems":"相关物品",
    "store.mashup.mashupContentsFull":"%s 款皮肤、材质包和世界",
    "store.mashup.mashupContentsSkinAndTexturePack":"%s 款皮肤和材质包",
    "store.mashup.mashupContentsSkinAndWorld":"%s 款皮肤和世界",
    "store.mashup.mashupContentsTexturePackAndWorld":"材质包和世界",
    "store.mashup.mashupContentsSkinPack":"%s 款皮肤",
    "store.mashup.last_updated":"上次更新：%s",
    "store.mashup.up_to_date":"包是最新的",
    "store.mashup.out_of_date_tooltip":"这个包可能没有在其最新更新之后所发布的物品/方块的皮肤",
    "store.mashup.description":"说明",
    "store.new.icon":"新",
    "store.offerDescription.title":"包说明",
    "store.offerDescription.tags":"标签：",
    "store.offerDescription.genre":"流派：",
    "store.offerDescription.players":"用户：",
    "store.offerDescription.playerCountNote":"注意：用户指的是创建者希望获得最佳体验的用户数量。",
    "store.offerDescription.languages":"语言：",
    "store.offerDescription.showMore":"展开",
    "store.offerDescription.showLess":"收起",
    "store.ratings.ratingsCount":"%s 评级",
    "store.ratings.ratingOutOfFive":"%s（共 5 星）",
    "store.ratings.rateContent":"为此包评级",
    "store.ratings.rateContentGeneral":"为此内容评级",
    "store.ratings.yourRating":"您的评分",
    "store.ratings.stars":" %s 星",
    "store.ratings.rate":"为此包评分！",
    "store.ratings.signIn.title":"为市场中的物品评级",
    "store.ratings.signIn.description1":"告诉创作者和社区您关于此物品的体验！",
    "store.ratings.signIn.description2":"您需要先使用 Microsoft 账户登录，然后才能为某个物品评级。",
            "store.purchase.signIn":"用大量精彩内容扩充你的游戏。",
    "store.purchase.signInPart2":"用 Microsoft 账户登录，开始使用市场！",
    "store.purchase.realmoney.disclaimer":"*购买 %s 硬币(需要 %s)并兑换此 %s 硬币包，还剩下 %s。",
    "store.purchase.notAvailable":"当前不可用",
    "store.wishlist.toast.added":"%s 已添加到您的愿望清单",
    "store.wishlist.toast.removed":"%s 已从您的愿望清单中移除",
    "store.wishlist.toast.failed":"%s 这一次无法添加/移除",
    "store.bundleUpsell.contents.single":"+1 个包",
    "store.bundleUpsell.contents.plural":"+%s 个包",
    "store.coins.currentCoins":"您拥有 %s 个硬币",
    "store.coins.purchase.confirmation":"获得更多硬币来解锁这个包？",
    "store.coins.purchase.coinsLeftToBuy":"你还需要 %s 个硬币才能解锁这个包。",
    "store.coins.purchase":"购买硬币",
    "store.coins.offer0":"硬币堆！",
    "store.coins.offer1":"硬币叠！",
    "store.coins.offer2":"硬币山！",
    "store.coins.header":"使用硬币解除锁定各类炫酷物品！",
    "store.coins.value":"最佳值！",
    "store.coins.purchase.toast.withCoinCount":"您刚刚购买了 %s 个硬币！",
    "store.coins.purchase.toast.unknownCoinCount":"您刚刚购买了硬币！",
    "store.coins.purchased.failed.title":"出错了",
    "store.coins.purchased.failed.body":"无法连接至应用商店。请登录至应用商店或者检查您的网络连接。",
    "store.coins.tooManyCoins":"使用一些硬币后可以购买更多。",
    "store.coins.incomplete.title":"硬币购买未完成",
    "store.coins.incomplete.fulfill.a":"看来我们上次并没有完成。现在我们来完成你的购买吧。",
    "store.coins.incomplete.fulfill.b":"看来您用了其他 Microsoft 账户开始购买。是否要用这个账户完成购买？",
    "store.coins.incomplete.fulfill.c":"有人已使用此设备上的计费帐户进行购买。您是否要使用此帐户完成购买？",
    "store.coins.fixAppReceipt.title":"出错了",
    "store.coins.fixAppReceipt.body":"似乎应用收据出现问题，请登录以继续。",
    "store.coins.fixAppReceipt.button":"登录到商店",
    "store.purchase.toast.generic":"您刚购买 %s！",
    "store.featured.realms.title":"免费试玩 Realms",
    "store.featured.realms.desc":"和您的好友一起体验游玩儿《我的世界》的最佳方式。",
    "store.hyperlink.creator.notFound":"抱歉，未找到超链接中指定的创建者。",
    "store.hyperlink.ingame":"抱歉，当您处于世界中时，不允许使用超链接。请退出世界并重试。",
    "store.resource.try":"来试试吧！",
    "store.resource.create":"管理资源包",
    "store.resource.screenshots":"截图",
    "store.resourcePack.activateTexturePack":"激活材质包！",
    "store.resourcePack.leaveWorldToActivate":"退出世界以申请",
    "store.3pserverItem.fetchingCancel":"取消",
    "store.3pserverItem.fetchingItem":"%s 有一些有趣的内容要与您共享。",
    "store.3pserverItem.fetchingItemTitle":"稍等片刻",
    "store.3pserverItem.unlock":"解除 %s 的锁定",
    "store.3pserverItem.alreadyPurchased":"已拥有",
    "store.restore.description":"正在恢复您的购买！",
    "store.restore.failed":"抱歉，无法恢复您的购买。请检查您的网络连接？",
    "store.connection.failed.title":"出错了",
    "store.connection.failed.body":"现在我们无法连接到市场。请稍后再试！",
    "store.connection.failed.code":"错误代码：%s",
    "store.connection.failed.request":"现在我们无法访问这个页面。请尝试访问其他页面！",
    "store.featured.createdBy":"创建者：%s",
    "store.downloading":"正在下载...",
    "store.downloading.title":"正在下载：%s",
    "store.updating":"正在更新...",
    "store.updating.title":"正在更新：%s",
    "store.importing.title":"正在导入：%s",
    "store.importing":"正在导入...",
    "store.showMore":"查看全部",
    "store.inventory.no.xbl":"我的包",
    "store.promo.today":"仅限今天！",
    "store.promo.upsell":"今日提供免费礼物，不要错过！",
    "store.promo.comeBackTomorrow":"回访即享免费的未来之礼！",
    "store.promo.end":"新年快乐！",
    "store.promo.comingSoon":"为期 12 天的《我的世界》将于明天开始！",
    "store.promo.holiday.first":"在《我的世界》的第一天，",
    "store.promo.holiday.second":"在《我的世界》的第二天，",
    "store.promo.holiday.third":"在《我的世界》的第三天，",
    "store.promo.holiday.fourth":"在《我的世界》的第四天，",
    "store.promo.holiday.fifth":"在《我的世界》的第五天，",
    "store.promo.holiday.sixth":"在《我的世界》的第六天，",
    "store.promo.holiday.seventh":"在《我的世界》的第七天，",
    "store.promo.holiday.eighth":"在《我的世界》的第八天，",
    "store.promo.holiday.ninth":"在《我的世界》的第九天，",
    "store.promo.holiday.tenth":"在《我的世界》的第十天，",
    "store.promo.holiday.eleventh":"在《我的世界》的第十一天，",
    "store.promo.holiday.twelfth":"在《我的世界》的第十二天，",
    "store.promo.date.jan":"1 月 %s",
    "store.promo.date.feb":"2 月 %s",
    "store.promo.date.mar":"3 月 %s",
    "store.promo.date.apr":"4 月 %s",
    "store.promo.date.may":"5 月 %s",
    "store.promo.date.jun":"6 月 %s",
    "store.promo.date.july":"7 月 %s",
    "store.promo.date.aug":"8 月 %s",
    "store.promo.date.sep":"9 月 %s",
    "store.promo.date.oct":"10 月 %s",
    "store.promo.date.nov":"11 月 %s",
    "store.promo.date.dec":"12 月 %s",
    "store.myAccount":"我的帐户",
    "store.xbl.signin":"登录",
    "store.xbl.signinOrSignUp":"登录或免费注册",
    "store.xbl.disconnected":"已断开连接",
    "store.xbl.conversionFailedTitle":"出错了",
    "store.xbl.conversionFailedMessage":"请稍后再试。",
    "store.sales.allByCreator":"特惠中！",
    "store.sales.bundlesOnSale":"同捆包特惠中！",
    "store.sales.mashupsOnSale":"混搭包特惠中！",
    "store.sales.skinsOnSale":"皮肤特惠中！",
    "store.sales.texturesOnSale":"材质包特惠中！",
    "store.sales.worldsOnSale":"世界特惠中！",
    "store.showalloffers.list.title":"%s 商店",
    "store.showalloffers.list.back":"返回",
    "store.suggestedOffers.defaultTitle":"有趣的玩法",
    "store.minecoin.notavailable":"此版本的《我的世界》尚未推出硬币购买。",
    "store.search.allResults":"%d项结果",
    "store.search.dynamicPlaceHolderText":"尝试搜索%s！",
    "store.search.error.searchStringAndFilters":"糟糕！未找到符合'%s'及已选择的过滤器的结果。尝试扩大搜索…",
    "store.search.error.searchStringAndNoFilters":"糟糕！未找到与'%s'有关的结果。请尝试另一个短语...",
    "store.search.error.emptySearchStringAndFilters":"糟糕！未找到符合已选择的过滤器的结果。尝试扩大搜索…",
    "store.search.error.emptySearch":"哎呀！搜索内容不能为空。",
    "store.search.greyListedResults":" ——只显示能在该设备上工作的内容。",
    "store.search.noConnectionErrorText":"糟糕！您似乎已经断开了网络连接。请检查您的网络连接并重试。",
    "store.search.placeHolderText":"在这里输入搜索内容",
    "store.search.pluralResults":" 结果",
    "store.search.pluralPossibleResults":" 可能的结果",
    "store.search.singularResult":" 结果",
    "store.search.singularPossibleResult":" 可能的结果",
    "store.search.title":"搜索",
    "store.search.trendingRowTitle":"热门搜索：%s",
    "store.search.button":"搜索",
    "store.search.filters.bundles":"同捆包",
    "store.search.filters.clear":"清空过滤器",
    "store.search.filters.reset":"重置过滤器",
    "store.search.filter.clear.creator":"清空创建者过滤器",
    "store.search.filter.creator":"创建者",
    "store.search.filter.creator.selectedCount":"%d 创建者",
    "store.search.filter.offer_type":"优惠类型",
    "store.search.filter.offer_type.selectedCount":"%d 优惠类型",
    "store.search.filter.offer_type.bundles":"同捆包",
    "store.search.filter.offer_type.realmsplus":"Realms Plus",
    "store.search.filter.offer_type.csb":"市场通行证",
    "store.search.filter.clear.pack_type":"清空包类型过滤器",
    "store.search.filter.mashupPacks":"混搭包",
    "store.search.filter.andSelectedText":"和 %s",
    "store.search.filter.pack_type":"包类型",
    "store.search.filter.pack_type.selectedCount":"%d 包类型",
    "store.search.filter.minecoin":"Minecoins",
    "store.search.filter.minecoin.selectedCount":"%d Minecoin 过滤器",
    "store.search.filter.clear.minecoin":"清空 Minecoin 过滤器",
    "store.search.filter.rating":"评级",
    "store.search.filter.rating.selectedCount":"%d 评级过滤器",
    "store.search.filter.clear.rating":"清空评级过滤器",
    "store.search.filter.skinPacks":"皮肤",
    "store.search.filter.texturePacks":"材质",
    "store.search.filter.title":"过滤器",
    "store.search.filter.worldTemplates":"世界",
    "store.search.filter.installed_state":"已安装状态",
    "store.search.filter.installed":"已安装",
    "store.search.filter.notInstalled":"未安装",
    "store.search.filter.clear.installed":"重置已安装过滤器",
    "store.search.sort_menu.sortConstWord":"排序",
    "store.search.sort_menu.Default":"相关性",
    "store.search.sort_menu.NewestFirst":"时间由近及远",
    "store.search.sort_menu.OldestFirst":"时间由远及近",
    "store.search.sort_menu.A_to_Z":"A 到 Z",
    "store.search.sort_menu.Z_to_A":"Z 到 A",
    "store.search.sort_menu.Installed":"已安装",
    "store.search.sort_menu.notInstalled":"未安装",
    "store.search.sort_menu.HighestPrice":"价格：从高到低",
    "store.search.sort_menu.LowestPrice":"价格：从低到高",
    "store.search.sort_menu.HighestRating":"评级：从高到低",
    "store.search.sort_menu.LowestRating":"评级：从低到高",
    "store.search.sort_menu.resultText":"作者：%s",
    "store.search.sort_menu.A_to_Z.tts.title":"'A' 到 'Z'		 Single quotes (') are there for emphasis on the sound of the letters that will be spoken.",
    "store.search.sort_menu.Z_to_A.tts.title":"'Z' 到 'A'		 Single quotes (') are there for emphasis on the sound of the letters that will be spoken.",
    "store.pagination.next":"下一个 &gt;		 Chevrons (< and >) should not be moved",
    "store.pagination.previous":"&lt; 上一个		 Chevrons (< and >) should not be moved",
    "store.shareDescription":"呜哇！%s做出了这么酷的包。您得来看看。",
    "store.copyToastMessage":"链接已复制到剪贴板！",
    "store.uploadContentToRealmsSuccess":"内容已成功上传至所选的 Realm。",
    "store.uploadContentToRealmsFail.title":"错误",
    "store.uploadContentToRealmsProgressTitle":"正在将内容应用到 Realm",
    "store.uploadContentToRealmsProgressText":"所选的内容已应用到您的 Realm。",
    "store.uploadContentToRealmsFail.message":"未能将内容上传至所选的 Realm！",
    "store.uploadContentToRealmsFail.forbidden.message":"您未拥有一个或多个所应用的内容！",
    "store.applyToRealm":"在 Realm 上创建",
    "store.inRealmsPlus":"在 Realms Plus 中",
    "store.inCsb":"在市场通行证中",
    "store.uploadWorldTitle":"替换世界吗？",
    "store.uploadPackTitle":"替换包吗？",
    "store.uploadWorldMessage":"这将从您的 Realm 的活跃插槽中移除您当前的世界，并允许您将其替换为新的世界。您的 Realm 成员将有机会访问您的新世界。选择“取消”以下载当前世界的副本，以防止数据丢失，或者选择“确认”以继续并替换您的世界。",
    "store.uploadPackMessage":"这将从您的 Realm 中移除所有当前应用的资源和行为包，并将其替换为所选的包。想要继续吗?",

}