chat: dict = {
    "chat.cannotSend":"无法发送聊天信息",
    "chat.copy":"复制到剪贴板",
    "chat.link.confirm":"确定要打开以下网页？",
    "chat.link.confirmTrusted":"想要打开这个链接还是复制到剪贴板？",
    "chat.link.open":"在浏览器中打开",
    "chat.link.warning":"永远不要打开你不信任的人发来的链接！",
    "chat.mentions.autocomplete.allPlayers":"全部玩家选项",
    "chat.mute":"静音聊天",
    "chat.realmsFilterDisabled":"此 Realm 已关闭聊天过滤。",
    "chat.settings":"聊天设置",
    "chat.settings.defaultChatColor":"默认聊天颜色",
    "chat.settings.chatColor":"聊天颜色",
    "chat.settings.chatFont":"聊天字体",
    "chat.settings.color":"颜色",
    "chat.settings.font":"字体",
    "chat.settings.fontColor":"字体颜色",
    "chat.settings.fontSize":"大小：%s",
    "chat.settings.fontSize.disabled":"大小：%s 时可用",
    "chat.settings.lineSpacing":"行间距",
    "chat.settings.lineSpacingNumber":"x%s",
    "chat.settings.mentions":"我的选项",
    "chat.settings.mentionsColor":"我的提及颜色",
    "chat.settings.muteAll":"静音所有聊天",
    "chat.settings.unmuteAll":"取消静音所有聊天",
    "chat.settings.tts":"聊天文本转语音",
    "chat.stream.emote":"(%s) * %s %s",
    "chat.stream.text":"(%s) <%s> %s",
    "chat.title":"聊天",
    "chat.title.cheats":"聊天和命令",
    "chat.type.achievement":"%s 刚刚获得了 %s 成就！",
    "chat.type.achievement.taken":"%s失去了%s成就",
        "chat.type.announcement":"[%s] %s",
    "chat.type.emote":"* %s %s",
    "chat.type.sleeping":"%s正在床上睡觉。要快进到黎明，需要所有玩家同时在床上睡觉。",
    "chat.type.text":"<%s> %s",
    "chat.renamed":"你已暂时在此服务器上重命名为 '%s'",

}