dr: dict = {
    "dr.banner.sale":"特惠！",
    "dr.banner.limitedTimeOffer":"限时优惠！",
    "dr.right_side.category_title":"%s",
    "dr.rarity":"稀有度",
    "dr.rarity.common":"普通",
    "dr.rarity.epic":"史诗",
    "dr.rarity.legendary":"传说",
    "dr.rarity.rare":"稀有",
    "dr.rarity.uncommon":"非凡",
    "dr.button.ok":"好的",
    "dr.loading":"加载中……",
    "dr.classic_skins.addition_skin_count":"+%s",
    "dr.classic_skins.choose_custom_skin":"选择新皮肤",
    "dr.classic_skins.custom_skin_title":"导入皮肤",
    "dr.classic_skins.custom_skin_description":"从设备中导入一个图像文件作为外观使用。这将不会在设备或课程之间同步。",
    "dr.classic_skins.custom_skin_description_popup":"如果启用了'仅允许受信任的皮肤'选项，则有自定义皮肤的玩家将不可见",
    "dr.classic_skins.custom_skin_section_title":"拥有的皮肤",
    "dr.classic_skins.invalidCustomSkin":"选择的图像不能作为《我的世界》皮肤。",
    "dr.classic_skins.owned":"已拥有",
    "dr.classic_skins.purchasable":"获取更多",
    "dr.classic_skins.realms_plus":"Realms Plus",
    "dr.classic_skins.right_side.author_name":"作者：%s",
    "dr.classic_skins.right_side.author_minecraft":"《我的世界》出品",
    "dr.classic_skins.right_side.featured_title":"特色与推荐皮肤包",
    "dr.classic_skins.right_side.limited_usage":"限制使用",
    "dr.classic_skins.right_side.limited_usage.tooltip":"该皮肤可以在这里使用，但不能漫游。",
    "dr.classic_skins.right_side.free_usage":"到处可用",
    "dr.classic_skins.right_side.free_usage.tooltip":"该皮肤将漫游到您登录的任何地方。",
    "dr.classic_skins.right_side.purchasing_disclaimer":"*购买 %s 硬币(需要 %s)并兑换此 %s 硬币包，还剩下 %s。",
    "dr.classic_skins.right_side.skin_count.plural":"%s 款皮肤",
    "dr.classic_skins.right_side.skin_count.singular":"%s 款皮肤",
    "dr.classic_skins.right_side.texture_count.plural":"%s 个材质包",
    "dr.classic_skins.right_side.texture_count.singular":"%s 个材质包",
    "dr.classic_skins.right_side.world_count.plural":"%s 个世界",
    "dr.classic_skins.right_side.world_count.singular":"%s 个世界",
    "dr.classic_skins.see_pack_in_store":"在商店中查看包",
    "dr.classic_skins.see_in_store":"在商店中查看",
    "dr.classic_skins.realms_plus_button":"Realms Plus",
    "dr.classic_skins.select_skin":"为您的皮肤选择正确的模型类型",
    "dr.classic_skins.select_skin.title":"皮肤类型",
    "dr.classic_skins.upsellWithoutStore":"您必须购买皮肤包才能使用此皮肤，但我们无法连接到市场。",
    "dr.collector_title.featured":"精选 %s",
    "dr.collector_title.general":"所有 %s",
    "dr.collector_title.owned":"已拥有 %s",
    "dr.collect_achievement_item":"收集",
    "dr.equip_piece":"装备",
    "dr.emotes.play_again":"重新播放",
    "dr.header.animation":"表情",
    "dr.header.capes":"海角",
    "dr.header.categoryFeaturedList":"%s 精选	 %s is the category name (ie. Style or Body)",
    "dr.zooming":"缩放",
    "dr.header.classic_skins":"经典皮肤",
    "dr.header.creator_piece_list":"创作者：%s",
    "dr.header.customization":"角色创建器",
    "dr.accessibility.header.customization":"角色创建器标签 1，共 4",
    "dr.accessibility.header.classic_skins":"经典皮肤标签 2，共 4",
    "dr.accessibility.header.animation":"表情标签 3，共 4",
    "dr.accessibility.header.capes":"披风标签 4，共 4",
    "dr.header.featured":"特色项目",
    "dr.header.featured_skins":"精选皮肤",
    "dr.header.previewAppearance":"预览外观",
    "dr.header.colorPicker":"颜色选取器",
    "dr.achievement.achievement_locked.not_signed_in":"此项目将在完成一个成就后解锁。",
    "dr.achievement.achievement_locked.signed_in":"此项目将在完成 %s 成就后解锁。",
    "dr.achievement.achievement_unlocked":"此项目已在完成 %s 成就后解锁。",
    "dr.achievement.challenge_locked":"此项目将在完成一个《我的世界:",
    "dr.achievement.challenge_unlocked":"此项目已在完成一个《我的世界:",
    "dr.arm_size_label_text":"手臂大小",
    "dr.body_size_label_text":"高度",
    "dr.mouth_color":"嘴部",
    "dr.iris_color":"虹膜",
    "dr.sclera_color":"巩膜",
    "dr.eyebrows_color":"眉毛",
    "dr.hair_color":"头发",
    "dr.facial_hair_color":"面部毛发",
    "dr.skin_color":"底座",
    "dr.primary_channel":"主要的",
    "dr.secondary_channel":"辅助",
    "dr.accent_channel":"重音",
    "dr.left_arm":"左臂",
    "dr.right_arm":"右臂",
    "dr.both_arms":"双臂",
    "dr.left_leg":"左腿",
    "dr.right_leg":"右腿",
    "dr.both_legs":"双腿",
    "dr.limb_switcher_default_title":"肢体选择",
    "dr.arm_size.slim":"细",
    "dr.arm_size.wide":"宽",
    "dr.height_size.smaller":"较小",
    "dr.height_size.small":"小",
    "dr.height_size.medium":"中",
    "dr.height_size.tall":"高",
    "dr.none_button_text":"无",
    "dr.go_to_profile_settings_text":"前往档案设置",
    "dr.default_piece_button_text":"默认",
    "dr.categories.body":"身体",
    "dr.categories.style":"样式",
    "dr.categories.base":"基地",
    "dr.categories.eyes":"眼睛",
    "dr.categories.mouth":"嘴巴",
    "dr.categories.hair":"头发",
    "dr.categories.facial_hair":"面部毛发",
    "dr.categories.arms":"手臂",
    "dr.categories.animation":"表情",
    "dr.categories.legs":"腿部",
    "dr.categories.size":"大小",
    "dr.categories.top":"上衣",
    "dr.categories.bottom":"下装",
    "dr.categories.outerwear":"外套",
    "dr.categories.headwear":"头饰",
    "dr.categories.gloves":"手套",
    "dr.categories.footwear":"鞋类",
    "dr.categories.back_item":"背部物品",
    "dr.categories.face_item":"面部物品",
    "dr.categories.capes":"披风",
    "dr.notification.to_skins":"正在切换至经典皮肤",
    "dr.notification.to_persona":"正在切换至角色创建器",
    "dr.prompt.switching_to_persona_title":"切换至角色创建器",
    "dr.prompt.switching_to_persona_detail":"您正在切换到此栏位的角色创建器。角色创建器可让您逐个物品地在《我的世界》中打造角色。您的经典皮肤将保存为此栏位中的备选项，您可以在以后切换回去。",
    "dr.prompt.switching_to_skin_title":"切换到经典皮肤",
    "dr.prompt.switching_to_skin_detail":"您正在切换到此栏位的经典皮肤。经典皮肤可应用到整个角色上，无法自定义。您的角色创建器外观将保存为此栏位中的备选项，您可以在以后切换回去。",
    "dr.prompt.do_not_show_again":"不再显示此内容",
    "dr.label.current_persona":"这是您当前的角色",
    "dr.label.current_skin":"这是您当前的皮肤",
    "dr.notification.persona_save":"该角色已被保存",
    "dr.notification.persona_create":"该角色已被创建",
    "dr.notification.persona_create_new":"新角色已被创建",
    "dr.notification.classic_skin_created_new":"新皮肤已被创建",
    "dr.notification.persona_delete":"该角色已被删除",
    "dr.notification.item_selection_failed":"无法选择项目",
    "dr.notification.character_failed":"无法加载角色%s",
    "dr.notification.character_failed_start":"无法加载字符%s。可在档案中重新进行加载。",
    "dr.notification.equipped_piece":"您已装备 %s",
    "dr.modal.persona_delete_confirm":"当前角色将被删除。确定要继续？",
    "dr.modal.persona_delete_confirm_title":"删除角色？",
    "dr.modal.difference_information_title":"角色和经典皮肤差异",
    "dr.default.alex.bottom":"艾莉克斯的裤子",
    "dr.default.alex.hair":"艾莉克斯的头发",
    "dr.default.alex.mouth":"艾莉克斯的嘴",
    "dr.default.alex.shoes":"艾莉克斯的鞋子",
    "dr.default.alex.skin":"艾莉克斯",
    "dr.default.alex.top":"艾莉克斯的衬衫",
    "dr.default.emote.basicClap":"简单拍手",
    "dr.default.emote.communicationFollowMe":"跟着我",
    "dr.default.emote.communicationPoint":"在那里！",
    "dr.default.emote.overheadWave":"浪潮",
    "dr.default.eyes":"标准注视",
    "dr.default.steve.bottom":"史蒂夫的裤子",
    "dr.default.steve.hair":"史蒂夫的头发",
    "dr.default.steve.mouth":"史蒂夫的嘴",
    "dr.default.steve.shoes":"史蒂夫的鞋子",
    "dr.default.steve.skin":"史蒂夫",
    "dr.default.steve.top":"史蒂夫的衬衫",
    "dr.emotes.slot":"表情 %d",
    "dr.emotes.key":"键 %d",
    "dr.character_creator_getting_started_title":"开始",
    "dr.character_creator_getting_started_detail":"选择左侧的物品，看看它们在您的角色身上的样子！",
    "dr.deep_link_fail.profile":"深层链接失败：无法加载档案",
    "dr.deep_link_fail.dressing_room":"深层链接失败：无法打开优惠",
    "dr.marketplace.get_more_skins":"获取更多皮肤",
    "dr.classic_skins.show_more":"展开",
    "dr.color.button_name":"颜色",
    "dr.color.air_force_blue":"空军蓝",
    "dr.color.alex_green":"艾莉克斯绿色",
    "dr.color.alex_mouth":"艾莉克斯唇色",
    "dr.color.alex_orange":"艾莉克斯橙色",
    "dr.color.alex_skin":"艾莉克斯肤色",
    "dr.color.amulet_green":"护符绿色",
    "dr.color.auburn_red":"褐红色",
    "dr.color.bronco_vanilla":"野马香草色",
    "dr.color.bronze_olive":"青铜橄榄色",
    "dr.color.brown_pod_black":"棕豆荚黑色",
    "dr.color.bunker_blueish_black":"地堡蓝黑色",
    "dr.color.cape_brown":"斗篷棕色",
    "dr.color.celery_green":"芹菜绿色",
    "dr.color.chalky_blonde":"白垩金色",
    "dr.color.cocoa_brown":"深棕色",
    "dr.color.cool_brown_pod":"酷炫深棕色",
    "dr.color.cool_chocolate":"酷炫栗色",
    "dr.color.cool_melon":"冷调西瓜色",
    "dr.color.cool_tuft_bush":"酷炫桦树色",
    "dr.color.cool_tuscany":"冷调托斯卡纳色",
    "dr.color.copper_red":"铜红色",
    "dr.color.dark_brown":"深棕色",
    "dr.color.dark_brown_pod":"深棕豆荚色",
    "dr.color.dark_comet_grey":"深彗星灰色",
    "dr.color.dark_red":"深红色",
    "dr.color.dark_salmon":"深鲑红色",
    "dr.color.dark_warm_madras":"深暖调马德拉斯色",
    "dr.color.dark_warm_mikado":"深榛子色",
    "dr.color.dutch_blonde":"荷兰金色",
    "dr.color.green_house":"温室色",
    "dr.color.light_brown":"浅棕色",
    "dr.color.light_comet_grey":"浅彗星灰色",
    "dr.color.light_gold":"浅金色",
    "dr.color.light_jordy_blue":"浅乔迪蓝",
    "dr.color.magnolia_white":"玉兰白",
    "dr.color.medium_blonde":"中度金色",
    "dr.color.medium_brown":"中度棕色",
    "dr.color.minecraft_black":"《我的世界》黑色",
    "dr.color.minecraft_blue":"《我的世界》蓝色",
    "dr.color.minecraft_cyan":"《我的世界》青色",
    "dr.color.minecraft_green":"《我的世界》绿色",
    "dr.color.minecraft_grey":"《我的世界》灰色",
    "dr.color.minecraft_light_blue":"《我的世界》淡蓝色",
    "dr.color.minecraft_light_grey":"《我的世界》浅灰色",
    "dr.color.minecraft_lime_green":"《我的世界》黄绿色",
    "dr.color.minecraft_magenta":"《我的世界》品红色",
    "dr.color.minecraft_orange":"《我的世界》橙色",
    "dr.color.minecraft_pink":"《我的世界》粉红色",
    "dr.color.minecraft_purple":"《我的世界》紫色",
    "dr.color.minecraft_red":"《我的世界》红色",
    "dr.color.minecraft_white":"《我的世界》白色",
    "dr.color.minecraft_yellow":"《我的世界》黄色",
    "dr.color.muddy_waters":"磨制花岗岩",
    "dr.color.nepal_grey_blue":"尼泊尔灰蓝色",
    "dr.color.nugget_blonde":"金块金色",
    "dr.color.pale_brown":"淡棕色",
    "dr.color.peach_orange":"蜜桃橙色",
    "dr.color.purpleish_black":"紫黑色",
    "dr.color.salmon":"鲑红色",
    "dr.color.seal_brown":"深暮光色",
    "dr.color.spanish_white":"梧牙覆白",
    "dr.color.spring_rain_green":"春雨绿色",
    "dr.color.steve_blue":"史蒂夫蓝色",
    "dr.color.steve_brown":"史蒂夫棕色",
    "dr.color.steve_mouth":"史蒂夫唇色",
    "dr.color.steve_skin":"史蒂夫肤色",
    "dr.color.strawberry_blonde":"草莓金色",
    "dr.color.tangaroa_dark_blue":"坦加罗深蓝色",
    "dr.color.vanilla":"香草色",
    "dr.color.warm_bisque":"暖调橘黄色",

}