dr: dict = {
    "dr.banner.sale":"特惠！",
    "dr.banner.limitedTimeOffer":"限时优惠！",
    "dr.right_side.category_title":"%s",
    "dr.rarity":"稀有度",
    "dr.rarity.common":"普通",
    "dr.rarity.epic":"史诗",
    "dr.rarity.legendary":"传说",
    "dr.rarity.rare":"稀有",
    "dr.rarity.uncommon":"非凡",
    "dr.button.ok":"好的",
    "dr.loading":"加载中...",
    "dr.classic_skins.addition_skin_count":"+%s",
    "dr.classic_skins.choose_custom_skin":"选择新皮肤",
    "dr.classic_skins.custom_skin_title":"导入皮肤",
    "dr.classic_skins.custom_skin_description":"从设备中导入一个图像文件作为外观使用。这将不会在设备或课程之间同步。",
    "dr.classic_skins.custom_skin_description_popup":"如果启用了'仅允许受信任的皮肤'选项，则有自定义皮肤的玩家将不可见",
    "dr.classic_skins.custom_skin_section_title":"拥有的皮肤",
    "dr.classic_skins.invalidCustomSkin":"选择的图像不能作为《我的世界》皮肤。",
    "dr.classic_skins.owned":"已拥有",
    "dr.classic_skins.purchasable":"获取更多",
    "dr.classic_skins.realms_plus":"Realms Plus",
    "dr.classic_skins.right_side.author_name":"作者：%s",
    "dr.classic_skins.right_side.author_minecraft":"《我的世界》出品",
    "dr.classic_skins.right_side.featured_title":"特色与推荐皮肤包",
    "dr.classic_skins.right_side.limited_usage":"限制使用",
    "dr.classic_skins.right_side.limited_usage.tooltip":"该皮肤可以在这里使用，但不能漫游。",
    "dr.classic_skins.right_side.free_usage":"到处可用",
    "dr.classic_skins.right_side.free_usage.tooltip":"该皮肤将漫游到您登录的任何地方。",
    "dr.classic_skins.right_side.purchasing_disclaimer":"*购买 %s 硬币(需要 %s)并兑换此 %s 硬币包，还剩下 %s。",
    "dr.classic_skins.right_side.skin_count.plural":"%s 款皮肤",
    "dr.classic_skins.right_side.skin_count.singular":"%s 款皮肤",
    "dr.classic_skins.right_side.texture_count.plural":"%s 个材质包",
    "dr.classic_skins.right_side.texture_count.singular":"%s 个材质包",
    "dr.classic_skins.right_side.world_count.plural":"%s 个世界",
    "dr.classic_skins.right_side.world_count.singular":"%s 个世界",
    "dr.classic_skins.see_pack_in_store":"在商店中查看包",
    "dr.classic_skins.see_in_store":"在商店中查看",
    "dr.classic_skins.realms_plus_button":"Realms Plus",
    "dr.classic_skins.select_skin":"为您的皮肤选择正确的模型类型",
    "dr.classic_skins.select_skin.title":"皮肤类型",
    "dr.classic_skins.upsellWithoutStore":"您必须购买皮肤包才能使用此皮肤，但我们无法连接到市场。",
    "dr.collector_title.featured":"精选 %s",
    "dr.collector_title.general":"所有 %s",
    "dr.collector_title.owned":"已拥有 %s",
    "dr.collect_achievement_item":"收集",
    "dr.equip_piece":"装备",
    "dr.emotes.play_again":"重新播放",
    "dr.emotes.assignment":"将 '%s' 分配至一个栏位",
    "dr.emotes.replace":"替换",
    "dr.header.animation":"表情",
    "dr.header.capes":"披肩",
    "dr.header.categoryFeaturedList":"%s 精选	 %s is the category name (ie. Style or Body)",
    "dr.zooming":"缩放",
    "dr.header.classic_skins":"经典皮肤",
    "dr.header.creator_piece_list":"创作者：%s",
    "dr.header.customization":"角色创建器",
    "dr.accessibility.header.customization":"角色创建器标签 1，共 4",
    "dr.accessibility.header.classic_skins":"经典皮肤标签 2，共 4",
    "dr.accessibility.header.animation":"表情标签 3，共 4",
    "dr.accessibility.header.capes":"披风标签 4，共 4",
    "dr.header.featured":"特色项目",
    "dr.header.featured_skins":"精选皮肤",
    "dr.header.previewAppearance":"预览外观",
    "dr.header.colorPicker":"颜色选取器",
    "dr.achievement.achievement_locked.not_signed_in":"此项目将在完成一个成就后解锁。",
    "dr.achievement.achievement_locked.signed_in":"此项目将在完成 %s 成就后解锁。",
    "dr.achievement.achievement_unlocked":"此项目已在完成 %s 成就后解锁。",
            "dr.arm_size_label_text":"手臂大小",
    "dr.body_size_label_text":"高度",
    "dr.mouth_color":"嘴部",
    "dr.iris_color":"虹膜",
    "dr.sclera_color":"巩膜",
    "dr.eyebrows_color":"眉毛",
    "dr.hair_color":"头发",
    "dr.facial_hair_color":"面部毛发",
    "dr.skin_color":"底座",
    "dr.primary_channel":"主要的",
    "dr.secondary_channel":"辅助",
    "dr.accent_channel":"重音",
    "dr.left_arm":"左臂",
    "dr.right_arm":"右臂",
    "dr.both_arms":"双臂",
    "dr.left_leg":"左腿",
    "dr.right_leg":"右腿",
    "dr.both_legs":"双腿",
    "dr.limb_switcher_default_title":"肢体选择",
    "dr.none_button_text":"无",
    "dr.none_emote_button_text":"全部清除",
    "dr.go_to_profile_settings_text":"转到“设置”",
    "dr.default_piece_button_text":"默认",
    "dr.categories.body":"身体",
    "dr.categories.style":"样式",
    "dr.categories.base":"基地",
    "dr.categories.eyes":"眼睛",
    "dr.categories.mouth":"嘴巴",
    "dr.categories.hair":"头发",
    "dr.categories.facial_hair":"面部毛发",
    "dr.categories.arms":"手臂",
    "dr.categories.animation":"表情",
    "dr.categories.legs":"腿部",
    "dr.categories.size":"大小",
    "dr.categories.top":"上衣",
    "dr.categories.bottom":"下装",
    "dr.categories.outerwear":"外套",
    "dr.categories.headwear":"头饰",
    "dr.categories.gloves":"手套",
    "dr.categories.footwear":"鞋类",
    "dr.categories.back_item":"背部物品",
    "dr.categories.face_item":"面部物品",
    "dr.categories.capes":"披风",
    "dr.notification.to_skins":"正在切换至经典皮肤",
    "dr.notification.to_persona":"正在切换至角色创建器",
    "dr.prompt.switching_to_persona_title":"切换至角色创建器",
    "dr.prompt.switching_to_persona_detail":"您正在切换到此栏位的角色创建器。角色创建器可让您逐个物品地在《我的世界》中打造角色。您的经典皮肤将保存为此栏位中的备选项，您可以在以后切换回去。",
    "dr.prompt.switching_to_skin_title":"切换到经典皮肤",
    "dr.prompt.switching_to_skin_detail":"您正在切换到此栏位的经典皮肤。经典皮肤可应用到整个角色上，无法自定义。您的角色创建器外观将保存为此栏位中的备选项，您可以在以后切换回去。",
    "dr.prompt.do_not_show_again":"不再显示此内容",
    "dr.label.current_persona":"这是您当前的角色",
    "dr.label.current_skin":"这是您当前的皮肤",
    "dr.notification.persona_save":"该角色已被保存",
    "dr.notification.persona_create":"该角色已被创建",
    "dr.notification.persona_create_new":"新角色已被创建",
    "dr.notification.classic_skin_created_new":"新皮肤已被创建",
    "dr.notification.persona_delete":"该角色已被删除",
    "dr.notification.item_selection_failed":"无法选择项目",
    "dr.notification.character_failed":"无法加载角色%s",
    "dr.notification.character_failed_start":"无法加载字符%s。可在档案中重新进行加载。",
    "dr.notification.equipped_piece":"您已装备 %s",
    "dr.notification.custom_banned":"皮肤因违反社区标准而被多人游戏屏蔽。",
    "dr.modal.persona_delete_confirm":"当前角色将被删除。确定要继续？",
    "dr.modal.persona_delete_confirm_title":"删除角色？",
    "dr.modal.difference_information_title":"角色和经典皮肤差异",
    "dr.modal.restricted_content_title":"限制警告",
    "dr.modal.restricted_content_text":"此内容在大多数地理区域可用，但在少数地理区域中受到限制。",
    "dr.default.alex.bottom":"艾莉克斯的裤子",
    "dr.default.alex.hair":"艾莉克斯的头发",
    "dr.default.alex.mouth":"艾莉克斯的嘴",
    "dr.default.alex.shoes":"艾莉克斯的鞋子",
    "dr.default.alex.skin":"艾莉克斯",
    "dr.default.alex.top":"艾莉克斯的衬衫",
    "dr.default.emote.basicClap":"简单拍手",
    "dr.default.emote.communicationFollowMe":"跟着我",
    "dr.default.emote.communicationPoint":"在那里！",
    "dr.default.emote.overheadWave":"浪潮",
    "dr.default.eyes":"标准注视",
    "dr.default.steve.bottom":"史蒂夫的裤子",
    "dr.default.steve.hair":"史蒂夫的头发",
    "dr.default.steve.mouth":"史蒂夫的嘴",
    "dr.default.steve.shoes":"史蒂夫的鞋子",
    "dr.default.steve.skin":"史蒂夫",
    "dr.default.steve.top":"史蒂夫的衬衫",
    "dr.emotes.slot":"表情 %d",
    "dr.emotes.key":"键 %d",
    "dr.character_creator_getting_started_title":"开始",
    "dr.character_creator_getting_started_detail":"选择左侧的物品，看看它们在您的角色身上的样子！",
    "dr.deep_link_fail.profile":"深层链接失败：无法加载档案",
    "dr.deep_link_fail.dressing_room":"深层链接失败：无法打开优惠",
    "dr.marketplace.get_more_skins":"获取更多皮肤",
    "dr.classic_skins.show_more":"展开",
    "dr.color.button_name":"颜色",
    "dr.color.amber_dark":"琥珀色 - 深",
    "dr.color.amber_dark_soft":"琥珀色 - 深色柔和",
    "dr.color.amber_light":"琥珀色 - 浅",
    "dr.color.auburn_red":"褐红色",
    "dr.color.blue_dark":"蓝色 - 深",
    "dr.color.blue_light":"蓝色 - 浅色",
    "dr.color.blue_mid":"蓝色 - 中等",
    "dr.color.blue_vivid":"蓝色 - 鲜艳",
    "dr.color.blueish_black":"蓝黑色",
    "dr.color.brown_dark":"棕色 - 深色",
    "dr.color.brown_light":"棕色 - 浅色",
    "dr.color.brown_mid":"棕色 - 中",
    "dr.color.brown_very_dark":"棕色 – 极深色",
    "dr.color.copper_red":"铜红色",
    "dr.color.dark_blonde":"暗金色",
    "dr.color.dark_brown":"深棕色",
    "dr.color.dark_cool":"深色 - 冷色",
    "dr.color.dark_gray":"深灰色",
    "dr.color.dark_red":"深红色",
    "dr.color.dark_soft":"深色 - 柔和",
    "dr.color.dark_warm":"深色 - 暖色",
    "dr.color.deep_black":"深黑色",
    "dr.color.deep_brown":"深棕色",
    "dr.color.green_bright":"绿色 - 明亮",
    "dr.color.green_cool_dark":"绿色 – 冷深色",
    "dr.color.green_light":"绿色 - 浅",
    "dr.color.green_mid":"绿色 - 中等",
    "dr.color.green_warm_dark":"绿色 – 暖深色",
    "dr.color.gray_blue":"灰蓝色",
    "dr.color.gray_dark":"灰色 - 深色",
    "dr.color.gray_light":"灰色 - 浅色",
    "dr.color.light_blonde":"浅金色",
    "dr.color.light_brown":"浅棕色",
    "dr.color.light_cool":"浅色 - 冷色",
    "dr.color.light_gray":"淡灰色",
    "dr.color.light_medium":"浅色 - 中等",
    "dr.color.light_red":"浅红色",
    "dr.color.light_warm":"浅色 - 暖色",
    "dr.color.mc_black":"MC 黑色",
    "dr.color.medium_blonde":"中度金色",
    "dr.color.medium_brown":"中度棕色",
    "dr.color.medium_cool":"中等 - 冷色",
    "dr.color.medium_dark_cool":"中深 - 冷",
    "dr.color.medium_dark_soft":"中等偏深 - 柔和",
    "dr.color.medium_dark_warm":"中等偏深 - 暖色",
    "dr.color.medium_light_blonde":"中浅金色",
    "dr.color.medium_light_cool":"中等偏浅 - 冷色",
    "dr.color.medium_light_deep":"中等偏浅 - 深色",
    "dr.color.medium_light_vibrant":"中等偏浅 - 靓丽",
    "dr.color.medium_light_warm":"中等偏浅 - 暖色",
    "dr.color.medium_soft":"中等 - 柔和",
    "dr.color.medium_warm":"中等 - 暖色",
    "dr.color.minecraft_gray":"《我的世界》灰色",
    "dr.color.minecraft_black":"《我的世界》黑色",
    "dr.color.minecraft_blue":"《我的世界》蓝色",
    "dr.color.minecraft_cyan":"《我的世界》青色",
    "dr.color.minecraft_green":"《我的世界》绿色",
    "dr.color.minecraft_light_blue":"《我的世界》淡蓝色",
    "dr.color.minecraft_light_gray":"《我的世界》浅灰色",
    "dr.color.minecraft_lime_green":"《我的世界》黄绿色",
    "dr.color.minecraft_magenta":"《我的世界》品红色",
    "dr.color.minecraft_orange":"《我的世界》橙色",
    "dr.color.minecraft_pink":"《我的世界》粉红色",
    "dr.color.minecraft_purple":"《我的世界》紫色",
    "dr.color.minecraft_red":"《我的世界》红色",
    "dr.color.minecraft_white":"《我的世界》白色",
    "dr.color.minecraft_yellow":"《我的世界》黄色",
    "dr.color.muted_gray":"柔和灰色",
    "dr.color.purpleish_black":"紫黑色",
    "dr.color.red_dark":"红色 - 深色",
    "dr.color.reddish_black":"红黑色",
    "dr.color.soft_black":"柔和黑色",
    "dr.color.soft_blonde":"柔和金色",
    "dr.color.soft_magenta":"柔和品红色",
    "dr.color.very_dark_cool":"极深色 - 冷色",
    "dr.color.very_dark_warm":"极深色 - 暖色",
    "dr.color.very_light_blonde":"极浅金色",
    "dr.color.very_light_cool":"极浅色 - 冷色",
    "dr.color.very_light_soft":"极浅色 - 柔和",
    "dr.color.very_light_warm":"极浅色 - 暖色",
    "dr.color.vibrant_orange":"亮橙色",
    "dr.color.white":"白色",
    "dr.color.white_deep":"白色 - 深色",
    "dr.color.white_light":"白色 - 浅色",
    "dr.color.white_mid":"白色 - 中等",
    "dr.color.yellow_green":"黄绿色",

}