gameTest: dict = {
    "gameTest.description":"与游戏测试交互。",
    "gameTest.error.unknownCommandMode":"提供的命令模式未知",
    "gameTest.error.missingStructure":"在半径 %s 范围内找不到任何结构方块",
    "gameTest.error.cannotFindLookedAtBlock":"找不到您正在注视的方块",
    "gameTest.error.cannotFindStuctureBlockContainingBlock":"找不到包含目标位置的结构方块 %s，%s，%s",
    "gameTest.error.structureTooBig":"该结构在每个轴上必须小于 %s 方块",
    "gameTest.error.repeatCountTooSmall":"重复次数必须大于 0",
    "gameTest.error.failConditionMet":"符合失败条件",
    "gameTest.error.timeout":"在 %s 刻内没有成功或失败",
    "gameTest.error.noFinishedSequences":"没有完成的序列",
    "gameTest.error.flakyTestError":"成功次数不足：%s 次成功，共 %s 次尝试。要求成功次数：%s。最多尝试次数：%s。",
    "gameTest.error.testMissing":"找不到名称为‘%s’的测试。",
    "gameTest.error.structureNotSpawned":"未能生成路径为“%s”的测试结构	 %s is the file path of the structure",
    "gameTest.error.flakyFailed":"片状测试%s失败，尝试：%s/%s",
    "gameTest.error.flakyFailedShowSuccesses":"，成功：%s（需要 %s）           	 This appears right after gameTest.error.flakyFailed if multiple successes are required",
    "gameTest.error.failed":"%s失败！",
    "gameTest.error.succeededInInvalidTick":"在无效标记中成功：预期 %s，但当前标记为 %s",
    "gameTest.error.noTestsFound":"未找到用于标签‘%s’的测试",
    "gameTest.error.simulatedPlayerOutOfBounds":"模拟玩家“%s”已离开其游戏测试结构太远。",
    "gameTest.error.unkownEvent":"未知事件名称 '%s'",
    "gameTest.optionalPrefix":"（可选）",
    "gameTest.assert.couldNotSetBlock":"无法设置方块“%s”",
    "gameTest.assert.missingButton":"预期一个按钮",
    "gameTest.assert.missingLever":"预期一个拉杆",
    "gameTest.assert.couldNotSpawnEntity":"无法生成“%s”类型的实体",
    "gameTest.assert.onlyWorksWithMobs":"spawnWithoutBehaviors() 只适用于生物",
    "gameTest.assert.mobWontMove":"无法使生物移动“%s”",
    "gameTest.assert.noPathFound":"未找到类型为“%s”的实体的路径",
    "gameTest.assert.pathFound":"已找到类型为“%s”的实体的路径",
    "gameTest.assert.expectEntityOfType":"预期“%s”类型的实体",
    "gameTest.assert.unexpectedDataResult":"意外的实体数据结果",
    "gameTest.assert.didNotExpectEntityOfType":"意外的“%s”类型的实体",
    "gameTest.assert.expectBlock":"预期的方块类型 '%s'",
    "gameTest.assert.expectBlockWithState":"状态为‘%s’的预期方块",
    "gameTest.assert.unexpectedBlock":"没有意料到的方块类型 '%s'",
    "gameTest.assert.unexpectedBlockState":"方块未达到预期的方块状态",
    "gameTest.assert.expectItemOfType":"预期 %s 类型的物品实体",
    "gameTest.assert.unexpectedItemOfType":"意外的 %s 类型的物品实体",
    "gameTest.assert.wrongEntityItemCount":"意外的 %s 类型的物品实体数量。预期：%s。实际：%s。",
    "gameTest.assert.noContainerFound":"未找到容器",
    "gameTest.assert.expectEmptyContainer":"预期空容器",
    "gameTest.assert.expectItemInContainer":"容器不包含 %s 类型的物品",
    "gameTest.assert.missingComponent":"实体缺少组件“%s”",
    "gameTest.assert.hasComponent":"实体有组件“%s”",
    "gameTest.assert.missingArmor":"实体在栏位 %s 中缺少盔甲 %s，数据 %s",
    "gameTest.assert.hasArmor":"实体在栏位 %s 中有盔甲 %s，数据 %s",
    "gameTest.assert.unexpectedRedstonePowerLevel":"意外的红石力量等级。预期：%s。实际：%s。",
    "gameTest.assert.expectWaterLogged":"预期含水方块",
    "gameTest.assert.unexpectedWaterLogged":"意外的含水方块",
    "gameTest.assert.missingExplosionComponent":"由于实体没有爆炸部件，无法设置实体的导火索",
    "gameTest.assert.invalidEntityInstance":"无效实体实例",
    "gameTest.assert.unexpectedParameterValue":"参数‘%s’的意外值",
    "gameTest.assert.expectEntityInstance":"预期“%s”类型的实体实例",
    "gameTest.assert.didNotExpectEntityInstance":"意外的“%s”类型的实体实例",
    "gameTest.assert.invalidFluidType":"无效液体类型",
    "gameTest.assert.expectCauldron":"预期的炼药锅方块类型",
    "gameTest.success.runningTests":"正在运行 %s 测试...",
    "gameTest.success.relativePosition":"位置相对于 %s：%s						 first %s is the name of the test and the second %s is the local location in the test structure",
    "gameTest.success.passed":"%s通过！",
    "gameTest.success.flakyPassedEnough":"%s通过了 %s 次尝试，总计有 %s 次尝试。	 this is used when a test has passed a sufficient number of times",
    "gameTest.success.flakyPassed":"片状测试%s成功，尝试：%s，成功：%s。	 this one is used when a test has passed, but not yet reached the required number of times to succeed",
    "gameTest.success.testsStarted":"正在运行 %s 个带有标签‘%s’的测试…",
    "gameTest.report.testLocation":"在：%s，%s，%s（相关：%s，%s，%s）",
    "gameTest.report.tickCount":"标记：%s                                              	 This appears right below the gameTest.report.testLocation line",
    "gameTest.report.testCount":"游戏测试完成！运行了 %s 个测试",
    "gameTest.report.someTestsFailed":"%s 个所要求的测试失败 :",
    "gameTest.report.allRequiredTestsPassed":"所有要求的测试均通过 :",
    "gameTest.report.optionalFailures":"%s 个可选测试失败",
    "gameTest.report.bookTitle":"游戏测试报告                                      	 A book with this title is placed next to each test with the test results inside",

}