gathering: dict = {
    "gathering.button.minecraftLive":"《我的世界 Live》",
    "gathering.caption.startsIn":"距离开始还有 %s",
    "gathering.caption.endsIn":"距离结束还有 %s",
    "gathering.caption.eventOver":"活动结束",
    "gathering.info.button.readMore":"阅读更多…",
    "gathering.info.button.voteNow":"立即投票",
    "gathering.info.title.liveIsComing":"《我的世界 Live》即将推出！",
    "gathering.info.header.minecraftLive":"《我的世界 Live》",
    "gathering.info.body.liveIsComing":"是时候为《我的世界》添加新生物了，选择权在您手中。",
    "gathering.info.modal.title.connectFail":"连接失败",
    "gathering.info.modal.body.connectFail":"很不幸，我们无法连接。请稍后再试。",
    "gathering.connect.title":"正在查找服务器...",
    "gathering.info.qr.title.onlineService":"了解更多",
    "gathering.info.qr.body.onlineService.nso":"需要 Nintendo Switch Online 会员资格才能参加《我的世界》的活动。",
    "gathering.info.qr.body.onlineService.psn":"需要登录 \'PlayStation Plus\' 才能参加《我的世界》的活动。",
    "gathering.info.qr.body.onlineService":"需要登录才能参加《我的世界》的活动。",
    "gathering.info.qr.title.childAccount":"不允许在线播放",
    "gathering.info.qr.body.childAccount":"当前你的父母监控制限制你在线玩游戏。",
    "gathering.info.qr.title.console":"现场活动直播",
    "gathering.info.qr.body.console":"扫描以加入我们的现场活动直播",
    "gathering.info.signIn.title":"登录以参加此项活动。",
    "gathering.info.signIn.body":"请登录 Microsoft 帐户以参加此项活动。",

}