authentication: dict = {
    "authentication.demo.body.default":"正在开始演示版本体验……",
    "authentication.demo.body.error":"抱歉，该课程当前不可用。",
    "authentication.demo.title":"正在加载演示版本",
    "authentication.demo.title.error":"课程不可用",
    "authentication.pleaseSignIn":"使用您的学校或组织账户登录以探索 Minecraft Education。",
    "authentication.loggingin":"登录中…",
    "authentication.signIn":"登录",
    "authentication.signIn.tryAgain":"再试一次",
    "authentication.signingInTo":"正在登录进%s",
    "authentication.unableToConnect":"无法连接",
    "authentication.unauthenticated":"该帐户无法使用 Minecraft Education。",
    "authentication.location":"如需更多信息：",
    "authentication.tryagain":"用其他帐户登录",
    "authentication.welcome":"欢迎，%s！",
    "authentication.exitingGame":"再见，请尽快回来。",
    "authentication.finalTrialWarning":"这是您对《我的世界》教育版的最后一次试用。%1%1在此会话之后，您的学校或组织将需要购买许可证才能继续使用《我的世界》教育版的所有功能。",
    "authentication.oneTrialWarning":"在您的学校或组织需要购买许可证之前，您还剩 1 次试用《我的世界》教育版的机会。%1%1每次打开《我的世界》教育版，都会消耗一次试用机会。",
    "authentication.trialMessageTitle":"免费试用",
    "authentication.trialWelcome":"欢迎！%1%1在您的学校或组织需要购买许可证之前，您有 %2 次 Minecraft Education 试用机会。%1%1每次打开 Minecraft Education，都会消耗一次试用机会。尽情探索吧！",
    "authentication.trialWarning":"在您的学校或组织需要购买许可证之前，您有 %2 次 Minecraft Education 试用机会。%1%1每次打开 Minecraft Education，都会消耗一次试用机会。",
    "authentication.trialEnded":"您的 Minecraft Education 试用版已结束。%1%1您的学校或组织需购买许可证才能继续使用 Minecraft Education 的所有功能。%1%1您现在将从您的 %2 账户中注销，您可以继续探索功能有限的演示课程。",
    "authentication.trialEndedTitle":"试用版已到期",
    "authentication.clickToPurchase":"如何购买		 Translations should be 20 characters or less",
    "authentication.adalException":"我们无法连接到您当前所需的服务。请检查您的互联网连接，然后再试一次。",
    "authentication.buyMinecraft":"前往 App Store",
    "authentication.edu.leaveGame.title":"您已被注销",
    "authentication.edu.leaveGame.body":"另一个设备已使用您的账户登录。",
    "authentication.edu.leaveGame.help":"帮助",
    "authentication.educationOnly":"如果您不是教育用户，可以前往应用商店下载标准版本.",
    "authentication.minecraftInstead":"应用商店",
    "authentication.signInButton":"用其他账户登录",
    "authentication.signInRequired":"需要登录",
    "authentication.store.confirm.button":"确认",
    "authentication.store.confirmPurchase":"确认购买",
    "authentication.store.intro":"您的 Minecraft Education 试用机会已用完。您需要购买许可，才能继续使用 Minecraft Education。",
    "authentication.store.popup.purchaseFailed.title":"出错了",
    "authentication.store.popup.purchaseFailed.msg":"抱歉，无法完成购买。请检查网络连接？",
    "authentication.store.purchase.info1":"付款会在确认购买后向您的 iTunes 账户收取，除非在当前订阅期结束前至少 24 小时关闭自动更新，否则订阅会自动更新。在当前订阅期结束之前 24 小时内，更新费用会根据您此前选择的订阅价格选项，向您的账户收取。",
    "authentication.store.purchase.info2":"购买之后您可以访问 iTunes 账户，管理您的订阅，关闭自动更新。如果您在订阅激活后取消，订阅剩余有效期间将不予退款。此订阅会让您的 iTunes 账户将与您的 Office 365 教育版账户关联，因此您将失去资格，无法使用此 iTunes 账户购买额外的 Minecraft Education 许可。",
    "authentication.store.purchase.button":"购买许可（%s/年）",
    "authentication.store.terms":"使用条款",
    "authentication.store.viewTermsAndConditions":"条款和条件",
    "authentication.store.viewPrivacyPolicy":"隐私政策",
    "authentication.toast.refreshFailed.title":"帐户",
    "authentication.toast.refreshFailed.body":"您的帐户信息出错，请再次登录以继续使用多人玩家功能。",
    "authentication.error.generic.title":"无法登录",
    "authentication.error.generic.body":"我们无法将您登录。请确保您正在使用学校或组织账户登录，随后请重试。",
    "authentication.error.generic.link1":"了解有关账户资格的信息。",
    "authentication.error.generic.link2":"尝试演示课程。",
    "authentication.error.outOfDate.title":"需要更新",
    "authentication.error.outOfDate.body":"很抱歉， 此版本的 Minecraft Education 不再受支持。请更新至最新版本以继续探索。",
    "authentication.error.outOfDate.downloadPage":"转至下载页面",
    "authentication.error.accountType.body":"哎呀！看来您使用了个人账户进行登录。此账户不符合使用 Minecraft Education 的条件。请确保您正在使用学校或组织账户登录，随后请重试。",

}