feed: dict = {
    "feed.like":赞",
    "feed.manage_feed":管理信息提要",
    "feed.comment":评论",
    "feed.reported_label":举报",
    "feed.ignore":忽略",
    "feed.nrreport":%d 个举报",
    "feed.nrreports":%d 个举报",
    "feed.newPost":新建帖子",
    "feed.daysAgo":%d 天前",
    "feed.hoursAgo":%d 小时前",
    "feed.minutesAgo":%d 分钟前",
    "feed.now":刚才",
    "feed.whatup":您正在做什么？",
    "feed.upload":您的屏幕截图正在上传...",
    "feed.manage":管理信息提要",
    "feed.share":共享",
    "feed.addScreenshot":添加屏幕截图",
    "feed.comments":评论",
    "feed.edit":编辑",
    "feed.screenshots":屏幕截图",
    "feed.return":菜单",
    "feed.goToFeed":动态信息",
    "feed.cancel":取消",
    "feed.previous":上一个",
    "feed.next":下一个",
    "feed.delete":删除",
    "feed.deleted":已删除项",
    "feed.report_xbox":报告至 Xbox 执行",
    "feed.report_club":向俱乐部报告",
    "feed.clubdescription":Realm 描述",
    "feed.no_feed_item_content":将在此处显示 Realm 中的屏幕截图和讨论。按“新建帖子”开始操作",
    "feed.no_reported_item_content":未报告任何项",
    "feed.no_screenshot":您没有任何屏幕截图",
    "feed.reportToastMessage":已报告项",
    "feed.forbidden":未经授权发布到时间线",
    "feed.failedToPost":发布不成功",
    "feed.failedToPostDescription":无效的截图",
    "feed.uppload_started":正在上传截图",
    "feed.uppload_success":截图已上传",
    "feed.connected":每一个 Realm 都使用了您的 Microsoft 账户与俱乐部连接。",

}