stat: dict = {
    "stat.animalsBred":"繁殖动物次数",
    "stat.armorCleaned":"清洗过的护甲片",
    "stat.bannerCleaned":"清洗过的旗帜",
    "stat.beaconInteraction":"与信标互动",
    "stat.blocksButton":"方块",
    "stat.boatOneCm":"坐船移动距离",
    "stat.breakItem":"消耗了%1$s个工具",
    "stat.brewingstandInteraction":"与酿造台互动",
    "stat.cakeSlicesEaten":"吃过的蛋糕",
    "stat.cauldronFilled":"填满的炼药锅",
    "stat.cauldronUsed":"从炼药锅取出的水",
    "stat.chestOpened":"开过的箱子",
    "stat.climbOneCm":"已攀爬距离",
    "stat.crafted":"合成次数",
    "stat.craftItem":"合成了 %1$s 个物品",
    "stat.createWorld":"已创建的世界数",
    "stat.crouchOneCm":"潜行距离",
    "stat.damageDealt":"造成伤害",
    "stat.damageTaken":"受到伤害",
    "stat.deaths":"死亡次数",
    "stat.depleted":"工具消耗数",
    "stat.dispenserInspected":"搜索过的发射器",
    "stat.diveOneCm":"水下移动距离",
    "stat.drop":"物品掉落",
    "stat.dropperInspected":"搜索过的投掷器",
    "stat.enderchestOpened":"开过的末影箱",
    "stat.entityKilledBy":"%s 杀死了你 %d 次",
    "stat.entityKilledBy.none":"您从未被 %s 杀死",
    "stat.entityKills":"你杀死了 %d只 %s",
    "stat.entityKills.none":"你从来没有杀死过 %s",
    "stat.fallOneCm":"摔落高度",
    "stat.fishCaught":"捕鱼数",
    "stat.flowerPotted":"盆栽",
    "stat.flyOneCm":"飞行距离",
    "stat.furnaceInteraction":"与熔炉互动",
    "stat.generalButton":"通用",
    "stat.hopperInspected":"搜索过的漏斗",
    "stat.horseOneCm":"骑马移动距离",
    "stat.itemEnchanted":"附魔物品",
    "stat.itemsButton":"物品",
    "stat.joinMultiplayer":"加入多人游戏次数",
    "stat.jump":"跳跃次数",
    "stat.junkFished":"钓到垃圾次数",
    "stat.leaveGame":"游戏退出次数",
    "stat.loadWorld":"读取存档次数",
    "stat.mineBlock":"挖掘了 %1$s 个方块",
    "stat.minecartOneCm":"坐矿车移动距离",
    "stat.mined":"开采次数",
    "stat.mobKills":"生物击杀数",
    "stat.mobsButton":"生物",
    "stat.noteblockPlayed":"演奏过的音符盒",
    "stat.noteblockTuned":"调节过的音符盒",
    "stat.pigOneCm":"骑猪移动距离",
    "stat.playerKills":"玩家击杀数",
    "stat.playOneMinute":"游戏时间(分钟)",
    "stat.recordPlayed":"播放的唱片",
    "stat.sprintOneCm":"疾跑距离",
    "stat.startGame":"游戏次数",
    "stat.swimOneCm":"游泳距离",
    "stat.talkedToVillager":"村民交互次数",
    "stat.timeSinceDeath":"自上次死亡",
    "stat.tradedWithVillager":"村民交易次数",
    "stat.trappedChestTriggered":"陷阱箱触发次数",
    "stat.treasureFished":"钓到宝藏次数",
    "stat.used":"使用次数",
    "stat.useItem":"使用了 %1$s 个物品",
    "stat.walkOneCm":"行走距离",
    "stat.workbenchInteraction":"与工作台互动",

}