cloud_upload: dict = {
    "cloud_upload.title":"Mojang 玩家支持",
    "cloud_upload.prompt.description":"根据您最近的支持凭证，Mojang 玩家支持已经批准您上传自己的世界。您可以在世界选择屏幕或世界设置下上传受影响的世界。",
    "cloud_upload.prompt.do_not_show_toggle":"不再显示此窗口",
    "cloud_upload.prompt.button.worlds":"前往世界",
    "cloud_upload.prompt.button.learn_more":"了解更多",
    "cloud_upload.toggle.accept_terms":"接受微软服务协议",
    "cloud_upload.button.upload":"上传世界（%s）",
    "cloud_upload.button.service_agreement":"使用条款",
    "cloud_upload.button.privacy_statement":"隐私声明",
    "cloud_upload.terms.title":"条款和条件",
    "cloud_upload.terms.description":"要上传您的世界，请接受 Microsoft 服务协议。上传的世界受 Microsof 服务协议的约束，该协议可在使用条款中找到。上传后，您仍然可以玩您的世界。",
    "cloud_upload.uploading.title":"世界文件上传中 [%d/%d]",
    "cloud_upload.uploading.description_1":"上传您的世界文件可能需要几分钟的时间。在上传过程中，不要关闭游戏或离开此屏幕。",
    "cloud_upload.uploading.description_2":"世界的规模可能会很大。请使用 Wi-Fi，不要使用移动数据。",
    "cloud_upload.succeeded.description":"您的世界上传已成功。谢谢！",
    "cloud_upload.failed.retryable.description":"无法上传您的世界，因为 %s",
    "cloud_upload.failed.description":"无法上传您的世界，因为 %s",
    "cloud_upload.tts.message":"世界文件上传中",
    "cloud_upload.input_error_number_of_files":"您的世界文件过多。如果想重试，请与 LiveOps 联系。",
    "cloud_upload.input_error_maximum_size":"某个文件过大。如果想重试，请与 LiveOps 联系。",
    "cloud_upload.input_error_record_already_completed":"世界成功上传。请与 LiveOps 联系以获取更多信息。",
    "cloud_upload.operation_error_missing_files_on_complete_upload":"网络错误。请重试或与 LiveOps 联系。",
    "cloud_upload.unknown_error":"未知错误。请重试或与 LiveOps 联系。(错误代码：%s)",

}