commands: dict = {
    "commands.ability.description": "设置一名玩家的能力。",
    "commands.ability.noability": "不存在名为 '{}' 的技能",
    "commands.ability.granted": "已赋予你 '{}' 技能",
    "commands.ability.revoked": "已从你身上撤销 '{}' 技能",
    "commands.ability.success": "技能已更新",
    "commands.achievement.alreadyHave": "玩家 {} 已经获得了 {} 成就",
    "commands.achievement.description": "授予或删除某位玩家的成就。",
    "commands.achievement.dontHave": "玩家 {} 还未获得 {} 成就",
    "commands.achievement.give.success.all": "成功将所有成就授予 {}",
    "commands.achievement.give.success.one": "成功地给予了 {} 统计数据 {}",
    "commands.achievement.statTooLow": "玩家 {} 并没有统计数据 {}",
    "commands.achievement.take.success.all": "成功从 {} 中解锁了所有成就",
    "commands.achievement.take.success.one": "成功从 {} 中获得了统计数据 {}",
    "commands.achievement.unknownAchievement": "未知的成就或统计数据 '{}'",
    "commands.agent.attack.success": "代理机器人攻击成功",
    "commands.agent.attack.failed": "代理机器人攻击失败",
    "commands.agent.collect.success": "代理机器人收集成功",
    "commands.agent.collect.failed": "代理机器人收集失败",
    "commands.agent.createagent.success": "已创建代理机器人",
    "commands.agent.createagent.failed": "无法创建代理机器人",
    "commands.agent.destroy.success": "代理机器人摧毁了一个方块",
    "commands.agent.destroy.failed": "代理机器人摧毁失败",
    "commands.agent.detect.success": "代理机器人探测成功",
    "commands.agent.detect.failed": "代理机器人探测失败",
    "commands.agent.detectredstone.success": "代理机器人 detectredstone 成功",
    "commands.agent.detectredstone.failed": "代理机器人 detectredstone 失败",
    "commands.agent.drop.success": "代理机器人掉落成功",
    "commands.agent.drop.failed": "代理机器人掉落失败",
    "commands.agent.dropall.success": "代理机器人 dropall 成功",
    "commands.agent.dropall.failed": "代理机器人 dropall 失败",
    "commands.agent.getitemcount.success": "代理机器人 getitemcount 成功",
    "commands.agent.getitemcount.failed": "代理机器人 getitemcount 失败",
    "commands.agent.getitemspace.success": "代理机器人 getitemspace 成功",
    "commands.agent.getitemspace.failed": "代理机器人 getitemspace 失败",
    "commands.agent.getitemdetail.success": "代理机器人 getitemdetail 成功",
    "commands.agent.getitemdetail.failed": "代理机器人 getitemdetail 失败",
    "commands.agent.getposition.success": "代理机器人获得位置成功",
    "commands.agent.getposition.failed": "代理机器人获得位置失败",
    "commands.agent.inspect.success": "代理机器人检查成功",
    "commands.agent.inspect.failed": "代理机器人检查失败",
    "commands.agent.inspectdata.success": "代理检查数据成功",
    "commands.agent.inspectdata.failed": "代理检查数据失败",
    "commands.agent.move.success": "代理机器人移动成功",
    "commands.agent.move.failed": "无法移动代理机器人",
    "commands.agent.outofrange": "无法发出命令，代理机器人超出范围",
    "commands.agent.place.success": "代理机器人放置成功",
    "commands.agent.place.failed": "代理机器人放置失败",
    "commands.agent.setitem.success": "代理机器人设置物品成功",
    "commands.agent.setitem.failed": "代理机器人设置物品失败",
    "commands.agent.turn.success": "代理机器人转动成功",
    "commands.agent.turn.failed": "无法转动代理机器人",
    "commands.agent.till.success": "代理机器人耕种成功",
    "commands.agent.till.failed": "代理机器人耕种失败",
    "commands.agent.tpagent.description": "传送您的代理机器人。",
    "commands.agent.tpagent.success": "代理机器人已传送",
    "commands.agent.tpagent.failed": "代理机器人传送失败",
    "commands.agent.transfer.success": "代理机器人转移成功",
    "commands.agent.transfer.failed": "代理机器人转移失败",
    "commands.always.day": "昼夜更替 {}",
    "commands.always.day.locked": "昼夜更替已锁定",
    "commands.always.day.unlocked": "昼夜更替已解锁",
    "commands.ban.description": "将玩家添加到黑名单。",
    "commands.autocomplete.a": "所有玩家",
    "commands.autocomplete.c": "我的代理机器人",
    "commands.autocomplete.e": "所有实体",
    "commands.autocomplete.p": "最近的玩家",
    "commands.autocomplete.r": "随机玩家",
    "commands.autocomplete.s": "您自己",
    "commands.autocomplete.v": "所有代理机器人",
    "commands.ban.failed": "无法封禁玩家 {}",
    "commands.ban.success": "已封禁玩家 {}",
    "commands.banip.description": "将 IP 地址添加到黑名单。",
    "commands.banip.invalid": "你输入了一个无效的 IP 地址或者此玩家不在线",
    "commands.banip.success": "已封禁 IP 地址 {}",
    "commands.banip.success.players": "已封禁的 IP 地址 {} 属于 {}",
    "commands.banlist.ips": "总共有 {} 个被封禁的IP地址：",
    "commands.banlist.players": "总共有 {} 个被封禁的玩家：",
    "commands.blockdata.description": "修改方块的数据标签。",
    "commands.blockdata.placeFailed": "此处不能放置方块",
    "commands.blockdata.destroyFailed": "此处不能挖掘",
    "commands.blockdata.failed": "数据标签未更改：{}",
    "commands.blockdata.notValid": "目标模块不是数据持有模块",
    "commands.blockdata.outOfWorld": "无法更改世界外的方块",
    "commands.blockdata.success": "方块数据更新为：{}",
    "commands.blockdata.tagError": "数据标签解析失败：{}",
    "commands.blockstate.invalidState": "“{}”为无效方块状态。",
    "commands.blockstate.stateError": "方块状态：“{}”在此方块上无效：“{}”。",
    "commands.blockstate.typeError": "方块状态的无效值类型：“{}”。",
    "commands.blockstate.valueError": "方块状态的无效值：“{}”。",
    "commands.bossbar.add.success": "已创建自定义 Boss 条 [{}]",
    "commands.bossbar.add.failure.invalid": "无效的 Boss 条 ID。ID 应该为 namespace:id 或 id 形式（默认为《我的世界》namespace）。",
    "commands.bossbar.add.failure.exists": "一个 ID 为 '{}' 的 Boss 条已经存在",
    "commands.bossbar.description": "创建和修改 Boss 条",
    "commands.bossbar.get.max": "自定义 Boss 条 [{}] 最多有 {}",
    "commands.bossbar.get.players": "自定义 Boss 条 [{}] 当前有 {} 名玩家在线：{}",
    "commands.bossbar.get.players.none": "自定义 Boss 条 [{}] 当前没有玩家在线",
    "commands.bossbar.get.players.one": "自定义 Boss 条 [{}] 当前有 1 名玩家在线：{}",
    "commands.bossbar.get.value": "自定义 Boss 条 [{}] 有一个 {} 的值",
    "commands.bossbar.get.visible.true": "自定义 Boss 条 [{}] 当前显示",
    "commands.bossbar.get.visible.false": "自定义 Boss 条 [{}] 当前隐藏",
    "commands.bossbar.list": "有 {} 个自定义 Boss 条处于活跃状态：{}",
    "commands.bossbar.list.none": "没有自定义 Boss 条处于活跃状态",
    "commands.bossbar.list.one": "有 1 个自定义 Boss 条处于活跃状态：{}",
    "commands.bossbar.notFound": "ID 为 '{}' 的 Boss 条不存在",
    "commands.bossbar.remove": "已移除自定义 Boss 条 [{}]",
    "commands.change-setting.description": "当专用服务器运行时在上面更改设定。",
    "commands.change-setting.success": "{} 已更改",
    "commands.chunkinfo.compiled": "区块已编译。",
    "commands.chunkinfo.data": "前 64 个顶点为：{}",
    "commands.chunkinfo.empty": "区块是空的。",
    "commands.chunkinfo.hasLayers": "区块含有 {} 个层面",
    "commands.chunkinfo.hasNoRenderableLayers": "区块没有可渲染层。",
    "commands.chunkinfo.isEmpty": "区块有 {} 个空层面",
    "commands.chunkinfo.location": "区块位置：({}, {}, {})",
    "commands.chunkinfo.noChunk": "区块位置 {}, {}, {} 上未找到区块",
    "commands.chunkinfo.notCompiled": "区块未编译。",
    "commands.chunkinfo.notEmpty": "区块非空。",
    "commands.chunkinfo.vertices": "{} 层的缓冲包含了 {} 个点",
    "commands.classroommode.description": "尝试启动并连接到教室模式。",
    "commands.classroommode.success": "正在尝试启动教室模式……",
    "commands.clear.description": "清除玩家物品栏中的物品。",
    "commands.clear.failure": "无法清除 {} 的物品栏",
    "commands.clear.failure.no.items": "无法清除 {} 的物品栏，没有可清除的物品",
    "commands.clear.success": "清除了 {} 的物品栏，删除了 {} 个物品",
    "commands.clear.tagError": "数据标签解析失败：{}",
    "commands.clear.testing": "{} 有 {} 个与条件匹配的物品",
    "commands.clearfixedinv.description": "移除所有固定物品栏槽位。",
    "commands.clearfixedinv.success": "已清除固定物品栏",
    "commands.clone.description": "将一个地区的方块克隆到另一个地区。",
    "commands.clone.failed": "未复制方块",
    "commands.clone.filtered.error": "过滤用法需要选定一个过滤方块",
    "commands.clone.noOverlap": "源坐标和目标坐标不能重叠",
    "commands.clone.success": "{} 个方块已复制",
    "commands.clone.tooManyBlocks": "选定区域内的方块太多 ({} > {})",
    "commands.closechat.description": "会关闭本地玩家打开状态下的聊天窗口。",
    "commands.closechat.success": "聊天已关闭",
    "commands.closechat.failure": "聊天未打开",
    "commands.closewebsocket.description": "如有 WebSocket 连接时将其关闭。",
    "commands.code.description": "启动代码编辑器。",
    "commands.code.success": "已启动代码编辑器。",
    "commands.compare.failed": "源坐标和目标坐标不相同",
    "commands.compare.success": "已比较 {} 个方块",
    "commands.compare.tooManyBlocks": "选定区域内的方块太多 ({} > {})",
    "commands.compactdb.description": "明确压缩 levelDB 记录。",
    "commands.compactdb.success": "已成功压缩 levelDB 记录。",
    "commands.corruptworld.description": "破坏服务器上加载的世界。",
    "commands.corruptworld.success": "被成功破坏的世界。",
    "commands.damage.description": "对指定实体实施伤害。",
    "commands.damage.specify.damage": "请指定有效的伤害值。",
    "commands.damage.success": "已对 {} 实施伤害",
    "commands.damage.failed": "无法对 {} 实施伤害",
    "commands.damage.tooManySources": "只能有一个源实体。请调整您的选择器，将选择限定到一个实体上。",
    "commands.daylock.description": "锁定和解锁昼夜更替。",
    "commands.debug.description": "启动或停止调试会话。",
    "commands.debug.notStarted": "尚未开始，无法停止分析！",
    "commands.debug.start": "开始调试分析",
    "commands.debug.stop": "在 {} 秒 ({} 刻) 后停止调试分析",
    "commands.defaultgamemode.description": "设置默认的游戏模式。",
    "commands.defaultgamemode.success": "世界的默认游戏模式现为 {}",
    "commands.deop.description": "撤销一名玩家的操作员状态。",
    "commands.deop.failed": "无法撤销（权限级别过高）：{}",
    "commands.deop.success": "已夺去 {} 的管理员权限",
    "commands.deop.message": "你已被夺去 OP 权限",
    "commands.dialogue.description": "为用户开启非用户角色对话。",
    "commands.dialogue.changeFailed": "无法更改非用户角色的场景。",
    "commands.dialogue.changeSuccess": "对话成功地为全局内的非用户角色改变了场景。",
    "commands.dialogue.changePerPlayerSuccess": "对话成功地为{}内的非用户角色改变了场景。",
    "commands.dialogue.invalidScene": "引用了无效的场景。",
    "commands.dialogue.noNpcComponent": "选定的演员没有非用户角色组件。",
    "commands.dialogue.npcNotFound": "无法找到非用户角色。",
    "commands.dialogue.npcNotInRange": "已发现一个非用户角色，但不在接收用户 {} 的勾选范围内。",
    "commands.dialogue.success": "对话已发送至 {}。",
    "commands.dialogue.tooManyNPCs": "非用户角色的选择器不明确，导致选项太多。请只选择一个非用户角色。",
    "commands.difficulty.description": "设置难度等级。",
    "commands.difficulty.usage": "/difficulty ",
    "commands.difficulty.success": "将游戏难度设置为 {}",
    "commands.downfall.success": "天气已切换",
    "commands.effect.description": "添加或删除状态效果。",
    "commands.effect.failure.notActive": "无法从 {} 身上消除 {}，因为没有此效果",
    "commands.effect.failure.notActive.all": "无法从 {} 身上消除任何效果，因为什么效果都没有",
    "commands.effect.failure.notAMob": "{} 不能拥有效果",
    "commands.effect.notFound": "没有 ID 为 {} 的生物状态效果",
    "commands.effect.success": "给予 {} 时长为 {} 秒的 {} * {} 效果",
    "commands.effect.success.removed": "消除了 {} 身上的 {}",
    "commands.effect.success.removed.all": "已消除 {} 身上的全部效果",
    "commands.enchant.cantCombine": "{} 无法和 {} 结合",
    "commands.enchant.invalidLevel": "{} 不支持等级 {}",
    "commands.enchant.cantEnchant": "不能向目标物品添加选定附魔：{}",
    "commands.enchant.description": "对玩家选定的物品增加一项附魔",
    "commands.enchant.noItem": "目标没有拿着物品：{}",
    "commands.enchant.notFound": "没有 ID 为 {} 的魔咒",
    "commands.enchant.success": "{} 附魔成功",
    "commands.entitydata.description": "修改实体的数据标签。",
    "commands.entitydata.failed": "数据标签未更改：{}",
    "commands.entitydata.noPlayers": "{} 是一位玩家，不能更改",
    "commands.entitydata.success": "实体数据已更新：{}",
    "commands.entitydata.tagError": "数据标签解析失败：{}",
    "commands.event.description": "触发指定对象的事件",
    "commands.event.error.empty": "事件名称不能为空",
    "commands.event.error.failed": "{} 无法在下列实体中执行：{}",
    "commands.event.success": "{} 成功在下列实体中执行：{}",
    "commands.execute.allInvocationsFailed": "全部调用失败：'{}'",
    "commands.execute.failed": "将 '{}' 执行为 {} 失败",
    "commands.execute.description": "代表一个或多个实体执行命令",
    "commands.execute.outRangedDetectPosition": "检测位置： {} {} {} 超出范围。",
    "commands.execute.falseCondition": "执行子命令 {} {} 解析出 FALSE。",
    "commands.fill.description": "用特定方块填充全部或部分地区。",
    "commands.fill.failed": "未填充方块",
    "commands.fill.outOfWorld": "无法在世界外放置方块",
    "commands.fill.success": "{} 个方块已填充",
    "commands.fill.tagError": "数据标签解析失败：{}",
    "commands.fill.tooManyBlocks": "选定区域内的方块太多 ({} > {})",
    "commands.fill.replace.auxvalue.invalid": "方块 {} 的替换数据值无效",
    "commands.fog.description": "添加或移除迷雾设置文件",
    "commands.fog.invalidFogId": "无效的迷雾设置 Id：{}",
    "commands.fog.invalidUserId": "未找到 id 为 {} 的迷雾设置文件",
    "commands.fog.limitReached": "{} 的迷雾标识达到尺寸上限",
    "commands.fog.success.pop": "已成功将最后一次推送的 id 为 {} 的迷雾设置从 {} 中移除",
    "commands.fog.success.push": "已成功将 id 为 {} 的迷雾设置添加至 {}",
    "commands.fog.success.remove": "已成功将 id 为 {} 的迷雾设置从 {} 中移除",
    "commands.function.description": "运行在相应的功能文件中找到的命令。",
    "commands.function.functionNameNotFound": "未找到 {} 功能。",
    "commands.function.invalidCharacters": "标题为“{}”的函数无效，函数名称中不允许使用字符“{}”。",
    "commands.function.noEngineVersionSpecified": "无法运行 {} 功能。您必须在行为包的 manifest.json 上指定一个 min_engine_version。",
    "commands.function.success": "成功执行 {} 个功能项。",
    "commands.gamemode.description": "设置一名玩家的游戏模式。",
    "commands.gamemode.success.other": "将 {} 的游戏模式设置为 {}",
    "commands.gamemode.success.self": "将自己的游戏模式设置为 {}",
    "commands.gamemode.fail.invalid": "游戏模式 '{}' 无效",
    "commands.gamerule.description": "设置或查询游戏规则价值。",
    "commands.gamerule.type.invalid": "无效的游戏规则类型 '{}'",
    "commands.gamerule.type.nocheatsenabled": "只有这个世界启用作弊时，游戏规则 '{}' 才能使用。",
    "commands.gamerule.nopermission": "只有服务器所有人才能修改 '{}'",
    "commands.gamerule.norule": "不存在叫做 '{}' 的游戏规则",
    "commands.gamerule.success": "游戏规则 {} 已更新为 {}",
    "commands.generic.async.initiated": "'{}' 的命令已开始（异步步骤 {}）",
    "commands.generic.boolean.invalid": "'{}' 不是个布尔值参数",
    "commands.generic.chunk.notFound": "未找到指定区块",
    "commands.generic.componentError": "组件列表解析失败",
    "commands.generic.dimension.notFound": "未找到指定维度",
    "commands.generic.disabled": "此世界未启用无敌模式。",
    "commands.generic.disabled.templateLocked": "设置当前已锁定。您可以在“游戏设置”菜单中解锁“模板世界选项”来更改它们。",
    "commands.generic.double.tooBig": "你输入的数字 ({}) 太大了，最高只能为 {}",
    "commands.generic.double.tooSmall": "你输入的数字 ({})太小了，至少需要为 {}",
    "commands.generic.duplicateType": "重复的类型参数",
    "commands.generic.duplicateSelectorArgument": "重复的 {} 选择器参数",
    "commands.generic.encryption.badkey": "提供的公钥错误。PEM 格式化之后预期为 120 字节的密钥。",
    "commands.generic.encryption.badsalt": "提供的加密盐错误。基础的 64 编码之前预期为 16 字节。",
    "commands.generic.encryption.required": "需要加密的会话",
    "commands.generic.entity.invalidType": "实体类型 '{}' 是无效的",
    "commands.generic.entity.invalidUuid": "提供的实体 UUID 格式无效",
    "commands.generic.entity.notFound": "无法找到此实体",
    "commands.generic.exception": "在执行此指令时出现了未知的错误",
    "commands.generic.invalidAgentType": "适用于仅 代理机器人选择器的类型参数",
    "commands.generic.invalidcontext": "对给定命令类型的上下文无效",
    "commands.generic.invalidDevice": "您输入的命令 {} 在此设备上不受支持",
    "commands.generic.invalidPlayerType": "适用于仅玩家选择器的类型参数",
    "commands.generic.invalidType": "未知的类型参数",
    "commands.generic.levelError": "最高等级必须高于最低等级",
    "commands.generic.malformed.body": "正文缺失或变形",
    "commands.generic.malformed.type": "无效请求类型",
    "commands.generic.notimplemented": "未执行",
    "commands.generic.num.invalid": "'{}' 不是一个有效的数字",
    "commands.generic.num.tooBig": "你输入的数字 ({}) 太大了，它最高只能为 {}",
    "commands.generic.num.tooSmall": "你输入的数字 ({}) 太小了，它至少需要为 {}",
    "commands.generic.outOfWorld": "无法访问世界外的方块",
    "commands.generic.parameter.invalid": "'{}' 为无效参数",
    "commands.generic.permission.selector": "<选择器扩展权限不足>",
    "commands.generic.player.notFound": "无法找到该玩家",
    "commands.generic.protocol.mismatch": "所提供的协议版本与《我的世界》协议版本不符",
    "commands.generic.radiusError": "最小选择器半径必须小于最大选择器半径",
    "commands.generic.radiusNegative": "半径不能为负数",
    "commands.generic.rotationError": "旋转值超出范围",
    "commands.generic.running": "命令已在运行",
    "commands.generic.step.failed": "命令步骤失败",
    "commands.generic.syntax": "语法错误：意外的“{}”：出现在“{}>>{}<<{}”",
    "commands.generic.noTargetMatch": "没有与选择器匹配的目标",
    "commands.generic.targetNotPlayer": "选择器必须为玩家类型",
    "commands.generic.tooManyNames": "目标名称参数过多",
    "commands.generic.tooManyTargets": "与选择器匹配的目标过多",
    "commands.generic.too.many.requests": "已请求太多指令，请等待一个指令完成",
    "commands.generic.unknown": "未知的命令：{}。请检查命令是否存在，以及您对它是否拥有使用权限。",
    "commands.generic.usage": "用法：{}",
    "commands.generic.usage.noparam": "使用：",
    "commands.generic.version.mismatch": "该指令不存在请求的版本",
    "commands.generic.version.missing": "来自聊天框以外的命令调用应指定命令版本",
    "commands.getchunkdata.description": "获取特定区块的像素。",
    "commands.getchunkdata.success": "区块数据已接收",
    "commands.getchunks.description": "获取已加载的区块列表。",
    "commands.getchunks.success": "区块列表已接收",
    "commands.getlocalplayername.description": "返回本地玩家名称。",
    "commands.getspawnpoint.description": "获取特定玩家的生成位置。",
    "commands.gettopsolidblock.description": "会获得特定位置下方的顶部非空气方块的位置",
    "commands.gettopsolidblock.notfound": "特定位置下方没有固体方块",
    "commands.give.block.notFound": "没有这种 {} 名字的方块",
    "commands.give.description": "将物品给予一名玩家。",
    "commands.give.item.invalid": "命令语法无效: 不存在具有该数值的 {}",
    "commands.give.item.notFound": "没有这种 {} 名字的物品",
    "commands.give.map.invalidData": "提供的地图数据无效",
    "commands.give.map.featureNotFound": "无法制作探险地图。在此维度上找不到特征",
    "commands.give.success": "给予 {}  {} * {} 效果",
    "commands.give.successRecipient": "你已被给予 {} * {}",
    "commands.give.tagError": "数据标签解析失败：{}",
    "commands.hasitem.fail.invalidData": "“数据”有无效输入，必须为整数。",
    "commands.hasitem.fail.invalidQuantity": "“数量”有无效输入，必须为整数或一系列整数。",
    "commands.hasitem.fail.invalidSlot": "“栏位”有无效输入，必须为整数或一系列整数。",
    "commands.hasitem.fail.noItem": "“物品”缺失，“hasitem”过滤器需要此参数。",
    "commands.hasitem.fail.slotNoLocation": "如果没有给出“位置”，则指定“栏位”将无效。",
    "commands.help.description": "提供帮助/命令列表。",
    "commands.help.footer": "小提示： 在输入命令时可以使用    键来自动补全命令或参数",
    "commands.help.header": "--- 显示帮助手册总 {} 页中的第 {}  页 (/help <页码>) ---",
    "commands.help.command.aliases": "{}（也称为 {}）：",
    "commands.immutableworld.description": "设置世界的不可变状态。",
    "commands.immutableworld.info": "immutableworld = {}",
    "commands.kick.description": "从服务器踢出一名玩家。",
    "commands.kick.description.edu": "会从游戏中移除一位玩家。",
    "commands.kick.no.player": "请提供您想要踢出的玩家的名称",
    "commands.kick.not.found": "无法找到玩家 {}",
    "commands.kick.not.yourself": "您无法将自己从游戏中移除",
    "commands.kick.success": "已将 {} 踢出游戏",
    "commands.kick.success.reason": "已将 {} 踢出游戏：'{}'",
    "commands.kick.success.reasonedu": "已将 {} 移除出游戏：'{}'",
    "commands.kick.no.host": "主办者不会被踢出游戏。",
    "commands.kick.no.teacher": "不能将教师从游戏中移除。",
    "commands.kill.successful.edu": "已移除 {}",
    "commands.kill.successful": "已清除 {}",
    "commands.kill.description.edu": "移除实体（玩家、生物等）。",
    "commands.kill.description": "击杀实体（玩家、生物等）。",
    "commands.list.description": "列出服务器上的玩家。",
    "commands.locate.description": "显示距离最近的给定类型的建筑位置。",
    "commands.locate.fail.noplayer": "命令只能由有效玩家使用",
    "commands.locate.fail.nostructurefound": "此维度中未找到有效结构",
    "commands.locate.success": "最近的 {} 位于方块 {}, (y?), {}",
    "commands.loot.description": "将特定的战利品表放入指定的物品栏或世界中。",
    "commands.loot.failure.invalidLootTable": "战利品表 '{}' 未找到",
    "commands.loot.failure.mainhandOffhandOnNonEntity": "主手槽位或副手槽位不能用于非实体对象。",
    "commands.loot.failure.entityNoLootTable": "实体 {} 没有战利品表",
    "commands.loot.failure.noContainer": "在目标位置 {} 上的不是一个容器",
    "commands.loot.success": "{} 物品已掉落。",
    "commands.togglecontentlog.toggle": "开启/关闭内容日志命令",
    "commands.togglecontentlog.enabled": "内容日志已开启",
    "commands.togglecontentlog.disabled": "内容日志已关闭",
    "commands.me.description": "显示一条关于您自己的消息。",
    "commands.message.display.incoming": "{} 悄悄地对你说：{}",
    "commands.message.display.outgoing": "你悄悄地对 {} 说：{}",
    "commands.message.sameTarget": "你不能向自己发出私人信息！",
    "commands.mobevent.description": "会控制允许哪些生物事件运行。",
    "commands.mobevent.eventsEnabledSetToTrue": "生物事件已启用。设置为 \"false\" 的单独事件将不会运行。",
    "commands.mobevent.eventsEnabledSetToFalse": "生物事件已禁用。单独事件将不会运行。",
    "commands.mobevent.eventsEnabledIsTrue": "生物事件已启用。设置为 \"false\" 的单独事件将不会运行。",
    "commands.mobevent.eventsEnabledIsFalse": "生物事件已启用。设置为 \"false\" 的单独事件将不会运行。",
    "commands.mobevent.eventSetToTrue": "生物事件{} (id:{}) 设置为 \"true\"。",
    "commands.mobevent.eventSetToTrueButEventsDisabled": "生物事件{} (id:{}) 设置为 \"true\"，但是生物事件已禁用。",
    "commands.mobevent.eventSetToFalse": "生物事件{} (id:{}) 设置为 \"false\"。",
    "commands.mobevent.eventIsTrue": "生物事件{} (id:{}) 设置为 \"true\"。",
    "commands.mobevent.eventIsTrueButEventsDisabled": "生物事件{} (id:{}) 设置为 \"true\"，但是生物事件已禁用。",
    "commands.mobevent.eventIsFalse": "生物事件{} (id:{}) 设置为 \"false\"。",
    "commands.music.description": "允许您控制正在播放的音乐曲目。",
    "commands.music.failure.emptyTrackName": "您必须输入一个不为空的曲目名称。",
    "commands.music.success.queueAction": "{} 已加入播放序列，将在当前曲目停止后开始播放。",
    "commands.music.success.playAction": "{} 已加入播放序列。",
    "commands.music.success.stopAction": "自定义音乐即将停止。",
    "commands.music.success.volumeAction": "音乐音量更新为 {}。",
    "commands.op.description": "授予一名玩家操作员状态。",
    "commands.op.failed": "无法夺得权限（已夺得或具有更高权限）：{}",
    "commands.op.success": "已将 {} 设为管理员",
    "commands.op.message": "你已夺得权限",
    "commands.origin.commandblock": "命令方块",
    "commands.origin.external": "外部",
    "commands.origin.devconsole": "DevConsole",
    "commands.origin.script": "脚本引擎",
    "commands.origin.server": "服务器",
    "commands.origin.teacher": "老师",
    "commands.ops.description": "重新加载并应用权限许可。",
    "commands.ops.reloaded": "已从文件重新加载权限。",
    "commands.ops.set.success": "为玩家{}设置操作员级别成功。",
    "commands.permissions.description": "重新加载并应用许可。",
    "command.permissions.list.fail.filenotfound": "从文件列出权限失败，文件未找到。",
    "commands.permissions.reloaded": "已从文件重新加载许可。",
    "command.permissions.reload.fail.filenotfound": "从文件重新加载权限失败，文件未找到。",
    "commands.permissions.set.failed": "无法将权限级别{}设置给玩家{}。",
    "commands.permissions.set.success": "将权限级别{}设置给玩家{}成功。",
    "commands.permissions.save.failed": "无法将权限级别{}保存给玩家{}。",
    "commands.permissions.save.success": "将权限级别{}保存给玩家{}成功。",
    "commands.spawnParticleEmitter.description": "制作一个粒子发射器",
    "commands.spawnParticleEmitter.success": "创建 {} 的请求已发送给所有玩家。",
    "commands.particle.description": "创建粒子。",
    "commands.particle.notFound": "未知的效果名称 ({})",
    "commands.particle.success": "播放 {} 效果 {} 次",
    "commands.playanimation.description": "使一个或多个实体播放一次性动画。假设所有变量都设置正确。",
    "commands.playanimation.success": "动画请求已发送至客户端进行处理。",
    "commands.players.list": "目前有 {}/{} 个玩家在线：",
    "commands.players.list.names": "{}",
    "commands.playsound.description": "播放声音。",
    "commands.playsound.playerTooFar": "玩家 {} 离得太远了，无法听到这声音",
    "commands.playsound.success": "向 {} 播放声音 '{}",
    "commands.position.description": "打开/关闭玩家的坐标。",
    "commands.publish.failed": "无法建立本地游戏",
    "commands.publish.started": "本地游戏已在端口 {} 上开启",
    "commands.querytarget.description": "获取单个或多个给定目标实体的转型、名称和 id 信息。",
    "commands.querytarget.success": "目标数据：{}",
    "commands.reload.description": "从所有行为包中重新加载所有功能文件。",
    "commands.reload.success": "现有功能文件已重新加载。重启《我的世界》以重新加载新功能。",
    "commands.replaceitem.description": "替换物品栏中的物品。",
    "commands.replaceitem.failed": "无法将 {} 号物品栏的物品 {} 替换成 {} * {}",
    "commands.replaceitem.keepFailed": "已有一个物品占用 {} 物品栏 {}。",
    "commands.replaceitem.noContainer": "位于 {} 的方块不是容器",
    "commands.replaceitem.badSlotNumber": "无法替换槽位 {}，必须是 {} 和 {} 之间的值。",
    "commands.replaceitem.success": "将 {} 号物品栏的物品 {} 替换为了 {} * {}",
    "commands.replaceitem.success.entity": "已将 {} 的 {} 槽位中的 {} 替换为 {} * {}",
    "commands.replaceitem.tagError": "数据标签解析失败：{}",
    "commands.ride.description": "使实体骑乘其他实体，使实体停止骑乘，使坐骑驱赶骑手，或召唤坐骑或骑手。",
    "commands.ride.evictRiders.success": "成功驱赶骑手的坐骑：{}",
    "commands.ride.startRiding.failure": "不符合骑乘条件的骑手：{}",
    "commands.ride.startRiding.groupDoesntFit": "这群骑手不符合坐骑。",
    "commands.ride.startRiding.notRideable": "所选实体无法骑乘。",
    "commands.ride.startRiding.rideFull": "此坐骑已经满员。",
    "commands.ride.startRiding.rideFullRidersLeft": "此坐骑已经满员，未能添加某些骑手。",
    "commands.ride.startRiding.success": "成功添加至坐骑的骑手：{}",
    "commands.ride.startRiding.tooManyRiders": "指定的骑手太多。对于 teleport_ride 来说一次只能有一名骑手。",
    "commands.ride.startRiding.tooManyRides": "指定的骑手太多。一次只能有一名骑手。",
    "commands.ride.stopRiding.success": "已成功停止骑乘的骑手：{}",
    "commands.ride.summonRide.failed": "坐骑已被召唤，但这些骑手无法添加至坐骑：{}",
    "commands.ride.summonRide.notRideable": "实体已被召唤，但无法骑乘。",
    "commands.ride.summonRide.success": "这些骑手成功召唤的坐骑：{}",
    "commands.ride.summonRider.failed": "骑手已被召唤，但无法添加至坐骑：{}",
    "commands.ride.summonRider.fullRides": "骑手无法添加至这些满员的坐骑：{}",
    "commands.ride.summonRider.ridesWithNoRideableComp": "以下实体无法骑乘：{}",
    "commands.ride.summonRider.success": "坐骑成功召唤的骑手：{}",
    "commands.say.description": "在聊天框中向其他玩家发送信息。",
    "commands.schedule.delay.functionQueued": "在游戏时间为 {} 的一瞬间，在 {} 执行函数 {}。",
    "commands.schedule.delay.negativeTime": "时间不能为负数。",
    "commands.schedule.description": "当加载一个区域，或在一定时间后，安排一个执行的动作。",
    "commands.schedule.functionQueued": "功能已在队列中，将在指定区域完全加载后执行。",
    "commands.schedule.functionRan": "成功在功能 {} 中执行 {} 个功能项。",
    "commands.schedule.invalidOrigin": "执行此函数所需的源无效。",
    "commands.schedule.name.empty": "常加载区域名称不能为空。",
    "commands.schedule.too.many.areas": "发现多个名称为 {} 的常加载区域。请使用单个区域。",
    "commands.scoreboard.description": "跟踪和显示各种目标的得分。",
    "commands.scoreboard.allMatchesFailed": "没有匹配的对象",
    "commands.scoreboard.noMultiWildcard": "仅允许使用一个用户通配符",
    "commands.scoreboard.objectiveNotFound": "没有找到名称为 '{}' 的目标",
    "commands.scoreboard.objectiveReadOnly": "无法设置只读目标 '{}'",
    "commands.scoreboard.objectives.add.alreadyExists": "已存在名为 '{}' 的目标",
    "commands.scoreboard.objectives.add.displayTooLong": "'{}' 作为目标的显示名太长了，它最多只能有 {} 个字",
    "commands.scoreboard.objectives.add.success": "已成功添加新目标 '{}'",
    "commands.scoreboard.objectives.add.tooLong": "'{}' 作为目标名太长了，它最多只能有 {} 个字",
    "commands.scoreboard.objectives.add.wrongType": "无效的目标标准类型 '{}'",
    "commands.scoreboard.objectives.add.needName": "目标需要一个名称。",
    "commands.scoreboard.objectives.description": "修改记分板目标。",
    "commands.scoreboard.objectives.list.count": "记分板正在显示 {} 个目标",
    "commands.scoreboard.objectives.list.empty": "记分板上没有目标",
    "commands.scoreboard.objectives.list.entry": "- {}：显示为 '{}'，类型为 '{}'",
    "commands.scoreboard.objectives.remove.success": "成功地移除了目标 '{}'",
    "commands.scoreboard.objectives.setdisplay.invalidSlot": "没有名称为 '{}' 的显示区",
    "commands.scoreboard.objectives.setdisplay.successCleared": "已清空目标显示区 '{}'",
    "commands.scoreboard.objectives.setdisplay.successSet": "将显示区中的显示目标从 '{}' 设置为 '{}'",
    "commands.scoreboard.players.add.success": "已为 {} 添加{} 到 [{}] （现在为 {}）",
    "commands.scoreboard.players.add.multiple.success": "已为 {} 项目添加{} 到 [{}]",
    "commands.scoreboard.players.nameNotFound": "必须提供玩家姓名。",
    "commands.scoreboard.players.enable.noTrigger": "目标 {} 不是触发因子",
    "commands.scoreboard.players.enable.success": "已对 {} 启用触发因子 {}",
    "commands.scoreboard.players.list.count": "记分板上正在显示 {} 个被追踪的玩家：",
    "commands.scoreboard.players.list.empty": "记分板上没有追踪的玩家",
    "commands.scoreboard.players.list.player.count": "正在为 {} 显示 {} 个追踪目标：",
    "commands.scoreboard.players.list.player.empty": "玩家 {} 没有分数记录",
    "commands.scoreboard.players.list.player.entry": "- {}: {} ({})",
    "commands.scoreboard.players.operation.invalidOperation": "操作 {} 无效",
    "commands.scoreboard.players.operation.notFound": "未找到 {} 的 {} 分数",
    "commands.scoreboard.players.operation.success": "已为 {} 项目更新 [{}]",
    "commands.scoreboard.players.offlinePlayerName": "玩家离线",
    "commands.scoreboard.players.random.invalidRange": "最小值 {} 不小于最大值 {}",
    "commands.scoreboard.players.remove.success": "已为 {} 从 [{}] 中移除 {}（现在为 {}）",
    "commands.scoreboard.players.remove.multiple.success": "已为 {} 项目从 [{}] 中移除 {}",
    "commands.scoreboard.players.reset.success": "已重置玩家 {} 的分数",
    "commands.scoreboard.players.resetscore.success": "已重置玩家 {} 的 {} 分数",
    "commands.scoreboard.players.set.success": "将 {} 的 [{}] 设定为 {}",
    "commands.scoreboard.players.set.multiple.success": "将 {} 的 [{}] 设定为 {}",
    "commands.scoreboard.players.set.tagError": "无法解析数据标签，原因：{}",
    "commands.scoreboard.players.set.tagMismatch": "数据标签与 {} 不匹配",
    "commands.scoreboard.players.score.notFound": "未找到 {} 的 {} 分数",
    "commands.scoreboard.players.test.failed": "分数 {} 不在 {} 到 {} 范围内",
    "commands.scoreboard.players.test.success": "分数 {} 在 {} 到 {} 范围内",
    "commands.scoreboard.players.get.success": "{}",
    "commands.seed.success": "种子：{}",
    "commands.setblock.description": "将一个方块更改为另一种方块。",
    "commands.setblock.failed": "无法放置方块",
    "commands.setblock.noChange": "该方块无法放置",
    "commands.setblock.notFound": "没有 ID/名称为 {} 的方块",
    "commands.setblock.outOfWorld": "无法在世界外放置方块",
    "commands.setblock.success": "方块已放置",
    "commands.setblock.tagError": "数据标签解析失败：{}",
    "commands.setidletimeout.success": "成功地将空闲时限设为 {} 分钟。",
    "commands.setfixedinvslots.description": "设置服务器的固定物品栏槽位。",
    "commands.setfixedinvslots.success": "固定物品栏槽位设置为 {}",
    "commands.setfixedinvslot.description": "将固定槽位设置为特定物品。",
    "commands.setfixedinvslot.success": "固定物品栏槽位 {} 设置为 {}",
    "commands.globalpause.description": "设置或取得所有玩家的全游戏暂停状态。",
    "commands.globalpause.success": "已设置或取得暂停状态",
    "commands.setmaxplayers.description": "设置此游戏会话的最大玩家数量。",
    "commands.setmaxplayers.success": "设置最大玩家数为 {}。",
    "commands.setmaxplayers.success.upperbound": "（绑定到最大允许连接数）",
    "commands.setmaxplayers.success.lowerbound": "（绑定到当前玩家数）",
    "commands.setworldspawn.description": "设置世界的生成。",
    "commands.setworldspawn.success": "将世界的生成点设置为 ({}, {}, {})",
    "commands.setworldspawn.wrongDimension": "不能在这个维度设置世界生成",
    "commands.setworldspawn.notAllowedInLegacyWorlds": "不能在旧的世界设置世界生成",
    "commands.spawnpoint.success.single": "将 {}'s 的生成点设置为 ({}, {}, {})",
    "commands.spawnpoint.description": "设置玩家的生成点。",
    "commands.spawnpoint.success.multiple.specific": "将 {} 的生成点设置为 ({}, {}, {})",
    "commands.spawnpoint.success.multiple.generic": "设置 {} 的生成点",
    "commands.spawnpoint.wrongDimension": "不能在这个维度设置出生点",
    "commands.clearspawnpoint.success.single": "{} 的生成点已移除",
    "commands.clearspawnpoint.description": "移除玩家的生成点。",
    "commands.clearspawnpoint.success.multiple": "{} 的生成点已移除",
    "commands.spreadplayers.description": "将实体传送到随机位置。",
    "commands.spreadplayers.failure.players": "无法将 {} 个玩家扩散至 {},{} 周围（玩家数量过多 - 最大玩家数为 {}）",
    "commands.spreadplayers.failure.players.unsafe": "无法将 {} 个玩家扩散至 {},{} 周围（经过 {} 次尝试后没有找到安全的位置）",
    "commands.spreadplayers.failure.teams": "无法将 {} 个队伍扩散至 {},{} 周围（玩家数量过多 - 最大队伍数为 {}）",
    "commands.spreadplayers.info.players": "(玩家间的平均距离在迭代 {} 次后为 {} 个方块)",
    "commands.spreadplayers.info.teams": "(队伍间的平均距离在迭代 {} 次后为 {} 个方块)",
    "commands.spreadplayers.spreading.players": "正在将 {} 个玩家扩散至距离 {},{} 周围 {} 个方块（最小距离 {} 个方块）",
    "commands.spreadplayers.spreading.teams": "正在将 {} 个队伍扩散至距离 {},{} 周围 {} 个方块（最小距离 {} 个方块）",
    "commands.spreadplayers.success.players": "已将 {} 个玩家成功扩散至 {},{} 周围",
    "commands.spreadplayers.success.teams": "已将 {} 个队伍成功扩散至 {},{} 周围",
    "commands.stats.cleared": "已清除 {} 的统计信息",
    "commands.stats.failed": "无效的参数",
    "commands.stats.noCompatibleBlock": "无法对 {}, {}, {} 坐标的方块跟踪统计",
    "commands.stats.success": "正在将 {} 的统计信息储存在 {} 的 {} 上",
    "commands.stop.description": "关闭服务器。",
    "commands.stop.start": "正在关闭服务器",
    "commands.stopsound.description": "停止播放声音。",
    "commands.stopsound.success": "停止 {} 声音，持续 {}",
    "commands.stopsound.success.all": "停止所有声音，持续 {}",
    "commands.structure.description": "在世界中保存或加载一个结构。",
    "commands.structure.empty.load": "无法加载没有实体和方块的结构",
    "commands.structure.empty.save": "无法保存没有实体和方块的结构",
    "commands.structure.invalid.animationTime": "动画时间必须大于等于 0",
    "commands.structure.invalid.integrity": "完整性必须在 0 到 100 之间取值",
    "commands.structure.invalid.name": "名称应采用“名称”或“命名空间：名称”的格式。如果未提供命名空间，则将分配默认命名空间。",
    "commands.structure.load.success": "已加载名称为 {} 的结构",
    "commands.structure.load.queued": "放置请求已在队列中，将在指定区域完全加载后执行。",
    "commands.structure.notFound": "找不到 {} 结构。请确保名称拼写正确，随后重试。",
    "commands.structure.save.success": "已保存名称为 {} 的结构",
    "commands.structure.size.tooBig": "结构的大小不能大于 ({}, {}, {})，曾经是 ({}, {}, {})",
    "commands.structure.size.tooSmall": "结构的大小不能小于 ({}, {}, {})，曾经是 ({}, {}, {})",
    "commands.structure.unknown.action": "已提供未知的结构操作",
    "commands.structure.unloadedChunks": "在未加载区域中加载结构的功能尚未实现",
    "commands.structure.y.tooHigh": "无法在世界外放置方块。请尝试为  的 Y 组成部分输入 {} 或更低的数值。",
    "commands.structure.y.tooLow": "无法在世界外放置方块。请尝试为  的 Y 组成部分输入一个大于 {} 的数值。",
    "commands.structure.delete.success": "结构 {} 已删除。",
    "commands.summon.description": "召唤一个实体。",
    "commands.summon.failed": "无法召唤对象",
    "commands.summon.outOfWorld": "无法在世界外召唤对象",
    "commands.summon.success": "对象已成功召唤",
    "commands.summon.tagError": "数据标签解析失败：{}",
    "commands.tag.description": "管理存储在实体中的标签。",
    "commands.tag.add.failed": "目标已有该标签，或已有太多标签",
    "commands.tag.add.success.single": "已添加标签“{}” 至 {}",
    "commands.tag.add.success.multiple": "已添加标签“{}” 至 {} 个实体",
    "commands.tag.list.single.empty": "{} 没有标签",
    "commands.tag.list.single.success": "{} 有 {} 个标签：{}",
    "commands.tag.list.multiple.empty": "{} 个实体上没有标签",
    "commands.tag.list.multiple.success": "{} 个实体上总计有 {} 个标签：{}",
    "commands.tag.remove.failed": "目标没有该标签",
    "commands.tag.remove.success.single": "已移除 {}上的标签“{}”",
    "commands.tag.remove.success.multiple": "已移除 {} 个实体上的标签“{}”",
    "commands.tell.description": "向一名或多名玩家发送私密消息。",
    "commands.tellraw.description": "向其他玩家发送 JSON 消息。",
    "commands.tellraw.jsonException": "无效的 json：{}",
    "commands.tellraw.jsonStringException": "无效的 JSON 字符串数据。",
    "commands.tellraw.error.noData": "未提供任何数据。",
    "commands.tellraw.error.notArray": "原始文本对象必须包含一个数组。示例：\"rawtext\":[{..}]",
    "commands.tellraw.error.textNotString": "原始文本中的“text”域必须包含一个字符串。示例：\"rawtext\":[{\"text\": \"text to display\"}]",
    "commands.tellraw.error.translateNotString": "原始文本中的“translate”域必须包含一个语言关键词。示例：\"rawtext\":[{\"translate\": \"gui.ok\"}]",
    "commands.tellraw.error.selectorNotString": "原始文本的选择器字段必须包含一个字符串形式的选择器。示例：“rawtext”：[{\"selector\": \"@e\"}]",
    "commands.tellraw.error.scoreNotObject": "原始文本中的分数字段必须包含对象。例如 \"rawtext\":[{\"score\": {\"name\": \"my_name\", \"objective\": \"my_objective\"}}]",
    "commands.tellraw.error.scoreNameNotString": "分数字段中的名称字段必须是字符串。例如 \"rawtext\":[{\"score\": {\"name\": \"my_name\", \"objective\": \"my_objective\"}}]",
    "commands.tellraw.error.scoreObjectiveNotString": "分数字段中的对象字段必须是字符串。例如 \"rawtext\":[{\"score\": {\"name\": \"my_name\", \"objective\": \"my_objective\"}}]",
    "commands.tellraw.error.withNotArrayOrRawText": "原始文本中的与字段必须包含一个数组或另一个原始文本对象。示例 1：\"rawtext\":[{\"translate\": \"chat.type.announcement\", \"with\": [ \"value1\", \"value2\" ]}]  示例 2：\"rawtext\":[{\"translate\": \"chat.type.announcement\", \"with\":{\"rawtext\":[{\"text\": \"value1\"}, {\"text\": \"value2\"}]}}]",
    "commands.tellraw.error.itemIsNotObject": "原始文本数组中的 JSON 值不是对象。示例：\"rawtext\": [{ \"text\" : \"my text\" }]",
    "commands.educlientinfo.description": "获取租户 ID 和主机状态。供 CM 使用。",
    "commands.testfor.description": "计数与指定条件相匹配的实体（玩家、生物、物品等）。",
    "commands.testfor.failure": "{} 与要求的数据结构不匹配",
    "commands.testfor.success": "发现 {}",
    "commands.testfor.tagError": "数据标签解析失败：{}",
    "commands.testforblock.description": "测试某个方块是否位于特定位置。",
    "commands.testforblock.failed.data": "位于 {},{},{} 的方块与预期的方块状态不匹配。",
    "commands.testforblock.failed.nbt": "位于 {},{},{} 的方块并没有所需的 NBT 标签。",
    "commands.testforblock.failed.tile": "位于 {},{},{} 的方块为 {} ( 预定：{})",
    "commands.testforblock.failed.tileEntity": "位于 {},{},{} 的方块不拥有实体附加值且不支持标签配对。",
    "commands.testforblock.outOfWorld": "无法测试位于世界外的方块",
    "commands.testforblock.success": "成功找到了位于 {},{},{} 的方块。",
    "commands.testforblocks.description": "测试两个地区的方块是否匹配。",
    "commands.tickingarea.description": "添加、删除或列出常加载区域。",
    "commands.tickingarea.inuse": "{}/{} 常加载区域正在使用。",
    "commands.tickingarea.entitycount": "实体中有 {} 个带 tick_world 组件的常加载区域。",
    "commands.tickingarea.noneExist.currentDimension": "当前维度中不存在任何常加载区域。",
    "commands.tickingarea-add-bounds.success": "已将常加载区域从 {} 添加到 {}。",
    "commands.tickingarea-add-bounds.preload.success": "从 {} 到 {} 添加常加载区域，用于预先下载。",
    "commands.tickingarea-add-circle.success": "已添加常加载区域，中心位于 {}，区块半径为 {}。",
    "commands.tickingarea-add-circle.preload.success": "以 {} 为中心的 {} 个区块半径内添加常加载区域，用于预先下载。",
    "commands.tickingarea-add.failure": "已达到常加载区域的最大数量 ({})。无法再添加更多常加载区域。",
    "commands.tickingarea-add.conflictingname": "名为 {} 的常加载区域已存在。",
    "commands.tickingarea-add.chunkfailure": "常加载区域包含 {} 个以上区块，常加载区域过大，无法创建。",
    "commands.tickingarea-add.radiusfailure": "半径不能大于 {}，常加载区域过大，无法创建。",
    "commands.tickingarea-remove.success": "已删除常加载区域",
    "commands.tickingarea-remove.failure": "当前维度中不存在任何包含方块位置 {} 的常加载区域。",
    "commands.tickingarea-remove.byname.failure": "当前维度中不存在任何名为 {} 的常加载区域。",
    "commands.tickingarea-remove_all.success": "已删除常加载区域",
    "commands.tickingarea-remove_all.failure": "当前维度中不存在任何常加载区域。",
    "commands.tickingarea-preload.success": "更新的常加载区域",
    "commands.tickingarea-preload.byposition.failure": "当前维度中不存在任何包含方块位置 {} 的常加载区域。",
    "commands.tickingarea-preload.byname.failure": "当前维度中不存在任何名为 {} 的常加载区域。",
    "commands.tickingarea-preload.count": "{} 个匹配区域被标记用于预先下载。",
    "commands.tickingarea-list.chunks": "区块\t\t Meaning a chunk of the world.",
    "commands.tickingarea-list.circle.radius": "半径",
    "commands.tickingarea-list.preload": "预先下载",
    "commands.tickingarea-list.success.currentDimension": "当前维度中的所有常加载区域的列表",
    "commands.tickingarea-list.success.allDimensions": "所有维度中的所有常加载区域的列表",
    "commands.tickingarea-list.failure.allDimensions": "任何维度中都不存在任何常加载区域。",
    "commands.tickingarea-list.to": "到\t\t Used in the context of \"from position to other position\"",
    "commands.tickingarea-list.type.circle": "圆形",
    "commands.time.added": "将时间调快了 {}",
    "commands.time.description": "更改或查询世界的游戏时间。",
    "commands.time.disabled": "此世界启用了终为白日模式。",
    "commands.time.query.day": "日期为 {}",
    "commands.time.query.daytime": "白天为 {}",
    "commands.time.query.gametime": "游戏时间为 {}",
    "commands.time.set": "将时间设为 {}",
    "commands.time.stop": "时间 {}",
    "commands.title.description": "控制屏幕标题。",
    "commands.title.success": "标题命令执行成功",
    "commands.titleraw.description": "使用 JSON 消息控制屏幕标题。",
    "commands.titleraw.success": "Titleraw 命令执行成功",
    "commands.toggledownfall.description": "切换天气。",
    "commands.tp.description": "传送实体（玩家、生物等）。",
    "commands.tp.notSameDimension": "无法传送，因为目标玩家不存在于同一个维度",
    "commands.tp.outOfWorld": "无法传送世界外的实体",
    "commands.tp.permission": "您没有使用此斜杠命令的权限。",
    "commands.tp.safeTeleportFail": "无法将 {} 传送到 {}，因为该区域有障碍。",
    "commands.tp.far": "无法将 {} 传送到 {} 的未加载区域",
    "commands.tp.success": "已将 {} 传送至 {}",
    "commands.tp.successVictim": "您已被传送至 {}",
    "commands.tp.success.coordinates": "已将 {} 传送至 {}, {}, {}",
    "commands.transferserver.description": "将玩家转移至另一个服务器。",
    "commands.transferserver.successful": "已转移的玩家",
    "commands.transferserver.invalid.port": "无效端口(0-65535)",
    "commands.trigger.description": "设置触发器以供激活。",
    "commands.trigger.disabled": "触发因子 {} 没有启用",
    "commands.trigger.invalidMode": "触发模式 {} 无效",
    "commands.trigger.invalidObjective": "触发因子名称 {} 无效",
    "commands.trigger.invalidPlayer": "只有玩家能使用/trigger命令",
    "commands.trigger.success": "触发因子 {} 已随 {} {} 改变",
    "commands.unban.failed": "无法解除玩家 {} 的封禁",
    "commands.unban.success": "已解封玩家 {}",
    "commands.unbanip.invalid": "你输入了一个无效的IP地址",
    "commands.unbanip.success": "已解封 IP 地址 {}",
    "commands.validategamelighting.description": "验证游戏内指定区域的照明系统",
    "commands.validategamelighting.checkRegionTooBig": "用于检查照明系统的区域过大!（{}>{}）",
    "commands.validategamelighting.outOfWorld": "无法检查世界以外的照明系统",
    "commands.volumearea.description": "添加、移除或列出当前维度的卷。",
    "commands.volumearea.add.definitionDoesntExist.failure": "没有匹配标识符 \"{}\" 的卷定义。",
    "commands.volumearea.add.exceededLimit.failure": "卷的最大数量 {} 已达到。无法添加更多卷。",
    "commands.volumearea.add.failure": "无法创建卷。",
    "commands.volumearea.add.success": "添加了从 {} 到 {} 的卷 \"{}\"。",
    "commands.volumearea.remove.byName.failure": "当前维度中不存在名为 {} 的卷。",
    "commands.volumearea.remove.byPosition.failure": "当前维度中不存在包含方块位置 {} 的卷。",
    "commands.volumearea.remove.success": "移除了当前维度的卷",
    "commands.volumearea.remove_all.success": "移除了当前维度的卷",
    "commands.volumearea.list.success.currentDimension": "列出当前维度的所有卷",
    "commands.volumearea.list.success.allDimensions": "列出所有维度的所有卷",
    "commands.volumearea.list.failure.allDimensions": "任何维度中不存在卷。",
    "commands.volumearea.entry.withIdentifier": "- {}: {} 从 {} {} {} 到 {} {} {}",
    "commands.volumearea.entry.withoutIdentifier": "- {}：从 {} {} {} 到 {} {} {}",
    "commands.volumearea.noneExist.currentDimension": "当前维度中不存在卷。",
    "commands.volumearea.inUse": "{}/{} 个卷在使用中。",
    "commands.weather.clear": "更换到晴朗天气",
    "commands.weather.description": "设置天气。",
    "commands.weather.disabled": "此世界未启用天气更替模式。",
    "commands.weather.query": "天气状态是：{}",
    "commands.weather.query.clear": "不下雨",
    "commands.weather.query.rain": "下雨",
    "commands.weather.query.thunder": "雷阵雨",
    "commands.weather.rain": "更换到下雨天",
    "commands.weather.thunder": "更换到雷雨天",
    "commands.allowlist.add.failed": "无法将 {} 添加到允许列表中",
    "commands.allowlist.add.success": "已将 {} 加入允许列表",
    "commands.allowlist.description": "管理服务器允许列表。",
    "commands.allowlist.disabled": "允许列表已关闭",
    "commands.allowlist.enabled": "允许列表已启用",
    "commands.allowlist.list": "现有 {} 名（可看到的共 {} 名）在允许列表中的玩家：",
    "commands.allowlist.reloaded": "已从文件重新读取允许列表。",
    "commands.allowlist.remove.failed": "无法从允许列表中移除 {}",
    "commands.allowlist.remove.success": "已将 {} 移出允许列表",
    "commands.world_age.description": "改变或查询世界的年龄（自创建以来的时间）。",
    "commands.world_age.added": "该世界的年龄增加 {}",
    "commands.world_age.query": "世界年龄为 {}",
    "commands.world_age.set": "将世界年龄设置为 {}",
    "commands.worldborder.center.success": "将世界边界的中心设置为 {},{}",
    "commands.worldborder.damage.amount.success": "将世界边界伤害设置为每方块 {}（原为每方块 {}）",
    "commands.worldborder.damage.buffer.success": "将世界边界伤害缓存设为 {} 个方块（原为 {} 个方块）",
    "commands.worldborder.get.success": "当前世界边界宽度为 {} 个方块",
    "commands.worldborder.set.success": "设置世界边界的宽度为 {} 个方块（原为 {} 个方块）",
    "commands.worldborder.setSlowly.grow.success": "正将世界边界宽度逐渐增加为 {} 个方块（原为 {} 个方块），时间 {} 秒",
    "commands.worldborder.setSlowly.shrink.success": "正将世界边界宽度逐渐缩小为 {} 个方块（原为 {} 个方块），时间 {} 秒",
    "commands.worldborder.warning.distance.success": "将世界边界警告设置到 {} 个方块的距离（原为 {} 个方块）",
    "commands.worldborder.warning.time.success": "将世界边界警告设置到 {} 秒的距离（原为 {} 秒）",
    "commands.worldbuilder.description": "切换世界建造者调用方状态。",
    "commands.worldbuilder.success": "世界建造者状态更新为 {}",
    "commands.wsserver.description": "尝试在所提供的 URL 上连接到 WebSocket 服务器。",
    "commands.wsserver.invalid.url": "所提供的服务器 URL 无效",
    "commands.wsserver.request.existing": "另一项连接要求目前正在运行",
    "commands.wsserver.request.failed": "无法连接到服务器：{}",
    "commands.wsserver.success": "已建立服务器连接：{}",
    "commands.xp.description": "添加或删除玩家经验值。",
    "commands.xp.failure.widthdrawXp": "无法向玩家给予负经验值",
    "commands.xp.success": "已将 {} 的经验给予 {}",
    "commands.xp.success.levels": "给予 {} {} 级经验",
    "commands.xp.success.negative.levels": "从 {} 身上拿走了 {} 级经验"
}