menu: dict = {
    "menu.achievements":"成就",
    "menu.convertingLevel":"正在扩张世界",
    "menu.copyright":"©Mojang AB",
    "menu.disconnect":"断开连接",
    "menu.educatorResources":"教育者资源",
    "menu.editions":"版本",
    "menu.beta":"Beta 版！！！",
    "menu.game":"游戏菜单",
    "menu.generatingLevel":"正在生成世界",
    "menu.generatingTerrain":"生成地形中",
    "menu.howToPlay":"游戏指南",
    "menu.howToPlay.caps":"游戏指南",
    "menu.host":"主机",
    "menu.howToPlay.generalMessage":"面向新老玩家的《我的世界》百科全书。",
    "menu.howToPlay.access":"按下 :",
    "menu.howToPlay.access.noicon":"按下 [A] 打开游戏指南！",
    "menu.loadingLevel":"加载世界中",
    "menu.multiplayer":"多人游戏",
    "menu.online":"Minecraft Realms",
    "menu.options":"选项",
    "menu.settings":"设置",
    "menu.settings.caps":"设置",
    "menu.classroom_settings.caps":"教室设置",
    "menu.serverStore":"%s 商店",
    "menu.serverGenericName":"服务器",
    "menu.play":"游戏",
    "menu.playdemo":"开始试玩世界",
    "menu.playOnRealms":"在 Realm 上玩",
    "menu.quickplay":"快速开始游戏",
    "menu.quit":"保存并退出",
    "menu.quit.edu":"保存&退出",
    "menu.quiz":"参加测验",
    "menu.resetdemo":"重置试玩世界",
    "menu.resourcepacks":"资源包",
    "menu.globalpacks":"全局资源",
    "menu.storageManagement":"存储",
    "menu.behaviors":"行为包",
    "menu.worldtemplates":"世界模板",
    "menu.respawning":"重生中",
    "menu.returnToGame":"继续游戏",
    "menu.returnToMenu":"保存并退回到标题画面",
    "menu.shareToLan":"对局域网开放",
    "menu.simulating":"模拟世界中",
    "menu.singleplayer":"单人游戏",
    "menu.store":"市场",
    "menu.skins":"皮肤",
    "menu.start":"开始",
    "menu.switchingLevel":"转接世界中",
    "menu.makingBackup":"制作备份中...",
    "menu.saving":"保存中……",
    "menu.toolboxMode":"工具箱模式",

}