packdiscoveryerror: dict = {
    "packdiscoveryerror.manifest_pack_error":无法打开资源包。",
    "packdiscoveryerror.incomplete_pack":不完整的包。",
    "packdiscoveryerror.unsupported_file_format":无效的 zip 存档。",
    "packdiscoveryerror.missing_manifest":无法找到资源包中的清单。",
    "packdiscoveryerror.manifest_parse_error":无法分析如下堆栈的资源包清单：%s",
    "packdiscoveryerror.required_manifest_property_missing":资源包清单中缺少 '%s'。",
    "packdiscoveryerror.required_manifest_property_wrong_type":资源包清单中的必备 '%s' 元素为错误类型。",
    "packdiscoveryerror.required_manifest_property_empty":资源包清单中的必备 '%s' 元素为空。",
    "packdiscoveryerror.required_manifest_property_invalid_value":资源包清单中提供的 '%s' 元素具有无效值。",
    "packdiscoveryerror.malformed_uuid":所提供的 '%s' 元素在包清单中不是有效的 UUID。",
    "packdiscoveryerror.malformed_version":所提供的 '%s' 元素在包清单中不兼容 SemVer (semver.org)。",
    "packdiscoveryerror.missing_modules":包清单中缺少 '%s' 元素；默认为资源包。",
    "packdiscoveryerror.missing_dependency":缺少 ID '%s' 和版本 '%s' 的依赖项。",
    "packdiscoveryerror.unsupported_format_version":不支持提供的格式版本 '%s'。",
    "packdiscoveryerror.duplicate_uuid":所提供的 UUID '%s' 元素已存在于包清单中。",
    "packdiscoveryerror.multiple_modules":包清单中检测到多个冲突的模块。",
    "packdiscoveryerror.invalid_capability_value":不支持包功能“%s”。",
    "packdiscoveryerror.unsupported_format_patch":版本 '%s' 中提供的修订组件将被忽略，并被视为 0。",
    "packdiscoveryerror.ignored_property":属性 '%s' 未用于该种类型的内容。字段将被忽略。",
    "packdiscoveryerror.version_too_high":属性 '%s' 的版本为 '%s'，该值过高。我们能接受的最高值是 '%s'。",
    "packdiscoveryerror.version_too_low":属性 '%s' 的版本为 '%s'，该值过低。我们能接受的最低值是 '%s'。",
    "packdiscoveryerror.format_version_1_engine_version_cap":属性 '%s` 的值必须小于 `%s`。要使用更高的版本，您需要使用格式版本 2。",

}