skins: dict = {
    "skins.browse":浏览",
    "skins.buy.buyButton":购买",
    "skins.buy.cancelButton":取消",
    "skins.buy.noConnection":无法连接到市场。请检查您的互联网连接？",
    "skins.information.ingame":抱歉，你不能在游戏内更改皮肤。请从主菜单中访问选项。",
    "skins.information.invalidCustomSkin":选择的图像不能作为《我的世界》皮肤",
    "skins.information.upsellWithoutStore":您必须购买皮肤包才能使用此皮肤，但我们无法连接到市场。",
    "skins.information.selectSkin":选择适用皮肤的模式",
    "skins.restore.button":恢复",
    "skins.show.restorePurchaseButton":恢复",
    "skins.skinpackHeader.packs":皮肤包",
    "skins.skinpackHeader.standard":标准",
    "skins.title":皮肤",
    "skins.picker.title":选择皮肤",
    "skins.picker.accept.button":确认",
    "skins.picker.unlock.button":解锁",
    "skins.picker.custom.button":选择新皮肤",
    "skins.picker.default":默认",
    "skins.picker.recent":最近",
    "skins.picker.no.cross.platform":受平台限制的皮肤包",
    "skins.picker.no.multiplayer":多人游戏限制的皮肤包",
    "skins.picker.expanded.back":'%s' 中的皮肤",
    "skins.store.upsell.equip.button":装备此皮肤",
    "skins.store.upsell.info":你需要解锁此包才能装备你所选的皮肤。",
    "skins.store.upsell.seePack":查看市场中的包",
    "skins.store.upsell.unlockPack":您需要解锁此包才能装备您所选的皮肤。",
    "skins.store.equipped":您已配备 %s 皮肤。",

}