codeScreen: dict = {
    "codeScreen.aznbReset.title=重置所有笔记本",
    "codeScreen.aznbReset.body=您即将清除所有项目。无法撤消此操作。是否确定？",
    "codeScreen.chooseEditor=选择编辑器：",
    "codeScreen.editor.description.aznb=学习如何利用 Python 进行编程！使用笔记本界面探索计算机科学课程、教程和挑战。",
    "codeScreen.editor.description.makeCode=您可以通过 Microsoft MakeCode 在 Minecraft 中使用方块、Python 或 JavaScript 进行编程！",
    "codeScreen.editor.description.tynker=使用 Tynker 建造自己的世界！使用代码制作迷你游戏，制作即时建筑，制作自己的模组。",
    "codeScreen.memoryWarning=此设备的内存不符合推荐要求。编辑器可能无法正常工作。",
    "codeScreen.memoryError=编辑器进程出错，请检查您的设备是否有足够的内存。",
    "codeScreen.needCheats=必须开启当前世界中的无敌模式才能编码！",
    "codeScreen.networkError=无法连接网络。请检查您的互联网设置。",
    "codeScreen.title=代码编辑器",
    "codeScreen.changeEditorModal.title=更改编辑器",
    "codeScreen.resetWarning=是否确定要更改正在使用的编辑器？所有未保存的工作都将丢失。",
    "codeScreen.changeEditorModal.change=更改",
    "codeScreen.button.flipWindow=翻转窗口",
    "codeScreen.button.largerWindow=较大的窗口",
    "codeScreen.button.smallerWindow=较小的窗口",
    "codeScreen.button.resetEditor=重置编辑器",
    "codeScreen.button.changeEditor=更改编辑器",
    "codeScreen.buttonTTS.splitLeft=向左移动",
    "codeScreen.buttonTTS.splitRight=向右移动",
    "codeScreen.buttonTTS.selectEditor=选择编辑器",
    "codeScreen.buttonTTS.maximize=最大化",
    "codeScreen.buttonTTS.restore=恢复",
    "codeScreen.buttonTTS.home=首页",

}