trade: dict = {
    "trade.doesNotWant":"商人不想要这个",
    "trade.excalamation":"！",
    "trade.expProgress":"经验：%d/%d",
    "trade.expMax":"经验：最大",
    "trade.levelPrefix":"%d 级",
    "trade.levelPrefixAndName":"%d - %s 级",
    "trade.levelPrefixAndName.max":"最大等级 - %s",
    "trade.nameAndLevel":"%s - %s",
    "trade.level.1":"新手",
    "trade.level.2":"学徒",
    "trade.level.3":"熟手",
    "trade.level.4":"专家",
    "trade.level.5":"大师",
    "trade.mysteriousText":"轻拍",
    "trade.notEnough":"不够 %s",
    "trade.question":"？",
    "trade.trade":"交易",

}