joincode: dict = {
            "joincode.entry_popup.title":"输入加入代码",
    "joincode.connecting.title":"加入世界",
    "joincode.connecting.lower_text":"正在搜索世界……",
    "joincode.error.title":"加入错误",
    "joincode.error.message.no_match":"您输入的加入代码无法匹配目前可用的任何世界。",
    "joincode.error.message.no_response":"连接到加入代码服务时出现了问题。请重试。",
    "joincode.error.message.not_available":"加入代码目前不可用。请求您的主机提供其 IP 地址来供您加入其游戏。",
    "joincode.error.message.service_error":"出错了。请再试一次。",
    "joincode.found.title":"加入世界",
    "joincode.found.message":"您是要加入这个世界吗？",
    "joincode.found.host_name":"主办人：%1",
    "joincode.icon_text.null":"空",
    "joincode.icon_text.1":"书与笔",
    "joincode.icon_text.2":"气球",
    "joincode.icon_text.3":"铁轨",
    "joincode.icon_text.4":"艾莉克斯",
    "joincode.icon_text.5":"曲奇",
    "joincode.icon_text.6":"鱼",
    "joincode.icon_text.7":"代理机器人",
    "joincode.icon_text.8":"蛋糕",
    "joincode.icon_text.9":"镐",
    "joincode.icon_text.10":"水桶",
    "joincode.icon_text.11":"史蒂夫",
    "joincode.icon_text.12":"苹果",
    "joincode.icon_text.13":"胡萝卜",
    "joincode.icon_text.14":"熊猫",
    "joincode.icon_text.15":"告示牌",
    "joincode.icon_text.16":"药水",
    "joincode.icon_text.17":"地图",
    "joincode.icon_text.18":"羊驼",
    "joincode.ip_entry.button_tts":"更多选项",
    "joincode.ip_entry.address.tooltip":"要找到 IP 地址，需请求主机暂停游戏。IP 地址和端口号可以在暂停屏幕的多人游戏选项卡上找到。",
    "joincode.ip_entry.port.tooltip":"要找到端口号，需请求主机暂停游戏。IP 地址和端口号可以在暂停屏幕的多人游戏选项卡上找到。",
    "joincode.generate_new.button.text":"生成新的加入代码",
    "joincode.generate_new.tooltip.text":"生成新的代码不会中断您的多人游戏会话。",
    "joincode.button.share_link.text":"分享链接",
    "joincode.generating_new":"加载中…",
    "joincode.tooltip.errortext":"生成加入代码时出错了。",
    "joincode.tooltip.account.error":"验证您的账户时出现了问题。请重启 Minecraft Education 并重试。",
    "joincode.tooltip.infotext":"把加入代码给您的同学，让他们加入您的世界。",
    "joincode.button.stop_hosting.text":"停止托管",
    "joincode.confirmation.stop_hosting.message":"如果停止托管世界，所有玩家的多人游戏会话将结束。您确定要这么做吗？",
    "joincode.button.start_hosting.text":"开始托管",
    "joincode.confirmation.start_hosting.message":"如果您开始托管，我们将为您创建一个您可以给其他玩家的代码，这样他们就可以加入您的世界了。您想开始托管吗？",
    "joincode.service.unreachable":"无法访问发现服务",
    "joincode.button.generate_code.text":"生成新的加入代码",
    "joincode.confirmation.generate_code.message":"创建一个新的加入代码不会停止您的多人游戏。新代码将被用于邀请其他玩家。",
    "joincode.service.unavailable":"加入代码目前不可用。请尝试刷新或使用您的 IP 地址作为代替。",

}