demo: dict = {
    "demo.day.1":"此试玩版只有5天游戏内时间, 尽力而为吧!",
    "demo.day.2":"第二天",
    "demo.day.3":"第三天",
    "demo.day.4":"第四天",
    "demo.day.5":"这是你游戏内的最后一天!",
    "demo.day.6":"你已经度过了5天的试玩时间，按F2来截图留念",
    "demo.day.warning":"您的试玩时间即将结束！",
    "demo.demoExpired":"试玩的时间结束了！",
    "demo.help.buy":"即刻购买！",
    "demo.help.fullWrapped":"这个试玩将会持续游戏内5天的时间 (现实时间大约为1小时40分钟) 。查看成就来获得提示！祝您玩得开心！",
    "demo.help.inventory":"按 %1$s 打开你的道具栏",
    "demo.help.jump":"按 %1$s 跳跃",
    "demo.help.later":"继续玩！",
    "demo.help.movement":"按 %1$s, %2$s, %3$s, %4$s 以及鼠标来移动",
    "demo.help.movementMouse":"使用鼠标来查看四周",
    "demo.help.movementShort":"通过按下%1$s，%2$s，%3$s，%4$s来移动",
    "demo.help.title":"《我的世界》试玩模式",
    "demo.remainingTime":"剩余时间：%s",
    "demo.reminder":"试玩时间已经结束，请购买游戏来继续或开始一个新的世界！",

}