disconnect: dict = {
    "disconnect.closed":"连接已关闭",
    "disconnect.downloadPack":"从服务器下载安装包并应用时出错。请重试。",
    "disconnect.disconnected":"被服务器中断连接",
    "disconnect.endOfStream":"数据流终止",
    "disconnect.genericReason":"%s",
    "disconnect.kicked":"您已被踢出游戏",
    "disconnect.kicked.reason":"您已被踢出游戏：",
    "disconnect.removed":"您已被移除出游戏",
    "disconnect.removed.reason":"您已被移除出游戏：",
    "disconnect.loginFailed":"登入失败",
    "disconnect.loginFailedInfo":"登入失败：%s",
    "disconnect.loginFailedInfo.invalidSession":"无效的会话 (请尝试重启你的游戏)",
    "disconnect.loginFailedInfo.serversUnavailable":"身份验证目前正在停机维护。",
    "disconnect.lost":"连接已丢失",
    "disconnect.overflow":"缓冲区溢出",
    "disconnect.quitting":"退出",
    "disconnect.spam":"由于滥发信息而被踢出游戏",
    "disconnect.timeout":"连接超时",

}