realmsCreateScreen: dict = {
    "realmsCreateScreen.title.create":创建一个 Realm 服务器",
    "realmsCreateScreen.title.extend":延长你的 Realm",
    "realmsCreateScreen.title.renew":更新你的 Realm",
    "realmsCreateScreen.defaultRealm":%s的 Realm",
    "realmsCreateScreen.creatingRealm":正在创建 Realm……",
    "realmsCreateScreen.nameHeader.name":Realm 名称",
    "realmsCreateScreen.nameHeader.rename":重命名 Realm？",
    "realmsCreateScreen.termsAndConditionsAgree":同意",
    "realmsCreateScreen.termsAndConditionsHeader":条款和条件",
    "realmsCreateScreen.viewTermsAndConditions":条款和条件",
    "realmsCreateScreen.viewPrivacyPolicy":查看隐私政策",
    "realmsCreateScreen.durationHeader":持续时间",
    "realmsCreateScreen.durationShort":30 天",
    "realmsCreateScreen.durationLong":180 天",
    "realmsCreateScreen.sizeHeader":层级",
    "realmsCreateScreen.purchasePrefix.create":创建",
    "realmsCreateScreen.purchasePrefix.extend":延长",
    "realmsCreateScreen.purchasePrefix.renew":更新",
    "realmsCreateScreen.subscription.trial":免费创建！%s（30 天后 %s/每月）",
    "realmsCreateScreen.subscription.buy":以每月 %s 创建",
    "realmsCreateScreen.subscription.renew":以每月 %s 更新",
    "realmsCreateScreen.consumable.trial":免费创建！",
    "realmsCreateScreen.consumable.buy":以 %s 创建",
    "realmsCreateScreen.consumable.renew":以 %s 更新",
    "realmsCreateScreen.consumable.extend":以 %s 延长",
    "realmsCreateScreen.errorRealmName":你的 Realm 名称不能为空。",
    "realmsCreateScreen.errorRealmNameAndTOS":你的 Realm 名称不能为空，而且你必须接受服务条款才能创建 Realm。",
    "realmsCreateScreen.errorTOS":必须接受条款和条件才能创建 Realm。",
    "realmsCreateScreen.goBack":返回",
    "realmsCreateScreen.createFailed.title":出错了",
    "realmsCreateScreen.purchaseFailed":抱歉，无法完成 Realm 购买。请检查互联网连接？",
    "realmsCreateScreen.createFailed.content":购买成功，但现在无法创建您的 Realm。我们会尽快创建您的 Realm。请稍后在此设备上查看。",
    "realmsCreateScreen.createFailed.profanity":不允许 Realm 名称 %s。",
    "realmsCreateScreen.createFailed.generic":无法验证俱乐部名称。请稍后重试。",
    "realmsCreateScreen.maxRealms.title":最大订阅数",
    "realmsCreateScreen.maxRealms.content":您在该平台上已达到最大活跃订阅数，现在无法创建新的订阅。",
    "realmsCreateScreen.offerNotFound.title":商店连接已中断",
    "realmsCreateScreen.offerNotFound.content":您的设备与商店连接中断，我们无法确认此优惠是否可用。请检查您的互联网连接，或稍后再试。",
    "realmsCreateScreen.offerNotAvailable.title":商店连接已中断",
    "realmsCreateScreen.offerNotAvailable.content":您的设备与商店连接中断，我们无法确认此优惠是否可用。请检查您的互联网连接，或稍后再试。",
    "realmsCreateScreen.extendRealms.content":您已经尽可能延长 Realms 订阅，现在无法增加额外时间。请稍后再试。",
    "realmsCreateScreen.usersTwo":2 名玩家",
    "realmsCreateScreen.usersTen":10 名玩家",
    "realmsCreateScreen.viewTOS":要查看 Minecraft Realms 的条款和条件，请在任意网络浏览器中访问 https:",
    "realmsCreateScreen.viewPrivacyPolicyText":要查看 Minecraft Realms 的隐私政策，请在任意网络浏览器中访问 https:",
    "realmsCreateScreen.waitingPurchase":正在购买中！稍后即可完成。",
    "realmsCreateScreen.paymentFailed.title":支付服务",
    "realmsCreateScreen.paymentFailed.body":目前无法连接 Realms，不能完成购买。请稍后再试。",
    "realmsCreateScreen.incomplete":不完整 Realm",
    "realmsCreateScreen.incomplete.create.a":看来我们上次并没有完成。现在我们来完成创建您的 Realm 吧。",
    "realmsCreateScreen.incomplete.create.b":看来您用了其他 Microsoft 账户创建 Realm。是否要用这个 Microsoft 账户作为所有人，完成创建该 Realm？",
    "realmsCreateScreen.incomplete.create.c":有人用此设备上的计费账户开始了创建 Realm。您是否要用这个 Microsoft 账户作为所有人，完成创建该 Realm？",
    "realmsCreateScreen.incomplete.renew.a":看来我们上次并没有完成。现在我们来完成更新您的 Realm 吧。",
    "realmsCreateScreen.incomplete.renew.b":看来您用了其他 Microsoft 账户开始更新 Realm。是否要用这个账户作为所有人，完成更新该 Realm？",
    "realmsCreateScreen.incomplete.renew.c":有人用此设备上的计费账户开始了更新 Realm。您是否要用这个 Microsoft 账户作为所有人，完成更新该 Realm？",
    "realmsCreateScreen.incomplete.override.renew":您正在尝试创建新 Realm，但我们发现您此前有更新 Realm 的购买记录。是否要现在应用此购买？",
    "realmsCreateScreen.incomplete.override.create":您正在尝试更新 Realm，但我们发现您此前有创建 Realm 的购买记录。是否要现在应用此购买？",
    "realmsCreateScreen.incomplete.override.realm":您正在尝试更新 Realm，但我们发现您此前有创建其他 Realm 的购买记录。是否要现在应用此购买？",
    "realmsCreateScreen.prepare.store.title":需要购买历史记录",
    "realmsCreateScreen.prepare.store.body":我们需要您登录到商店查看您的购买历史记录，然后才能继续。",
    "realmsCreateScreen.prepare.store.button":登录到商店",
    "realmsCreateScreen.nsoinfotext":若要使用 Realms，您需要订阅 Nintendo Switch Online。",
    "realmsCreateScreen.playNowTitle":立即在 Realm 上玩吗？",
    "realmsCreateScreen.playNowMessage1":您可以邀请好友加入您的 Realm 并立即开始玩游戏。",
    "realmsCreateScreen.playNowMessage2":或者，您可以随时在游戏屏幕的世界选项卡中找到它。您可以编辑它以改变游戏模式，甚至上传任何世界至您的 Realm 上。",
    "realmsCreateScreen.playWithFriends":与好友一起玩",
    "realmsCreateScreen.playSolo":独自玩",
    "realmsCreateScreen.purchaseConfirmation.title":购买 Realm？",
    "realmsCreateScreen.purchaseConfirmation.create.message":确定要创建一个 Realm 吗？",
    "realmsCreateScreen.purchaseConfirmation.extend.message":确定要延期一个 Realm 吗？",
    "realmsCreateScreen.purchaseConfirmation.renew.message":确定要续订一个 Realm 吗？",
    "realmsCreateScreen.purchaseConfirmation.continue":确认购买",
    "realmsCreateScreen.purchaseConfirmation.cancel":取消",
    "realmsCreateScreen.title":创建 Realm",
    "realmsCreateScreen.nameHeader":Realm 名称",
    "realmsCreateScreen.chooseWorld":创建 Realm：选择世界",

}