lategameTips: dict = {
    "lategameTips.1":"如果你拥有黄金盔甲，那么僵尸猪灵就不会攻击你，除非你激怒了它们。",
    "lategameTips.2":"将那些火球打回恶魂那里！",
    "lategameTips.3":"圆石可以抵御恶魂发射的火球，可用于守卫传送门。",
    "lategameTips.4":"我们的音乐是由 C418、Lena Raine 和 Kumi Tanioka 出品。",
    "lategameTips.5":"最终会对此游戏进行更新！",
    "lategameTips.6":"苦力怕诞生于编程失误。",
    "lategameTips.7":"Minecraft 的第一个版本只花了 6 天时间就搭建好了！",
    "lategameTips.8":"末影人的语言实际上就是反着说的英语。",
    "lategameTips.9":"Minecraft 的原名为 Cave Game。",
    "lategameTips.10":"蜘蛛骑手非常罕见，是一种骷髅骑着蜘蛛的生物！",
    "lategameTips.11":"在下界中行进一个方块相当于在主世界中行进八个方块。",
    "lategameTips.12":"使用幻翼膜来修理您的鞘翅。",
    "lategameTips.13":"鞘翅可以用来滑翔，它们会出现在末地城的船中！",
    "lategameTips.14":"打开设置菜单中的实验性游戏内容，即可测试一些新功能！",
    "lategameTips.15":"被骷髅箭消灭的怪物有机会掉落音乐唱片。",
    "lategameTips.16":"材质包会改变游戏中方块、物品甚至菜单的外观。试试吧！",
    "lategameTips.17":"使用焰火火箭会提高鞘翅在半空中的速度。只要…确保它们别爆炸就好，否则会让你疼得够呛！",
    "lategameTips.18":"真得有人会看这些吗？",
    "lategameTips.19":"激流附魔将在雨中推动您穿过空气。",
    "lategameTips.20":"信标是一种强力物品，只能用一颗产自凋灵的下界之星来合成！",
    "lategameTips.21":"下界之星不会被爆炸摧毁。",
    "lategameTips.22":"你可以与猪灵交换物品。",
    "lategameTips.23":"在下界重生需要充能的重生锚。",
    "lategameTips.24":"你可以用荧石为重生锚充能。",
    "lategameTips.25":"你可以用绯红真菌来饲养疣猪兽，但千万要小心。",
    "lategameTips.26":"黄金是下界和荒地生物群系里最常见的资源。",
    "lategameTips.27":"闪长岩是一种会让您对它非爱即恨的东西。",

}