keyboard: dict = {
    "keyboard.keyName.backspace":"返回",
    "keyboard.keyName.tab":"TAB",
    "keyboard.keyName.return":"返回",
    "keyboard.keyName.pause":"暂停",
    "keyboard.keyName.lshift":"SHIFT",
    "keyboard.keyName.control":"控制",
    "keyboard.keyName.alt":"替代",
    "keyboard.keyName.capsLock":"大写",
    "keyboard.keyName.escape":"ESC",
    "keyboard.keyName.space":"空格",
    "keyboard.keyName.pgDown":"PAGE DOWN 键",
    "keyboard.keyName.pgUp":"PAGE UP 键",
    "keyboard.keyName.end":"结束",
    "keyboard.keyName.home":"首页",
    "keyboard.keyName.left":"左",
    "keyboard.keyName.up":"上",
    "keyboard.keyName.right":"右",
    "keyboard.keyName.down":"下",
    "keyboard.keyName.insert":"插入",
    "keyboard.keyName.delete":"删除",
    "keyboard.keyName.0":"0",
    "keyboard.keyName.1":"1",
    "keyboard.keyName.2":"2",
    "keyboard.keyName.3":"3",
    "keyboard.keyName.4":"4",
    "keyboard.keyName.5":"5",
    "keyboard.keyName.6":"6",
    "keyboard.keyName.7":"7",
    "keyboard.keyName.8":"8",
    "keyboard.keyName.9":"9",
    "keyboard.keyName.a":"A",
    "keyboard.keyName.b":"B",
    "keyboard.keyName.c":"C",
    "keyboard.keyName.d":"D",
    "keyboard.keyName.e":"E",
    "keyboard.keyName.f":"F",
    "keyboard.keyName.g":"G",
    "keyboard.keyName.h":"H",
    "keyboard.keyName.i":"I",
    "keyboard.keyName.j":"J",
    "keyboard.keyName.k":"K",
    "keyboard.keyName.l":"L",
    "keyboard.keyName.m":"M",
    "keyboard.keyName.n":"N",
    "keyboard.keyName.o":"O",
    "keyboard.keyName.p":"P",
    "keyboard.keyName.q":"Q",
    "keyboard.keyName.r":"R",
    "keyboard.keyName.s":"S",
    "keyboard.keyName.t":"T",
    "keyboard.keyName.u":"U",
    "keyboard.keyName.v":"V",
    "keyboard.keyName.w":"W",
    "keyboard.keyName.x":"X",
    "keyboard.keyName.y":"Y",
    "keyboard.keyName.z":"Z",
    "keyboard.keyName.f1":"F1",
    "keyboard.keyName.f2":"F2",
    "keyboard.keyName.f3":"F3",
    "keyboard.keyName.f4":"F4",
    "keyboard.keyName.f5":"F5",
    "keyboard.keyName.f6":"F6",
    "keyboard.keyName.f7":"F7",
    "keyboard.keyName.f8":"F8",
    "keyboard.keyName.f9":"F9",
    "keyboard.keyName.f10":"F10",
    "keyboard.keyName.f11":"F11",
    "keyboard.keyName.f12":"F12",
    "keyboard.keyName.f13":"F13",
    "keyboard.keyName.numpad0":"数字键盘 0",
    "keyboard.keyName.numpad1":"数字键盘 1",
    "keyboard.keyName.numpad2":"数字键盘 2",
    "keyboard.keyName.numpad3":"数字键盘 3",
    "keyboard.keyName.numpad4":"数字键盘 4",
    "keyboard.keyName.numpad5":"数字键盘 5",
    "keyboard.keyName.numpad6":"数字键盘 6",
    "keyboard.keyName.numpad7":"数字键盘 7",
    "keyboard.keyName.numpad8":"数字键盘 8",
    "keyboard.keyName.numpad9":"数字键盘 9",
    "keyboard.keyName.scroll":"滚动",
    "keyboard.keyName.equals":"等于",
    "keyboard.keyName.add":"加",
    "keyboard.keyName.minus":"减",
    "keyboard.keyName.subtract":"减",
    "keyboard.keyName.multiply":"乘",
    "keyboard.keyName.divide":"除",
    "keyboard.keyName.decimal":"小数点",
    "keyboard.keyName.grave":"波浪号",
    "keyboard.keyName.numLock":"数字锁定",
    "keyboard.keyName.slash":"斜杠",
    "keyboard.keyName.semicolon":"分号",
    "keyboard.keyName.apostrophe":"撇号",
    "keyboard.keyName.comma":"逗号",
    "keyboard.keyName.period":"句号",
    "keyboard.keyName.backslash":"反斜杠",
    "keyboard.keyName.lbracket":"左括号",
    "keyboard.keyName.rbracket":"右括号",
    "keyboard.keyName.backspace.short":"退格",
    "keyboard.keyName.tab.short":"TAB",
    "keyboard.keyName.return.short":"返回",
    "keyboard.keyName.pause.short":"暂停",
    "keyboard.keyName.lshift.short":"SHIFT",
    "keyboard.keyName.control.short":"CTRL",
    "keyboard.keyName.alt.short":"ALT",
    "keyboard.keyName.capsLock.short":"CAPS",
    "keyboard.keyName.escape.short":"ESC",
    "keyboard.keyName.space.short":"空格",
    "keyboard.keyName.pgDown.short":"PgDn",
    "keyboard.keyName.pgUp.short":"PgUp",
    "keyboard.keyName.end.short":"END",
    "keyboard.keyName.home.short":"HOME",
    "keyboard.keyName.left.short":"左",
    "keyboard.keyName.up.short":"上",
    "keyboard.keyName.right.short":"右",
    "keyboard.keyName.down.short":"下",
    "keyboard.keyName.insert.short":"INS",
    "keyboard.keyName.delete.short":"DEL",
    "keyboard.keyName.numpad0.short":"N0",
    "keyboard.keyName.numpad1.short":"N1",
    "keyboard.keyName.numpad2.short":"N2",
    "keyboard.keyName.numpad3.short":"N3",
    "keyboard.keyName.numpad4.short":"N4",
    "keyboard.keyName.numpad5.short":"N5",
    "keyboard.keyName.numpad6.short":"N6",
    "keyboard.keyName.numpad7.short":"N7",
    "keyboard.keyName.numpad8.short":"N8",
    "keyboard.keyName.numpad9.short":"N9",
    "keyboard.keyName.scroll.short":"SCROLL",
        "keyboard.keyName.add.short":"N+",
    "keyboard.keyName.minus.short":"-",
    "keyboard.keyName.subtract.short":"N-",
    "keyboard.keyName.multiply.short":"N*",
    "keyboard.keyName.divide.short":"N/",
    "keyboard.keyName.decimal.short":"N.",
    "keyboard.keyName.grave.short":"`",
    "keyboard.keyName.numLock.short":"数字锁定",
    "keyboard.keyName.slash.short":"/",
    "keyboard.keyName.semicolon.short":";",
    "keyboard.keyName.apostrophe.short":"'",
    "keyboard.keyName.comma.short":",",
    "keyboard.keyName.period.short":".",
        "keyboard.keyName.lbracket.short":"[",
    "keyboard.keyName.rbracket.short":"]",
    "keyboard.onScreen.lineNumber":"行 %s",

}