trial: dict = {
    "trial.pauseScreen.remainingTime":"剩余的使用时间：%s",
    "trial.pauseScreen.buyGame":"解锁完整游戏",
    "trial.survival.welcome":"欢迎使用《我的世界》试用！",
    "trial.survival.remainingTime":"剩余%d分钟",
    "trial.pauseScreen.cb.buyGame":"常见问题解答",
    "trial.noInvitesOrJoining":"请购买完整版游戏以和好友一起游戏",
    "trial.upsell.trialLabel":"《我的世界》试用版",
    "trial.upsell.title":"开始试玩吧！",
    "trial.upsell.description":"在此试用版中，您只有90分钟的游戏时间去打造，建设，探索和享受您的世界！购买完整版以保留您的世界。",
    "trial.upsell.description.updated":"探索、合成、建造并享受乐趣！在此试用版中，您会拥有 90 分钟的探索时间。解锁完整版继续探索，多久都可以！",
    "trial.upsell.description.worldsDontTransferToFullGame.line1":"探索、合成、建造并享受乐趣！在此试玩版中，您会拥有 90 分钟的游戏时间。解锁完整版游戏，探索无限世界，想玩多久都可以！*",
    "trial.upsell.description.worldsDontTransferToFullGame.line2":"*（这个世界不会迁移到完整版游戏中）",
    "trial.upsell.unlock":"解锁完整游戏",
    "trial.upsell.startTrial":"开始试玩",
    "trial.upsell.continueTrial":"继续试用",
    "trial.upsell.cb.unlock":"常见问题解答",
    "trial.upsell.cb.description.worldsDontTransferToFullGame.line1":"探索、制作、建造并享受乐趣！在此试用版的世界中，您会拥有 90 分钟的游戏时间。发现错误？访问 bugs.mojang.com 进行报告！其他问题？查看我们的常见问题解答。",
    "trial.upsell.cb.description.worldsDontTransferToFullGame.line2":"（试用版中的世界不会转移至完整版游戏。）",
    "trial.upsell.expiredDescription.line1":"时间已过期。请购买以解锁完整游戏：",
    "trial.upsell.expiredDescription.line2":"—探索无限世界",
    "trial.upsell.expiredDescription.line3":"—与好友一起畅玩",
    "trial.upsell.expiredDescription.line4":"—加工百种物品",
    "trial.upsell.expiredDescription.line5":"-发现神秘建筑和领域",
    "trial.upsell.expiredNewDescription":"您想继续探索、合成和建造吗？解锁完整版本，探索多久都可以！这个世界会为您保存好，供以后继续探索，但在解锁完整版本之前，您将无法修改。",
    "trial.upsell.expiredNewDescription.worldsDontTransferToFullGame.line1":"您是否想继续探索、合成和建造？解锁完整版游戏，探索无限世界，想玩多久都可以！*",
    "trial.upsell.expiredTitle":"时间到！",
    "trial.upsell.expiredViewWorld":"查看世界",
    "trial.upsell.cb.expiredNewDescription.worldsDontTransferToFullGame.line1":"您想继续探索、制作和建造吗？开启试用版中的新世界继续玩游戏！",
    "trial.upsell.cb.startNew":"开启新世界",
    "trial.tabbed_upsell.title":"解锁完整游戏",
    "trial.tabbed_upsell.button":"购买《我的世界》！",
    "trial.tabbed_upsell.buttonAlternate":"解锁《我的世界》完整游戏",
    "trial.tabbed_upsell.minecraft.title":"《我的世界》",
    "trial.tabbed_upsell.minecraft.description":"无限探索您自己的独特世界，建造您能想象到的一切——从最简单的住宅，到最宏伟的城堡！您可以在创造模式中利用无限资源建造奇迹，也可以在生存模式中进行挖掘，合成武器和盔甲，抵御各种危险生物并在夜晚幸存下来。另外还可以在线与好友一起畅玩！立即解锁完整游戏！",
    "trial.tabbed_upsell.xbl.title":"Microsoft 账户",
    "trial.tabbed_upsell.xbl.description":"您可以借助完整的《我的世界》体验获得创造模式、成就等等，另外您还可以借助 Microsoft 账户在《我的世界》社区中结识其他玩家！您可以加入您好友的世界，在服务器上结识新的好友，并将您的市场购买同步到您玩《我的世界》的任何地方。",
    "trial.tabbed_upsell.xbl.description.line2":"*（在带有市场的版本中）",
    "trial.tabbed_upsell.achievements.title":"成就",
    "trial.tabbed_upsell.achievements.description":"除了获得带有创造模式、多人游戏等等的完整《我的世界》游戏体验，您还将获得成就和玩家分数。它们将记录您的《我的世界》进度，并向您的 Microsoft 账户好友展示您的成就。立即获得完整游戏来开始获得它们！",
    "trial.tabbed_upsell.multiplayer.title":"多人游戏",
    "trial.tabbed_upsell.multiplayer.description":"完整的《我的世界》游戏体验能够让您享受创造模式、成就以及与您的好友在多种《我的世界》设备上进行多人游戏！和控制台、电脑和移动端上的好友一起创造、探索和生存。立即解锁完整的《我的世界》游戏体验！",
    "trial.tabbed_upsell.server.title":"服务器",
    "trial.tabbed_upsell.server.description":"服务器提供了一些享受《我的世界》的最有创意的方式！玩精彩的小游戏，邂逅《我的世界》社区并结识新的好友。立即解锁完整的《我的世界》游戏体验以尝试服务器！",
    "trial.tabbed_upsell.store.title":"商店",
    "trial.tabbed_upsell.store.description":"访问我们的游戏内商店——《我的世界》市场。用新的皮肤让自己焕然一新，更改您的世界，或者探索来自最佳的社区创建者的超赞新地图！立即获取完整游戏！",
    "trial.tabbed_upsell.creative.title":"创造",
    "trial.tabbed_upsell.creative.description":"购买《我的世界》并获得创造模式！访问整个物品栏——您能建造什么只取决于您的想象力！飞遍您的世界，用任何东西、一切东西建造您的梦想之家，或者干脆用无限量的 TNT 炸掉一座山！",
    "trial.tabbed_upsell.addon.title":"附加件",
    "trial.tabbed_upsell.addon.description":"想让狼表现得像兔子一样吗？把所有的树都变成棉花糖？您可以在完整的《我的世界》游戏体验中使用附加件改变一切！此外，您还可以访问多人游戏、创造模式、成就等等！立即购买《我的世界》获得完整访问权限！",
    "trial.tabbed_upsell.seeds.title":"种子",
    "trial.tabbed_upsell.seeds.description":"解锁完整的《我的世界》游戏体验，获得访问种子的权限！种子会帮助您发现新的生物群系——在冰原上生存，攀登险峻的峭壁，或者徒步穿越沙漠。立即以独特的模板开始游戏或探索随机的新世界！立即购买《我的世界》，获得访问种子、创造模式、多人游戏以及更多内容的权限！",
    "trial.thanks_for_testing.title":"感谢您的测试",
    "trial.thanks_for_testing.button":"导航至常见问题解答！",
    "trial.thanks_for_testing.minecraft.title":"《我的世界》试用版",
    "trial.thanks_for_testing.minecraft.description":"感謝您下载《我的世界》Chromebook 试用版！您的游戏测试将为错误修复和技术故障排除提供宝贵的数据。发现错误？访问 bugs.mojang.com 进行报告！其他问题？查看我们的常见问题解答。",
    "trial.thanks_for_testing.xbl.title":"Microsoft 账户",
    "trial.thanks_for_testing.xbl.description":"解锁完整的《我的世界》游戏体验可以获得创造模式、成就等等，另外您还可以借助 Microsoft 账户在《我的世界》社区中结识其他用户！您可以加入您好友的世界，在服务器上结识新的好友，并将您的市场购买同步到您体验《我的世界》的任何地方。",
    "trial.thanks_for_testing.xbl.description.line2":"*（在带有市场的版本中）",
    "trial.thanks_for_testing.achievements.description":"除了获得带有创造模式、多人游戏等等的完整《我的世界》游戏体验，您还将获得成就。成就和玩家分数记录了您的《我的世界》进度，并向您的 Microsoft 账户好友展示您的成就。",
    "trial.thanks_for_testing.multiplayer.description":"完整的《我的世界》游戏体验能够让您享受创造模式、成就以及与您的好友在多种《我的世界》设备上进行多人游戏！和控制台、电脑和移动端上的好友一起玩，一起创造、探索和生存。",
    "trial.thanks_for_testing.server.description":"作为完整的《我的世界》游戏体验的一部分，服务器提供了一些享受《我的世界》的最有创意的方式！玩精彩的小游戏，邂逅《我的世界》社区并结识新的好友。",
    "trial.thanks_for_testing.store.description":"解锁完整游戏可以获得访问我们游戏内商店——《我的世界》市场的权限。用新的皮肤让自己焕然一新，更改您的世界，或者探索来自最佳的社区创建者的超赞新地图！",
    "trial.thanks_for_testing.creative.description":"完整的《我的世界》游戏体验中最受欢迎的部分：创造模式！访问整个物品栏——您能建造什么只取决于您的想象力！飞遍您的世界，用任何东西、一切东西建造您的梦想之家，或者干脆用无限量的 TNT 炸掉一座山！",
    "trial.thanks_for_testing.addon.description":"想让狼表现得像兔子一样吗？把所有的树都变成棉花糖？您可以在完整的《我的世界》游戏体验中使用插件改变一切！此外，您还可以访问多人游戏、创造模式、成就等等！",
    "trial.thanks_for_testing.seeds.description":"解锁完整的《我的世界》游戏体验可以获得访问种子的权限！种子会帮助您发现新的生物群系——在冰原上生存，攀登险峻的峭壁，或者徒步穿越沙漠。立即以独特的模板开始游戏或探索随机的新世界！",
    "trial.tabbed_upsell.navleft":"导航标签左",
    "trial.tabbed_upsell.navRight":"导航标签右",
    "trial.starter.collection.title":"《我的世界》新手系列",
    "trial.master.collection.title":"《我的世界》大师系列",
    "trial.starter.collection.button":"购买新手系列",
    "trial.master.collection.button":"购买大师系列",
    "trial.starter.offer":"获得《我的世界》、700 个 Minecoin、2 个皮肤包、1 个材质包和 1 个混搭包。",
    "trial.master.offer":"获得《我的世界》、1000 个 Minecoin、4 个皮肤包、2 个材质包、3 张地图和 1 个混搭包。",
    "trial.collection.1.title":"1000 个 Minecoin",
    "trial.collection.1.description":"在市场购买皮肤、材质和世界！",
    "trial.collection.2.title":"700 个 Minecoin",
    "trial.collection.2.description":"在市场购买皮肤、材质和世界！",
    "trial.collection.3.title":"野生生物：热带草原",
    "trial.collection.3.description":"乘坐一辆 4 座的越野车进行游览！",
    "trial.collection.4.title":"冒险者的梦想",
    "trial.collection.4.description":"探索 Noxcrew 充满了古老城堡的奇妙世界！",
    "trial.collection.5.title":"PureBDcraft 包",
    "trial.collection.5.description":"将您的《我的世界》的世界转变成一部漫画！",
    "trial.collection.6.title":"私掠船遗迹",
    "trial.collection.6.description":"广阔的热带荒野上旋风般的寻宝之旅！",
    "trial.collection.7.title":"希腊神话混搭包",
    "trial.collection.7.description":"探索古老的世界、材质包和皮肤！",
    "trial.collection.8.title":"冬季迷你小游戏节日",
    "trial.collection.8.description":"充满了游戏和挑战的游乐场！",
    "trial.collection.9.title":"彩色粉笔皮肤包",
    "trial.collection.9.description":"准备好迎接彩虹般的彩色粉笔带来的巨大欢乐！",
    "trial.collection.10.title":"塑料材质包",
    "trial.collection.10.description":"让您的世界变得简洁、多彩、生机勃勃！",
    "trial.collection.11.title":"皮肤包 1",
    "trial.collection.11.description":"快用这个皮肤包装扮您的角色吧！",
    "trial.collection.12.title":"反派皮肤包",
    "trial.collection.12.description":"快来穿成蛋糕疯子、科学怪人或更糟糕的造型吧！",
    "trial.includes":"包含",
    "trial.survival.mode.title":"生存",
    "trial.creative.mode.title":"创造",
    "trial.survival.mode.1.intro_description":"《我的世界》原始体验：收集资源来制作工具和建造结构、寻找和种植食物来填饱肚子、和危险的生物战斗，并探索广阔的世界。",
    "trial.survival.mode.2.intro_description":"首先要收集一些木头和泥土来建造临时房屋，以帮助您度过第一个夜晚！之后就全看您自己了。",
    "trial.creative.mode.1.intro_description":"在创造模式中建造您想象得到的任何事物！不会受到伤害、在天空中翱翔、享受可立即取得游戏中所有方块的快感！这个模式让你可以专注于建造，并给予您用来建造美丽事物的全部所需。",
    "trial.creative.mode.2.intro_description":"您也可以拜访灵感岛——一个世界教程和创造模式介绍，并即刻从中学习如何成为建造大师！您可以在《我的世界》市场中找到更多类似的有趣世界。",
    "trial.tour.marketplace":"游览市场",
    "trial.world.title":"哪个试用版世界？",

}