feature: dict = {
    "feature.end_city":"末地城",
    "feature.fortress":"下界要塞",
    "feature.mansion":"林地宅邸",
    "feature.mineshaft":"废弃矿井",
    "feature.missingno":"未知功能",
    "feature.monument":"海底遗迹",
    "feature.stronghold":"要塞",
    "feature.temple":"神庙",
    "feature.village":"村庄",
    "feature.shipwreck":"沉船",
    "feature.buried_treasure":"埋藏的宝藏",
    "feature.ruins":"海洋废墟",
    "feature.pillager_outpost":"掠夺者前哨",
    "feature.bastion_remnant":"堡垒遗迹",
    "feature.ruined_portal":"破坏的传送门",
    "feature.ancient_city":"古城",
    "feature.trail_ruins":"小径废墟",

}