gameTip: dict = {
        "gameTip.cameraMovement.touch":"触摸并拖动屏幕可环顾四周。",
                                                        "gameTip.findTree":"冲击一棵树以收集木头。",
        "gameTip.breakWood.touch":"点击并按住一棵树以打碎木头。",
                                "gameTip.selectWoodForMakePlank.touch":"点击选择木头。",
            "gameTip.selectGridForMakePlank.touch":"点击在网格合成表中添加木头。",
            "gameTip.selectOutputSlot.touch":"点击输出槽来合成物品。",
            "gameTip.selectHotBar.touch":"点击一个开放槽来将其添加到您的物品栏。",
            "gameTip.open.recipe.touch":"点击此处以打开搜索标签。",
            "gameTip.craftTable.touch":"点击此处以选择工作台配方书。",
            "gameTip.selectHotBar.craftTable":"将工作台放到热键中以使用它。",
        "gameTip.closeInventory.touch":"点击此处以关闭物品栏。",
        "gameTip.needMoreMaterials":"您需要 2 块木头才能制作木镐。",
        "gameTip.selectItemInHotBar.touch":"点击热键来选择项目。",
            "gameTip.placeCraftTable.touch":"点击地面，放置好工作台。",
                    "gameTip.useCraftTable.touch":"触碰工作台开始使用。",
                "gameTip.needPlanksAndSticks":"合成 3 块木板和 2 根棒子。",
    "gameTip.selectWoodenPickaxe":"合成一把木制镐来采集石头和煤炭。",
        "gameTip.outputSlot.wooden.pickaxe.touch":"点击输出槽来合成一把木制镐。",
        "gameTip.selectHotBar.wooden.pickaxe":"将镐放到热键中以使用它。",
    "gameTip.hintsDone":"您可以自由发挥！探索、制作和寻找食物与庇护所，活过夜晚！祝您玩得愉快！",

}