gameTip: dict = {
    "gameTip.cameraMovement.mouse":"环顾四周。使用鼠标转向",
    "gameTip.cameraMovement.touch":"触摸并拖动屏幕可环顾四周",
            "gameTip.playerMovement.touch":"使用摇杆移动",
    "gameTip.playerMovement.touch.classic":"使用摇杆移动",
        "gameTip.hotbar.mouse":"滚动鼠标滚轮可在快捷栏中选择  并按住它",
    "gameTip.hotbar.touch":"在快捷栏中点击  可按住它",
    "gameTip.hotbar.controller":"在快捷栏中点击  可按住它",
    "gameTip.breakBlock.mouse":"按住左键可打破方块",
    "gameTip.breakBlock.touch":"点击并按住可打破方块",
    "gameTip.breakBlock.touch.classic":"点击并按住可打破方块",
    "gameTip.breakBlock.controller":"点击并按住可打破方块",
    "gameTip.placeBlock.mouse":"点击放置方块",
    "gameTip.placeBlock.touch":"点击放置方块",
    "gameTip.placeBlock.controller":"点击地面可放置方块",
        "gameTip.openInventory.touch":"打开物品栏可查看合成配方",
        "gameTip.sneak.mouse":"你正在潜行！现在不能从边缘掉下去",
    "gameTip.sneak.touch":"你正在潜行，所以不能从边缘掉下去",
    "gameTip.sneak.controller":"你正在潜行，所以不能从边缘掉下去",
    "gameTip.placeCraftingTable.mouse":"放置你的工作台。按住工作台并点击进行放置",
    "gameTip.placeCraftingTable.touch":"点击地面放置你的工作台",
    "gameTip.placeCraftingTable.controller":"放置你的工作台，按住它然后点击地面",
    "gameTip.useCraftingTable.mouse":"右键单击工作台即可使用",

}