gameTip: dict = {
    "gameTip.cameraMovement.mouse":移动 :",
    "gameTip.cameraMovement.touch":触摸并拖动屏幕可环顾四周。",
    "gameTip.cameraMovement.controller":移动 :",
    "gameTip.playerMovement.keyboard":按 :",
    "gameTip.playerMovement.touch":触摸 :",
    "gameTip.playerMovement.controller":移动 :",
    "gameTip.jumpMovement.keyboard":按 :",
    "gameTip.jumpMovement.touch":点击 :",
    "gameTip.jumpMovement.controller":按 :",
    "gameTip.jumpForward.keyboard":同时按 :",
    "gameTip.jumpForward.touch":按住 :",
    "gameTip.jumpForward.controller":向上推 :",
    "gameTip.findTree":冲击一棵树以收集木头。",
    "gameTip.breakWood.mouse":对准一棵树按住 :",
    "gameTip.breakWood.touch":点击并按住一棵树以打碎木头。",
    "gameTip.breakWood.controller":对准一棵树按下 :",
    "gameTip.openInventory.keyboard":按 :",
    "gameTip.openInventory.touch":点击 :",
    "gameTip.openInventory.controller":按 :",
    "gameTip.selectWoodForMakePlank.keyboard":点击 :",
    "gameTip.selectWoodForMakePlank.touch":点击选择木头。",
    "gameTip.selectWoodForMakePlank.controller":使用 :",
    "gameTip.selectGridForMakePlank.keyboard":在网格合成表中点击 :",
    "gameTip.selectGridForMakePlank.touch":点击在网格合成表中添加木头。",
    "gameTip.selectGridForMakePlank.controller":使用 :",
    "gameTip.selectOutputSlot.keyboard"::",
    "gameTip.selectOutputSlot.touch":点击输出槽来合成物品。",
    "gameTip.selectOutputSlot.controller":在输出槽上按 :",
    "gameTip.selectHotBar.keyboard"::",
    "gameTip.selectHotBar.touch":点击一个开放槽来将其添加到您的物品栏。",
    "gameTip.selectHotBar.controller":在下方的一个开放槽上按 :",
    "gameTip.open.recipe.keyboard"::",
    "gameTip.open.recipe.touch":点击此处以打开搜索标签。",
    "gameTip.open.recipe.controller":按 :",
    "gameTip.open.recipe.touchcontroller":在此处按 :",
    "gameTip.craftTable.keyboard":light_mouse_left_button:",
    "gameTip.craftTable.touch":点击此处以选择工作台配方书。",
    "gameTip.craftTable.controller":使用 :",
    "gameTip.outputSlotCraftTable.controller":按 :",
    "gameTip.selectHotBar.craftTable":将工作台放到热键中以使用它。",
    "gameTip.closeInventory.keyboard":在此处按 :",
    "gameTip.closeInventory.touch":点击此处以关闭物品栏。",
    "gameTip.closeInventory.controller":按 :",
    "gameTip.needMoreMaterials":您需要 2 块木头才能制作木镐。",
    "gameTip.selectItemInHotBar.keyboard":使用 :",
    "gameTip.selectItemInHotBar.touch":点击热键来选择项目。",
    "gameTip.selectItemInHotBar.controller":使用 :",
    "gameTip.placeCraftTable.keyboard"::",
    "gameTip.placeCraftTable.touch":点击地面，放置好工作台。",
    "gameTip.placeCraftTable.controller":按 :",
    "gameTip.useCraftTable.keyboard"::",
    "gameTip.useCraftTable.touch":触碰工作台开始使用。",
    "gameTip.useCraftTable.controller":在工作台上按 :",
    "gameTip.needPlanksAndSticks":合成 3 块木板和 2 根棒子。",
    "gameTip.selectWoodenPickaxe":合成一把木制镐来采集石头和煤炭。",
    "gameTip.outputSlot.wooden.pickaxe.keyboard"::",
    "gameTip.outputSlot.wooden.pickaxe.touch":点击输出槽来合成一把木制镐。",
    "gameTip.outputSlot.wooden.pickaxe.controller":按 :",
    "gameTip.selectHotBar.wooden.pickaxe":将镐放到热键中以使用它。",
    "gameTip.hintsDone":您可以自由发挥！探索、制作和寻找食物与庇护所，活过夜晚！祝您玩得愉快！",

}