course: dict = {
    "course.edu.begin":"开始",
    "course.edu.byLessonsEndGeneric":"本节课结束时，您将学习到以下内容:",
    "course.edu.byLessonsEndOrdered":"第%d节课结束时，您将学习到以下内容:",
    "course.edu.collaborativeLesson":"协作课程",
    "course.edu.collaborativeLessonAndQuiz":"协作课程与测验",
    "course.edu.connectionFailed":"糟糕！您似乎已经断开了网络连接。请检查您的网络连接并重试！",
    "course.edu.connectionProblem.courseList":"连接课程列表时出现问题。 请检查您的互联网连接并再试一次。",
    "course.edu.connectionProblem.quiz":"连接测验时出现问题。 请重试。",
    "course.edu.continueButton":"继续",
    "course.edu.courses":"课程",
    "course.edu.createdBy":"作者：%s",
    "course.edu.estimatedLength":"预计长度",
    "course.edu.estimatedLength.formatted":"%d%s %d%s",
    "course.edu.estimatedLength.minutesUnit":"分",
    "course.edu.estimatedLength.secondsUnit":"秒",
    "course.edu.goal":"教育目标：%s",
    "course.edu.hostButton":"主机",
    "course.edu.instructions":"说明",
    "course.edu.join":"加入",
    "course.edu.launchFailed":"糟糕！该世界未能启动成功！您最近是否删除了一个世界模板？",
    "course.edu.learnMoreButton":"了解更多",
    "course.edu.lessonComplete":"课程完成",
    "course.edu.lessonIncludesQuiz":"此课程包含一个测验",
    "course.edu.lessonIsLocked":"此课程已锁定",
    "course.edu.lessonObjectives":"课程目标",
    "course.edu.notSupported":"暂未支持",
    "course.edu.noCoursesFound.title":"未找到课程",
    "course.edu.noCoursesFound.body":"您似乎没有被分配任何课程。",
    "course.edu.objective.bulletedString":"- %s",
    "course.edu.progress.new":"新",
    "course.edu.progress.inProgress":"进行中",
    "course.edu.progress.completed":"已完成",
    "course.edu.refresh.courses":"刷新课程",
    "course.edu.refresh.lessons":"刷新课程",
    "course.edu.restartButton":"重新开始",
    "course.edu.restartConfirmation.title":"重启课程？",
    "course.edu.restartConfirmation.body":"重启会抹去您所有的成果，并重启课程。%s您确定要重启吗？",
    "course.edu.restartFailed.title":"哦不！",
    "course.edu.restartFailed.body":"我们未能找到这一课程。我们正在尝试重新下载。",
    "course.edu.startButton":"开始",
    "course.edu.tasks":"任务",
    "course.edu.teacherHasNotGivenAcccess":"老师没有给予您访问该课程的权限。",
    "course.edu.titleWithOrderPrefix.formatted":"%d：%s",
    "course.edu.tryItNowButton":"立即试用",
    "course.edu.enterIp":"输入您想加入的世界的 IP 地址。",
    "course.edu.ipAddress":"IP 地址",
    "course.edu.ipPlaceholder":"请输入 IP 或服务器地址",
    "course.edu.ipTooltipText":"如需找到 IP 地址，请要求主机暂停游戏。 IP 地址在屏幕右侧显示。",
    "course.edu.joinLesson":"加入游戏",
    "course.edu.joinLessonIntro":"与同学一起加入同一个战局，或者如果他们没有出现在清单中，则输入他们的 IP 地址。",
    "course.edu.joinLessonIntroTeacher":"选择你想加入的小组，或者如果他们没有出现在清单中，则输入他们的 IP 地址。",
    "course.edu.noLessonFoundJoinIp":"输入 IP 地址",
    "course.edu.portTooltipText":"端口号码决定需要使用的特定的服务器程序。 除非服务器主机规定，端口无需改变。",
    "course.edu.searching":"正在搜索世界……",

}