edu: dict = {
    "edu.signin_screen.viewTerms":"查看条款",
    "edu.play_screen.view_worlds":"查看我的世界",
    "edu.play_screen.view_library":"查看库",
    "edu.play_screen.create_new":"新建",
    "edu.play_screen.join_world":"加入世界",
    "edu.play_screen.import":"导入",
    "edu.play_screen.new":"新",
    "edu.play_screen.guided_create":"引导式创建",
    "edu.play_screen.traditional":"传统",
    "edu.play_screen.from_template":"模板",
    "edu.worlds_screen.title":"我的世界",
    "edu.worlds_screen.new_world":"新的世界",
    "edu.worlds_screen.new":"新",
    "edu.worlds_screen.templates":"模板",
    "edu.worlds_screen.guided_create":"引导式创建",
    "edu.worlds_screen.traditional":"传统",
    "edu.worlds_screen.search_placeholder":"搜索我的世界",
    "edu.worlds_screen.play":"游戏",
    "edu.worlds_screen.host":"主机",
    "edu.worlds_screen.settings":"设置",
    "edu.worlds_screen.manage":"管理",
    "edu.worlds_screen.back":"返回",
    "edu.worlds_screen.copy":"复制",
    "edu.worlds_screen.export":"导出",
    "edu.worlds_screen.share":"分享",
    "edu.worlds_screen.delete":"删除",
    "edu.worlds_screen.courses_title":"我的课程",
    "edu.templates.title":"我的模板",
    "edu.templates.search_placeholder":"搜索我的模板",
    "edu.templates.created_by":"依据 %1",
    "edu.templates.create_new":"新建",
    "edu.templates.delete":"删除",
    "edu.templates.delete_title":"是否删除此世界模板？",
    "edu.templates.delete_body":"您确定要删除“%s”世界模板？这不会影响您用此模板创建的任何世界。",
    "edu.templates.delete_confirm":"删除",
    "edu.templates.info_banner":"世界模板是蓝图。你可以使用它们来创建始终以相同的方式开始的新世界。",
    "edu.templates.empty_banner":"你可以从《我的世界：教育版》库、其他《我的世界：教育版》用户或 education.minecraft.net 获取世界模板。",
    "edu.pause.multiplayer.disabled":"用户课程在该课程中不可用。",
    "edu.pause.ipaddress":"IP 地址",
    "edu.pause.port":"端口",
    "edu.pause.nethernetLabel":"连接 ID",

}