createWorldScreen: dict = {
    "createWorldScreen.action.editLocal":创造无限！",
    "createWorldScreen.action.local":创建世界！",
    "createWorldScreen.action.realms":创建世界！",
    "createWorldScreen.action.realmsReset":重置 Realm",
    "createWorldScreen.advanced":高级",
    "createWorldScreen.cheatSettings":作弊",
    "createWorldScreen.worldOptions":世界选项",
    "createWorldScreen.worldSettings":世界设置",
    "createWorldScreen.worldManagement":世界管理",
    "createWorldScreen.alwaysDay":终为白日",
    "createWorldScreen.bonusChest":奖励箱",
    "createWorldScreen.pvp":误伤",
    "createWorldScreen.immediaterespawn":立即重生",
    "createWorldScreen.respawnRadius":重生半径",
    "createWorldScreen.trustPlayers":信任玩家",
    "createWorldScreen.fireSpreads":火焰蔓延",
    "createWorldScreen.mobLoot":生物战利品",
    "createWorldScreen.tileDrops":方块掉落",
    "createWorldScreen.keepInventory":保留物品栏",
    "createWorldScreen.naturalregeneration":自然生命恢复",
    "createWorldScreen.tntexplodes":TNT 爆炸",
    "createWorldScreen.respawnblocksexplode":重生方块爆炸",
    "createWorldScreen.weathercycle":天气更替",
    "createWorldScreen.daylightcycle":开启昼夜更替",
    "createWorldScreen.mobSpawn":生物生成",
    "createWorldScreen.mobgriefing":生物破坏",
    "createWorldScreen.educationtoggle":Education Edition",
    "createWorldScreen.entitiesdroploot":实体掉落战利品",
    "createWorldScreen.commandblocksenabled":命令方块已开启",
    "createWorldScreen.experimentalgameplay":实验性游戏内容",
    "createWorldScreen.experimentalgameplayinfo":§7体验正在开发中的功能。创造世界后无法关闭。",
    "createWorldScreen.experimentalbiomes":自定义生物群系",
    "createWorldScreen.experimentalbiomesDescription":创建自定义生物群系并更改世界生成",
    "createWorldScreen.experimentalCreatorFeatures":即将推出的创作者功能",
    "createWorldScreen.experimentalCreatorFeaturesDescription":包括演员属性和可调整的雾参数",
    "createWorldScreen.experimentalmoddingDescription":做很多重复的事情？这可能有助于创建您的加载项",
    "createWorldScreen.cavesandcliffs":洞穴及悬崖",
    "createWorldScreen.cavesandcliffsDescription":探索新的多样化洞穴生成",
    "createWorldScreen.vanillaExperiments":香草实验",
    "createWorldScreen.vanillaExperimentsDescription":体验正在开发的新香草功能",
    "createWorldScreen.wildUpdate":荒野更新",
    "createWorldScreen.wildUpdateDescription":尝试即将到来的荒野更新中的新功能",
    "createWorldScreen.spectatorMode":旁观模式",
    "createWorldScreen.spectatorModeDescription":试用旁观模式早期版本",
    "createWorldScreen.experimentalholiday":假日创造者功能",
    "createWorldScreen.experimentalholidayDescription":添加数据驱动的方块和物品技术，以自定义方块形状、旋转、损坏等",
    "createWorldScreen.experimentalGameTest":应用测试框架",
    "createWorldScreen.experimentalGameTestDescription":用于构建和测试任何新内容的工具集",
    "createWorldScreen.experimentalMolangFeatures":实验 Molang 功能",
    "createWorldScreen.experimentalMolangFeaturesDescription":Molang 实验性查询和语言功能",
    "createWorldScreen.worldPreferences":世界偏好",
    "createWorldScreen.startWithMap":初始地图",
    "createWorldScreen.defaultName":我的世界",
    "createWorldScreen.create":创建",
    "createWorldScreen.createOnRealms":在 Realms 服务器上创建",
    "createWorldScreen.delete":删除",
    "createWorldScreen.deleteWorld":删除世界",
    "createWorldScreen.delete.desc":永久删除您的世界。",
    "createWorldScreen.delete.confirm":永久删除世界？",
    "createWorldScreen.deleteWarningFormat":您确定要删除 '%s' 吗？这个世界将永远失去！（很长时间！）",
    "createWorldScreen.editTitleFormat":编辑 '%s'",
    "createWorldScreen.game.settings":游戏设置",
    "createWorldScreen.gameMode":游戏模式",
    "createWorldScreen.gameMode.default":默认游戏模式",
    "createWorldScreen.gameMode.personal":个人游戏模式",
    "createWorldScreen.gameMode.adventure":冒险",
    "createWorldScreen.gameMode.creative":创造",
    "createWorldScreen.gameMode.creative.desc":无限资源。无损伤。飞行。即使您稍后切换到生存模式也无法获得成就。",
    "createWorldScreen.gameMode.survival":生存",
    "createWorldScreen.gameMode.survival.desc":资源有限，你需要工具。你可能会受伤。小心怪物。",
    "createWorldScreen.gameMode.serverDefault":默认",
    "createWorldScreen.header.delete":世界永久性",
    "createWorldScreen.header.editLocal":编辑世界",
    "createWorldScreen.header.local":创建一个世界",
    "createWorldScreen.header.realms":创建一个 Realm 服务器",
    "createWorldScreen.header.realmsReset":重置你的 Realm？",
    "createWorldScreen.levelName":名称",
    "createWorldScreen.levelSeed":种子",
    "createWorldScreen.multiplayer.settings":多人游戏设置",
    "createWorldScreen.progress.local":创造一个新世界......",
    "createWorldScreen.progress.realms":正在重置 Realm……",
    "createWorldScreen.seed.desc":输入种子再次生成相同的地形。为随机世界留下空白。",
    "createWorldScreen.showCoordinates":显示坐标",
    "createWorldScreen.worldType":世界类型",
    "createWorldScreen.randomtickspeed":随机刻速度",
    "createWorldScreen.randomtickspeed.reset":重置随机刻速度",
    "createWorldScreen.serverSimDistance":模拟距离",
    "createWorldScreen.serverSimDistanceFormat":%s 个区块",
    "createWorldScreen.showbordereffect":显示边框效果",
    "createWorldScreen.check_internet_connection":您未连接到互联网。您的好友将无法加入您的多人游戏世界。登录至您的 Microsoft 账户，与您的好友同玩。",
    "createWorldScreen.disconnectedXboxLive":您未连接到 Microsoft 服务。您的拥有玩家代号的好友将无法加入您的多人游戏世界。登录至您的 Microsoft 账户，与您的好友同玩。",
    "createWorldScreen.clearPlayerData.button":清除玩家数据",
    "createWorldScreen.clearPlayerData.title":从世界清除玩家数据？",
    "createWorldScreen.clearPlayerData.body1":选择“所有玩家数据”会从世界上删除所有玩家数据。下一次任何玩家进入这个世界时，其将使用新的默认数据开始玩。",
    "createWorldScreen.clearPlayerData.body2":选择“保持拥有玩家数据”，将保留您当前的数据（如物品栏物品和位置），并将其应用于“世界所有者”。后者指任何在本地加载世界的玩家或其所在 Realm 的所有者。",
    "createWorldScreen.clearPlayerData.all":所有玩家数据",
    "createWorldScreen.clearPlayerData.allExceptLocal":保持拥有玩家数据",
    "createWorldScreen.clearPlayerData.cancel":取消",
    "createWorldScreen.clearPlayerData.progress":正在清除玩家数据",
    "createWorldScreen.upload":上传世界",

}