createWorldUpsell: dict = {
    'createWorldUpsell.removeTrial=不在世界列表中显示试玩",
    'createWorldUpsell.title=创建新世界或 Realm？",
    'createWorldUpsell.title.realm=创建新 Realm",
    'createWorldUpsell.button.realm=新 Realm",
    'createWorldUpsell.button.world=新的世界",
    'createWorldUpsell.button.trialText=开始 30 天免费试玩",
    'createWorldUpsell.price.realm=%1$s/月",
    'createWorldUpsell.price.coin.realm=%1$s 硬币/月",
    'createWorldUpsell.price.world=免费",
    'createWorldUpsell.realm.sellPoint1=添加无限成员，与最多 §d%d§r 名好友在线同时进行游戏",
    'createWorldUpsell.realm.sellPoint2=已在线保存：在任何带有《我的世界》市场的设备上玩《我的世界》",
    'createWorldUpsell.realm.sellPoint3=在设备上占用零存储空间",
    'createWorldUpsell.realm.sellPoint4=好友们甚至在你离开时也能正常游戏",
    'createWorldUpsell.signIn=用 Microsoft 账户创建 Realm",
    'createWorldUpsell.world.sellPoint1=与最多 7 名好友在线同玩",
    'createWorldUpsell.world.sellPoint2=保存到设备上：离线游戏",
    'createWorldUpsell.world.sellPoint3=使用设备存储",

}