xbox: dict = {
    "xbox.signin.error":请登录至 Microsoft 账户，与好友畅玩，获取玩家分数和成就。",
    "xbox.signin.error.pocket.line1":感谢测试 Realms！这些功能不是最终版，您可能遇到漏洞。请向我们发送反馈！我们乐于倾听。",
    "xbox.signin.error.pocket.line2":",
    "xbox.signin.error.pocket.line3":在此测试中，每个人都必须登录到 Microsoft 账户，以便将邀请发送给您并添加到 Realm 中。",
    "xbox.signin.warning.kickPlayer":您将返回主菜单。是否继续？",
    "xbox.connection.error":已从 Microsoft 账户断开连接",
    "xbox.signin":登录",
    "xbox.signin.beta.blocked":在试用版中暂不支持使用 Microsoft 账户登录。",
    "xbox.signin.enterCode":输入此代码：",
    "xbox.signin.letsPlay":开始玩游戏吧！",
    "xbox.signin.message":使用您的免费 Microsoft 帐户登录，体验《我的世界》的完整世界。",
    "xbox.signin.url":https:",
    "xbox.signin.useDifferentAccount":使用不同的 Microsoft 帐户登录",
    "xbox.signin.website":在另一台设备上访问此网站：",
    "xbox.signin.welcome":欢迎使用！",
    "xbox.signin.newaccount.welcome":欢迎！",
    "xbox.signin.newaccount.info":您的好友以及他们的好友可以看见您是否在线、您的游戏剪辑以及您最近使用过的应用程序和玩过的游戏。您可以在 Xbox.com 中更改这些权限。",
    "xbox.signinFirst":请先登录",
    "xbox.signinFree":免费注册",
    "xbox.signout":注销",
    "xbox.signinquestion":登录？",
    "xbox.notnow":稍后再说",
    "xbox.signingin":正在用 Microsoft 账户登录…",
    "xbox.signingin.offline":登录中……",
    "xbox.firstsignin.line1":欢迎来到《我的世界》！使用 Microsoft 账户开始连接《我的世界》社区，在那里，PC、控制台、手机和平板玩家可以一起畅玩。至于最棒的部分？",
    "xbox.firstsignin.line2":它完全免费！",
    "xbox.firstsignin.line3":还没有账户？马上创建一个以获得成就，并加入 Realms 和服务器吧！",
    "xbox.firstsignin.line3.norealmsOrServers":没有账户？立即创建一个以赢取成就并与您的跨平台好友一起畅玩！",
    "xbox.failedsignin.body":无法将您登录到您的 Microsoft 账户。访问 Realms、档案和市场物品将受到限制。请稍后再试。",
    "xbox.failedsignin.error":错误代码：",
    "xbox.failedsignin.moreInfo":更多信息",
    "xbox.dev_wrongSandboxSigninFailed.title":出错了",
    "xbox.dev_wrongSandboxSigninFailed.line1":无法登录至%s沙盒。请更改沙盒并重新启动《我的世界》，或者使用另一个账号登录。重新启动时沙盒将为%s。",
    "xbox.dev_wrongSandboxSigninFailed.button.dev":更改为开发沙盒",
    "xbox.dev_wrongSandboxSigninFailed.button.retail":更改为零售沙盒",
    "xbox.dev_wrongSandboxSigninFailed.button.clearXbl":清除账户登录数据",
    "xbox.achievementssignin.line1":成就和玩家分数表示您在《我的世界》中的进度。",
    "xbox.achievementssignin.line2":用 Microsoft 账户登录，开始获得它们！",
    "xbox.addfriendsignin.line1":当您的好友在线时，使用他们的玩家代号找到他们。",
    "xbox.addfriendsignin.line2":用 Microsoft 账户登录，开始添加好友！",
    "xbox.invitesignin.line1":当您的好友在线时，使用他们的玩家代号邀请他们并查看他们的世界。",
    "xbox.invitesignin.line2":用 Microsoft 账户登录，开始邀请好友！",
    "xbox.thirdpartysignin.line1":炫酷的迷你小游戏和全新玩家正在等着你！但首先，'%s' 想要知道你是谁。",
    "xbox.thirdpartysignin.line2":您需要用 Microsoft 账户登录才能进行连接！",
    "xbox.signInLong":免费注册！",
    "xbox.signOutLong":从您的 Microsoft 账户注销",
    "xbox.externalServer.title":在服务器上玩游戏",
    "xbox.externalServer.line1":服务器提供了一些最有创意的方式供您玩《我的世界》！您只需要登入，我们就可确保您有权限与不认识的人在线玩游戏。",
    "xbox.genericsignin.line1":您的《我的世界》帐户允许您在 PC 和移动设备上与好友一同玩在线多人游戏。至于最棒的部分？",
    "xbox.genericsignin.line2":免费！",
    "xbox.genericsignin.line3":您可以随时随地使用它来玩《我的世界》。",
    "xbox.disconectionscreen.notSignedIn":用 Microsoft 账户登录，与好友畅玩。",
    "xbox.disconectionscreen.multiplayerNotAllowed":此 Microsoft 帐户没有权限加入多人游戏。",
    "xbox.disconectionscreen.accessDenied":您必须与本游戏中某人是好友才能加入。",
    "xbox.friendfinder.enterGamertag":输入玩家代号",
    "xbox.friendfinder.findFriends":按玩家代号查找好友",
    "xbox.friendfinder.searchingForGamertag":正在搜索",
    "xbox.friendfinder.gamertagNotFound":未找到玩家代号",
    "xbox.profile.addFriend":添加好友",
    "xbox.profile.addFriend.success":成功！%s 已被添加到您的好友列表。",
    "xbox.profile.block":方块",
    "xbox.profile.currentlyPlaying":目前正在玩 %s",
    "xbox.profile.favorite":收藏",
    "xbox.profile.favoriteHelperText":收藏的好友会出现在好友列表的最前面。无论他们何时上线或开始直播，您都会看见他们。",
    "xbox.profile.friend":好友",
    "xbox.profile.friendHelperText":关注 %s。在互相关注后，您即可邀请他们加入您的游戏。",
    "xbox.profile.mute":静音",
    "xbox.profile.realName":在 Xbox 应用程序中管理用于共享您的实际姓名的隐私设置。",
    "xbox.profile.removeFriend":解除好友关系",
    "xbox.profile.report":举报",
    "xbox.report.gamertag":举报 %s",
    "xbox.report.optionalText":在此处输入文本（可选）",
    "xbox.report.toast":您已举报 %s",
    "xbox.report.toastError":无法发送您的举报。请稍后再试。",
    "xbox.report.whereReport":您在哪里观察到了不好的行为？",
    "xbox.report.whereReportDescription":请告知我们事件发生的地方。这能帮我们研究您的案例。",
    "xbox.report.whyReport":您为什么举报 %s？",
    "xbox.report.area.chat":聊天消息",
    "xbox.report.area.skin":玩家皮肤",
    "xbox.report.area.gameplay":游戏",
    "xbox.report.area.ingame":游戏内构建",
    "xbox.report.area.other":其他",
    "xbox.report.cyberbullying":网络霸凌",
    "xbox.report.falseReporting":过多的虚假/不准确举报",
    "xbox.report.exploits":漏洞利用和第三方应用程序",
    "xbox.report.harassingComments":骚扰或诽谤性评论",
    "xbox.report.hateSpeech":仇恨言论",
    "xbox.report.illegalDrugs":非法药物或活动",
    "xbox.report.impersonatingStaff":冒充员工、玩家支持人员或社区代表",
    "xbox.report.inGameTrolling":应用程序内引战和滥发消息",
    "xbox.report.nameOrGamertag":玩家名称或玩家代号",
    "xbox.report.modding":修改",
    "xbox.report.obsceneLanguage":淫秽或粗俗语言",
    "xbox.report.postLinkToInappropriateContent":发布指向不当内容或恶意软件的链接",
    "xbox.report.realLifeInfo":现实生活信息和威胁",
    "xbox.report.sexualReference":性内容与暴力内容",
    "xbox.report.spam":出于商业目的滥发消息",
    "xbox.report.terrorismOrViolentExtremism":恐怖主义或暴力极端主义",
    "xbox.report.childSexualExploitationOrAbuse":儿童性剥削或性虐待",
    "xbox.report.imminentHarm":即将发生的伤害",
    "xbox.report.nonConsensualIntimateImagery":未经同意的亲密影像",
    "xbox.report.policyViolation":违反政策",
    "xbox.report.harassment":骚扰或欺凌",
    "xbox.report.profanity":脏话",
    "xbox.report.childSexualExploitationGrooming":儿童性剥削与儿童诱骗",
    "xbox.report.controversial":有争议的话题",
    "xbox.report.notoriousFigure":臭名昭著的形象",
    "xbox.report.cheating":作弊",
    "xbox.report.defamation":诽谤、冒充和虚假信息",
    "xbox.report.drugs":毒品",
    "xbox.report.fraud":欺诈",
    "xbox.report.advertising":滥发信息或广告",
    "xbox.report.selfHarm":自残或自杀",
    "xbox.report.nudity":裸体或色情",
    "xbox.report.sexuallyInappropriate":不恰当性内容",
    "xbox.report.extremeViolence":极端暴力或恐怖",
    "xbox.report.quittingEarly":提前退出",
    "xbox.report.unsportingBehavior":没有体育道德的行为",
    "xbox.report.voiceCommunication":语音交流",

}