permissions: dict = {
    "permissions.ability.build":"建造",
    "permissions.ability.mine":"挖掘",
    "permissions.ability.doorsandswitches":"使用门和开关",
    "permissions.ability.opencontainers":"打开容器",
    "permissions.ability.attackplayers":"攻击玩家",
    "permissions.ability.attackmobs":"攻击生物",
    "permissions.ability.op":"操作员命令",
    "permissions.ability.invisible":"变为隐形",
    "permissions.ability.teleport":"使用传送",
    "permissions.NeedPermission":"你需要许可",
    "permissions.AddFriends":"由于您 Microsoft 账户的设置问题，您无法添加好友。请确保您的在线安全设置已允许添加好友。请前往 aka.ms/MCMultiplayerHelp 查看如何更改这些设置。",
    "permissions.MultiplayerSessions":"由于您 Microsoft 账户的设置问题，您无法在 Realms 上进行游戏。请确保您的在线安全设置已允许多人游戏。请前往 aka.ms/MCMultiplayerHelp 查看如何更改这些设置。",
    "permissions.Communications":"由于您 Microsoft 账户的设置问题，您无法与其他玩家聊天。请确保您的隐私设定已允许与他人交流。请前往 aka.ms/MCMultiplayerHelp 查看如何更改这些设置。",
    "permissions.RealmsAddFriends":"由于 Xbox 账户设置问题，您将无法在您的 Realm 中添加新好友与您同玩。这可以在 Xbox.com 上的隐私与在线安全设置中进行更改。请问是否要继续？",
    "permissions.CloudSave":"由于 Xbox 账户设置问题，您无法将您的世界保存到 Xbox。这可以在 Xbox.com 上的隐私与在线安全设置中进行更改。	disable_3rd_party_console_resource_pack_check",
    "permissions.MultiplayerSessionsOnConsole":"由于您 Microsoft 账户的设置问题，您无法在 Realms 上进行游戏。请确保您的在线安全设置已允许多人游戏，且当前您已拥有 Xbox Live 金会员订阅。请前往 aka.ms/MCMultiplayerHelp 查看如何更改这些设置。	disable_3rd_party_console_resource_pack_check",
    "permissions.MultiplayerSessionsOnConsoleGamecore":"由于您 Microsoft 账户的设置问题，您无法在 Realms 中进行游戏。	disable_3rd_party_console_resource_pack_check",
    "permissions.open.account.help.button":"获取关于解决此问题的帮助",
    "permissions.open.account.help.button.gamecore":"修复此问题",
    "permissions.open.account.setting.button":"请参阅服务条款",
    "permissions.GoBack":"返回",
    "permissions.Continue":"继续",
    "permissions.chatmute":"聊天当前被禁用",
    "permissions.deopingother.message":"如果降低他们的权限级别，那么他们将不再具有操作员级别权限。",
    "permissions.description.visitors":"访客可以自由探索您的世界，但无法与方块、物品或实体交互。信任玩家已关闭。",
    "permissions.description.members":"成员是您的世界中的活动玩家，他们可以破坏和创建方块，并攻击生物和其他玩家。",
    "permissions.description.operators":"操作员是可以设置玩家权限并将命令用于获取对您世界的更多控制权的成员。",
    "permissions.level":"权限级别",
    "permissions.level.custom":"自定义...",
    "permissions.level.member":"成员",
    "permissions.level.operator":"操作员",
    "permissions.level.visitor":"访客",
    "permissions.nocheats":"作弊已禁用",
    "permissions.nocheats.message":"仅当无敌模式已打开时，诸如传送等某些命令才可用。可通过“课程设置”下的暂停菜单来打开无敌模式。如果您选择打开无敌模式，这个世界中的成就将被禁用。",
    "permissions.nocheats.message.noachievements":"仅当无敌模式已打开时，诸如传送等某些命令才可用。可通过“课程设置”下的暂停菜单来打开无敌模式。",
    "permissions.nocheats.turnon":"在作弊打开时设置操作",
    "permissions.nocheats.turnoff":"在作弊关闭时设置操作",
    "permissions.nocheats.cancel":"取消",
    "permissions.deopingself":"删除操作员权限？",
    "permissions.deopingself.message":"降低权限级别，您将不再具有操作员级别权限。",
    "permissions.title":"玩家权限",
    "permissions.title.settings":"玩家从邀请加入时的权限",
    "permissions.title.settings.edu":"加入您的世界的用户的权限级别",
    "permissions.toast.playerLeft":"一名玩家离开了游戏。",
    "permissions.toast.playerJoined":"一名玩家加入了游戏。",
    "permissions.kickplayer":"踢出玩家",
    "permissions.kickplayer.reason":"您已被主机从会话中踢出。",
    "permissions.kickplayer.message":"是否将%s踢出世界？被踢出的玩家不可重新加入此会话。",
    "permissions.kickplayer.message.dedicatedserver":"是否将%s踢出世界？",
    "permissions.kickplayer.title":"踢出玩家？",
    "permissions.banplayer":"封禁玩家",
    "permissions.banplayer.reason":"您已被主机从会话中封禁。",
    "permissions.banplayer.message":"是否将%s从世界中封禁？被封禁的玩家不可重新加入。",
    "permissions.banplayer.title":"封禁玩家？",
    "permissions.ClubsAccess":"由于您没有俱乐部的访问权限，您无法访问 Realms Feed。请前往 aka.ms/MCClubsHelp 查看如何更改这些设置。",
    "permissions.ClubsPost":"由于您没有俱乐部的访问权限，您无法发布到 Realms Feed。请前往 aka.ms/MCClubsHelp 查看如何更改这些设置。",
    "permissions.button.kickplayer":"将玩家移除出游戏",
    "permissions.popup.title":"权限选项",
    "permissions.dropdown.title":"%s 权限级别",
    "permissions.operator":"操作员",
    "permissions.member":"成员",
    "permissions.visitor":"访客",
    "permissions.removeplayer":"移除玩家",
    "permissions.removeplayer.reason":"您已被主机从会话中移除。",
    "permissions.removeplayer.message":"您确定要把该玩家从此世界上移除吗？当您移除该玩家时，将生成一个新的加入代码，使其无法重新连接。",
    "permissions.removeplayer.title":"移除玩家确认",

}