storageManager: dict = {
    "storageManager.contentType.world":"世界",
    "storageManager.contentType.worldTemplate":"世界模板",
    "storageManager.contentType.resourcePack":"资源",
    "storageManager.contentType.behaviorPack":"行为包",
    "storageManager.contentType.skinPack":"皮肤包",
    "storageManager.contentType.invalid":"无效",
    "storageManager.contentType.cachedData":"缓存数据",
    "storageManager.contentType.worlds":"世界",
    "storageManager.contentType.legacy_worlds":"旧世界",
    "storageManager.contentType.worldTemplates":"世界模板",
    "storageManager.contentType.resourcePacks":"资源包",
    "storageManager.contentType.behaviorPacks":"行为包",
    "storageManager.contentType.skinPacks":"皮肤包",
    "storageManager.sync_legacy_worlds":"同步旧世界",
    "storageManager.sync_legacy_worlds_description":"从旧版本的《我的世界》中查询世界。这可能需要一段时间才能完成。",
    "storageManager.sync_legacy_worlds.conversion_description":"单击一个世界，将它转换为可玩的世界",
    "storageManager.sync_legacy_worlds.conversion_complete.content":"你已经转换了你的世界。现在可以在“所有世界”中找到它。",
    "storageManager.sync_legacy_worlds.conversion_complete.title":"成功！",
    "storageManager.sync_legacy_worlds.conversion_complete.confirm_button":"前往“所有世界”",
    "storageManager.sync_legacy_worlds.conversion_complete.cancel_button":"关闭",
    "storageManager.sync_legacy_worlds.fetch_complete.title":"成功！",
    "storageManager.sync_legacy_worlds.fetch_complete.content":"我们在之前版本的《我的世界》中找到了 %s 个旧的世界。",
    "storageManager.sync_legacy_worlds.conversion_explanation.title":"正在转换世界",
    "storageManager.sync_legacy_worlds.conversion_explanation.content":"你需要将 “%s”转换为最新版本的《我的世界》才可以玩。",
    "storageManager.sync_legacy_worlds.conversion_explanation.confirm_button":"招降",
    "storageManager.sync_legacy_worlds.conversion_explanation.cancel_button":"取消",
    "storageManager.baseWorld":"基础世界",
    "storageManager.mainSizeLabel":"%s - 1 项目",
    "storageManager.mainSizeLabelPlural":"%s - %s 项目",
    "storageManager.unknownElements":"未知",
    "storageManager.delete.title":"是否永久性删除 %s ？",
    "storageManager.title.item.single":"项目",
    "storageManager.title.item.plural":"项目",
    "storageManager.delete.content":"您确定要删除选中的物品吗？这些物品将永远丢失！（很长一段时间！）%s%s%s",
    "storageManager.delete.content.redownload":"您可以从市场重新下载已购买的内容。",
    "storageManager.delete.content.worldtemplate":"删除模板可能会导致使用这些模板的世界无法再按照预期使用。",
    "storageManager.delete.content.affectedWorlds":"下列世界可能会像预期的那样停止运转：",
    "storageManager.delete.confirm":"删除",
    "storageManager.delete.cancel":"取消",
        "storageManager.delete.premium":"您即将删除 '%s'。您仍然会拥有 %s，如果以后还想再次使用 %s，您可以从市场中重新下载。",
    "storageManager.delete.premium.end":"确定要删除此 '%s' 吗？",
    "storageManager.deleting.content":"正在删除内容",
    "storageManager.download.premium":"%s 当前未安装。",
    "storageManager.download.premium.end":"您想要下载 %s ( %s )吗？",
    "storageManager.dependency.titleText":"您想要中断这些吗？",
    "storageManager.dependency.warningText":"其他项目可能需要您正在删除的内容才能正常运行。您确定要冒险损坏这些项目吗？",
    "storageManager.dependency.doneText":"其他 %s 可以删除，并且不会影响其他资源。",
    "storageManager.dependency.noItems":"没有待删除的其他项目。",
    "storageManager.dependency.breakItem":"需要您删除的内容：",
    "storageManager.dependency.removeDependencies":"保留该项目，此包需要",
    "storageManager.dependency.breakPack":"确定要打破此包吗?",
    "storageManager.share.compress":"正在压缩选中的资源…",
    "storageManager.share.totalPercent":"-100%",
    "storageManager.dependency.continue":"继续",
    "storageManager.dependency.continue.scroll":"滚动继续",
    "storageManager.sortLargest":"大小 - 按从大到小排列",
    "storageManager.sortDateRecent":"已使用数据 - 按从近到远排列",
    "storageManager.sortDateOldest":"已使用数据 - 按从远到近排列",
    "storageManager.version":"版本",
    "storageManager.multiselectDelete":"删除",
    "storageManager.multiselectShare":"分享",
    "storageManager.multiselect":"多选",
    "storageManager.miscellaneous":"杂项",
    "storageManager.groupType":"类型",
    "storageManager.groupPack":"插件",
    "storageManager.shareTitle":"导出资源",
    "storageManager.mcpack":"《我的世界》包",
    "storageManager.mcaddon":"《我的世界》插件",
    "storageManager.mcworld":"《我的世界》的世界",

}