npcscreen: dict = {
    "npcscreen.action.buttonmode":按钮模式",
    "npcscreen.action.onEnter":进入时",
    "npcscreen.action.onExit":退出时",
    "npcscreen.action.buttonname":按钮名称",
    "npcscreen.action.command.placeholder":在此处键入命令...",
    "npcscreen.action.command.title":命令",
    "npcscreen.action.url.placeholder":在此处键入 URL...",
    "npcscreen.action.url.title":URL",
    "npcscreen.action.url.warning.invalidUri":仅支持以“http”或“https”开头的网址。",
    "npcscreen.action.url.warning.emptyUri":如果没有添加 URL，此按钮将打开一个新的浏览器窗口。",
    "npcscreen.addcommand":添加命令",
    "npcscreen.addtext":在此处键入对话...",
    "npcscreen.addurl":添加 URL",
    "npcscreen.advancedsettings":高级设置",
    "npcscreen.advancedtitle":高级 NPC 设置",
    "npcscreen.appearance":外观",
    "npcscreen.basictitle":非玩家角色",
    "npcscreen.dialog":对话",
    "npcscreen.editdialog":“编辑”对话框",
    "npcscreen.help.command.a":单击此按钮在 NPC 对话框中添加命令。",
    "npcscreen.help.command.b":可以同时添加多个命令。",
    "npcscreen.help.url.a":单击此按钮在 NPC 对话框中添加 URL 超链接。",
    "npcscreen.help.url.b":链接会在玩家的默认浏览器中打开。",
    "npcscreen.learnmore":了解更多",
    "npcscreen.name":名称",
    "npcscreen.npc":NPC",
    "npcscreen.requiresop":所需的操作",

}