accessibility: dict = {
    "accessibility.disableTTS":"文本转语音已禁用",
    "accessibility.enableTTS":"文本转语音已启用",
    "accessibility.chat.tts.gamepad.back":"按下 %s 返回",
    "accessibility.chat.tts.gamepad.exitChat":"按下 %s 退出聊天",
    "accessibility.chat.tts.gamepad.sendMessage":"按下 %s 发送消息",
    "accessibility.chat.tts.says":"%s 说 %s",
    "accessibility.chat.tts.hideChat":"隐藏聊天",
    "accessibility.chat.tts.keyboard":"键盘",
    "accessibility.chat.tts.muteChatToggle":"全部静音",
    "accessibility.chat.tts.sendChatMessage":"发送",
    "accessibility.chat.tts.textboxTitle":"聊天",
    "accessibility.game.playerView":"玩家视图",
    "accessibility.loading.done":"完成",
    "accessibility.saving.done":"完成",
    "accessibility.downloading.start":"下载已开始",
    "accessibility.downloading.Progress":"正在下载 %s%",
    "accessibility.downloading.canceled":"下载已取消",
    "accessibility.downloading.complete":"下载完成",
    "accessibility.importing.start":"导入已开始",
    "accessibility.importing.Progress":"正在导入 %s%",
    "accessibility.importing.canceled":"导入已取消",
    "accessibility.importing.complete":"导入完成",
    "accessibility.signin.xbl":"正在登录至 Xbox Live",
    "accessibility.chat.howtoopen":"按 %s 打开聊天",
    "accessibility.chat.howtoemote":"按或按住 %s 发表情",
    "accessibility.key.mouseButton":"鼠标按钮 %s",
    "accessibility.key.gamepad":"控制器 %s",
    "accessibility.list.or.two":"%s或%s",
    "accessibility.list.or.three_or_more.first":"%s",
    "accessibility.list.or.three_or_more.inner":"，%s",
    "accessibility.list.or.three_or_more.last":"，或 %s",
    "accessibility.button.tts.title":"按钮",
    "accessibility.checkbox.tts.title":"复选框",
    "accessibility.checkbox.tts.status":"状态 %s			 Status will be checked or unchecked",
    "accessibility.dropdown.tts.title":"下拉",
    "accessibility.screen.tts.title":"%s屏幕		 %s will be replaced with the title of the screen (Example:",
    "accessibility.slider.tts.title":"滑块",
    "accessibility.tab.tts.title":"标签",
    "accessibility.textbox.tts.title":"文本框",
    "accessibility.toggle.tts.title":"切换",
    "accessibility.button.close":"关闭",
    "accessibility.button.back":"返回",
    "accessibility.button.exit":"退出",
    "accessibility.dropdown.listItem":"列表项",
    "accessibility.minecoin":"Minecoin",
    "accessibility.minecoins":"Minecoin",
    "accessibility.sectionName":"第 %s 部分：",
    "accessibility.state.on":"：打开",
    "accessibility.state.off":"：关闭",
    "accessibility.state.checked":"：选中",
    "accessibility.state.unchecked":"：取消选中",
    "accessibility.state.selected":"：已选择",
    "accessibility.state.unselected":"：未选择",
    "accessibility.store.offerDescription.share":"分享",
    "accessibility.store.wishlist.button":"愿望清单",
    "accessibility.index":" 第 %s 个，共 %s 个		 This is numbering, which number out of the total number of objects is available for interaction. Example:",
    "accessibility.slider.tts.percentValue":"%s%",
    "accessibility.play.editWorld":"编辑世界",
    "accessibility.play.editRealm":"编辑 Realm",
    "accessibility.play.editServer":"编辑服务器",
    "accessibility.play.importWorld":"导入世界",
    "accessibility.play.leaveRealm":"离开 Realm",
    "accessibility.play.realmFeed":"Realm 内容",
    "accessibility.play.tabLeft":"按下选项卡左边的 %s",
    "accessibility.play.tabRight":"按下选项卡右边的 %s",
    "accessibility.play.legacyWorldsDelete":"删除旧的世界",
    "accessibility.play.uploadWorld":"上传世界",
    "accessibility.pause.permissions":"权限",
    "accessibility.pause.profile":"选择个人资料",
    "accessibility.start.buttonHelper":"%s：%s		 Used for on-screen gamepad helpers (eg. 'Y Button :",
    "accessibility.screenName.achievements":"成就屏幕",
    "accessibility.screenName.chat":"聊天屏幕",
    "accessibility.screenName.chatSettings":"聊天设置屏幕",
    "accessibility.screenName.createNew":"创建新的屏幕",
    "accessibility.screenName.createWorld":"创建世界设置屏幕",
    "accessibility.screenName.editCharacter":"角色创建器",
    "accessibility.screenName.editWorldSettings":"编辑世界设置屏幕",
    "accessibility.screenName.error":"错误屏幕",
    "accessibility.screenName.howToPlay":"游戏指南屏幕",
    "accessibility.screenName.inviteToGame":"邀请至游戏屏幕",
    "accessibility.screenName.joinByIP":"通过 IP 对话框加入",
    "accessibility.screenName.joinCode":"加入代码对话框",
    "accessibility.screenName.library":"库屏幕",
    "accessibility.screenName.modalDialog":"弹出对话框",
    "accessibility.screenName.myTemplates":"我的模板屏幕",
    "accessibility.screenName.myWorlds":"我的世界屏幕",
    "accessibility.screenName.patchNotes":"补丁说明屏幕",
    "accessibility.screenName.pause":"暂停屏幕",
    "accessibility.screenName.permissions":"权限屏幕",
    "accessibility.screenName.play":"开始游戏屏幕",
    "accessibility.screenName.profile":"个人资料屏幕",
    "accessibility.screenName.realmSettings":"Realm 设置屏幕",
    "accessibility.screenName.settings":"游戏设置屏幕",
    "accessibility.screenName.skinPicker":"皮肤选择屏幕",
    "accessibility.screenName.start":"主菜单",
    "accessibility.screenName.vrAlignment":"VR 对齐屏幕",
    "accessibility.screenName.emoteWheel":"表情屏幕",
    "accessibility.settings.reset":"重置",
    "accessibility.settings.chooseSeed":"选择种子",
    "accessibility.start.feedback":"提交反馈",
    "accessibility.start.new":"新",
    "accessibility.start.profile":"选择个人资料",
    "accessibility.start.skinPicker":"选择皮肤",
    "accessibility.store.tag":"标签",
    "accessibility.textbox.editing":"正在编辑",
    "accessibility.text.period":"句号",
    "accessibility.text.period.url":"点					 Pronunciation for a period inside of a URL, as in 'www dot microsoft dot com'",
    "accessibility.text.comma":"逗号",
    "accessibility.text.colon":"冒号",
    "accessibility.text.apostrophe":"撇号",
    "accessibility.text.semiColon":"分号",
    "accessibility.text.questionMark":"问号",
    "accessibility.text.quotationMark":"引号",
    "accessibility.text.space":"空格",
    "accessibility.text.tilde":"波浪号",
    "accessibility.text.graveAccent":"重音符",
    "accessibility.text.lessThan":"小于号",
    "accessibility.text.greaterThan":"大于号",
    "accessibility.text.leftBrace":"左花括号",
    "accessibility.text.rightBrace":"右花括号",
    "accessibility.text.rightBracket":"右括号",
    "accessibility.text.leftBracket":"左括号",
    "accessibility.text.verticalBar":"竖线",
    "accessibility.text.forwardSlash":"斜杠",
    "accessibility.text.backwardSlash":"反斜杠",
    "accessibility.text.exclamationPoint":"感叹号",
    "accessibility.text.atSign":"@ 符号",
    "accessibility.text.hashTag":"井号",
    "accessibility.text.dollarSign":"美元符号",
    "accessibility.text.percent":"百分号",
    "accessibility.text.caret":"脱字号",
    "accessibility.text.ampersand":"& 符号",
    "accessibility.text.asterisk":"星号",
    "accessibility.text.leftParenthesis":"左圆括号",
    "accessibility.text.rightParenthesis":"右圆括号",
    "accessibility.text.hyphen":"连字符",
    "accessibility.text.underScore":"下划线",
    "accessibility.text.plus":"加号",
    "accessibility.text.equals":"等号",
    "accessibility.text.unsupported":"未识别字符",
    "accessibility.toast":"通知		 This is the name of the popup that appears when a player gets a notification for a game invite or achievement unlocked",
    "accessibility.worldTemplates.help":"帮助",
    "accessibility.popup.title":"关闭屏幕阅读器？",
    "accessibility.popup.message.line1":"欢迎来到《我的世界》！",
    "accessibility.popup.message.default":"您的设备上默认启用了屏幕阅读器支持。",
    "accessibility.popup.message.platform":"我们发现您的系统启用了一个屏幕阅读器，并且自动启用了《我的世界》的屏幕阅读器。",
    "accessibility.popup.message.touch":"触摸和拖动以在屏幕上找到控件，双击控件以进行选择。若要在屏幕上滚动，上下滑动时双击并按住即可。",
    "accessibility.popup.message.xbl":"我们发现您的账户已经启用了“让游戏读给我听”，并且自动启用了《我的世界》的屏幕阅读器。",
    "accessibility.popup.message.line3":"您想将它关掉吗？",
    "accessibility.popup.left_button_text":"关闭",
    "accessibility.popup.right_button_text":"保持打开",
    "accessibility.controllerLayoutScreen.buttonRemapped":"%s 已被绑定至 %s",
    "accessibility.controllerLayoutScreen.buttonBoundTo":"%s 按钮：%s",
    "accessibility.controllerLayoutScreen.buttonRemapping":"为 %s 选择要绑定的输入",
    "accessibility.gamepad.faceButton.down":"按钮 A",
    "accessibility.gamepad.faceButton.right":"按钮 B",
    "accessibility.gamepad.faceButton.left":"按钮 X",
    "accessibility.gamepad.faceButton.up":"按钮 Y",
    "accessibility.gamepad.button.systemLeft":"查看键",
    "accessibility.gamepad.button.systemRight":"菜单键",
    "accessibility.gamepad.dpad.down":"方向键下",
    "accessibility.gamepad.dpad.up":"方向键上",
    "accessibility.gamepad.dpad.left":"方向键左",
    "accessibility.gamepad.dpad.right":"方向键右",
    "accessibility.gamepad.stick.left":"左摇杆",
    "accessibility.gamepad.stick.right":"右摇杆",
    "accessibility.gamepad.trigger.right":"右扳机",
    "accessibility.gamepad.trigger.left":"左扳机",
    "accessibility.gamepad.bumper.right":"右杆",
    "accessibility.gamepad.bumper.left":"左杆",
    "accessibility.keyboard.leftBracket":"左方框键			 left square bracket means '[' on the english keyboard",
    "accessibility.keyboard.rightBracket":"右方框键		 right square bracket means ']' on the english keyboard",
    "accessibility.emotes.hovered":"%s，表情按钮 %d，%d 的 %d",
    "accessibility.emotes.assigned":"已指派 %s 表情",
    "accessibility.emotes.unassigned":"未指派",
    "accessibility.emotes.playSuccess":"播放表情",
    "accessibility.emotes.playFailed":"此按钮没有指派的表情，按 %s 以访问更改表情按钮",
    "accessibility.emotes.changeEmotesInstruction.button":"%s 以访问",
    "accessibility.emotes.keyboard.arrow":"箭",
    "accessibility.emotes.instruction.keyboard":"按右或左键在表情按钮之间切换。按下箭头以访问更改表情按钮。",

}